include("${SETTINGS}")
include("${CMAKE_CURRENT_LIST_DIR}/Helpers.cmake")
if(NOT CONFIG)
  set(CONFIG Release)
endif()
set(work "${TEST_BINARY_DIR}/archives")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
get_filename_component(_cmake_bin "${CMAKE_COMMAND}" DIRECTORY)
find_program(_cpack NAMES cpack HINTS "${_cmake_bin}" REQUIRED)
foreach(generator IN ITEMS TGZ ZIP)
  run_checked("${_cpack}" --config "${QUEST_BUILD_DIR}/CPackConfig.cmake"
    -G "${generator}" -C "${CONFIG}" -B "${work}/${generator}")
  file(GLOB archives "${work}/${generator}/*.tar.gz" "${work}/${generator}/*.zip")
  list(LENGTH archives count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Expected one complete ${generator} archive, got ${archives}")
  endif()
  list(GET archives 0 archive)
  file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${work}/${generator}/extracted")
  file(GLOB_RECURSE headers "${work}/${generator}/extracted/quest.h")
  set(prefixes "")
  set(suffix "/${QUEST_INSTALL_INCLUDEDIR}/quest.h")
  string(LENGTH "${suffix}" suffix_length)
  foreach(header IN LISTS headers)
    string(LENGTH "${header}" header_length)
    math(EXPR prefix_length "${header_length} - ${suffix_length}")
    if(prefix_length GREATER 0)
      string(SUBSTRING "${header}" ${prefix_length} -1 ending)
      if(ending STREQUAL suffix)
        string(SUBSTRING "${header}" 0 ${prefix_length} prefix)
        list(APPEND prefixes "${prefix}")
      endif()
    endif()
  endforeach()
  list(LENGTH prefixes count)
  if(NOT count EQUAL 1)
    message(FATAL_ERROR "Archive has no unique ${QUEST_INSTALL_INCLUDEDIR}/quest.h: ${headers}")
  endif()
  list(GET prefixes 0 prefix)
  check_relocation("${prefix}")
  consume("${prefix}" "${work}/${generator}/consumer")
endforeach()
