include("${SETTINGS}")
include("${CMAKE_CURRENT_LIST_DIR}/Helpers.cmake")
if(NOT CONFIG)
  set(CONFIG Release)
endif()
set(work "${TEST_BINARY_DIR}/install")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}")
run_checked("${CMAKE_COMMAND}" --install "${QUEST_BUILD_DIR}" --config "${CONFIG}" --prefix "${work}/stage")
file(RENAME "${work}/stage" "${work}/relocated prefix")
check_relocation("${work}/relocated prefix")
consume("${work}/relocated prefix" "${work}/consumer")
