include("${SETTINGS}")
include("${CMAKE_CURRENT_LIST_DIR}/Helpers.cmake")
if(NOT CONFIG)
  set(CONFIG Release)
endif()
set(prefix "${TEST_BINARY_DIR}/install/relocated prefix")
set(cases components major_version)
if(QUEST_TEST_OMP AND NOT QUEST_TEST_SHARED)
  list(APPEND cases missing_openmp)
endif()
if(QUEST_TEST_MPI AND (QUEST_TEST_SUBCOMM OR NOT QUEST_TEST_SHARED))
  list(APPEND cases missing_mpi)
endif()
if(QUEST_TEST_SHARED)
  list(APPEND cases private_shared)
endif()
foreach(case IN LISTS cases)
  set(binary "${TEST_BINARY_DIR}/behavior/${case}")
  file(REMOVE_RECURSE "${binary}")
  run_checked("${CMAKE_COMMAND}" -S "${QUEST_SOURCE_DIR}/tests/packaging/behavior"
    -B "${binary}" -C "${TEST_BINARY_DIR}/install/consumer/initial.cmake" "-DCASE=${case}")
  run_checked("${CMAKE_COMMAND}" --build "${binary}" --config "${CONFIG}" --parallel 2)
endforeach()
