include("${SETTINGS}")
include("${CMAKE_CURRENT_LIST_DIR}/Helpers.cmake")
set(work "${TEST_BINARY_DIR}/relocated-sdk")
file(REMOVE_RECURSE "${work}")
file(MAKE_DIRECTORY "${work}/sdk/include" "${work}/sdk/lib")
file(COPY "${QUEST_CUSTATEVEC_INCLUDE_DIR}/custatevec.h" DESTINATION "${work}/sdk/include")
get_filename_component(library_dir "${QUEST_CUSTATEVEC_LIBRARY}" DIRECTORY)
file(GLOB libraries "${library_dir}/libcustatevec.so*" "${library_dir}/libcustatevec.dylib*")
if(NOT libraries)
  message(FATAL_ERROR "No cuStateVec shared libraries to relocate")
endif()
file(COPY ${libraries} DESTINATION "${work}/sdk/lib")
set(QUEST_CUQUANTUM_ROOT "${work}/sdk")
set(QUEST_CUQUANTUM_DIR "")
set(prefix "${TEST_BINARY_DIR}/install/relocated prefix")
file(GLOB_RECURSE exports "${prefix}/*QuEST*.cmake")
foreach(export IN LISTS exports)
  file(READ "${export}" text)
  foreach(producer_path IN ITEMS "${QUEST_CUSTATEVEC_INCLUDE_DIR}" "${library_dir}" "${QUEST_CUDA_ROOT}")
    if(producer_path)
      string(FIND "${text}" "${producer_path}" index)
      if(NOT index EQUAL -1)
        message(FATAL_ERROR "Producer SDK path leaked into ${export}: ${producer_path}")
      endif()
    endif()
  endforeach()
endforeach()
consume("${prefix}" "${work}/consumer")
file(STRINGS "${work}/consumer/CMakeCache.txt" found REGEX "^CUQUANTUM_cuStateVec_LIBRARY:")
string(FIND "${found}" "${work}/sdk/lib/" index)
if(index EQUAL -1)
  message(FATAL_ERROR "The consumer did not discover the relocated SDK: ${found}")
endif()

# The installed archive records a minimum component version and major ABI.
set(header "${work}/sdk/include/custatevec.h")
file(READ "${header}" original_header)
foreach(case older future_major)
  if(case STREQUAL "older")
    set(major 0)
  else()
    string(REGEX MATCH "CUSTATEVEC_VER_MAJOR[ \t]+([0-9]+)" unused "${original_header}")
    math(EXPR major "${CMAKE_MATCH_1} + 1")
  endif()
  string(REGEX REPLACE "(CUSTATEVEC_VER_MAJOR[ \t]+)[0-9]+" "\\1${major}" changed "${original_header}")
  string(REGEX REPLACE "(CUSTATEVEC_VER_(MINOR|PATCH)[ \t]+)[0-9]+" "\\10" changed "${changed}")
  file(WRITE "${header}" "${changed}")
  execute_process(COMMAND "${CMAKE_COMMAND}"
    -S "${QUEST_SOURCE_DIR}/tests/packaging/consumer" -B "${work}/${case}"
    -C "${work}/consumer/initial.cmake"
    RESULT_VARIABLE result OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(result EQUAL 0 OR NOT "${out}${err}" MATCHES "QuEST requires cuStateVec")
    message(FATAL_ERROR "QuEST did not reject ${case} cuStateVec headers with its ABI diagnostic:\n${out}\n${err}")
  endif()
endforeach()
file(WRITE "${header}" "${original_header}")
