Quantum Exact Simulation Toolkit: QuEST_internal.h File Reference
GPU/QuEST_internal.h File Reference
Internal functions used to implement the public facing API in qubits.h.
#include "../QuEST_precision.h"
Functions
void exitWithError (int errorCode, const char *func)
REAL findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state.
unsigned long int hashString (char *str)
REAL measureInZero (MultiQubit multiQubit, const int measureQubit)
Update the state vector to be consistent with measuring measureQubit=0.
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void QuESTAssert (int isValid, int errorCode, const char *func)
int validateAlphaBeta (Complex alpha, Complex beta)
int validateMatrixIsUnitary (ComplexMatrix2 u)
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Variables
const char * errorCodes []
Detailed Description
Internal functions used to implement the public facing API in qubits.h.
Do not call these functions directly.
Definition in file GPU/QuEST_internal.h.
Function Documentation
exitWithError()
void exitWithError (int errorCode, const char * func)
Definition at line 232 of file QuEST_env_local.c.
References errorCodes.
Referenced by QuESTAssert().
{
     printf("!!!\n");
     printf("QuEST Error in function %s: %s\n", func, errorCodes[errorCode]);
     printf("!!!\n");
     printf("exiting..\n");
     exit(errorCode);
 }
findProbabilityOfZero()
REAL findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state.
Parameters
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
Definition at line 1217 of file QuEST_env_localGPU.cu.
References copySharedReduceBlock(), MultiQubit::firstLevelReduction, MultiQubit::numAmpsPerChunk, REAL, REDUCE_SHARED_SIZE, MultiQubit::secondLevelReduction, and swapDouble().
Referenced by findProbabilityOfOutcome(), and measureInZero().
 {
     long long int numValuesToReduce = multiQubit.numAmpsPerChunk>>1;
     int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
     REAL stateProb=0;
     int firstTime=1;
     int maxReducedPerLevel = REDUCE_SHARED_SIZE;
     while(numValuesToReduce>1){
         if (numValuesToReduce<maxReducedPerLevel){
             // Need less than one CUDA block to reduce values
             valuesPerCUDABlock = numValuesToReduce;
             numCUDABlocks = 1;
         } else {
             // Use full CUDA blocks, with block size constrained by shared mem usage
             valuesPerCUDABlock = maxReducedPerLevel;
             numCUDABlocks = ceil((REAL)numValuesToReduce/valuesPerCUDABlock);
         }
         sharedMemSize = valuesPerCUDABlock*sizeof(REAL);
         if (firstTime){
             findProbabilityOfZeroKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                     multiQubit, measureQubit, multiQubit.firstLevelReduction);
             firstTime=0;
         } else {
             cudaDeviceSynchronize();
             copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                     multiQubit.firstLevelReduction,
                     multiQubit.secondLevelReduction, valuesPerCUDABlock);
             cudaDeviceSynchronize();
             swapDouble(&(multiQubit.firstLevelReduction), &(multiQubit.secondLevelReduction));
         }
         numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
     }
     cudaMemcpy(&stateProb, multiQubit.firstLevelReduction, sizeof(REAL), cudaMemcpyDeviceToHost);
     return stateProb;
 }
hashString()
unsigned long int hashString (char * str)
Definition at line 2026 of file QuEST.c.
Referenced by seedQuESTDefault().
{
     unsigned long int hash = 5381;
     int c;
     while ((c = *str++))
         hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
     return hash;
 }
measureInZero()
REAL measureInZero (MultiQubit multiQubit, const int measureQubit)
Update the state vector to be consistent with measuring measureQubit=0.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that a zero have been measured on the qubit indicated by measureQubit (where his label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0. It then returns the probability of making this measurement.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
Definition at line 1388 of file QuEST_env_localGPU.cu.
References findProbabilityOfZero(), MultiQubit::numAmpsPerChunk, and REAL.
 {
     REAL stateProb;
     stateProb = findProbabilityOfZero(multiQubit, measureQubit);
     int threadsPerCUDABlock, CUDABlocks;
     threadsPerCUDABlock = 128;
     CUDABlocks = ceil((REAL)(multiQubit.numAmpsPerChunk>>1)/threadsPerCUDABlock);
     if (stateProb!=0) measureInZeroKernel<<<CUDABlocks, threadsPerCUDABlock>>>(multiQubit, measureQubit, stateProb);
     return stateProb;
 }
phaseGate()
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 163 of file QuEST_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, phaseGateDistributed(), phaseGateLocal(), QuESTAssert(), and REAL.
Referenced by sGate(), sigmaZ(), and tGate().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     phaseGateLocal(multiQubit, targetQubit, type);
 }
QuESTAssert()
void QuESTAssert (int isValid, int errorCode, const char * func)
Definition at line 240 of file QuEST_env_local.c.
References exitWithError().
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledPhaseGate(), controlledUnitary(), createMultiQubit(), findProbabilityOfOutcome(), hadamard(), initializeStateFromSingleFile(), measure(), measureWithStats(), multiControlledPhaseGate(), multiControlledUnitary(), phaseGate(), reportState(), sigmaX(), sigmaY(), and unitary().
{
     if (!isValid) exitWithError(errorCode, func);
 }
validateAlphaBeta()
int validateAlphaBeta (Complex alpha, Complex beta)
Definition at line 415 of file QuEST.c.
References Complex::imag, Complex::real, and REAL_EPS.
Referenced by compactUnitary(), and controlledCompactUnitary().
{
     if ( fabs(alpha.real*alpha.real
                 + alpha.imag*alpha.imag
                 + beta.real*beta.real
                 + beta.imag*beta.imag - 1) > REAL_EPS ) return 0;
     else return 1;
 }
validateMatrixIsUnitary()
int validateMatrixIsUnitary (ComplexMatrix2 u)
Definition at line 391 of file QuEST.c.
References Complex::imag, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, and REAL_EPS.
Referenced by controlledUnitary(), multiControlledUnitary(), and unitary().
{
     if ( fabs(u.r0c0.real*u.r0c0.real
                 + u.r0c0.imag*u.r0c0.imag
                 + u.r1c0.real*u.r1c0.real
                 + u.r1c0.imag*u.r1c0.imag - 1) > REAL_EPS ) return 0;
     if ( fabs(u.r0c1.real*u.r0c1.real
                 + u.r0c1.imag*u.r0c1.imag
                 + u.r1c1.real*u.r1c1.real
                 + u.r1c1.imag*u.r1c1.imag - 1) > REAL_EPS ) return 0;
     if ( fabs(u.r0c0.real*u.r0c1.real
                 + u.r0c0.imag*u.r0c1.imag
                 + u.r1c0.real*u.r1c1.real
                 + u.r1c0.imag*u.r1c1.imag) > REAL_EPS ) return 0;
     if ( fabs(u.r0c1.real*u.r0c0.imag
                 - u.r0c0.real*u.r0c1.imag
                 + u.r1c1.real*u.r1c0.imag
                 - u.r1c0.real*u.r1c1.imag) > REAL_EPS ) return 0;
     return 1;
 }
validateUnitVector()
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Definition at line 423 of file QuEST.c.
References REAL_EPS.
{
     if ( fabs(sqrt(ux*ux + uy*uy + uz*uz) - 1) > REAL_EPS ) return 0;
     else return 1;
 }
Variable Documentation
errorCodes
const char* errorCodes[]
Definition at line 27 of file QuEST.c.
Referenced by exitWithError().