Distributed QUEST: qubits_env_wrapper.h File Reference
qubits_env_wrapper.h File Reference
Specifications for QUEST library functions whose implementation depends on environment (local, MPI)
Functions
void initQUESTEnv (QUESTEnv *env)
void closeQUESTEnv (QUESTEnv env)
void syncQUESTEnv (QUESTEnv env)
double calcTotalProbability (MultiQubit multiQubit)
void rotateQubit (MultiQubit multiQubit, const int rotQubit, Complex alpha, Complex beta)
double findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Detailed Description
Specifications for QUEST library functions whose implementation depends on environment (local, MPI)
Definition in file qubits_env_wrapper.h.
Function Documentation
double calcTotalProbability (MultiQubit multiQubit)
Definition at line 43 of file qubits_env_local.c.
References DEBUG, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, and MultiQubit::stateVec.
Referenced by main().
{
         double pTotal=0;
         long long int index;
         long long int numAmpsPerRank = multiQubit.numAmps;
         for (index=0; index<numAmpsPerRank; index++){
                 pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index];
                 pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index];
         }
         return pTotal;
 }
void closeQUESTEnv (QUESTEnv env)
Definition at line 20 of file qubits_env_local.c.
Referenced by main().
{
         // MPI finalize goes here in MPI version. Call this function anyway for consistency
 }
double findProbabilityOfZero (MultiQubit multiQubit, const int measureQubit)
Definition at line 94 of file qubits_env_local.c.
References MultiQubit::chunkId, findProbabilityOfZeroDistributed(), findProbabilityOfZeroLocal(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), and MultiQubit::numAmps.
 {
         double stateProb=0;
         stateProb = findProbabilityOfZeroLocal(multiQubit, measureQubit);
         return stateProb;
 }
void initQUESTEnv (QUESTEnv * env)
Definition at line 9 of file qubits_env_local.c.
References DEBUG, QUESTEnv::numRanks, and QUESTEnv::rank.
Referenced by main().
{
         // init MPI environment
         int rank, numRanks;
         env->rank=0;
         env->numRanks=1;
 }
void rotateQubit (MultiQubit multiQubit, const int rotQubit, Complex alpha, Complex beta)
Definition at line 75 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), ComplexArray::imag, MultiQubit::numAmps, MultiQubit::pairStateVec, ComplexArray::real, rotateQubitDistributed(), rotateQubitLocal(), and MultiQubit::stateVec.
Referenced by main().
 {
         // all values required to update state vector lie in this rank
         rotateQubitLocal(multiQubit, rotQubit, alpha, beta);
 }
void syncQUESTEnv (QUESTEnv env)
Definition at line 16 of file qubits_env_local.c.
{
         // MPI Barrier goes here in MPI version.
 }