Distributed QuEST: qubits.h File Reference
qubits.h File Reference
The QuEST library API and objects.
#include "precision.h"
Data Structures
struct ComplexArray
Represents an array of complex numbers grouped into an array of real components and an array of coressponding complex components.
struct Complex
Represents one complex number.
struct ComplexMatrix2
Represents a 2x2 matrix of complex numbers.
struct Vector
Represents a 3-vector of real numbers.
struct MultiQubit
Represents a system of qubits.
struct QuESTEnv
Information about the environment the program is running in.
Enumerations
enum phaseGateType { SIGMA_Z = 0, S_GATE = 1, T_GATE = 2 }
Functions
void createMultiQubit (MultiQubit *multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits.
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void initStateZero (MultiQubit *multiQubit)
Initialise a set of qubits to the classical zero state .
void initStatePlus (MultiQubit *multiQubit)
Initialise a set of qubits to the plus state .
void multiControlledPhaseGate (MultiQubit multiQubit, int *controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase gate, also known as the multiple-qubit controlled sigmaZ gate.
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase gate, also known as the controlled sigmaZ gate.
void sGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit S gate.
void tGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit T gate.
void initQuESTEnv (QuESTEnv *env)
Initialize the QuEST environment.
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode).
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get the probability of the state at an index in the full state vector.
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
void controlledRotateX (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
void controlledRotateY (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
void controlledRotateZ (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
void controlledRotateAroundAxis (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
void multiControlledUnitary (MultiQubit multiQubit, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Z (also known as the Z, Pauli-Z or phase-flip) gate.
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL *stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Detailed Description
The QuEST library API and objects.
Definition in file qubits.h.
Enumeration Type Documentation
enum phaseGateType
Enumerator:
SIGMA_Z
S_GATE
T_GATE
Definition at line 73 of file qubits.h.
{SIGMA_Z=0, S_GATE=1, T_GATE=2};
Function Documentation
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
Should be equal to 1.
Parameters:
[in] multiQubit object representing a set of qubits
Returns:
total probability
Definition at line 64 of file qubits_env_local.c.
References DEBUG, ComplexArray::imag, MPI_QuEST_REAL, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
  /* IJB - implemented using Kahan summation for greater accuracy at a slight floating
     point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm */
  /* Don't change the bracketing in this routine! */
  REAL pTotal=0;
  REAL y, t, c;
  long long int index;
  long long int numAmpsPerRank = multiQubit.numAmps;
  c = 0.0;
  for (index=0; index<numAmpsPerRank; index++){
    /* Perform pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index]; by Kahan */
   // pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index];
    y = multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index] - c;
    t = pTotal + y;
    c = ( t - pTotal ) - y;
    pTotal = t;
    /* Perform pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index]; by Kahan */
    //pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index];
    y = multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index] - c;
    t = pTotal + y;
    c = ( t - pTotal ) - y;
    pTotal = t;
  }
  return pTotal;
}
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 43 of file qubits_env_local.c.
{
        // MPI finalize goes here in MPI version. Call this function anyway for consistency
}
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a measurement and forcing the outcome. This is an irreversible change to the state vector, whereby incompatible states in the state vector are given zero amplitude and the remaining states are renormalised. Exits with error if the given outcome has ~zero probability, and so cannot be collapsed into.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns:
probability of the (forced) measurement outcome
Exceptions:
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}, or if the probability of outcome is zero (within machine epsilon)
Definition at line 198 of file qubits_env_local.c.
References MultiQubit::chunkId, collapseToOutcomeDistributedRenorm(), collapseToOutcomeDistributedSetZero(), collapseToOutcomeLocal(), findProbabilityOfOutcome(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert((outcome==0 || outcome==1), 10, __func__);
    REAL stateProb;
        stateProb = findProbabilityOfOutcome(multiQubit, measureQubit, outcome);
    QuESTAssert(fabs(stateProb)>REAL_EPS, 8, __func__);
    collapseToOutcomeLocal(multiQubit, measureQubit, stateProb, outcome);
    return stateProb;
}
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
Given valid complex numbers and , applies the unitary
which is general up to a global phase factor. Valid , satisfy .
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 104 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), compactUnitaryDistributed(), compactUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateAlphaBeta().
Referenced by rotateAroundAxis().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
        // all values required to update state vector lie in this rank
        compactUnitaryLocal(multiQubit, targetQubit, alpha, beta);
}
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
Given valid complex numbers and , applies the two-qubit unitary
to the control and target qubits. Valid , satisfy . The target unitary is general up to a global phase factor.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply the target unitary if this qubit has value 1
[in] targetQubit qubit on which to apply the target unitary
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 122 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledCompactUnitaryDistributed(), controlledCompactUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateAlphaBeta().
Referenced by controlledRotateAroundAxis().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
    QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
        controlledCompactUnitaryLocal(multiQubit, controlQubit, targetQubit, alpha, beta);
}
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
This applies sigmaX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits), or are equal.
Definition at line 181 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledNotDistributed(), controlledNotLocal(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), and MultiQubit::stateVec.
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
        controlledNotLocal(multiQubit, controlQubit, targetQubit);
}
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase gate, also known as the controlled sigmaZ gate.
For each state, if both input qubits have value one, multiply the amplitude of that state by -1. This applies the two-qubit unitary:
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] idQubit1,idQubit2 qubits to operate upon
Exceptions:
exitWithError if idQubit1 or idQubit2 are outside [0, multiQubit.numQubits), or are equal
Definition at line 1729 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), ComplexArray::real, REAL, and MultiQubit::stateVec.
{
        long long int index;
        long long int stateVecSize;
        int bit1, bit2;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
    QuESTAssert(idQubit1 >= 0 && idQubit1 < multiQubit.numQubits, 2, __func__);
    QuESTAssert(idQubit2 >= 0 && idQubit2 < multiQubit.numQubits, 1, __func__);
    QuESTAssert(idQubit1 != idQubit2, 3, __func__);
        // dimension of the state vector
        stateVecSize = multiQubit.numAmps;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel for \
        default  (none)                      \
        shared   (stateVecSize, stateVecReal,stateVecImag ) \
        private  (index,bit1,bit2)                     \
        schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
                bit1 = extractBit (idQubit1, index+chunkId*chunkSize);
                bit2 = extractBit (idQubit2, index+chunkId*chunkSize);
                if (bit1 && bit2) {
                        stateVecReal [index] = - stateVecReal [index];
                        stateVecImag [index] = - stateVecImag [index];
                }
        }
}
void controlledRotateAroundAxis (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies to states where the target qubit is 1 (is the vector of Pauli matrices).
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit with value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal or if axis is the zero vector
Definition at line 682 of file qubits.h.
References controlledCompactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
{
        double mag = sqrt(pow(axis.x,2) + pow(axis.y,2) + pow(axis.z,2));
        Vector unitAxis = {axis.x/mag, axis.y/mag, axis.z/mag};
        Complex alpha, beta;
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = sin(angle/2.0)*unitAxis.y;
        beta.imag = -sin(angle/2.0)*unitAxis.x;
        controlledCompactUnitary(multiQubit, controlQubit, targetQubit, alpha, beta);
}
void controlledRotateX (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 572 of file qubits.h.
References controlledRotateAroundAxis().
{
        Vector unitAxis = {1, 0, 0};
        controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
}
void controlledRotateY (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 607 of file qubits.h.
References controlledRotateAroundAxis().
{
        Vector unitAxis = {0, 1, 0};
        controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
}
void controlledRotateZ (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 642 of file qubits.h.
References controlledRotateAroundAxis().
{
        Vector unitAxis = {0, 0, 1};
        controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
}
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
The given unitary is applied to the target qubit if the control qubit has value 1, effecting the two-qubit unitary
on the control and target qubits.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply unitary if this qubit is 1
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions:
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if u is not unitary.
Definition at line 133 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledUnitaryDistributed(), controlledUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
        controlledUnitaryLocal(multiQubit, controlQubit, targetQubit, u);
}
void createMultiQubit (MultiQubit * multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
Allocate space for state vector of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. initStateZero should be called after this to initialise the qubits to the zero state.
Parameters:
[in,out] multiQubit a pointer to an object representing the set of qubits
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions:
exitWithError if numQubits <= 0
Definition at line 39 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, MultiQubit::numQubits, QuESTEnv::numRanks, MultiQubit::pairStateVec, QuESTAssert(), QuESTEnv::rank, ComplexArray::real, and MultiQubit::stateVec.
{
    QuESTAssert(numQubits>0, 9, __func__);
        long long int numAmps = 1L << numQubits;
        long long int numAmpsPerRank = numAmps/env.numRanks;
        multiQubit->stateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.real)));
        multiQubit->stateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.imag)));
        if (env.numRanks>1){
                multiQubit->pairStateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.real)));
                multiQubit->pairStateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.imag)));
        }
        if ( (!(multiQubit->stateVec.real) || !(multiQubit->stateVec.imag))
                 && numAmpsPerRank ) {
                printf("Could not allocate memory!");
                exit (EXIT_FAILURE);
        }
        if ( env.numRanks>1 && (!(multiQubit->pairStateVec.real) || !(multiQubit->pairStateVec.imag))
                 && numAmpsPerRank ) {
                printf("Could not allocate memory!");
                exit (EXIT_FAILURE);
        }
        multiQubit->numQubits = numQubits;
        multiQubit->numAmps = numAmpsPerRank;
        multiQubit->chunkId = env.rank;
        multiQubit->numChunks = env.numRanks;
}
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits.
Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
Parameters:
[in,out] multiQubit object to be deallocated
[in] env object representing the execution environment (local, multinode etc)
Definition at line 71 of file qubits.c.
References ComplexArray::imag, QuESTEnv::numRanks, MultiQubit::pairStateVec, ComplexArray::real, and MultiQubit::stateVec.
{
        free(multiQubit.stateVec.real);
        free(multiQubit.stateVec.imag);
        if (env.numRanks>1){
                free(multiQubit.pairStateVec.real);
                free(multiQubit.pairStateVec.imag);
        }
}
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
This performs no actual measurement and does not change the state of the qubits.
Parameters:
[in] multiQubit object representing the set of all qubits
[in] measureQubit qubit to study
[in] outcome for which to find the probability of the qubit being measured in
Returns:
probability of qubit measureQubit being measured in the given outcome
Exceptions:
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}.
Definition at line 189 of file qubits_env_local.c.
References MultiQubit::chunkId, findProbabilityOfZeroDistributed(), findProbabilityOfZeroLocal(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MPI_QuEST_REAL, MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), and REAL.
Referenced by collapseToOutcome(), and measureWithStats().
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
        REAL stateProb=0;
        stateProb = findProbabilityOfZeroLocal(multiQubit, measureQubit);
        if (outcome==1) stateProb = 1.0 - stateProb;
        return stateProb;
}
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
Definition at line 131 of file qubits.c.
References MultiQubit::numQubits, and QuESTEnv::numRanks.
{
        int numThreads=1;
# ifdef _OPENMP
        numThreads=omp_get_max_threads();
# endif
        sprintf(str, "%dqubits_CPU_%dranksx%dthreads", multiQubit.numQubits, env.numRanks, numThreads);
}
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
imaginary component at that index
Exceptions:
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 100 of file qubits_env_local.c.
References MultiQubit::chunkId, getChunkIdFromIndex(), ComplexArray::imag, MPI_QuEST_REAL, MultiQubit::numAmps, REAL, and MultiQubit::stateVec.
Referenced by getProbEl().
{
        return multiQubit.stateVec.imag[index];
}
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get the probability of the state at an index in the full state vector.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
realEl*realEl + imagEl*imagEl
Exceptions:
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 1971 of file qubits.c.
References getImagAmpEl(), getRealAmpEl(), and REAL.
{
        REAL real;
        REAL imag;
        real = getRealAmpEl(multiQubit, index);
        imag = getImagAmpEl(multiQubit, index);
        return real*real + imag*imag;
}
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
real component at that index
Exceptions:
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 96 of file qubits_env_local.c.
References MultiQubit::chunkId, getChunkIdFromIndex(), MPI_QuEST_REAL, MultiQubit::numAmps, REAL, ComplexArray::real, and MultiQubit::stateVec.
Referenced by getProbEl().
{
        return multiQubit.stateVec.real[index];
}
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
This takes to and to , and is equivalent to a rotation of around the x-axis then about the y-axis on the Bloch-sphere. I.e.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 175 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), hadamardDistributed(), hadamardLocal(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), and MultiQubit::stateVec.
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        hadamardLocal(multiQubit, targetQubit);
}
void initQuESTEnv (QuESTEnv * env)
Initialize the QuEST environment.
If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here
Parameters:
[in,out] env object representing the execution environment. A single instance is used for each program
Definition at line 22 of file qubits_env_local.c.
References DEBUG, init_by_array(), QuESTEnv::numRanks, and QuESTEnv::rank.
{
        // init MPI environment
        env->rank=0;
        env->numRanks=1;
    // init MT random number generator with two keys -- time and pid
    unsigned long int secs = time(NULL);
    unsigned long int pid = getpid();
    unsigned long int key[2];
    key[0] = secs; key[1] = pid;
    init_by_array(key, 2);
}
void initStatePlus (MultiQubit * multiQubit)
Initialise a set of qubits to the plus state .
This is the product state of qubits where every classical state is uniformly populated with real coefficient . This is equivalent to applying a Hadamard to every qubit in the zero state:
Parameters:
[in,out] multiQubit a pointer to the object representing the set of qubits to be initialised
Definition at line 177 of file qubits.c.
References DEBUG, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
        long long int chunkSize, stateVecSize;
        long long int index;
        // dimension of the state vector
        chunkSize = multiQubit->numAmps;
        stateVecSize = chunkSize*multiQubit->numChunks;
        REAL normFactor = 1.0/sqrt((REAL)stateVecSize);
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (chunkSize, stateVecReal, stateVecImag, normFactor) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<chunkSize; index++) {
                        stateVecReal[index] = normFactor;
                        stateVecImag[index] = 0.0;
                }
        }
        if (DEBUG) printf("COMPLETED INIT\n");
}
void initStateZero (MultiQubit * multiQubit)
Initialise a set of qubits to the classical zero state .
Parameters:
[in,out] multiQubit a pointer to the object representing the set of all qubits to initialise
Definition at line 139 of file qubits.c.
References MultiQubit::chunkId, DEBUG, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
        long long int stateVecSize;
        long long int index;
        // dimension of the state vector
        stateVecSize = multiQubit->numAmps;
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecSize, stateVecReal, stateVecImag) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<stateVecSize; index++) {
                        stateVecReal[index] = 0.0;
                        stateVecImag[index] = 0.0;
                }
        }
        if (multiQubit->chunkId==0){
                // zero state |0000..0000> has probability 1
                stateVecReal[0] = 1.0;
                stateVecImag[0] = 0.0;
        }
        if (DEBUG) printf("COMPLETED INIT\n");
}
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
Returns:
the measurement outcome, 0 or 1
Exceptions:
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 209 of file qubits_env_local.c.
References measureWithStats(), MultiQubit::numQubits, QuESTAssert(), and REAL.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    REAL stateProb;
    return measureWithStats(multiQubit, measureQubit, &stateProb);
}
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL * stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[out] stateProb a pointer to a REAL which is set to the probability of the occurred outcome
Returns:
the measurement outcome, 0 or 1
Exceptions:
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 215 of file qubits_env_local.c.
References MultiQubit::chunkId, collapseToOutcomeDistributedRenorm(), collapseToOutcomeDistributedSetZero(), collapseToOutcomeLocal(), findProbabilityOfOutcome(), genrand_real1(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
Referenced by measure().
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    int outcome;
    // find probability of qubit being in state 1
        REAL stateProbInternal = findProbabilityOfOutcome(multiQubit, measureQubit, 1);
    // we can't collapse to a state that has a probability too close to zero
    if (stateProbInternal<REAL_EPS) outcome=0;
    else if (1-stateProbInternal<REAL_EPS) outcome=1;
    else {
        // ok. both P(0) and P(1) are large enough to resolve
        // generate random float on [0,1]
        float randNum = genrand_real1();
        if (randNum<=stateProbInternal) outcome = 1;
        else outcome = 0;
    }
    if (outcome==0) stateProbInternal = 1-stateProbInternal;
    collapseToOutcomeLocal(multiQubit, measureQubit, stateProbInternal, outcome);
    *stateProb = stateProbInternal;
    return outcome;
}
void multiControlledPhaseGate (MultiQubit multiQubit, int * controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase gate, also known as the multiple-qubit controlled sigmaZ gate.
For each state, if all control qubits have value one, multiply the amplitude of that state by -1. This applies the many-qubit unitary:
on the control qubits.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubits array of input qubits
[in] numControlQubits number of input qubits
Exceptions:
exitWithError if numControlQubits is outside [1, multiQubit.numQubits)
Definition at line 1764 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), ComplexArray::real, REAL, and MultiQubit::stateVec.
{
        long long int index;
        long long int stateVecSize;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
    QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
        stateVecSize = multiQubit.numAmps;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none)                      \
        shared   (stateVecSize, stateVecReal,stateVecImag, mask ) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<stateVecSize; index++) {
                        if (mask == (mask & (index+chunkId*chunkSize)) ){
                                stateVecReal [index] = - stateVecReal [index];
                                stateVecImag [index] = - stateVecImag [index];
                        }
                }
        }
}
void multiControlledUnitary (MultiQubit multiQubit, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits. The given 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] controlQubits applies unitary if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions:
exitWithError if numControlQubits is outside [1, multiQubit.numQubits]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, multiQubit.numQubits]), or if controlQubits contains targetQubit, or if u is not unitary.
Definition at line 143 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), multiControlledUnitaryDistributed(), multiControlledUnitaryLocal(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
    QuESTAssert((mask & (1LL<<targetQubit)) != (1LL<<targetQubit), 3, __func__);
    multiControlledUnitaryLocal(multiQubit, targetQubit, mask, u);
}
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] env object representing the execution environment (local, multinode etc)
Definition at line 120 of file qubits.c.
References MultiQubit::chunkId, MultiQubit::numChunks, and MultiQubit::numQubits.
{
        long long int numAmps = 1L << multiQubit.numQubits;
        long long int numAmpsPerRank = numAmps/multiQubit.numChunks;
        if (multiQubit.chunkId==0){
                printf("QUBITS:\n");
                printf("Number of qubits is %d.\n", multiQubit.numQubits);
                printf("Number of amps is %lld.\n", numAmps);
                printf("Number of amps per rank is %lld.\n", numAmpsPerRank);
        }
}
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 47 of file qubits_env_local.c.
References QuESTEnv::numRanks, QuESTEnv::rank, and REAL.
{
        printf("EXECUTION ENVIRONMENT:\n");
        printf("Running locally on one node\n");
        printf("Number of ranks is %d\n", env.numRanks);
# ifdef _OPENMP
        printf("OpenMP enabled\n");
        printf("Number of threads available is %d\n", omp_get_max_threads());
# else
        printf("OpenMP disabled\n");
# endif
        printf("Precision: size of REAL is %ld bytes\n", sizeof(REAL));
}
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
File format:
real, imag
realComponent1, imagComponent1
realComponent2, imagComponent2
...
realComponentN, imagComponentN
File naming convention:
For each node that the program runs on, a file 'state_rank_[node_rank].csv' is generated. If there is more than one node, ranks after the first do not include the header
real, imag
so that files are easier to combine.
Parameters:
[in,out] multiQubit object representing the set of qubits
Definition at line 81 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL_STRING_FORMAT, and MultiQubit::stateVec.
{
        FILE *state;
        char filename[100];
        long long int index;
        sprintf(filename, "state_rank_%d.csv", multiQubit.chunkId);
        state = fopen(filename, "w");
        if (multiQubit.chunkId==0) fprintf(state, "real, imag\n");
        for(index=0; index<multiQubit.numAmps; index++){
                fprintf(state, REAL_STRING_FORMAT "," REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
        }
        fclose(state);
}
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 95 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, MultiQubit::numQubits, ComplexArray::real, REAL_STRING_FORMAT, MultiQubit::stateVec, and syncQuESTEnv().
{
        long long int index;
        int rank;
        if (multiQubit.numQubits<=5){
                for (rank=0; rank<multiQubit.numChunks; rank++){
                        if (multiQubit.chunkId==rank){
                                if (reportRank) {
                                        printf("Reporting state from rank %d [\n", multiQubit.chunkId);
                                        //printf("\trank, index, real, imag\n");
                                        printf("real, imag\n");
                                } else if (rank==0) {
                                        printf("Reporting state [\n");
                                        printf("real, imag\n");
                                }
                                for(index=0; index<multiQubit.numAmps; index++){
                                        printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
                                }
                                if (reportRank || rank==multiQubit.numChunks-1) printf("]\n");
                        }
                        syncQuESTEnv(env);
                }
        } else printf("Error: reportStateToScreen will not print output for systems of more than 5 qubits.\n");
}
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies where is the vector of Pauli matrices.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions:
exitWithError if rotQubit is outside [0, multiQubit.numQubits), or if axis is the zero vector
Definition at line 382 of file qubits.c.
References compactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
Referenced by rotateX(), rotateY(), and rotateZ().
{
        double mag = sqrt(pow(axis.x,2) + pow(axis.y,2) + pow(axis.z,2));
        Vector unitAxis = {axis.x/mag, axis.y/mag, axis.z/mag};
        Complex alpha, beta;
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = sin(angle/2.0)*unitAxis.y;
        beta.imag = -sin(angle/2.0)*unitAxis.x;
        compactUnitary(multiQubit, rotQubit, alpha, beta);
}
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
For angle , applies
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions:
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 395 of file qubits.c.
References rotateAroundAxis().
{
        Vector unitAxis = {1, 0, 0};
        rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
}
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
For angle , applies
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions:
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 401 of file qubits.c.
References rotateAroundAxis().
{
        Vector unitAxis = {0, 1, 0};
        rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
}
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
For angle , applies
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions:
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 407 of file qubits.c.
References rotateAroundAxis().
{
        Vector unitAxis = {0, 0, 1};
        rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
}
void sGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit S gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits)
Definition at line 1580 of file qubits.c.
References phaseGate(), and S_GATE.
{
                phaseGate(multiQubit, targetQubit, S_GATE);
}
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
This is a rotation of around the x-axis on the Bloch sphere. I.e.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 157 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), sigmaXDistributed(), sigmaXLocal(), and MultiQubit::stateVec.
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        sigmaXLocal(multiQubit, targetQubit);
}
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
This is a rotation of around the Y-axis on the Bloch sphere. I.e.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
fix -- put duplicate code (sigmaX, sigmaY) in seperate function
Definition at line 163 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), sigmaYDistributed(), sigmaYLocal(), and MultiQubit::stateVec.
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        sigmaYLocal(multiQubit, targetQubit);
}
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Z (also known as the Z, Pauli-Z or phase-flip) gate.
This is a rotation of around the Z-axis (a phase shift) on the Bloch sphere. I.e.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 1575 of file qubits.c.
References phaseGate(), and SIGMA_Z.
{
                phaseGate(multiQubit, targetQubit, SIGMA_Z);
}
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode).
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 35 of file qubits_env_local.c.
Referenced by initializeStateFromSingleFile(), and reportStateToScreen().
{
        // MPI Barrier goes here in MPI version.
}
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns:
1 if all processes succeeded, 0 if any one process failed
Definition at line 39 of file qubits_env_local.c.
{
        return successCode;
}
void tGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit T gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits)
Definition at line 1585 of file qubits.c.
References phaseGate(), and T_GATE.
{
                phaseGate(multiQubit, targetQubit, T_GATE);
}
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters:
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions:
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or matrix u is not unitary.
Definition at line 113 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, unitaryDistributed(), unitaryLocal(), and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
        // all values required to update state vector lie in this rank
        unitaryLocal(multiQubit, targetQubit, u);
}