Distributed QuEST: qubits_env_local.c File Reference
qubits_env_local.c File Reference
An implementation of the API in qubits.h for a local (non-MPI) environment.
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <omp.h>
#include "precision.h"
#include "qubits.h"
#include "qubits_internal.h"
#include "mt19937ar.h"
#include <time.h>
#include <sys/types.h>
#include <unistd.h>
Functions
void initQuESTEnv (QuESTEnv *env)
Initialize QuEST environment.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes.
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the probability amplitude at an index in the state vector.
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the probability amplitude at an index in the state vector.
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a unitary operation to a single qubit given a control qubit Only perform the rotation for elements where the control qubit is one.
void multiControlledUnitary (MultiQubit multiQubit, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a unitary operation to a single qubit given an array of control qubits Only perform the rotation for elements where all control qubits equal 1.
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0}} -- swap |0> and |1>.
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}} -- swap |0> and |1> and apply a phase of -i or i.
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
void hadamard (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2 -- turn a |0> into a |+> and a |1> into a |->.
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}} -- swap |0> and |1> and apply a phase of -i or i, only for elements when control qubit is 1.
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Find the probability of a specified qubit being in the zero or one state.
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 or measureQubit=1 according to the value of outcome.
int measure (MultiQubit multiQubit, int measureQubit)
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL *stateProb)
void exitWithError (int errorCode, const char *func)
void QuESTAssert (int isValid, int errorCode, const char *func)
Detailed Description
An implementation of the API in qubits.h for a local (non-MPI) environment.
Definition in file qubits_env_local.c.
Function Documentation
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
Should be equal to 1.
Parameters:
[in] multiQubit object representing a set of qubits
Returns:
total probability
Definition at line 61 of file qubits_env_local.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
  /* IJB - implemented using Kahan summation for greater accuracy at a slight floating
     point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm */
  /* Don't change the bracketing in this routine! */
  REAL pTotal=0;
  REAL y, t, c;
  long long int index;
  long long int numAmpsPerRank = multiQubit.numAmps;
  c = 0.0;
  for (index=0; index<numAmpsPerRank; index++){
    /* Perform pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index]; by Kahan */
   // pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index];
    y = multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index] - c;
    t = pTotal + y;
    c = ( t - pTotal ) - y;
    pTotal = t;
    /* Perform pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index]; by Kahan */
    //pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index];
    y = multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index] - c;
    t = pTotal + y;
    c = ( t - pTotal ) - y;
    pTotal = t;
  }
  return pTotal;
}
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 40 of file qubits_env_local.c.
{
        // MPI finalize goes here in MPI version. Call this function anyway for consistency
}
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 or measureQubit=1 according to the value of outcome.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that an outcome has been measured on the qubit indicated by measureQubit (where his label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 if outcome=0 or measureQubit=1 if outcome=1. It then returns the probability of making this measurement.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] outcome to measure the probability of and set the state to -- either zero or one
Returns:
probability of qubit measureQubit being either zero or one
Definition at line 195 of file qubits_env_local.c.
References collapseToOutcomeLocal(), findProbabilityOfOutcome(), MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    REAL stateProb;
        stateProb = findProbabilityOfOutcome(multiQubit, measureQubit, outcome);
    QuESTAssert(fabs(stateProb>REAL_EPS), 8, __func__);
    collapseToOutcomeLocal(multiQubit, measureQubit, stateProb, outcome);
    return stateProb;
}
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
Given two complex numbers alpha and beta, applies the operation
[alpha, -beta*
beta, alpha*]
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
alpha, beta must obey |alpha|^2 + |beta|^2 = 1
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 101 of file qubits_env_local.c.
References compactUnitaryLocal(), MultiQubit::numQubits, QuESTAssert(), and validateAlphaBeta().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
        // all values required to update state vector lie in this rank
        compactUnitaryLocal(multiQubit, targetQubit, alpha, beta);
}
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
Given two complex numbers alpha and beta and a control qubit, applies the operation:
[alpha, -beta*
beta, alpha*]
Only when the control qubit is one.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
alpha, beta must obey |alpha|^2 + |beta|^2 = 1
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform rotation if this qubit is 1
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 119 of file qubits_env_local.c.
References controlledCompactUnitaryLocal(), MultiQubit::numQubits, QuESTAssert(), and validateAlphaBeta().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
    QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
        controlledCompactUnitaryLocal(multiQubit, controlQubit, targetQubit, alpha, beta);
}
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}} -- swap |0> and |1> and apply a phase of -i or i, only for elements when control qubit is 1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform sigmaX rotation if this qubit is 1
Definition at line 178 of file qubits_env_local.c.
References controlledNotLocal(), MultiQubit::numQubits, and QuESTAssert().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
        controlledNotLocal(multiQubit, controlQubit, targetQubit);
}
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a unitary operation to a single qubit given a control qubit Only perform the rotation for elements where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform rotation if this qubit is 1
[in] u unitary matrix to apply
Definition at line 130 of file qubits_env_local.c.
References controlledUnitaryLocal(), MultiQubit::numQubits, QuESTAssert(), and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
    QuESTAssert(controlQubit != targetQubit, 3, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
        controlledUnitaryLocal(multiQubit, controlQubit, targetQubit, u);
}
void exitWithError (int errorCode, const char * func)
Definition at line 234 of file qubits_env_local.c.
Referenced by QuESTAssert().
{
    printf("!!!\n");
    printf("QuEST Error in function %s: %s\n", func, errorCodes[errorCode]);
    printf("!!!\n");
    printf("exiting..\n");
    exit(errorCode);
}
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Find the probability of a specified qubit being in the zero or one state.
Parameters:
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] outcome to measure the probability of -- either zero or one
Returns:
probability of qubit measureQubit being either zero or one
Definition at line 186 of file qubits_env_local.c.
References findProbabilityOfZeroLocal(), MultiQubit::numQubits, QuESTAssert(), and REAL.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
        REAL stateProb=0;
        stateProb = findProbabilityOfZeroLocal(multiQubit, measureQubit);
        if (outcome==1) stateProb = 1.0 - stateProb;
        return stateProb;
}
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the probability amplitude at an index in the state vector.
For debugging purposes.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
imaginary component at that index
Definition at line 97 of file qubits_env_local.c.
References ComplexArray::imag, and MultiQubit::stateVec.
{
        return multiQubit.stateVec.imag[index];
}
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the probability amplitude at an index in the state vector.
For debugging purposes.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
real component at that index
Definition at line 93 of file qubits_env_local.c.
References ComplexArray::real, and MultiQubit::stateVec.
{
        return multiQubit.stateVec.real[index];
}
void hadamard (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2 -- turn a |0> into a |+> and a |1> into a |->.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 172 of file qubits_env_local.c.
References hadamardLocal(), MultiQubit::numQubits, and QuESTAssert().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        hadamardLocal(multiQubit, targetQubit);
}
void initQuESTEnv (QuESTEnv * env)
Initialize QuEST environment.
If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here
Parameters:
[in,out] env object representing the execution environment. A single instance is used for each program
Definition at line 19 of file qubits_env_local.c.
References init_by_array(), QuESTEnv::numRanks, and QuESTEnv::rank.
{
        // init MPI environment
        env->rank=0;
        env->numRanks=1;
    // init MT random number generator with two keys -- time and pid
    unsigned long int secs = time(NULL);
    unsigned long int pid = getpid();
    unsigned long int key[2];
    key[0] = secs; key[1] = pid;
    init_by_array(key, 2);
}
int measure (MultiQubit multiQubit, int measureQubit)
Definition at line 205 of file qubits_env_local.c.
References measureWithStats(), MultiQubit::numQubits, QuESTAssert(), and REAL.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    REAL stateProb;
    return measureWithStats(multiQubit, measureQubit, &stateProb);
}
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL * stateProb)
Definition at line 211 of file qubits_env_local.c.
References collapseToOutcomeLocal(), findProbabilityOfOutcome(), genrand_real1(), MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
{
    QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
    int outcome;
    // find probability of qubit being in state 1
        REAL stateProbInternal = findProbabilityOfOutcome(multiQubit, measureQubit, 1);
    // we can't collapse to a state that has a probability too close to zero
    if (stateProbInternal<REAL_EPS) outcome=0;
    else if (1-stateProbInternal<REAL_EPS) outcome=1;
    else {
        // ok. both P(0) and P(1) are large enough to resolve
        // generate random float on [0,1]
        float randNum = genrand_real1();
        if (randNum<=stateProbInternal) outcome = 1;
        else outcome = 0;
    }
    if (outcome==0) stateProbInternal = 1-stateProbInternal;
    collapseToOutcomeLocal(multiQubit, measureQubit, stateProbInternal, outcome);
    *stateProb = stateProbInternal;
    return outcome;
}
void multiControlledUnitary (MultiQubit multiQubit, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a unitary operation to a single qubit given an array of control qubits Only perform the rotation for elements where all control qubits equal 1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubits perform rotation if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] u unitary matrix to apply
Definition at line 140 of file qubits_env_local.c.
References multiControlledUnitaryLocal(), MultiQubit::numQubits, QuESTAssert(), and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
    QuESTAssert((mask & (1LL<<targetQubit)) != (1LL<<targetQubit), 3, __func__);
    multiControlledUnitaryLocal(multiQubit, targetQubit, mask, u);
}
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] type the type of phase gate to apply -- one of {SIGMA_Z, S_GATE, T_GATE}
Definition at line 166 of file qubits_env_local.c.
Referenced by sGate(), sigmaZ(), and tGate().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        phaseGateLocal(multiQubit, targetQubit, type);
}
void QuESTAssert (int isValid, int errorCode, const char * func)
Definition at line 242 of file qubits_env_local.c.
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledPhaseGate(), controlledUnitary(), createMultiQubit(), findProbabilityOfOutcome(), hadamard(), measure(), measureWithStats(), multiControlledPhaseGate(), multiControlledUnitary(), phaseGate(), sigmaX(), sigmaY(), and unitary().
{
    if (!isValid) exitWithError(errorCode, func);
}
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
For debugging purposes.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 57 of file qubits_env_local.c.
{
        printf("Hostname unknown: running locally\n");
}
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 44 of file qubits_env_local.c.
References QuESTEnv::numRanks, and REAL.
{
        printf("EXECUTION ENVIRONMENT:\n");
        printf("Running locally on one node\n");
        printf("Number of ranks is %d\n", env.numRanks);
# ifdef _OPENMP
        printf("OpenMP enabled\n");
        printf("Number of threads available is %d\n", omp_get_max_threads());
# else
        printf("OpenMP disabled\n");
# endif
        printf("Precision: size of REAL is %ld bytes\n", sizeof(REAL));
}
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0}} -- swap |0> and |1>.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 154 of file qubits_env_local.c.
References MultiQubit::numQubits, QuESTAssert(), and sigmaXLocal().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        sigmaXLocal(multiQubit, targetQubit);
}
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}} -- swap |0> and |1> and apply a phase of -i or i.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 160 of file qubits_env_local.c.
References MultiQubit::numQubits, QuESTAssert(), and sigmaYLocal().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        sigmaYLocal(multiQubit, targetQubit);
}
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 32 of file qubits_env_local.c.
{
        // MPI Barrier goes here in MPI version.
}
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns:
1 if all processes succeeded, 0 if any one process failed
Definition at line 36 of file qubits_env_local.c.
{
        return successCode;
}
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 110 of file qubits_env_local.c.
References MultiQubit::numQubits, QuESTAssert(), unitaryLocal(), and validateMatrixIsUnitary().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
    QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
        // all values required to update state vector lie in this rank
        unitaryLocal(multiQubit, targetQubit, u);
}