Distributed QuEST: qubits.c File Reference
qubits.c File Reference
The core of the QuEST Library.
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "precision.h"
#include "qubits.h"
#include "qubits_internal.h"
#include <omp.h>
Defines
#define DEBUG 0
Functions
static int extractBit (const int locationOfBitFromRight, const long long int theEncodedNumber)
Get the value of the bit at a particular index in a number.
void createMultiQubit (MultiQubit *multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
void initStateZero (MultiQubit *multiQubit)
Initialise the state vector of probability amplitudes for a set of qubits to the zero state: |000...00>.
void initStatePlus (MultiQubit *multiQubit)
Initialise the state vector of probability amplitudes for a set of qubits to an equal real superposition of all amplitudes: |+++.
void initStateOfSingleQubit (MultiQubit *multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
void initStateDebug (MultiQubit *multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
void initializeStateFromSingleFile (MultiQubit *multiQubit, char filename[200], QuESTEnv env)
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
int validateMatrixIsUnitary (ComplexMatrix2 u)
int validateAlphaBeta (Complex alpha, Complex beta)
int validateUnitVector (REAL ux, REAL uy, REAL uz)
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector unitAxis)
Rotate a single qubit a certain angle about an axis.
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the x-axis.
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the y-axis.
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the z-axis.
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0}.
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0} for elements where controlQubit is one.
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}.
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,0},{{0,-1}} -- apply a phase of -1 to |1>.
void sGate (MultiQubit multiQubit, const int targetQubit)
void tGate (MultiQubit multiQubit, const int targetQubit)
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
The control phase (the two qubit phase gate).
void multiControlledPhaseGate (MultiQubit multiQubit, int *controlQubits, int numControlQubits)
The multiple qubit control phase gate.
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get probability of the state at an index in the state vector.
Variables
const char * errorCodes []
Detailed Description
The core of the QuEST Library.
Definition in file qubits.c.
Define Documentation
#define DEBUG 0
Definition at line 15 of file qubits.c.
Referenced by calcTotalProbability(), exchangeStateVectors(), findProbabilityOfZeroLocal(), initQuESTEnv(), initStateOfSingleQubit(), initStatePlus(), and initStateZero().
Function Documentation
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that the value 'outcome' has been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles the renormalisation.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being zero
Definition at line 2073 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // (good for shared memory parallelism)
        REAL renorm=1/sqrt(totalProbability);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        stateVecReal[thisTask] = stateVecReal[thisTask]*renorm;
                        stateVecImag[thisTask] = stateVecImag[thisTask]*renorm;
                }
        }
        return totalProbability;
}
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that a zero have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles setting amplitudes to 0.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Definition at line 2116 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // (good for shared memory parallelism)
        // ---------------------------------------------------------------- //
        //            find probability                                      //
        // ---------------------------------------------------------------- //
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        stateVecReal[thisTask] = 0;
                        stateVecImag[thisTask] = 0;
                }
        }
}
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
Performs an irreversible change to the state vector: it updates the vector according to the event that an outcome have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1 according to the value of outcome. In the local version, one or more blocks (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) fit entirely into one chunk.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being either zero or one
[in] outcome to measure the probability of and set the state to -- either zero or one
Definition at line 1990 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- sizes
        long long int sizeBlock,                                           // size of blocks
        sizeHalfBlock;                                       // size of blocks halved
        // ----- indices
        long long int thisBlock,                                           // current block
             index;                                               // current index for first half block
        // ----- measured probability
        REAL   renorm;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        // (good for shared memory parallelism)
        long long int numTasks=multiQubit.numAmps>>1;
        // ---------------------------------------------------------------- //
        //            dimensions                                            //
        // ---------------------------------------------------------------- //
        sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
        // and then the number to skip
        sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
        renorm=1/sqrt(totalProbability);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default (none) \
        shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag,renorm,outcome) \
        private   (thisTask,thisBlock,index)
# endif
        {
                if (outcome==0){
                        // measure qubit is 0
# ifdef _OPENMP
                        # pragma omp for schedule  (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock = thisTask / sizeHalfBlock;
                                index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                stateVecReal[index]=stateVecReal[index]*renorm;
                                stateVecImag[index]=stateVecImag[index]*renorm;
                                stateVecReal[index+sizeHalfBlock]=0;
                                stateVecImag[index+sizeHalfBlock]=0;
                        }
                } else {
                        // measure qubit is 1
# ifdef _OPENMP
                        # pragma omp for schedule  (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock = thisTask / sizeHalfBlock;
                                index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                stateVecReal[index]=0;
                                stateVecImag[index]=0;
                                stateVecReal[index+sizeHalfBlock]=stateVecReal[index+sizeHalfBlock]*renorm;
                                stateVecImag[index+sizeHalfBlock]=stateVecImag[index+sizeHalfBlock]*renorm;
                        }
                }
        }
}
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 648 of file qubits.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by compactUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                        stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
                        stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
                }
        }
}
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 509 of file qubits.c.
References Complex::imag, ComplexArray::imag, MultiQubit::numAmps, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by compactUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL alphaImag=alpha.imag, alphaReal=alpha.real;
        REAL betaImag=beta.imag, betaReal=beta.real;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        // store current state vector values in temp variables
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                        stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                                - betaReal*stateRealLo - betaImag*stateImagLo;
                        stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                                - betaReal*stateImagLo + betaImag*stateRealLo;
                        // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
                        stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                                + alphaReal*stateRealLo + alphaImag*stateImagLo;
                        stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                                + alphaReal*stateImagLo - alphaImag*stateRealLo;
                }
        }
}
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
Definition at line 371 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
        REAL diff;
        int chunkSize = mq1.numAmps;
        for (int i=0; i<chunkSize; i++){
                diff = mq1.stateVec.real[i] - mq2.stateVec.real[i];
                if (diff<0) diff *= -1;
                if (diff>precision) return 0;
                diff = mq1.stateVec.imag[i] - mq2.stateVec.imag[i];
                if (diff<0) diff *= -1;
                if (diff>precision) return 0;
        }
        return 1;
}
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 993 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by controlledCompactUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                                // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
                                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
                        }
                }
        }
}
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
Only perform the rotation for elements where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform rotation if this qubit is 1
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 762 of file qubits.c.
References MultiQubit::chunkId, extractBit(), Complex::imag, ComplexArray::imag, MultiQubit::numAmps, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledCompactUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL alphaImag=alpha.imag, alphaReal=alpha.real;
        REAL betaImag=beta.imag, betaReal=beta.real;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                                stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                                        - betaReal*stateRealLo - betaImag*stateImagLo;
                                stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                                        - betaReal*stateImagLo + betaImag*stateRealLo;
                                // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
                                stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                                        + alphaReal*stateRealLo + alphaImag*stateImagLo;
                                stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                                        + alphaReal*stateImagLo - alphaImag*stateRealLo;
                        }
                }
        }
}
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk. Only perform the rotation for elements where controlQubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1340 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by controlledNot().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
        private  (thisTask,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
                                stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
                        }
                }
        }
}
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0} for elements where controlQubit is one.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
Definition at line 1274 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledNot().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit(controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateVecReal[indexUp] = stateVecReal[indexLo];
                                stateVecImag[indexUp] = stateVecImag[indexLo];
                                stateVecReal[indexLo] = stateRealUp;
                                stateVecImag[indexLo] = stateImagUp;
                        }
                }
        }
}
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
The control phase (the two qubit phase gate).
For each state, if both input qubits are equal to one, multiply the amplitude of that state by -1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] idQubit1,idQubit2 specified qubits
Definition at line 1898 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_controlledPhaseGate().
{
        long long int index;
        long long int stateVecSize;
        int bit1, bit2;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
    QuESTAssert(idQubit1 >= 0 && idQubit1 < multiQubit.numQubits, 2, __func__);
    QuESTAssert(idQubit2 >= 0 && idQubit2 < multiQubit.numQubits, 1, __func__);
    QuESTAssert(idQubit1 != idQubit2, 3, __func__);
        // dimension of the state vector
        stateVecSize = multiQubit.numAmps;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel for \
        default  (none)                      \
        shared   (stateVecSize, stateVecReal,stateVecImag ) \
        private  (index,bit1,bit2)                     \
        schedule (static)
# endif
        for (index=0; index<stateVecSize; index++) {
                bit1 = extractBit (idQubit1, index+chunkId*chunkSize);
                bit2 = extractBit (idQubit2, index+chunkId*chunkSize);
                if (bit1 && bit2) {
                        stateVecReal [index] = - stateVecReal [index];
                        stateVecImag [index] = - stateVecImag [index];
                }
        }
}
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1056 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by controlledUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                    + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                    + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                        }
                }
        }
}
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
Only perform the rotation for elements where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform rotation if this qubit is 1
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 914 of file qubits.c.
References MultiQubit::chunkId, extractBit(), Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                                stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                        + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                                stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                        + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                                // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                                stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                        + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                                stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                        + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                        }
                }
        }
}
void createMultiQubit (MultiQubit * multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
Allocate space for state vector of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Definition at line 41 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, MultiQubit::numQubits, QuESTEnv::numRanks, MultiQubit::pairStateVec, QuESTAssert(), QuESTEnv::rank, ComplexArray::real, and MultiQubit::stateVec.
Referenced by main(), test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_findProbabilityOfOutcome(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
    QuESTAssert(numQubits>0, 9, __func__);
        long long int numAmps = 1L << numQubits;
        long long int numAmpsPerRank = numAmps/env.numRanks;
        multiQubit->stateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.real)));
        multiQubit->stateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.imag)));
        if (env.numRanks>1){
                multiQubit->pairStateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.real)));
                multiQubit->pairStateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.imag)));
        }
        if ( (!(multiQubit->stateVec.real) || !(multiQubit->stateVec.imag))
                 && numAmpsPerRank ) {
                printf("Could not allocate memory!");
                exit (EXIT_FAILURE);
        }
        if ( env.numRanks>1 && (!(multiQubit->pairStateVec.real) || !(multiQubit->pairStateVec.imag))
                 && numAmpsPerRank ) {
                printf("Could not allocate memory!");
                exit (EXIT_FAILURE);
        }
        multiQubit->numQubits = numQubits;
        multiQubit->numAmps = numAmpsPerRank;
        multiQubit->chunkId = env.rank;
        multiQubit->numChunks = env.numRanks;
}
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
Parameters:
[in,out] multiQubit object to be deallocated
[in] env object representing the execution environment (local, multinode etc)
Definition at line 78 of file qubits.c.
References ComplexArray::imag, QuESTEnv::numRanks, MultiQubit::pairStateVec, ComplexArray::real, and MultiQubit::stateVec.
Referenced by main(), test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_findProbabilityOfOutcome(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
        free(multiQubit.stateVec.real);
        free(multiQubit.stateVec.imag);
        if (env.numRanks>1){
                free(multiQubit.pairStateVec.real);
                free(multiQubit.pairStateVec.imag);
        }
}
static int extractBit (const int locationOfBitFromRight, const long long int theEncodedNumber) [static]
Get the value of the bit at a particular index in a number.
SCB edit: new definition of extractBit is much faster ***
Parameters:
[in] locationOfBitFromRight location of bit in theEncodedNumber
[in] theEncodedNumber number to search
Returns:
the value of the bit in theEncodedNumber
Definition at line 1887 of file qubits.c.
Referenced by controlledCompactUnitaryDistributed(), controlledCompactUnitaryLocal(), controlledNotDistributed(), controlledNotLocal(), controlledPhaseGate(), controlledUnitaryDistributed(), controlledUnitaryLocal(), and initStateOfSingleQubit().
{
        return (theEncodedNumber & ( 1LL << locationOfBitFromRight )) >> locationOfBitFromRight;
}
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
Size of regions to skip is a multiple of chunkSize.
Parameters:
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns:
probability of qubit measureQubit being zero
Definition at line 1832 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
{
        // ----- measured probability
        REAL   totalProbability;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // ---------------------------------------------------------------- //
        //            find probability                                      //
        // ---------------------------------------------------------------- //
        // initialise returned value
        totalProbability = 0.0;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask) \
        reduction ( +:totalProbability )
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        totalProbability += stateVecReal[thisTask]*stateVecReal[thisTask]
                                + stateVecImag[thisTask]*stateVecImag[thisTask];
                        /*
                        // summation -- kahan correction
                        y = stateVecReal[thisTask]*stateVecReal[thisTask]
                        + stateVecImag[thisTask]*stateVecImag[thisTask] - c;
                        t = totalProbability + y;
                        c = (t - totalProbability) - y;
                        totalProbability = t;
                        */
                }
        }
        return totalProbability;
}
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
Size of regions to skip is less than the size of one chunk.
Parameters:
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns:
probability of qubit measureQubit being zero
Definition at line 1759 of file qubits.c.
References DEBUG, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
{
        // ----- sizes
        long long int sizeBlock,                                           // size of blocks
        sizeHalfBlock;                                       // size of blocks halved
        // ----- indices
        long long int thisBlock,                                           // current block
             index;                                               // current index for first half block
        // ----- measured probability
        REAL   totalProbability;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps>>1;
        // ---------------------------------------------------------------- //
        //            dimensions                                            //
        // ---------------------------------------------------------------- //
        sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
        // and then the number to skip
        sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
        // initialise returned value
        totalProbability = 0.0;
        // initialise correction for kahan summation
        if (DEBUG) printf("sizeHalfBlock=%Ld sizeBlock=%Ld numTasks=%Ld\n",sizeHalfBlock,sizeBlock,numTasks);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private   (thisTask,thisBlock,index) \
        reduction ( +:totalProbability )
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock = thisTask / sizeHalfBlock;
                        index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        if (index<0){ printf("ABORTING as index=%Ld with thisBlock = %Ld  thisTask=%Ld \n", index,thisBlock,thisTask); exit(1);}
                        // summation -- simple implementation
                        totalProbability += stateVecReal[index]*stateVecReal[index]
                                + stateVecImag[index]*stateVecImag[index];
                        /*
                        // summation -- kahan correction
                        y = stateVecReal[index]*stateVecReal[index]
                        + stateVecImag[index]*stateVecImag[index] - c;
                        t = totalProbability + y;
                        c = (t - totalProbability) - y;
                        totalProbability = t;
                        */
                }
        }
        return totalProbability;
}
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
Definition at line 164 of file qubits.c.
References MultiQubit::numQubits, and QuESTEnv::numRanks.
{
        int numThreads=1;
# ifdef _OPENMP
        numThreads=omp_get_max_threads();
# endif
        sprintf(str, "%dqubits_CPU_%dranksx%dthreads", multiQubit.numQubits, env.numRanks, numThreads);
}
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get probability of the state at an index in the state vector.
Get the probability of the state at an index in the state vector.
For debugging purposes.
Parameters:
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns:
real component * real component + imag component * imag component
Definition at line 2152 of file qubits.c.
References getImagAmpEl(), getRealAmpEl(), and REAL.
{
        REAL real;
        REAL imag;
        real = getRealAmpEl(multiQubit, index);
        imag = getImagAmpEl(multiQubit, index);
        return real*real + imag*imag;
}
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1546 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by hadamard().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        int sign;
        if (updateUpper) sign=1;
        else sign=-1;
        REAL recRoot2 = 1.0/sqrt(2);
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        recRoot2, sign) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        stateVecRealOut[thisTask] = recRoot2*(stateRealUp + sign*stateRealLo);
                        stateVecImagOut[thisTask] = recRoot2*(stateImagUp + sign*stateImagLo);
                }
        }
}
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 1484 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by hadamard().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, recRoot2) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        stateVecReal[indexUp] = recRoot2*(stateRealUp + stateRealLo);
                        stateVecImag[indexUp] = recRoot2*(stateImagUp + stateImagLo);
                        stateVecReal[indexLo] = recRoot2*(stateRealUp - stateRealLo);
                        stateVecImag[indexLo] = recRoot2*(stateImagUp - stateImagLo);
                }
        }
}
void initializeStateFromSingleFile (MultiQubit * multiQubit, char filename[200], QuESTEnv env)
fix -- format needs to work for single precision values
Definition at line 336 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, REAL, MultiQubit::stateVec, and syncQuESTEnv().
Referenced by test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), and test_tGate().
{
        long long int chunkSize, stateVecSize;
        long long int indexInChunk, totalIndex;
        chunkSize = multiQubit->numAmps;
        stateVecSize = chunkSize*multiQubit->numChunks;
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        FILE *fp;
        char line[200];
        for (int rank=0; rank<(multiQubit->numChunks); rank++){
                if (rank==multiQubit->chunkId){
                        fp = fopen(filename, "r");
                        indexInChunk = 0; totalIndex = 0;
                        while (fgets(line, sizeof(char)*200, fp) != NULL && totalIndex<stateVecSize){
                                if (line[0]!='#'){
                                        int chunkId = totalIndex/chunkSize;
                                        if (chunkId==multiQubit->chunkId){
                                                sscanf(line, "%lf, %lf", &(stateVecReal[indexInChunk]),
                                                                &(stateVecImag[indexInChunk]));
                                                indexInChunk += 1;
                                        }
                                        totalIndex += 1;
                                }
                        }
                        fclose(fp);
                }
                syncQuESTEnv(env);
        }
}
void initStateDebug (MultiQubit * multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters:
[in,out] multiQubit object representing the set of qubits to be initialised
Definition at line 304 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_hadamard(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
        long long int chunkSize;
        long long int index;
        // dimension of the state vector
        chunkSize = multiQubit->numAmps;
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        REAL chunkOffset = (2.0*chunkSize*multiQubit->chunkId)/10.0;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (chunkSize, stateVecReal, stateVecImag, chunkOffset) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<chunkSize; index++) {
                        stateVecReal[index] = chunkOffset + (index*2.0)/10.0;
                        stateVecImag[index] = chunkOffset + (index*2.0+1.0)/10.0;
                }
        }
}
void initStateOfSingleQubit (MultiQubit * multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters:
[in,out] multiQubit object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] value of qubit 'qubitId'
Definition at line 257 of file qubits.c.
References MultiQubit::chunkId, DEBUG, extractBit(), ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_collapseToOutcome(), test_findProbabilityOfOutcome(), test_measure(), and test_measureWithStats().
{
        long long int chunkSize, stateVecSize;
        long long int index;
        int bit;
        const long long int chunkId=multiQubit->chunkId;
        // dimension of the state vector
        chunkSize = multiQubit->numAmps;
        stateVecSize = chunkSize*multiQubit->numChunks;
        REAL normFactor = 1.0/sqrt(stateVecSize/2);
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (chunkSize, stateVecReal, stateVecImag, normFactor, qubitId, outcome) \
        private  (index, bit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<chunkSize; index++) {
                        bit = extractBit(qubitId, index+chunkId*chunkSize);
                        if (bit==outcome) {
                                stateVecReal[index] = normFactor;
                                stateVecImag[index] = 0.0;
                        } else {
                                stateVecReal[index] = 0.0;
                                stateVecImag[index] = 0.0;
                        }
                }
        }
        if (DEBUG) printf("COMPLETED INIT\n");
}
void initStatePlus (MultiQubit * multiQubit)
Initialise the state vector of probability amplitudes for a set of qubits to an equal real superposition of all amplitudes: |+++.
..++>
Parameters:
[in,out] multiQubit object representing the set of qubits to be initialised
Definition at line 218 of file qubits.c.
References DEBUG, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_collapseToOutcome(), test_compactUnitary(), test_findProbabilityOfOutcome(), test_initStatePlus(), test_measure(), test_measureWithStats(), and test_unitary().
{
        long long int chunkSize, stateVecSize;
        long long int index;
        // dimension of the state vector
        chunkSize = multiQubit->numAmps;
        stateVecSize = chunkSize*multiQubit->numChunks;
        REAL normFactor = 1.0/sqrt(stateVecSize);
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (chunkSize, stateVecReal, stateVecImag, normFactor) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<chunkSize; index++) {
                        stateVecReal[index] = normFactor;
                        stateVecImag[index] = 0.0;
                }
        }
        if (DEBUG) printf("COMPLETED INIT\n");
}
void initStateZero (MultiQubit * multiQubit)
Initialise the state vector of probability amplitudes for a set of qubits to the zero state: |000...00>.
Parameters:
[in,out] multiQubit object representing the set of qubits to be initialised
Definition at line 176 of file qubits.c.
References MultiQubit::chunkId, DEBUG, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by main(), test_collapseToOutcome(), test_findProbabilityOfOutcome(), test_initStateZero(), test_measure(), and test_measureWithStats().
{
        long long int stateVecSize;
        long long int index;
        // dimension of the state vector
        stateVecSize = multiQubit->numAmps;
        // Can't use multiQubit->stateVec as a private OMP var
        REAL *stateVecReal = multiQubit->stateVec.real;
        REAL *stateVecImag = multiQubit->stateVec.imag;
        // initialise the state to |0000..0000>
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecSize, stateVecReal, stateVecImag) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<stateVecSize; index++) {
                        stateVecReal[index] = 0.0;
                        stateVecImag[index] = 0.0;
                }
        }
        if (multiQubit->chunkId==0){
                // zero state |0000..0000> has probability 1
                stateVecReal[0] = 1.0;
                stateVecImag[0] = 0.0;
        }
        if (DEBUG) printf("COMPLETED INIT\n");
}
void multiControlledPhaseGate (MultiQubit multiQubit, int * controlQubits, int numControlQubits)
The multiple qubit control phase gate.
For each state, if all input qubits are equal to one, multiply the amplitude of that state by -1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] controlQubits array of input qubits
[in] numControlQubits number of input qubits
Definition at line 1939 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numQubits, QuESTAssert(), ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_multiControlledPhaseGate().
{
        long long int index;
        long long int stateVecSize;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
    QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
        stateVecSize = multiQubit.numAmps;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none)                      \
        shared   (stateVecSize, stateVecReal,stateVecImag, mask ) \
        private  (index)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (index=0; index<stateVecSize; index++) {
                        if (mask == (mask & (index+chunkId*chunkSize)) ){
                                stateVecReal [index] = - stateVecReal [index];
                                stateVecImag [index] = - stateVecImag [index];
                        }
                }
        }
}
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where all the control qubits are 1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1120 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by multiControlledUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag, mask) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        if (mask == (mask & (thisTask+chunkId*chunkSize)) ){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                    + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                    + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                        }
                }
        }
}
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a control qubit.
Only perform the rotation for elements where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit perform rotation if this qubit is 1
[in] alpha rotation angle
[in] beta rotation angle
Definition at line 840 of file qubits.c.
References MultiQubit::chunkId, Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by multiControlledUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u, mask) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        if (mask == (mask & (indexUp+chunkId*chunkSize)) ){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                                stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                        + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                                stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                        + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                                // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                                stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                        + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                                stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                        + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                        }
                }
        }
}
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] type the type of phase gate to apply -- one of {SIGMA_Z, S_GATE, T_GATE}
Definition at line 1682 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
{
        REAL stateRealLo,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecReal,stateVecImag, recRoot2, type) \
        private  (thisTask,stateRealLo,stateImagLo)
# endif
        {
                if (type==SIGMA_Z){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateVecReal[thisTask] = -stateVecReal[thisTask];
                                stateVecImag[thisTask] = -stateVecImag[thisTask];
                        }
                } else if (type==S_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateRealLo = stateVecReal[thisTask];
                                stateImagLo = stateVecImag[thisTask];
                                stateVecReal[thisTask] = -stateImagLo;
                                stateVecImag[thisTask] = stateRealLo;
                        }
                } else if (type==T_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateRealLo = stateVecReal[thisTask];
                                stateImagLo = stateVecImag[thisTask];
                                stateVecReal[thisTask] = recRoot2 * (stateRealLo - stateImagLo);
                                stateVecImag[thisTask] = recRoot2 * (stateRealLo + stateImagLo);
                        }
                } else printf("Type %d is an invalid phase gate\n", type);
        }
}
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Rotate a single qubit by {{1,0},{0,p}} where p is a phase term determined by the type argument.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] type the type of phase gate to apply -- one of {SIGMA_Z, S_GATE, T_GATE}
fix -- can i rewrite this to not use mod?
fix -- can i rewrite this to not use mod?
fix -- can i rewrite this to not use mod?
Definition at line 1599 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealLo,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock,stateVecReal,stateVecImag,recRoot2,type) \
        private  (thisTask,thisBlock,indexUp,indexLo,stateRealLo,stateImagLo)
# endif
        {
                if (type==SIGMA_Z){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateVecReal[indexLo] = -stateVecReal[indexLo];
                                stateVecImag[indexLo] = -stateVecImag[indexLo];
                        }
                }
                else if (type==S_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                stateVecReal[indexLo] = -stateImagLo;
                                stateVecImag[indexLo] = stateRealLo;
                        }
                } else if (type==T_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                stateVecReal[indexLo] = recRoot2 * (stateRealLo - stateImagLo);
                                stateVecImag[indexLo] = recRoot2 * (stateRealLo + stateImagLo);
                        }
                } else printf("Type %d is an invalid phase gate\n", type);
        }
}
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] env object representing the execution environment (local, multinode etc)
Definition at line 153 of file qubits.c.
References MultiQubit::chunkId, MultiQubit::numChunks, and MultiQubit::numQubits.
Referenced by main().
{
        long long int numAmps = 1L << multiQubit.numQubits;
        long long int numAmpsPerRank = numAmps/multiQubit.numChunks;
        if (multiQubit.chunkId==0){
                printf("QUBITS:\n");
                printf("Number of qubits is %d.\n", multiQubit.numQubits);
                printf("Number of amps is %lld.\n", numAmps);
                printf("Number of amps per rank is %lld.\n", numAmpsPerRank);
        }
}
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
File format:
real, imag
realComponent1, imagComponent1
realComponent2, imagComponent2
...
realComponentN, imagComponentN
File naming convention:
For each node that the program runs on, a file 'state_rank_[node_rank].csv' is generated. If there is more than one node, ranks after the first do not include the header
real, imag
so that files are easier to combine.
Parameters:
[in,out] multiQubit object representing the set of qubits
Definition at line 107 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL_STRING_FORMAT, and MultiQubit::stateVec.
{
        FILE *state;
        char filename[100];
        long long int index;
        sprintf(filename, "state_rank_%d.csv", multiQubit.chunkId);
        state = fopen(filename, "w");
        if (multiQubit.chunkId==0) fprintf(state, "real, imag\n");
        for(index=0; index<multiQubit.numAmps; index++){
                fprintf(state, REAL_STRING_FORMAT "," REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
        }
        fclose(state);
}
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 124 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, MultiQubit::numAmps, MultiQubit::numChunks, MultiQubit::numQubits, ComplexArray::real, REAL_STRING_FORMAT, MultiQubit::stateVec, and syncQuESTEnv().
Referenced by reportTest().
{
        long long int index;
        int rank;
        if (multiQubit.numQubits<=5){
                for (rank=0; rank<multiQubit.numChunks; rank++){
                        if (multiQubit.chunkId==rank){
                                if (reportRank) {
                                        printf("Reporting state from rank %d [\n", multiQubit.chunkId);
                                        //printf("\trank, index, real, imag\n");
                                        printf("real, imag\n");
                                } else if (rank==0) {
                                        printf("Reporting state [\n");
                                        printf("real, imag\n");
                                }
                                for(index=0; index<multiQubit.numAmps; index++){
                                        printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
                                }
                                if (reportRank || rank==multiQubit.numChunks-1) printf("]\n");
                        }
                        syncQuESTEnv(env);
                }
        } else printf("Error: reportStateToScreen will not print output for systems of more than 5 qubits.\n");
}
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector unitAxis)
Rotate a single qubit a certain angle about an axis.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] unitAxis unit vector pointing along the axis about which to rotate. Does not need to be normalised
Definition at line 434 of file qubits.c.
References compactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
{
        Complex alpha, beta;
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = 0;
        beta.imag = -sin(angle/2.0)*(unitAxis.x + unitAxis.y);
        compactUnitary(multiQubit, rotQubit, alpha, beta);
}
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the x-axis.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Definition at line 452 of file qubits.c.
References compactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
{
        Complex alpha, beta;
    Vector unitAxis = {1, 0, 0};
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = 0;
        beta.imag = -sin(angle/2.0)*(unitAxis.x + unitAxis.y);
        compactUnitary(multiQubit, rotQubit, alpha, beta);
}
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the y-axis.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Definition at line 471 of file qubits.c.
References compactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
{
        Complex alpha, beta;
    Vector unitAxis = {0, 1, 0};
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = 0;
        beta.imag = -sin(angle/2.0)*(unitAxis.x + unitAxis.y);
        compactUnitary(multiQubit, rotQubit, alpha, beta);
}
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit a certain angle about the z-axis.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Definition at line 490 of file qubits.c.
References compactUnitary(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
{
        Complex alpha, beta;
    Vector unitAxis = {0, 0, 1};
        alpha.real = cos(angle/2.0);
        alpha.imag = -sin(angle/2.0)*unitAxis.z;
        beta.real = 0;
        beta.imag = -sin(angle/2.0)*(unitAxis.x + unitAxis.y);
        compactUnitary(multiQubit, rotQubit, alpha, beta);
}
void sGate (MultiQubit multiQubit, const int targetQubit)
Definition at line 1740 of file qubits.c.
References phaseGate(), and S_GATE.
Referenced by test_sGate().
{
                phaseGate(multiQubit, targetQubit, S_GATE);
}
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1237 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by sigmaX().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
        private  (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
                        stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
                }
        }
}
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,1},{1,0}.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 1177 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaX().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateVecReal[indexUp] = stateVecReal[indexLo];
                        stateVecImag[indexUp] = stateVecImag[indexLo];
                        stateVecReal[indexLo] = stateRealUp;
                        stateVecImag[indexLo] = stateImagUp;
                }
        }
}
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1444 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by sigmaY().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
        int realSign=1, imagSign=1;
        if (updateUpper) imagSign=-1;
        else realSign = -1;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut,realSign,imagSign) \
        private  (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        stateVecRealOut[thisTask] = realSign*stateVecImagIn[thisTask];
                        stateVecImagOut[thisTask] = imagSign*stateVecRealIn[thisTask];
                }
        }
}
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{0,-i},{i,0}.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 1384 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaY().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateVecReal[indexUp] = stateVecImag[indexLo];
                        stateVecImag[indexUp] = -stateVecReal[indexLo];
                        stateVecReal[indexLo] = -stateImagUp;
                        stateVecImag[indexLo] = stateRealUp;
                }
        }
}
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Rotate a single qubit by {{1,0},{{0,-1}} -- apply a phase of -1 to |1>.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
Definition at line 1735 of file qubits.c.
References phaseGate(), and SIGMA_Z.
Referenced by test_sigmaZ().
{
                phaseGate(multiQubit, targetQubit, SIGMA_Z);
}
void tGate (MultiQubit multiQubit, const int targetQubit)
Definition at line 1745 of file qubits.c.
References phaseGate(), and T_GATE.
Referenced by test_tGate().
{
                phaseGate(multiQubit, targetQubit, T_GATE);
}
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] u unitary matrix to apply
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 706 of file qubits.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by unitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real, rot1Imag, rot2Real, rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                                + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                        stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                                + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                }
        }
}
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 577 of file qubits.c.
References Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by unitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        // store current state vector values in temp variables
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                        stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                        stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                        // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                        stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                        stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                }
        }
}
int validateAlphaBeta (Complex alpha, Complex beta)
Definition at line 410 of file qubits.c.
References Complex::imag, Complex::real, and REAL_EPS.
Referenced by compactUnitary(), and controlledCompactUnitary().
{
        if ( fabs(alpha.real*alpha.real
                + alpha.imag*alpha.imag
                + beta.real*beta.real
                + beta.imag*beta.imag - 1) > REAL_EPS ) return 0;
        else return 1;
}
int validateMatrixIsUnitary (ComplexMatrix2 u)
Definition at line 385 of file qubits.c.
References Complex::imag, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, and REAL_EPS.
Referenced by controlledUnitary(), multiControlledUnitary(), and unitary().
{
        if ( fabs(u.r0c0.real*u.r0c0.real
                + u.r0c0.imag*u.r0c0.imag
                + u.r1c0.real*u.r1c0.real
                + u.r1c0.imag*u.r1c0.imag - 1) > REAL_EPS ) return 0;
    // check
        if ( fabs(u.r0c1.real*u.r0c1.real
                + u.r0c1.imag*u.r0c1.imag
                + u.r1c1.real*u.r1c1.real
                + u.r1c1.imag*u.r1c1.imag - 1) > REAL_EPS ) return 0;
        if ( fabs(u.r0c0.real*u.r0c1.real
                + u.r0c0.imag*u.r0c1.imag
                + u.r1c0.real*u.r1c1.real
                + u.r1c0.imag*u.r1c1.imag) > REAL_EPS ) return 0;
        if ( fabs(u.r0c1.real*u.r0c0.imag
                - u.r0c0.real*u.r0c1.imag
                + u.r1c1.real*u.r1c0.imag
                - u.r1c0.real*u.r1c1.imag) > REAL_EPS ) return 0;
        return 1;
}
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Definition at line 418 of file qubits.c.
References REAL_EPS.
{
        if ( fabs(sqrt(ux*ux + uy*uy + uz*uz) - 1) > REAL_EPS ) return 0;
        else return 1;
}
Variable Documentation
const char* errorCodes[]
Initial value:
 {
    "Success",
    "Invalid target qubit. Note qubits are zero indexed.",
    "Invalid control qubit. Note qubits are zero indexed.",
    "Control qubit cannot equal target qubit.",
    "Invalid number of control qubits",
    "Invalid unitary matrix.",
    "Invalid rotation arguments.",
    "Invalid system size. Cannot print output for systems greater than 5 qubits.",
    "Can't collapse to state with zero probability."
    "Invalid number of qubits."
}
Definition at line 17 of file qubits.c.
Referenced by exitWithError().