Quantum Exact Simulation Toolkit: QuEST.c File Reference
QuEST.c File Reference
#include "../QuEST.h"
#include "../QuEST_precision.h"
#include "../mt19937ar.h"
#include "QuEST_internal.h"
#include <unistd.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <sys/param.h>
#include <sys/types.h>
#include <sys/time.h>
Macros
#define _BSD_SOURCE
Functions
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase gate, also known as the controlled sigmaZ gate.
void controlledRotateAroundAxis (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
void controlledRotateX (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
void controlledRotateY (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
void controlledRotateZ (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
void createMultiQubit (MultiQubit *multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits.
static int extractBit (const int locationOfBitFromRight, const long long int theEncodedNumber)
Get the value of the bit at a particular index in a number.
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
int getNumAmps (MultiQubit multiQubit)
Get the number of probability amplitudes in a multiQubit object, given by 2^numQubits.
int getNumQubits (MultiQubit multiQubit)
Get the number of qubits in a multiQubit object.
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get the probability of the state at an index in the full state vector.
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
unsigned long int hashString (char *str)
void initClassicalState (MultiQubit multiQubit, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
void initializeStateFromSingleFile (MultiQubit *multiQubit, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
void initStateDebug (MultiQubit multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
void initStateOfSingleQubit (MultiQubit *multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
void initStatePlus (MultiQubit multiQubit)
Initialise a set of qubits to the plus state .
void initStateZero (MultiQubit multiQubit)
Initialise a set of qubits to the classical zero state .
void multiControlledPhaseGate (MultiQubit multiQubit, int *controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase gate, also known as the multiple-qubit controlled sigmaZ gate.
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
void seedQuEST (unsigned long int *seedArray, int numSeeds)
numSeeds <= 64
void seedQuESTDefault ()
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
void sGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit S gate.
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Z (also known as the Z, Pauli-Z or phase-flip) gate.
void tGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit T gate.
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
int validateAlphaBeta (Complex alpha, Complex beta)
int validateMatrixIsUnitary (ComplexMatrix2 u)
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Variables
const char * errorCodes []
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 13 of file QuEST.c.
Function Documentation
collapseToOutcomeDistributedRenorm()
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that the value 'outcome' has been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles the renormalisation.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being zero
Definition at line 1917 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
 {
     // ----- temp variables
     long long int thisTask;
     long long int numTasks=multiQubit.numAmpsPerChunk;
     REAL renorm=1/sqrt(totalProbability);
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     shared    (numTasks,stateVecReal,stateVecImag) \
     private   (thisTask)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             stateVecReal[thisTask] = stateVecReal[thisTask]*renorm;
             stateVecImag[thisTask] = stateVecImag[thisTask]*renorm;
         }
     }
     return totalProbability;
 }
collapseToOutcomeDistributedSetZero()
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that a zero have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles setting amplitudes to 0.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Definition at line 1957 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
 {
     // ----- temp variables
     long long int thisTask;
     long long int numTasks=multiQubit.numAmpsPerChunk;
     // ---------------------------------------------------------------- //
     //            find probability                                      //
     // ---------------------------------------------------------------- //
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     shared    (numTasks,stateVecReal,stateVecImag) \
     private   (thisTask)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             stateVecReal[thisTask] = 0;
             stateVecImag[thisTask] = 0;
         }
     }
 }
collapseToOutcomeLocal()
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
Performs an irreversible change to the state vector: it updates the vector according to the event that an outcome have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1 according to the value of outcome. In the local version, one or more blocks (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) fit entirely into one chunk.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being either zero or one
[in] outcome to measure the probability of and set the state to – either zero or one
Definition at line 1835 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
 {
     // ----- sizes
     long long int sizeBlock,                                  // size of blocks
          sizeHalfBlock;                                       // size of blocks halved
     // ----- indices
     long long int thisBlock,                                  // current block
          index;                                               // current index for first half block
     // ----- measured probability
     REAL   renorm;                                            // probability (returned) value
     // ----- temp variables
     long long int thisTask;                                   // task based approach for expose loop with small granularity
     // (good for shared memory parallelism)
     long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // ---------------------------------------------------------------- //
     //            dimensions                                            //
     // ---------------------------------------------------------------- //
     sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
     // and then the number to skip
     sizeBlock     = 2LL * sizeHalfBlock;                         // size of blocks (pairs of measure and skip entries)
     renorm=1/sqrt(totalProbability);
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default (none) \
     shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag,renorm,outcome) \
     private   (thisTask,thisBlock,index)
 # endif
     {
         if (outcome==0){
             // measure qubit is 0
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 thisBlock = thisTask / sizeHalfBlock;
                 index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                 stateVecReal[index]=stateVecReal[index]*renorm;
                 stateVecImag[index]=stateVecImag[index]*renorm;
                 stateVecReal[index+sizeHalfBlock]=0;
                 stateVecImag[index+sizeHalfBlock]=0;
             }
         } else {
             // measure qubit is 1
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 thisBlock = thisTask / sizeHalfBlock;
                 index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                 stateVecReal[index]=0;
                 stateVecImag[index]=0;
                 stateVecReal[index+sizeHalfBlock]=stateVecReal[index+sizeHalfBlock]*renorm;
                 stateVecImag[index+sizeHalfBlock]=stateVecImag[index+sizeHalfBlock]*renorm;
             }
         }
     }
 }
compactUnitaryDistributed()
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 619 of file QuEST.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and Complex::real.
Referenced by compactUnitary().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
     REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             rot1Real,rot1Imag, rot2Real,rot2Imag) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             // store current state vector values in temp variables
             stateRealUp = stateVecRealUp[thisTask];
             stateImagUp = stateVecImagUp[thisTask];
             stateRealLo = stateVecRealLo[thisTask];
             stateImagLo = stateVecImagLo[thisTask];
             // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
             stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
             stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
         }
     }
 }
compactUnitaryLocal()
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 490 of file QuEST.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, Complex::real, and MultiQubit::stateVec.
Referenced by compactUnitary().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     REAL alphaImag=alpha.imag, alphaReal=alpha.real;
     REAL betaImag=beta.imag, betaReal=beta.real;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             // store current state vector values in temp variables
             stateRealUp = stateVecReal[indexUp];
             stateImagUp = stateVecImag[indexUp];
             stateRealLo = stateVecReal[indexLo];
             stateImagLo = stateVecImag[indexLo];
             // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
             stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                 - betaReal*stateRealLo - betaImag*stateImagLo;
             stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                 - betaReal*stateImagLo + betaImag*stateRealLo;
             // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
             stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                 + alphaReal*stateRealLo + alphaImag*stateImagLo;
             stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                 + alphaReal*stateImagLo - alphaImag*stateRealLo;
         }
     }
 }
compareStates()
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
For debugging purposes.
Definition at line 379 of file QuEST.c.
Referenced by test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
     REAL diff;
     int chunkSize = mq1.numAmpsPerChunk;
     for (int i=0; i<chunkSize; i++){
         diff = fabs(mq1.stateVec.real[i] - mq2.stateVec.real[i]);
         if (diff>precision) return 0;
         diff = fabs(mq1.stateVec.imag[i] - mq2.stateVec.imag[i]);
         if (diff>precision) return 0;
     }
     return 1;
 }
controlledCompactUnitaryDistributed()
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 929 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and Complex::real.
Referenced by controlledCompactUnitary().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
     REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             rot1Real,rot1Imag, rot2Real,rot2Imag) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
             if (controlBit){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecRealUp[thisTask];
                 stateImagUp = stateVecImagUp[thisTask];
                 stateRealLo = stateVecRealLo[thisTask];
                 stateImagLo = stateVecImagLo[thisTask];
                 // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                 stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
                 stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
             }
         }
     }
 }
controlledCompactUnitaryLocal()
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 720 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, Complex::real, and MultiQubit::stateVec.
Referenced by controlledCompactUnitary().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     REAL alphaImag=alpha.imag, alphaReal=alpha.real;
     REAL betaImag=beta.imag, betaReal=beta.real;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
             if (controlBit){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecReal[indexUp];
                 stateImagUp = stateVecImag[indexUp];
                 stateRealLo = stateVecReal[indexLo];
                 stateImagLo = stateVecImag[indexLo];
                 // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                 stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                     - betaReal*stateRealLo - betaImag*stateImagLo;
                 stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                     - betaReal*stateImagLo + betaImag*stateRealLo;
                 // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
                 stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                     + alphaReal*stateRealLo + alphaImag*stateImagLo;
                 stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                     + alphaReal*stateImagLo - alphaImag*stateRealLo;
             }
         }
     }
 }
controlledNotDistributed()
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk. Only perform the rotation for elements where controlQubit is one.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1258 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, and REAL.
Referenced by controlledNot().
 {
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
     private  (thisTask,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
             if (controlBit){
                 stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
                 stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
             }
         }
     }
 }
controlledNotLocal()
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Definition at line 1193 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledNot().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateImagUp;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             controlBit = extractBit(controlQubit, indexUp+chunkId*chunkSize);
             if (controlBit){
                 stateRealUp = stateVecReal[indexUp];
                 stateImagUp = stateVecImag[indexUp];
                 stateVecReal[indexUp] = stateVecReal[indexLo];
                 stateVecImag[indexUp] = stateVecImag[indexLo];
                 stateVecReal[indexLo] = stateRealUp;
                 stateVecImag[indexLo] = stateImagUp;
             }
         }
     }
 }
controlledPhaseGate()
void controlledPhaseGate (MultiQubit multiQubit, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase gate, also known as the controlled sigmaZ gate.
For each state, if both input qubits have value one, multiply the amplitude of that state by -1. This applies the two-qubit unitary:
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] idQubit1,idQubit2 qubits to operate upon
Exceptions
exitWithError if idQubit1 or idQubit2 are outside [0, multiQubit.numQubits), or are equal
Definition at line 1748 of file QuEST.c.
Referenced by test_controlledPhaseGate().
 {
     long long int index;
     long long int stateVecSize;
     int bit1, bit2;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     QuESTAssert(idQubit1 >= 0 && idQubit1 < multiQubit.numQubits, 2, __func__);
     QuESTAssert(idQubit2 >= 0 && idQubit2 < multiQubit.numQubits, 1, __func__);
     QuESTAssert(idQubit1 != idQubit2, 3, __func__);
     // dimension of the state vector
     stateVecSize = multiQubit.numAmpsPerChunk;
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel for \
     default  (none)                          \
     shared   (stateVecSize, stateVecReal,stateVecImag ) \
     private  (index,bit1,bit2)                 \
     schedule (static)
 # endif
     for (index=0; index<stateVecSize; index++) {
         bit1 = extractBit (idQubit1, index+chunkId*chunkSize);
         bit2 = extractBit (idQubit2, index+chunkId*chunkSize);
         if (bit1 && bit2) {
             stateVecReal [index] = - stateVecReal [index];
             stateVecImag [index] = - stateVecImag [index];
         }
     }
 }
controlledRotateAroundAxis()
void controlledRotateAroundAxis (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies to states where the target qubit is 1 (is the vector of Pauli matrices).
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit with value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal or if axis is the zero vector
Definition at line 459 of file QuEST.c.
Referenced by controlledRotateX(), controlledRotateY(), and controlledRotateZ().
{
     double mag = sqrt(pow(axis.x,2) + pow(axis.y,2) + pow(axis.z,2));
     Vector unitAxis = {axis.x/mag, axis.y/mag, axis.z/mag};
     Complex alpha, beta;
     alpha.real = cos(angle/2.0);
     alpha.imag = -sin(angle/2.0)*unitAxis.z;
     beta.real = sin(angle/2.0)*unitAxis.y;
     beta.imag = -sin(angle/2.0)*unitAxis.x;
     controlledCompactUnitary(multiQubit, controlQubit, targetQubit, alpha, beta);
 }
controlledRotateX()
void controlledRotateX (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 472 of file QuEST.c.
{
     Vector unitAxis = {1, 0, 0};
     controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
 }
controlledRotateY()
void controlledRotateY (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 478 of file QuEST.c.
{
     Vector unitAxis = {0, 1, 0};
     controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
 }
controlledRotateZ()
void controlledRotateZ (MultiQubit multiQubit, const int controlQubit, const int targetQubit, REAL angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] tagretQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal.
Definition at line 484 of file QuEST.c.
{
     Vector unitAxis = {0, 0, 1};
     controlledRotateAroundAxis(multiQubit, controlQubit, targetQubit, angle, unitAxis);
 }
controlledUnitaryDistributed()
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 992 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and Complex::real.
Referenced by controlledUnitary().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
     REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             rot1Real,rot1Imag, rot2Real,rot2Imag) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
             if (controlBit){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecRealUp[thisTask];
                 stateImagUp = stateVecImagUp[thisTask];
                 stateRealLo = stateVecRealLo[thisTask];
                 stateImagLo = stateVecImagLo[thisTask];
                 stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                     + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                 stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                     + rot2Real*stateImagLo + rot2Imag*stateRealLo;
             }
         }
     }
 }
controlledUnitaryLocal()
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 850 of file QuEST.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, ComplexArray::real, REAL, Complex::real, and MultiQubit::stateVec.
Referenced by controlledUnitary().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     int controlBit;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
             if (controlBit){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecReal[indexUp];
                 stateImagUp = stateVecImag[indexUp];
                 stateRealLo = stateVecReal[indexLo];
                 stateImagLo = stateVecImag[indexLo];
                 // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                 stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                     + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                 stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                     + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                 // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                 stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                     + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                 stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                     + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
             }
         }
     }
 }
createMultiQubit()
void createMultiQubit (MultiQubit * multiQubit, int numQubits, QuESTEnv env)
Create a MultiQubit object representing a set of qubits.
Allocate space for state vector of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. initStateZero should be called after this to initialise the qubits to the zero state.
Parameters
[in,out] multiQubit a pointer to an object representing the set of qubits
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions
exitWithError if numQubits <= 0
Definition at line 44 of file QuEST.c.
Referenced by main(), test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_findProbabilityOfOutcome(), test_getImagAmpEl(), test_getProbEl(), test_getRealAmpEl(), test_hadamard(), test_initClassicalState(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
 {
     QuESTAssert(numQubits>0, 9, __func__);
     long long int numAmps = 1L << numQubits;
     long long int numAmpsPerRank = numAmps/env.numRanks;
     multiQubit->stateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.real)));
     multiQubit->stateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->stateVec.imag)));
     if (env.numRanks>1){
         multiQubit->pairStateVec.real = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.real)));
         multiQubit->pairStateVec.imag = malloc(numAmpsPerRank * sizeof(*(multiQubit->pairStateVec.imag)));
     }
     if ( (!(multiQubit->stateVec.real) || !(multiQubit->stateVec.imag))
             && numAmpsPerRank ) {
         printf("Could not allocate memory!");
         exit (EXIT_FAILURE);
     }
     if ( env.numRanks>1 && (!(multiQubit->pairStateVec.real) || !(multiQubit->pairStateVec.imag))
             && numAmpsPerRank ) {
         printf("Could not allocate memory!");
         exit (EXIT_FAILURE);
     }
     multiQubit->numQubits = numQubits;
     multiQubit->numAmpsPerChunk = numAmpsPerRank;
     multiQubit->chunkId = env.rank;
     multiQubit->numChunks = env.numRanks;
 }
destroyMultiQubit()
void destroyMultiQubit (MultiQubit multiQubit, QuESTEnv env)
Deallocate a MultiQubit object representing a set of qubits.
Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
Parameters
[in,out] multiQubit object to be deallocated
[in] env object representing the execution environment (local, multinode etc)
Definition at line 76 of file QuEST.c.
Referenced by main(), test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_findProbabilityOfOutcome(), test_getImagAmpEl(), test_getProbEl(), test_getRealAmpEl(), test_hadamard(), test_initClassicalState(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
     free(multiQubit.stateVec.real);
     free(multiQubit.stateVec.imag);
     if (env.numRanks>1){
         free(multiQubit.pairStateVec.real);
         free(multiQubit.pairStateVec.imag);
     }
 }
extractBit()
static int extractBit (const int locationOfBitFromRight, const long long int theEncodedNumber) static
Get the value of the bit at a particular index in a number.
SCB edit: new definition of extractBit is much faster ***
Parameters
[in] locationOfBitFromRight location of bit in theEncodedNumber
[in] theEncodedNumber number to search
Returns
the value of the bit in theEncodedNumber
Definition at line 1743 of file QuEST.c.
Referenced by controlledCompactUnitaryDistributed(), controlledCompactUnitaryLocal(), controlledNotDistributed(), controlledNotLocal(), controlledPhaseGate(), controlledUnitaryDistributed(), controlledUnitaryLocal(), and initStateOfSingleQubit().
 {
     return (theEncodedNumber & ( 1LL << locationOfBitFromRight )) >> locationOfBitFromRight;
 }
findProbabilityOfZeroDistributed()
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
Size of regions to skip is a multiple of chunkSize.
Parameters
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
Definition at line 1699 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
 {
     // ----- measured probability
     REAL   totalProbability;                                  // probability (returned) value
     // ----- temp variables
     long long int thisTask;                                   // task based approach for expose loop with small granularity
     long long int numTasks=multiQubit.numAmpsPerChunk;
     // ---------------------------------------------------------------- //
     //            find probability                                      //
     // ---------------------------------------------------------------- //
     // initialise returned value
     totalProbability = 0.0;
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     shared    (numTasks,stateVecReal,stateVecImag) \
     private   (thisTask) \
     reduction ( +:totalProbability )
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             totalProbability += stateVecReal[thisTask]*stateVecReal[thisTask]
                 + stateVecImag[thisTask]*stateVecImag[thisTask];
         }
     }
     return totalProbability;
 }
findProbabilityOfZeroLocal()
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
Size of regions to skip is less than the size of one chunk.
Parameters
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns
probability of qubit measureQubit being zero
Definition at line 1643 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
 {
     // ----- sizes
     long long int sizeBlock,                                  // size of blocks
          sizeHalfBlock;                                       // size of blocks halved
     // ----- indices
     long long int thisBlock,                                  // current block
          index;                                               // current index for first half block
     // ----- measured probability
     REAL   totalProbability;                                  // probability (returned) value
     // ----- temp variables
     long long int thisTask;
     long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // ---------------------------------------------------------------- //
     //            dimensions                                            //
     // ---------------------------------------------------------------- //
     sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
     // and then the number to skip
     sizeBlock     = 2LL * sizeHalfBlock;                         // size of blocks (pairs of measure and skip entries)
     // initialise returned value
     totalProbability = 0.0;
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
     private   (thisTask,thisBlock,index) \
     reduction ( +:totalProbability )
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule  (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock = thisTask / sizeHalfBlock;
             index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             totalProbability += stateVecReal[index]*stateVecReal[index]
                 + stateVecImag[index]*stateVecImag[index];
         }
     }
     return totalProbability;
 }
getEnvironmentString()
void getEnvironmentString (QuESTEnv env, MultiQubit multiQubit, char str[200])
Definition at line 145 of file QuEST.c.
{
     int numThreads=1;
 # ifdef _OPENMP
     numThreads=omp_get_max_threads();
 # endif
     sprintf(str, "%dqubits_CPU_%dranksx%dthreads", multiQubit.numQubits, env.numRanks, numThreads);
 }
getNumAmps()
int getNumAmps (MultiQubit multiQubit)
Get the number of probability amplitudes in a multiQubit object, given by 2^numQubits.
Definition at line 140 of file QuEST.c.
Referenced by test_getImagAmpEl(), test_getProbEl(), and test_getRealAmpEl().
{
     return multiQubit.numAmpsPerChunk*multiQubit.numChunks;
 }
getNumQubits()
int getNumQubits (MultiQubit multiQubit)
Get the number of qubits in a multiQubit object.
Definition at line 136 of file QuEST.c.
{
     return multiQubit.numQubits;
 }
getProbEl()
REAL getProbEl (MultiQubit multiQubit, long long int index)
Get the probability of the state at an index in the full state vector.
Parameters
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
realEl*realEl + imagEl*imagEl
Exceptions
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 1986 of file QuEST.c.
Referenced by main(), test_getProbEl(), and test_initClassicalState().
{
     REAL real;
     REAL imag;
     real = getRealAmpEl(multiQubit, index);
     imag = getImagAmpEl(multiQubit, index);
     return real*real + imag*imag;
 }
hadamardDistributed()
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1446 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, and REAL.
Referenced by hadamard().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     int sign;
     if (updateUpper) sign=1;
     else sign=-1;
     REAL recRoot2 = 1.0/sqrt(2);
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             recRoot2, sign) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             // store current state vector values in temp variables
             stateRealUp = stateVecRealUp[thisTask];
             stateImagUp = stateVecImagUp[thisTask];
             stateRealLo = stateVecRealLo[thisTask];
             stateImagLo = stateVecImagLo[thisTask];
             stateVecRealOut[thisTask] = recRoot2*(stateRealUp + sign*stateRealLo);
             stateVecImagOut[thisTask] = recRoot2*(stateImagUp + sign*stateImagLo);
         }
     }
 }
hadamardLocal()
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1385 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by hadamard().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     REAL recRoot2 = 1.0/sqrt(2);
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, recRoot2) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             stateRealUp = stateVecReal[indexUp];
             stateImagUp = stateVecImag[indexUp];
             stateRealLo = stateVecReal[indexLo];
             stateImagLo = stateVecImag[indexLo];
             stateVecReal[indexUp] = recRoot2*(stateRealUp + stateRealLo);
             stateVecImag[indexUp] = recRoot2*(stateImagUp + stateImagLo);
             stateVecReal[indexLo] = recRoot2*(stateRealUp - stateRealLo);
             stateVecImag[indexLo] = recRoot2*(stateImagUp - stateImagLo);
         }
     }
 }
hashString()
unsigned long int hashString (char * str)
Definition at line 2026 of file QuEST.c.
Referenced by seedQuESTDefault().
{
     unsigned long int hash = 5381;
     int c;
     while ((c = *str++))
         hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
     return hash;
 }
initClassicalState()
void initClassicalState (MultiQubit multiQubit, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
Note has stateInd 0, has stateInd 1, has stateInd , etc. Subsequent calls to getProbEl will yield 0 for all indices except stateInd.
Parameters
[in,out] multiQubit the object representing the set of qubits to be initialised
[in] stateInd the index (0 to the number of amplitudes, exclusive) of the state to give probability 1
Definition at line 222 of file QuEST.c.
Referenced by test_initClassicalState().
 {
     long long int stateVecSize;
     long long int index;
     // dimension of the state vector
     stateVecSize = multiQubit.numAmpsPerChunk;
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateInd, stateVecSize, stateVecReal, stateVecImag) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<stateVecSize; index++) {
             stateVecReal[index] = 0.0;
             stateVecImag[index] = 0.0;
         }
     }
         // give the specified classical state prob 1
     if (multiQubit.chunkId == stateInd/stateVecSize){
         stateVecReal[stateInd % stateVecSize] = 1.0;
         stateVecImag[stateInd % stateVecSize] = 0.0;
     }
 }
initializeStateFromSingleFile()
void initializeStateFromSingleFile (MultiQubit * multiQubit, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
For debugging purpsoses
fix – format needs to work for single precision values
Definition at line 343 of file QuEST.c.
Referenced by test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), and test_tGate().
{
     long long int chunkSize, stateVecSize;
     long long int indexInChunk, totalIndex;
     chunkSize = multiQubit->numAmpsPerChunk;
     stateVecSize = chunkSize*multiQubit->numChunks;
     REAL *stateVecReal = multiQubit->stateVec.real;
     REAL *stateVecImag = multiQubit->stateVec.imag;
     FILE *fp;
     char line[200];
     for (int rank=0; rank<(multiQubit->numChunks); rank++){
         if (rank==multiQubit->chunkId){
             fp = fopen(filename, "r");
             QuESTAssert(fp!=NULL, 11, __func__);
             indexInChunk = 0; totalIndex = 0;
             while (fgets(line, sizeof(char)*200, fp) != NULL && totalIndex<stateVecSize){
                 if (line[0]!='#'){
                     int chunkId = totalIndex/chunkSize;
                     if (chunkId==multiQubit->chunkId){
                         sscanf(line, "%lf, %lf", &(stateVecReal[indexInChunk]),
                                 &(stateVecImag[indexInChunk]));
                         indexInChunk += 1;
                     }
                     totalIndex += 1;
                 }
             }
             fclose(fp);
         }
         syncQuESTEnv(env);
     }
 }
initStateDebug()
void initStateDebug (MultiQubit multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters
[in,out] multiQubit object representing the set of qubits to be initialised
Definition at line 310 of file QuEST.c.
Referenced by test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_getImagAmpEl(), test_getProbEl(), test_getRealAmpEl(), test_hadamard(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
 {
     long long int chunkSize;
     long long int index;
         long long int indexOffset;
     // dimension of the state vector
     chunkSize = multiQubit.numAmpsPerChunk;
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
         indexOffset = chunkSize * multiQubit.chunkId;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (chunkSize, stateVecReal, stateVecImag, indexOffset) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<chunkSize; index++) {
             stateVecReal[index] = ((indexOffset + index)*2.0)/10.0;
             stateVecImag[index] = ((indexOffset + index)*2.0+1.0)/10.0;
         }
     }
 }
initStateOfSingleQubit()
void initStateOfSingleQubit (MultiQubit * multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters
[in,out] multiQubit object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] value of qubit 'qubitId'
Definition at line 264 of file QuEST.c.
Referenced by test_collapseToOutcome(), test_findProbabilityOfOutcome(), test_measure(), and test_measureWithStats().
 {
     long long int chunkSize, stateVecSize;
     long long int index;
     int bit;
     const long long int chunkId=multiQubit->chunkId;
     // dimension of the state vector
     chunkSize = multiQubit->numAmpsPerChunk;
     stateVecSize = chunkSize*multiQubit->numChunks;
     REAL normFactor = 1.0/sqrt((REAL)stateVecSize/2.0);
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit->stateVec.real;
     REAL *stateVecImag = multiQubit->stateVec.imag;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (chunkSize, stateVecReal, stateVecImag, normFactor, qubitId, outcome) \
     private  (index, bit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<chunkSize; index++) {
             bit = extractBit(qubitId, index+chunkId*chunkSize);
             if (bit==outcome) {
                 stateVecReal[index] = normFactor;
                 stateVecImag[index] = 0.0;
             } else {
                 stateVecReal[index] = 0.0;
                 stateVecImag[index] = 0.0;
             }
         }
     }
 }
initStatePlus()
void initStatePlus (MultiQubit multiQubit)
Initialise a set of qubits to the plus state .
This is the product state of qubits where every classical state is uniformly populated with real coefficient . This is equivalent to applying a Hadamard to every qubit in the zero state:
Parameters
[in,out] multiQubit the object representing the set of qubits to be initialised
Definition at line 189 of file QuEST.c.
Referenced by test_collapseToOutcome(), test_compactUnitary(), test_findProbabilityOfOutcome(), test_initStatePlus(), test_measure(), test_measureWithStats(), and test_unitary().
 {
     long long int chunkSize, stateVecSize;
     long long int index;
     // dimension of the state vector
     chunkSize = multiQubit.numAmpsPerChunk;
     stateVecSize = chunkSize*multiQubit.numChunks;
     REAL normFactor = 1.0/sqrt((REAL)stateVecSize);
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (chunkSize, stateVecReal, stateVecImag, normFactor) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<chunkSize; index++) {
             stateVecReal[index] = normFactor;
             stateVecImag[index] = 0.0;
         }
     }
 }
initStateZero()
void initStateZero (MultiQubit multiQubit)
Initialise a set of qubits to the classical zero state .
Parameters
[in,out] multiQubit the object representing the set of all qubits to initialise
Definition at line 153 of file QuEST.c.
Referenced by main(), test_collapseToOutcome(), test_findProbabilityOfOutcome(), test_initStateZero(), test_measure(), and test_measureWithStats().
 {
     long long int stateVecSize;
     long long int index;
     // dimension of the state vector
     stateVecSize = multiQubit.numAmpsPerChunk;
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecSize, stateVecReal, stateVecImag) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<stateVecSize; index++) {
             stateVecReal[index] = 0.0;
             stateVecImag[index] = 0.0;
         }
     }
     if (multiQubit.chunkId==0){
         // zero state |0000..0000> has probability 1
         stateVecReal[0] = 1.0;
         stateVecImag[0] = 0.0;
     }
 }
multiControlledPhaseGate()
void multiControlledPhaseGate (MultiQubit multiQubit, int * controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase gate, also known as the multiple-qubit controlled sigmaZ gate.
For each state, if all control qubits have value one, multiply the amplitude of that state by -1. This applies the many-qubit unitary:
on the control qubits.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubits array of input qubits
[in] numControlQubits number of input qubits
Exceptions
exitWithError if numControlQubits is outside [1, multiQubit.numQubits)
Definition at line 1783 of file QuEST.c.
Referenced by main(), and test_multiControlledPhaseGate().
 {
     long long int index;
     long long int stateVecSize;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
     long long int mask=0;
     for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
     QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
     stateVecSize = multiQubit.numAmpsPerChunk;
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none)                          \
     shared   (stateVecSize, stateVecReal,stateVecImag, mask ) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<stateVecSize; index++) {
             if (mask == (mask & (index+chunkId*chunkSize)) ){
                 stateVecReal [index] = - stateVecReal [index];
                 stateVecImag [index] = - stateVecImag [index];
             }
         }
     }
 }
multiControlledUnitaryDistributed()
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where all the control qubits are 1.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1056 of file QuEST.c.
References MultiQubit::chunkId, ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and Complex::real.
Referenced by multiControlledUnitary().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
     REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             rot1Real,rot1Imag, rot2Real,rot2Imag, mask) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             if (mask == (mask & (thisTask+chunkId*chunkSize)) ){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecRealUp[thisTask];
                 stateImagUp = stateVecImagUp[thisTask];
                 stateRealLo = stateVecRealLo[thisTask];
                 stateImagLo = stateVecImagLo[thisTask];
                 stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                     + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                 stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                     + rot2Real*stateImagLo + rot2Imag*stateRealLo;
             }
         }
     }
 }
multiControlledUnitaryLocal()
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
Definition at line 787 of file QuEST.c.
References MultiQubit::chunkId, ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, ComplexArray::real, REAL, Complex::real, and MultiQubit::stateVec.
Referenced by multiControlledUnitary().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     const long long int chunkSize=multiQubit.numAmpsPerChunk;
     const long long int chunkId=multiQubit.chunkId;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u, mask) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             if (mask == (mask & (indexUp+chunkId*chunkSize)) ){
                 // store current state vector values in temp variables
                 stateRealUp = stateVecReal[indexUp];
                 stateImagUp = stateVecImag[indexUp];
                 stateRealLo = stateVecReal[indexLo];
                 stateImagLo = stateVecImag[indexLo];
                 // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                 stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                     + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                 stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                     + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                 // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                 stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                     + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                 stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                     + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
             }
         }
     }
 }
phaseGateDistributed()
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 1568 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
 {
     REAL stateRealLo,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     REAL recRoot2 = 1.0/sqrt(2);
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecReal,stateVecImag, recRoot2, type) \
     private  (thisTask,stateRealLo,stateImagLo)
 # endif
     {
         if (type==SIGMA_Z){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 stateVecReal[thisTask] = -stateVecReal[thisTask];
                 stateVecImag[thisTask] = -stateVecImag[thisTask];
             }
         } else if (type==S_GATE){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 stateRealLo = stateVecReal[thisTask];
                 stateImagLo = stateVecImag[thisTask];
                 stateVecReal[thisTask] = -stateImagLo;
                 stateVecImag[thisTask] = stateRealLo;
             }
         } else if (type==T_GATE){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 stateRealLo = stateVecReal[thisTask];
                 stateImagLo = stateVecImag[thisTask];
                 stateVecReal[thisTask] = recRoot2 * (stateRealLo - stateImagLo);
                 stateVecImag[thisTask] = recRoot2 * (stateRealLo + stateImagLo);
             }
         } else printf("Type %d is an invalid phase gate\n", type);
     }
 }
phaseGateLocal()
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
fix – can i rewrite this to not use mod?
fix – can i rewrite this to not use mod?
fix – can i rewrite this to not use mod?
Definition at line 1492 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealLo,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
     REAL recRoot2 = 1.0/sqrt(2);
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock,stateVecReal,stateVecImag,recRoot2,type) \
     private  (thisTask,thisBlock,indexUp,indexLo,stateRealLo,stateImagLo)
 # endif
     {
         if (type==SIGMA_Z){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 thisBlock   = thisTask / sizeHalfBlock;
                 indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                 indexLo     = indexUp + sizeHalfBlock;
                 stateVecReal[indexLo] = -stateVecReal[indexLo];
                 stateVecImag[indexLo] = -stateVecImag[indexLo];
             }
         }
         else if (type==S_GATE){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 thisBlock   = thisTask / sizeHalfBlock;
                 indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                 indexLo     = indexUp + sizeHalfBlock;
                 stateRealLo = stateVecReal[indexLo];
                 stateImagLo = stateVecImag[indexLo];
                 stateVecReal[indexLo] = -stateImagLo;
                 stateVecImag[indexLo] = stateRealLo;
             }
         } else if (type==T_GATE){
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
             for (thisTask=0; thisTask<numTasks; thisTask++) {
                 thisBlock   = thisTask / sizeHalfBlock;
                 indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                 indexLo     = indexUp + sizeHalfBlock;
                 stateRealLo = stateVecReal[indexLo];
                 stateImagLo = stateVecImag[indexLo];
                 stateVecReal[indexLo] = recRoot2 * (stateRealLo - stateImagLo);
                 stateVecImag[indexLo] = recRoot2 * (stateRealLo + stateImagLo);
             }
         } else printf("Type %d is an invalid phase gate\n", type);
     }
 }
reportMultiQubitParams()
void reportMultiQubitParams (MultiQubit multiQubit)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
Parameters
[in,out] multiQubit object representing the set of qubits
[in] env object representing the execution environment (local, multinode etc)
Definition at line 125 of file QuEST.c.
Referenced by main().
{
     long long int numAmps = 1L << multiQubit.numQubits;
     long long int numAmpsPerRank = numAmps/multiQubit.numChunks;
     if (multiQubit.chunkId==0){
         printf("QUBITS:\n");
         printf("Number of qubits is %d.\n", multiQubit.numQubits);
         printf("Number of amps is %lld.\n", numAmps);
         printf("Number of amps per rank is %lld.\n", numAmpsPerRank);
     }
 }
reportState()
void reportState (MultiQubit multiQubit)
Print the current state vector of probability amplitudes for a set of qubits to file.
File format:
real, imag
realComponent1, imagComponent1
realComponent2, imagComponent2
...
realComponentN, imagComponentN
File naming convention:
For each node that the program runs on, a file 'state_rank_[node_rank].csv' is generated. If there is more than one node, ranks after the first do not include the header
real, imag
so that files are easier to combine.
Parameters
[in,out] multiQubit object representing the set of qubits
Definition at line 86 of file QuEST.c.
{
     FILE *state;
     char filename[100];
     long long int index;
     sprintf(filename, "state_rank_%d.csv", multiQubit.chunkId);
     state = fopen(filename, "w");
     QuESTAssert(state!=NULL, 11, __func__);
     if (multiQubit.chunkId==0) fprintf(state, "real, imag\n");
     for(index=0; index<multiQubit.numAmpsPerChunk; index++){
         fprintf(state, REAL_STRING_FORMAT "," REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
     }
     fclose(state);
 }
reportStateToScreen()
void reportStateToScreen (MultiQubit multiQubit, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 101 of file QuEST.c.
Referenced by reportTest().
{
     long long int index;
     int rank;
     if (multiQubit.numQubits<=5){
         for (rank=0; rank<multiQubit.numChunks; rank++){
             if (multiQubit.chunkId==rank){
                 if (reportRank) {
                     printf("Reporting state from rank %d [\n", multiQubit.chunkId);
                     printf("real, imag\n");
                 } else if (rank==0) {
                     printf("Reporting state [\n");
                     printf("real, imag\n");
                 }
                 for(index=0; index<multiQubit.numAmpsPerChunk; index++){
                     printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", multiQubit.stateVec.real[index], multiQubit.stateVec.imag[index]);
                 }
                 if (reportRank || rank==multiQubit.numChunks-1) printf("]\n");
             }
             syncQuESTEnv(env);
         }
     } else printf("Error: reportStateToScreen will not print output for systems of more than 5 qubits.\n");
 }
rotateAroundAxis()
void rotateAroundAxis (MultiQubit multiQubit, const int rotQubit, REAL angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies where is the vector of Pauli matrices.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if rotQubit is outside [0, multiQubit.numQubits), or if axis is the zero vector
Definition at line 428 of file QuEST.c.
Referenced by main(), rotateX(), rotateY(), and rotateZ().
{
     double mag = sqrt(pow(axis.x,2) + pow(axis.y,2) + pow(axis.z,2));
     Vector unitAxis = {axis.x/mag, axis.y/mag, axis.z/mag};
     Complex alpha, beta;
     alpha.real = cos(angle/2.0);
     alpha.imag = -sin(angle/2.0)*unitAxis.z;
     beta.real = sin(angle/2.0)*unitAxis.y;
     beta.imag = -sin(angle/2.0)*unitAxis.x;
     compactUnitary(multiQubit, rotQubit, alpha, beta);
 }
rotateX()
void rotateX (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 441 of file QuEST.c.
{
     Vector unitAxis = {1, 0, 0};
     rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
 }
rotateY()
void rotateY (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 447 of file QuEST.c.
Referenced by main().
{
     Vector unitAxis = {0, 1, 0};
     rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
 }
rotateZ()
void rotateZ (MultiQubit multiQubit, const int rotQubit, REAL angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
For angle , applies
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, multiQubit.numQubits).
Definition at line 453 of file QuEST.c.
{
     Vector unitAxis = {0, 0, 1};
     rotateAroundAxis(multiQubit, rotQubit, angle, unitAxis);
 }
seedQuEST()
void seedQuEST (unsigned long int * seedArray, int numSeeds)
numSeeds <= 64
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
Definition at line 2019 of file QuEST.c.
Referenced by test_measure().
{
     // init MT random number generator with user defined list of seeds
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     init_by_array(seedArray, numSeeds);
 }
seedQuESTDefault()
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
This default seeding function uses the mt19937 init_by_array function with three keys – time, pid and hostname. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Definition at line 1994 of file QuEST.c.
Referenced by initQuESTEnv().
{
     // init MT random number generator with three keys -- time, pid and a hash of hostname
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     struct timeval  tv;
     gettimeofday(&tv, NULL);
     double time_in_mill =
         (tv.tv_sec) * 1000 + (tv.tv_usec) / 1000 ; // convert tv_sec & tv_usec to millisecond
     unsigned long int pid = getpid();
     unsigned long int msecs = (unsigned long int) time_in_mill;
     char hostName[MAXHOSTNAMELEN+1];
     gethostname(hostName, sizeof(hostName));
     unsigned long int hostNameInt = hashString(hostName);
     unsigned long int key[3];
     key[0] = msecs; key[1] = pid; key[2] = hostNameInt;
     init_by_array(key, 3);
 }
sGate()
void sGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit S gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits)
Definition at line 1626 of file QuEST.c.
Referenced by test_sGate().
 {
     phaseGate(multiQubit, targetQubit, S_GATE);
 }
sigmaXDistributed()
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks
Qubits are zero-based and the
the first qubit is the rightmost
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1165 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, and REAL.
Referenced by sigmaX().
 {
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
     private  (thisTask)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
             stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
         }
     }
 }
sigmaXLocal()
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1106 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaX().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateImagUp;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             stateRealUp = stateVecReal[indexUp];
             stateImagUp = stateVecImag[indexUp];
             stateVecReal[indexUp] = stateVecReal[indexLo];
             stateVecImag[indexUp] = stateVecImag[indexLo];
             stateVecReal[indexLo] = stateRealUp;
             stateVecImag[indexLo] = stateImagUp;
         }
     }
 }
sigmaYDistributed()
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks
Qubits are zero-based and the
the first qubit is the rightmost
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1352 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, and REAL.
Referenced by sigmaY().
 {
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
     int realSign=1, imagSign=1;
     if (updateUpper) imagSign=-1;
     else realSign = -1;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut,realSign,imagSign) \
     private  (thisTask)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             stateVecRealOut[thisTask] = realSign*stateVecImagIn[thisTask];
             stateVecImagOut[thisTask] = imagSign*stateVecRealIn[thisTask];
         }
     }
 }
sigmaYLocal()
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1293 of file QuEST.c.
References ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaY().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateImagUp;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             stateRealUp = stateVecReal[indexUp];
             stateImagUp = stateVecImag[indexUp];
             stateVecReal[indexUp] = stateVecImag[indexLo];
             stateVecImag[indexUp] = -stateVecReal[indexLo];
             stateVecReal[indexLo] = -stateImagUp;
             stateVecImag[indexLo] = stateRealUp;
         }
     }
 }
sigmaZ()
void sigmaZ (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Z (also known as the Z, Pauli-Z or phase-flip) gate.
This is a rotation of around the Z-axis (a phase shift) on the Bloch sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 1621 of file QuEST.c.
Referenced by test_sigmaZ().
 {
     phaseGate(multiQubit, targetQubit, SIGMA_Z);
 }
tGate()
void tGate (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit T gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits)
Definition at line 1631 of file QuEST.c.
Referenced by test_tGate().
 {
     phaseGate(multiQubit, targetQubit, T_GATE);
 }
unitaryDistributed()
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
Remarks
Qubits are zero-based and the first qubit is the rightmost
Parameters
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] u unitary matrix to apply
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 675 of file QuEST.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and Complex::real.
Referenced by unitary().
 {
     REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk;
     REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
     REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
     REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
     REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
     REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
             rot1Real, rot1Imag, rot2Real, rot2Imag) \
     private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             // store current state vector values in temp variables
             stateRealUp = stateVecRealUp[thisTask];
             stateImagUp = stateVecImagUp[thisTask];
             stateRealLo = stateVecRealLo[thisTask];
             stateImagLo = stateVecImagLo[thisTask];
             stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                 + rot2Real*stateRealLo - rot2Imag*stateImagLo;
             stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                 + rot2Real*stateImagLo + rot2Imag*stateRealLo;
         }
     }
 }
unitaryLocal()
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 549 of file QuEST.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmpsPerChunk, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, ComplexArray::real, REAL, Complex::real, and MultiQubit::stateVec.
Referenced by unitary().
 {
     long long int sizeBlock, sizeHalfBlock;
     long long int thisBlock, // current block
          indexUp,indexLo;    // current index and corresponding index in lower half block
     REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
     long long int thisTask;
     const long long int numTasks=multiQubit.numAmpsPerChunk>>1;
     // set dimensions
     sizeHalfBlock = 1LL << targetQubit;
     sizeBlock     = 2LL * sizeHalfBlock;
     // Can't use multiQubit.stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
     private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (thisTask=0; thisTask<numTasks; thisTask++) {
             thisBlock   = thisTask / sizeHalfBlock;
             indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
             indexLo     = indexUp + sizeHalfBlock;
             // store current state vector values in temp variables
             stateRealUp = stateVecReal[indexUp];
             stateImagUp = stateVecImag[indexUp];
             stateRealLo = stateVecReal[indexLo];
             stateImagLo = stateVecImag[indexLo];
             // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
             stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                 + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
             stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                 + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
             // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
             stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                 + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
             stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                 + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
         }
     }
 }
validateAlphaBeta()
int validateAlphaBeta (Complex alpha, Complex beta)
Definition at line 415 of file QuEST.c.
Referenced by compactUnitary(), and controlledCompactUnitary().
{
     if ( fabs(alpha.real*alpha.real
                 + alpha.imag*alpha.imag
                 + beta.real*beta.real
                 + beta.imag*beta.imag - 1) > REAL_EPS ) return 0;
     else return 1;
 }
validateMatrixIsUnitary()
int validateMatrixIsUnitary (ComplexMatrix2 u)
Definition at line 391 of file QuEST.c.
Referenced by controlledUnitary(), multiControlledUnitary(), and unitary().
{
     if ( fabs(u.r0c0.real*u.r0c0.real
                 + u.r0c0.imag*u.r0c0.imag
                 + u.r1c0.real*u.r1c0.real
                 + u.r1c0.imag*u.r1c0.imag - 1) > REAL_EPS ) return 0;
     if ( fabs(u.r0c1.real*u.r0c1.real
                 + u.r0c1.imag*u.r0c1.imag
                 + u.r1c1.real*u.r1c1.real
                 + u.r1c1.imag*u.r1c1.imag - 1) > REAL_EPS ) return 0;
     if ( fabs(u.r0c0.real*u.r0c1.real
                 + u.r0c0.imag*u.r0c1.imag
                 + u.r1c0.real*u.r1c1.real
                 + u.r1c0.imag*u.r1c1.imag) > REAL_EPS ) return 0;
     if ( fabs(u.r0c1.real*u.r0c0.imag
                 - u.r0c0.real*u.r0c1.imag
                 + u.r1c1.real*u.r1c0.imag
                 - u.r1c0.real*u.r1c1.imag) > REAL_EPS ) return 0;
     return 1;
 }
validateUnitVector()
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Definition at line 423 of file QuEST.c.
{
     if ( fabs(sqrt(ux*ux + uy*uy + uz*uz) - 1) > REAL_EPS ) return 0;
     else return 1;
 }
Variable Documentation
errorCodes
const char* errorCodes[]
Initial value:
= {
    "Success",
    "Invalid target qubit. Note qubits are zero indexed.",
    "Invalid control qubit. Note qubits are zero indexed.",
    "Control qubit cannot equal target qubit.",
    "Invalid number of control qubits",
    "Invalid unitary matrix.",
    "Invalid rotation arguments.",
    "Invalid system size. Cannot print output for systems greater than 5 qubits.",
    "Can't collapse to state with zero probability.",
    "Invalid number of qubits.",
    "Invalid measurement outcome -- must be either 0 or 1.",
    "Could not open file"
}
Definition at line 27 of file QuEST.c.
Referenced by exitWithError().