Quantum Exact Simulation Toolkit: QuEST_env_local.c File Reference
QuEST_env_local.c File Reference
An implementation of the API in qubits.h for a local (non-MPI) environment.
#include "../QuEST.h"
#include "../QuEST_precision.h"
#include "../mt19937ar.h"
#include "QuEST_internal.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/types.h>
Functions
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
void exitWithError (int errorCode, const char *func)
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
void initQuESTEnv (QuESTEnv *env)
Initialize the QuEST environment.
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL *stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
void multiControlledUnitary (MultiQubit multiQubit, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void QuESTAssert (int isValid, int errorCode, const char *func)
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
Detailed Description
An implementation of the API in qubits.h for a local (non-MPI) environment.
Definition in file QuEST_env_local.c.
Function Documentation
calcTotalProbability()
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
Should be equal to 1.
Parameters
[in] multiQubit object representing a set of qubits
Returns
total probability
Definition at line 60 of file QuEST_env_local.c.
Referenced by test_compactUnitary(), and test_unitary().
{
     // implemented using Kahan summation for greater accuracy at a slight floating
     // point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm
     REAL pTotal=0;
     REAL y, t, c;
     long long int index;
     long long int numAmpsPerRank = multiQubit.numAmpsPerChunk;
     c = 0.0;
     for (index=0; index<numAmpsPerRank; index++){
         // Perform pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index]; by Kahan
         y = multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
         // Perform pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index]; by Kahan
         y = multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
     }
     return pTotal;
 }
closeQuESTEnv()
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 39 of file QuEST_env_local.c.
Referenced by main().
{
     // MPI finalize goes here in MPI version. Call this function anyway for consistency
 }
collapseToOutcome()
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a measurement and forcing the outcome. This is an irreversible change to the state vector, whereby incompatible states in the state vector are given zero amplitude and the remaining states are renormalised. Exits with error if the given outcome has ~zero probability, and so cannot be collapsed into.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns
probability of the (forced) measurement outcome
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}, or if the probability of outcome is zero (within machine epsilon)
Definition at line 192 of file QuEST_env_local.c.
Referenced by test_collapseToOutcome().
 {
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert((outcome==0 || outcome==1), 10, __func__);
     REAL stateProb;
     stateProb = findProbabilityOfOutcome(multiQubit, measureQubit, outcome);
     QuESTAssert(fabs(stateProb)>REAL_EPS, 8, __func__);
     collapseToOutcomeLocal(multiQubit, measureQubit, stateProb, outcome);
     return stateProb;
 }
compactUnitary()
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
Given valid complex numbers and , applies the unitary
which is general up to a global phase factor.
Valid , satisfy .
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 98 of file QuEST_env_local.c.
Referenced by main(), rotateAroundAxis(), test_compactUnitary(), and test_unitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
     // all values required to update state vector lie in this rank
     compactUnitaryLocal(multiQubit, targetQubit, alpha, beta);
 }
controlledCompactUnitary()
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
Given valid complex numbers and , applies the two-qubit unitary
to the control and target qubits. Valid , satisfy . The target unitary is general up to a global phase factor.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply the target unitary if this qubit has value 1
[in] targetQubit qubit on which to apply the target unitary
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 116 of file QuEST_env_local.c.
Referenced by controlledRotateAroundAxis(), main(), test_controlledCompactUnitary(), test_controlledUnitary(), and test_multiControlledUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
     controlledCompactUnitaryLocal(multiQubit, controlQubit, targetQubit, alpha, beta);
 }
controlledNot()
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
This applies sigmaX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits), or are equal.
Definition at line 175 of file QuEST_env_local.c.
Referenced by main(), and test_controlledNot().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     controlledNotLocal(multiQubit, controlQubit, targetQubit);
 }
controlledUnitary()
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
The given unitary is applied to the target qubit if the control qubit has value 1, effecting the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply unitary if this qubit is 1
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if u is not unitary.
Definition at line 127 of file QuEST_env_local.c.
Referenced by test_controlledUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     controlledUnitaryLocal(multiQubit, controlQubit, targetQubit, u);
 }
exitWithError()
void exitWithError (int errorCode, const char * func)
Definition at line 232 of file QuEST_env_local.c.
Referenced by QuESTAssert().
{
     printf("!!!\n");
     printf("QuEST Error in function %s: %s\n", func, errorCodes[errorCode]);
     printf("!!!\n");
     printf("exiting..\n");
     exit(errorCode);
 }
findProbabilityOfOutcome()
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
This performs no actual measurement and does not change the state of the qubits.
Parameters
[in] multiQubit object representing the set of all qubits
[in] measureQubit qubit to study
[in] outcome for which to find the probability of the qubit being measured in
Returns
probability of qubit measureQubit being measured in the given outcome
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}.
Definition at line 183 of file QuEST_env_local.c.
Referenced by collapseToOutcome(), main(), measureWithStats(), and test_findProbabilityOfOutcome().
 {
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     REAL stateProb=0;
     stateProb = findProbabilityOfZeroLocal(multiQubit, measureQubit);
     if (outcome==1) stateProb = 1.0 - stateProb;
     return stateProb;
 }
getImagAmpEl()
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
imaginary component at that index
Exceptions
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 94 of file QuEST_env_local.c.
Referenced by getProbEl(), and test_getImagAmpEl().
{
     return multiQubit.stateVec.imag[index];
 }
getRealAmpEl()
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
real component at that index
Exceptions
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 90 of file QuEST_env_local.c.
Referenced by getProbEl(), and test_getRealAmpEl().
{
     return multiQubit.stateVec.real[index];
 }
hadamard()
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
This takes to and to , and is equivalent to a rotation of around the x-axis then about the y-axis on the Bloch-sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 169 of file QuEST_env_local.c.
Referenced by main(), and test_hadamard().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     hadamardLocal(multiQubit, targetQubit);
 }
initQuESTEnv()
void initQuESTEnv (QuESTEnv * env)
Initialize the QuEST environment.
If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here
Parameters
[in,out] env object representing the execution environment. A single instance is used for each program
Definition at line 23 of file QuEST_env_local.c.
Referenced by main().
{
     // init MPI environment
     env->rank=0;
     env->numRanks=1;
         seedQuESTDefault();
 }
measure()
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 203 of file QuEST_env_local.c.
Referenced by main(), and test_measure().
{
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     REAL stateProb;
     return measureWithStats(multiQubit, measureQubit, &stateProb);
 }
measureWithStats()
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL * stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[out] stateProb a pointer to a REAL which is set to the probability of the occurred outcome
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 209 of file QuEST_env_local.c.
Referenced by main(), measure(), and test_measureWithStats().
{
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     int outcome;
     // find probability of qubit being in state 1
     REAL stateProbInternal = findProbabilityOfOutcome(multiQubit, measureQubit, 1);
     // we can't collapse to a state that has a probability too close to zero
     if (stateProbInternal<REAL_EPS) outcome=0;
     else if (1-stateProbInternal<REAL_EPS) outcome=1;
     else {
         // ok. both P(0) and P(1) are large enough to resolve
         // generate random float on [0,1]
         float randNum = genrand_real1();
         if (randNum<=stateProbInternal) outcome = 1;
         else outcome = 0;
     }
     if (outcome==0) stateProbInternal = 1-stateProbInternal;
     collapseToOutcomeLocal(multiQubit, measureQubit, stateProbInternal, outcome);
     *stateProb = stateProbInternal;
     return outcome;
 }
multiControlledUnitary()
void multiControlledUnitary (MultiQubit multiQubit, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits. The given 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubits applies unitary if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if numControlQubits is outside [1, multiQubit.numQubits]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, multiQubit.numQubits]), or if controlQubits contains targetQubit, or if u is not unitary.
Definition at line 137 of file QuEST_env_local.c.
Referenced by main(), and test_multiControlledUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     long long int mask=0;
     for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
     QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
     QuESTAssert((mask & (1LL<<targetQubit)) != (1LL<<targetQubit), 3, __func__);
     multiControlledUnitaryLocal(multiQubit, targetQubit, mask, u);
 }
phaseGate()
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 163 of file QuEST_env_local.c.
Referenced by sGate(), sigmaZ(), and tGate().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     phaseGateLocal(multiQubit, targetQubit, type);
 }
QuESTAssert()
void QuESTAssert (int isValid, int errorCode, const char * func)
Definition at line 240 of file QuEST_env_local.c.
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledPhaseGate(), controlledUnitary(), createMultiQubit(), findProbabilityOfOutcome(), hadamard(), initializeStateFromSingleFile(), measure(), measureWithStats(), multiControlledPhaseGate(), multiControlledUnitary(), phaseGate(), reportState(), sigmaX(), sigmaY(), and unitary().
{
     if (!isValid) exitWithError(errorCode, func);
 }
reportNodeList()
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
For debugging purposes.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 56 of file QuEST_env_local.c.
{
     printf("Hostname unknown: running locally\n");
 }
reportQuESTEnv()
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 43 of file QuEST_env_local.c.
Referenced by main().
{
     printf("EXECUTION ENVIRONMENT:\n");
     printf("Running locally on one node\n");
     printf("Number of ranks is %d\n", env.numRanks);
 # ifdef _OPENMP
     printf("OpenMP enabled\n");
     printf("Number of threads available is %d\n", omp_get_max_threads());
 # else
     printf("OpenMP disabled\n");
 # endif
     printf("Precision: size of REAL is %ld bytes\n", sizeof(REAL));
 }
sigmaX()
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
This is a rotation of around the x-axis on the Bloch sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 151 of file QuEST_env_local.c.
Referenced by main(), and test_sigmaX().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     sigmaXLocal(multiQubit, targetQubit);
 }
sigmaY()
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
This is a rotation of around the Y-axis on the Bloch sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 157 of file QuEST_env_local.c.
Referenced by test_sigmaY().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     sigmaYLocal(multiQubit, targetQubit);
 }
syncQuESTEnv()
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 31 of file QuEST_env_local.c.
Referenced by initializeStateFromSingleFile(), reportStateToScreen(), and test_controlledNot().
{
     // MPI Barrier goes here in MPI version.
 }
syncQuESTSuccess()
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns
1 if all processes succeeded, 0 if any one process failed
Definition at line 35 of file QuEST_env_local.c.
Referenced by main().
{
     return successCode;
 }
unitary()
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or matrix u is not unitary.
Definition at line 107 of file QuEST_env_local.c.
Referenced by main(), and test_unitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     // all values required to update state vector lie in this rank
     unitaryLocal(multiQubit, targetQubit, u);
 }