Quantum Exact Simulation Toolkit: QuEST_debug.h File Reference
QuEST_debug.h File Reference
Developer functions used for unit testing and debugging.
#include "QuEST_precision.h"
Functions
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
void initializeStateFromSingleFile (MultiQubit *multiQubit, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
void initStateDebug (MultiQubit multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
void initStateOfSingleQubit (MultiQubit *multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
Detailed Description
Developer functions used for unit testing and debugging.
Not part of the public API. May contain functions that are incomplete or untested.
Definition in file QuEST_debug.h.
Function Documentation
compareStates()
int compareStates (MultiQubit mq1, MultiQubit mq2, REAL precision)
Return whether two given wavefunctions are equivalent within a given precision Global phase included in equivalence check.
For debugging purposes.
Definition at line 379 of file QuEST.c.
References copyStateFromGPU(), ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_collapseToOutcome(), test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_measure(), test_measureWithStats(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
{
     REAL diff;
     int chunkSize = mq1.numAmpsPerChunk;
     for (int i=0; i<chunkSize; i++){
         diff = fabs(mq1.stateVec.real[i] - mq2.stateVec.real[i]);
         if (diff>precision) return 0;
         diff = fabs(mq1.stateVec.imag[i] - mq2.stateVec.imag[i]);
         if (diff>precision) return 0;
     }
     return 1;
 }
initializeStateFromSingleFile()
void initializeStateFromSingleFile (MultiQubit * multiQubit, char filename[200], QuESTEnv env)
Initialises the wavefunction amplitudes according to those specified in a file.
For debugging purpsoses
fix – format needs to work for single precision values
Definition at line 343 of file QuEST.c.
References MultiQubit::chunkId, copyStateToGPU(), env, ComplexArray::imag, MultiQubit::numAmpsPerChunk, MultiQubit::numChunks, QuESTAssert(), ComplexArray::real, REAL, MultiQubit::stateVec, and syncQuESTEnv().
Referenced by test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_hadamard(), test_initStatePlus(), test_initStateZero(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), and test_tGate().
{
     long long int chunkSize, stateVecSize;
     long long int indexInChunk, totalIndex;
     chunkSize = multiQubit->numAmpsPerChunk;
     stateVecSize = chunkSize*multiQubit->numChunks;
     REAL *stateVecReal = multiQubit->stateVec.real;
     REAL *stateVecImag = multiQubit->stateVec.imag;
     FILE *fp;
     char line[200];
     for (int rank=0; rank<(multiQubit->numChunks); rank++){
         if (rank==multiQubit->chunkId){
             fp = fopen(filename, "r");
             QuESTAssert(fp!=NULL, 11, __func__);
             indexInChunk = 0; totalIndex = 0;
             while (fgets(line, sizeof(char)*200, fp) != NULL && totalIndex<stateVecSize){
                 if (line[0]!='#'){
                     int chunkId = totalIndex/chunkSize;
                     if (chunkId==multiQubit->chunkId){
                         sscanf(line, "%lf, %lf", &(stateVecReal[indexInChunk]),
                                 &(stateVecImag[indexInChunk]));
                         indexInChunk += 1;
                     }
                     totalIndex += 1;
                 }
             }
             fclose(fp);
         }
         syncQuESTEnv(env);
     }
 }
initStateDebug()
void initStateDebug (MultiQubit multiQubit)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters
[in,out] multiQubit object representing the set of qubits to be initialised
Definition at line 310 of file QuEST.c.
References MultiQubit::chunkId, MultiQubit::deviceStateVec, ComplexArray::imag, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_compactUnitary(), test_controlledCompactUnitary(), test_controlledNot(), test_controlledPhaseGate(), test_controlledUnitary(), test_getImagAmpEl(), test_getProbEl(), test_getRealAmpEl(), test_hadamard(), test_multiControlledPhaseGate(), test_multiControlledUnitary(), test_sGate(), test_sigmaX(), test_sigmaY(), test_sigmaZ(), test_tGate(), and test_unitary().
 {
     long long int chunkSize;
     long long int index;
         long long int indexOffset;
     // dimension of the state vector
     chunkSize = multiQubit.numAmpsPerChunk;
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit.stateVec.real;
     REAL *stateVecImag = multiQubit.stateVec.imag;
         indexOffset = chunkSize * multiQubit.chunkId;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (chunkSize, stateVecReal, stateVecImag, indexOffset) \
     private  (index)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<chunkSize; index++) {
             stateVecReal[index] = ((indexOffset + index)*2.0)/10.0;
             stateVecImag[index] = ((indexOffset + index)*2.0+1.0)/10.0;
         }
     }
 }
initStateOfSingleQubit()
void initStateOfSingleQubit (MultiQubit * multiQubit, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters
[in,out] multiQubit object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] value of qubit 'qubitId'
Definition at line 264 of file QuEST.c.
References MultiQubit::chunkId, MultiQubit::deviceStateVec, extractBit(), ComplexArray::imag, MultiQubit::numAmpsPerChunk, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by test_collapseToOutcome(), test_findProbabilityOfOutcome(), test_measure(), and test_measureWithStats().
 {
     long long int chunkSize, stateVecSize;
     long long int index;
     int bit;
     const long long int chunkId=multiQubit->chunkId;
     // dimension of the state vector
     chunkSize = multiQubit->numAmpsPerChunk;
     stateVecSize = chunkSize*multiQubit->numChunks;
     REAL normFactor = 1.0/sqrt((REAL)stateVecSize/2.0);
     // Can't use multiQubit->stateVec as a private OMP var
     REAL *stateVecReal = multiQubit->stateVec.real;
     REAL *stateVecImag = multiQubit->stateVec.imag;
     // initialise the state to |0000..0000>
 # ifdef _OPENMP
 # pragma omp parallel \
     default  (none) \
     shared   (chunkSize, stateVecReal, stateVecImag, normFactor, qubitId, outcome) \
     private  (index, bit)
 # endif
     {
 # ifdef _OPENMP
 # pragma omp for schedule (static)
 # endif
         for (index=0; index<chunkSize; index++) {
             bit = extractBit(qubitId, index+chunkId*chunkSize);
             if (bit==outcome) {
                 stateVecReal[index] = normFactor;
                 stateVecImag[index] = 0.0;
             } else {
                 stateVecReal[index] = 0.0;
                 stateVecImag[index] = 0.0;
             }
         }
     }
 }
reportNodeList()
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
For debugging purposes.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 56 of file QuEST_env_local.c.
References env, and QuESTEnv::rank.
{
     printf("Hostname unknown: running locally\n");
 }