Quantum Exact Simulation Toolkit: QuEST_env_mpi.c File Reference
QuEST_env_mpi.c File Reference
An implementation of the API in qubits.h for an MPI environment.
#include "../QuEST.h"
#include "../QuEST_precision.h"
#include "../mt19937ar.h"
#include "QuEST_internal.h"
#include <unistd.h>
#include <mpi.h>
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <time.h>
#include <sys/types.h>
Macros
#define _BSD_SOURCE
Functions
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
static int chunkIsUpper (int chunkId, long long int chunkSize, int targetQubit)
Returns whether a given chunk in position chunkId is in the upper or lower half of a block.
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
void exchangeStateVectors (MultiQubit multiQubit, int pairRank)
void exitWithError (int errorCode, const char *func)
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
static int getChunkIdFromIndex (MultiQubit multiQubit, long long int index)
static int getChunkPairId (int chunkIsUpper, int chunkId, long long int chunkSize, int targetQubit)
get position of corresponding chunk, holding values required to update values in my chunk (with chunkId) when rotating targetQubit.
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
static void getRotAngle (int chunkIsUpper, Complex *rot1, Complex *rot2, Complex alpha, Complex beta)
Get rotation values for a given chunk.
static void getRotAngleFromUnitaryMatrix (int chunkIsUpper, Complex *rot1, Complex *rot2, ComplexMatrix2 u)
Get rotation values for a given chunk given a unitary matrix.
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
static int halfMatrixBlockFitsInChunk (long long int chunkSize, int targetQubit)
return whether the current qubit rotation will use blocks that fit within a single chunk.
void initQuESTEnv (QuESTEnv *env)
Initialize the QuEST environment.
static int isChunkToSkipInFindPZero (int chunkId, long long int chunkSize, int measureQubit)
Find chunks to skip when calculating probability of qubit being zero.
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL *stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
void multiControlledUnitary (MultiQubit multiQubit, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void QuESTAssert (int isValid, int errorCode, const char *func)
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
Detailed Description
An implementation of the API in qubits.h for an MPI environment.
Definition in file QuEST_env_mpi.c.
Macro Definition Documentation
_BSD_SOURCE
#define _BSD_SOURCE
Definition at line 13 of file QuEST_env_mpi.c.
Function Documentation
calcTotalProbability()
REAL calcTotalProbability (MultiQubit multiQubit)
Calculate the probability of being in any state by taking the norm of the entire state vector.
Should be equal to 1.
Parameters
[in] multiQubit object representing a set of qubits
Returns
total probability
Definition at line 112 of file QuEST_env_mpi.c.
References ComplexArray::imag, MPI_QuEST_REAL, MultiQubit::numAmpsPerChunk, MultiQubit::numChunks, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
     // Implemented using Kahan summation for greater accuracy at a slight floating
     //   point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm
     REAL pTotal=0;
     REAL y, t, c;
     REAL allRankTotals=0;
     long long int index;
     long long int numAmpsPerRank = multiQubit.numAmpsPerChunk;
     c = 0.0;
     for (index=0; index<numAmpsPerRank; index++){
         // Perform pTotal+=multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index]; by Kahan
         y = multiQubit.stateVec.real[index]*multiQubit.stateVec.real[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
         // Perform pTotal+=multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index]; by Kahan
         y = multiQubit.stateVec.imag[index]*multiQubit.stateVec.imag[index] - c;
         t = pTotal + y;
         // Don't change the bracketing on the following line
         c = ( t - pTotal ) - y;
         pTotal = t;
     }
     if (multiQubit.numChunks>1) MPI_Allreduce(&pTotal, &allRankTotals, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
     else allRankTotals=pTotal;
     return allRankTotals;
 }
chunkIsUpper()
static int chunkIsUpper (int chunkId, long long int chunkSize, int targetQubit) static
Returns whether a given chunk in position chunkId is in the upper or lower half of a block.
Parameters
[in] chunkId id of chunk in state vector
[in] chunkSize number of amps in chunk
[in] targetQubit qubit being rotated
Returns
1: chunk is in upper half of block, 0: chunk is in lower half of block fix – is this the same as isChunkToSkip?
Definition at line 150 of file QuEST_env_mpi.c.
Referenced by compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledUnitary(), getChunkPairId(), getRotAngle(), getRotAngleFromUnitaryMatrix(), hadamard(), multiControlledUnitary(), phaseGate(), sigmaX(), sigmaY(), and unitary().
 {
     long long int sizeHalfBlock = 1LL << (targetQubit);
     long long int sizeBlock = sizeHalfBlock*2;
     long long int posInBlock = (chunkId*chunkSize) % sizeBlock;
     return posInBlock<sizeHalfBlock;
 }
closeQuESTEnv()
void closeQuESTEnv (QuESTEnv env)
Close QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 60 of file QuEST_env_mpi.c.
{
     int finalized;
     MPI_Finalized(&finalized);
     if (!finalized) MPI_Finalize();
     else printf("ERROR: Trying to close QuESTEnv multiple times. Ignoring\n");
 }
collapseToOutcome()
REAL collapseToOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a measurement and forcing the outcome. This is an irreversible change to the state vector, whereby incompatible states in the state vector are given zero amplitude and the remaining states are renormalised. Exits with error if the given outcome has ~zero probability, and so cannot be collapsed into.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns
probability of the (forced) measurement outcome
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}, or if the probability of outcome is zero (within machine epsilon)
Definition at line 678 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, collapseToOutcomeDistributedRenorm(), collapseToOutcomeDistributedSetZero(), collapseToOutcomeLocal(), findProbabilityOfOutcome(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
 {
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert((outcome==0 || outcome==1), 10, __func__);
     REAL totalStateProb=findProbabilityOfOutcome(multiQubit, measureQubit, outcome);
     QuESTAssert(fabs(totalStateProb)>REAL_EPS, 8, __func__);
     int skipValuesWithinRank = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, measureQubit);
     if (skipValuesWithinRank) {
         collapseToOutcomeLocal(multiQubit, measureQubit, totalStateProb, outcome);
     } else {
         if (!isChunkToSkipInFindPZero(multiQubit.chunkId, multiQubit.numAmpsPerChunk, measureQubit)){
             // chunk has amps for q=0
             if (outcome==0) collapseToOutcomeDistributedRenorm(multiQubit, measureQubit,
                     totalStateProb);
             else collapseToOutcomeDistributedSetZero(multiQubit, measureQubit);
         } else {
             // chunk has amps for q=1
             if (outcome==1) collapseToOutcomeDistributedRenorm(multiQubit, measureQubit,
                     totalStateProb);
             else collapseToOutcomeDistributedSetZero(multiQubit, measureQubit);
         }
     }
     return totalStateProb;
 }
compactUnitary()
void compactUnitary (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
Given valid complex numbers and , applies the unitary
which is general up to a global phase factor.
Valid , satisfy .
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 272 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), compactUnitaryDistributed(), compactUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateAlphaBeta().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     Complex rot1, rot2;
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         compactUnitaryLocal(multiQubit, targetQubit, alpha, beta);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         getRotAngle(rankIsUpper, &rot1, &rot2, alpha, beta);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block.
         // send values to compactUnitaryDistributed in the correct order
         if (rankIsUpper){
             compactUnitaryDistributed(multiQubit,targetQubit,rot1,rot2,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec); //output
         } else {
             compactUnitaryDistributed(multiQubit,targetQubit,rot1,rot2,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec); //output
         }
     }
 }
controlledCompactUnitary()
void controlledCompactUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
Given valid complex numbers and , applies the two-qubit unitary
to the control and target qubits. Valid , satisfy . The target unitary is general up to a global phase factor.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply the target unitary if this qubit has value 1
[in] targetQubit qubit on which to apply the target unitary
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 354 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledCompactUnitaryDistributed(), controlledCompactUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngle(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateAlphaBeta().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     QuESTAssert(validateAlphaBeta(alpha, beta), 6, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     Complex rot1, rot2;
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         controlledCompactUnitaryLocal(multiQubit, controlQubit, targetQubit, alpha, beta);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         getRotAngle(rankIsUpper, &rot1, &rot2, alpha, beta);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. send values to controlledCompactUnitaryDistributed
         // in the correct order
         if (rankIsUpper){
             controlledCompactUnitaryDistributed(multiQubit,controlQubit,targetQubit,rot1,rot2,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec); //output
         } else {
             controlledCompactUnitaryDistributed(multiQubit,controlQubit,targetQubit,rot1,rot2,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec); //output
         }
     }
 }
controlledNot()
void controlledNot (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
This applies sigmaX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits), or are equal.
Definition at line 516 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledNotDistributed(), controlledNotLocal(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), and MultiQubit::stateVec.
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         controlledNotLocal(multiQubit, controlQubit, targetQubit);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. send values to controlledNot
         // in the correct order
         if (rankIsUpper){
             controlledNotDistributed(multiQubit,controlQubit,targetQubit,
                     multiQubit.pairStateVec, //in
                     multiQubit.stateVec); //out
         } else {
             controlledNotDistributed(multiQubit,controlQubit,targetQubit,
                     multiQubit.pairStateVec, //in
                     multiQubit.stateVec); //out
         }
     }
 }
controlledUnitary()
void controlledUnitary (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
The given unitary is applied to the target qubit if the control qubit has value 1, effecting the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubit apply unitary if this qubit is 1
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, multiQubit.numQubits) or are equal, or if u is not unitary.
Definition at line 397 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), controlledUnitaryDistributed(), controlledUnitaryLocal(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateMatrixIsUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(controlQubit >= 0 && controlQubit < multiQubit.numQubits, 2, __func__);
     QuESTAssert(controlQubit != targetQubit, 3, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     Complex rot1, rot2;
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         controlledUnitaryLocal(multiQubit, controlQubit, targetQubit, u);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. send values to controlledUnitaryDistributed
         // in the correct order
         if (rankIsUpper){
             controlledUnitaryDistributed(multiQubit,controlQubit,targetQubit,rot1,rot2,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec); //output
         } else {
             controlledUnitaryDistributed(multiQubit,controlQubit,targetQubit,rot1,rot2,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec); //output
         }
     }
 }
exchangeStateVectors()
void exchangeStateVectors (MultiQubit multiQubit, int pairRank)
Definition at line 242 of file QuEST_env_mpi.c.
References ComplexArray::imag, MPI_QuEST_REAL, MultiQubit::numAmpsPerChunk, MultiQubit::pairStateVec, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledUnitary(), hadamard(), multiControlledUnitary(), sigmaX(), sigmaY(), and unitary().
{
     // MPI send/receive vars
     int TAG=100;
     MPI_Status status;
     // Multiple messages are required as MPI uses int rather than long long int for count
     // For openmpi, messages are further restricted to 2GB in size -- do this for all cases
     // to be safe
     long long int maxMessageCount = 1LL<<29;
     if (sizeof(REAL)==8) maxMessageCount = (1LL<<28);
     else if (sizeof(REAL)==16) maxMessageCount = (1LL<<27);
     if (multiQubit.numAmpsPerChunk<maxMessageCount) maxMessageCount = multiQubit.numAmpsPerChunk;
     int numMessages = multiQubit.numAmpsPerChunk/maxMessageCount;
     int i;
     long long int offset;
     // send my state vector to pairRank's multiQubit.pairStateVec
     // receive pairRank's state vector into multiQubit.pairStateVec
     for (i=0; i<numMessages; i++){
         offset = i*maxMessageCount;
         MPI_Sendrecv(&multiQubit.stateVec.real[offset], maxMessageCount, MPI_QuEST_REAL, pairRank, TAG,
                 &multiQubit.pairStateVec.real[offset], maxMessageCount, MPI_QuEST_REAL,
                 pairRank, TAG, MPI_COMM_WORLD, &status);
         //printf("rank: %d err: %d\n", multiQubit.rank, err);
         MPI_Sendrecv(&multiQubit.stateVec.imag[offset], maxMessageCount, MPI_QuEST_REAL, pairRank, TAG,
                 &multiQubit.pairStateVec.imag[offset], maxMessageCount, MPI_QuEST_REAL,
                 pairRank, TAG, MPI_COMM_WORLD, &status);
     }
 }
exitWithError()
void exitWithError (int errorCode, const char * func)
Definition at line 752 of file QuEST_env_mpi.c.
References errorCodes.
Referenced by QuESTAssert().
{
     printf("!!!\n");
     printf("QuEST Error in function %s: %s\n", func, errorCodes[errorCode]);
     printf("!!!\n");
     printf("exiting..\n");
     MPI_Abort(MPI_COMM_WORLD, errorCode);
 }
findProbabilityOfOutcome()
REAL findProbabilityOfOutcome (MultiQubit multiQubit, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
This performs no actual measurement and does not change the state of the qubits.
Parameters
[in] multiQubit object representing the set of all qubits
[in] measureQubit qubit to study
[in] outcome for which to find the probability of the qubit being measured in
Returns
probability of qubit measureQubit being measured in the given outcome
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits), or if outcome is not in {0, 1}.
Definition at line 659 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, findProbabilityOfZeroDistributed(), findProbabilityOfZeroLocal(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MPI_QuEST_REAL, MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, QuESTAssert(), and REAL.
Referenced by collapseToOutcome(), and measureWithStats().
 {
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     REAL stateProb=0, totalStateProb=0;
     int skipValuesWithinRank = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, measureQubit);
     if (skipValuesWithinRank) {
         stateProb = findProbabilityOfZeroLocal(multiQubit, measureQubit);
     } else {
         if (!isChunkToSkipInFindPZero(multiQubit.chunkId, multiQubit.numAmpsPerChunk, measureQubit)){
             stateProb = findProbabilityOfZeroDistributed(multiQubit, measureQubit);
         } else stateProb = 0;
     }
     MPI_Allreduce(&stateProb, &totalStateProb, 1, MPI_QuEST_REAL, MPI_SUM, MPI_COMM_WORLD);
     if (outcome==1) totalStateProb = 1.0 - totalStateProb;
     return totalStateProb;
 }
getChunkIdFromIndex()
int getChunkIdFromIndex (MultiQubit multiQubit, long long int index) static
Definition at line 88 of file QuEST_env_mpi.c.
References MultiQubit::numAmpsPerChunk.
Referenced by getImagAmpEl(), and getRealAmpEl().
{
     return index/multiQubit.numAmpsPerChunk; // this is numAmpsPerChunk
 }
getChunkPairId()
static int getChunkPairId (int chunkIsUpper, int chunkId, long long int chunkSize, int targetQubit) static
get position of corresponding chunk, holding values required to update values in my chunk (with chunkId) when rotating targetQubit.
Parameters
[in] chunkIsUpper 1: chunk is in upper half of block, 0: chunk is in lower half
[in] chunkId id of chunk in state vector
[in] chunkSize number of amps in chunk
[in] targetQubit qubit being rotated
Returns
chunkId of chunk required to rotate targetQubit
Definition at line 217 of file QuEST_env_mpi.c.
References chunkIsUpper().
Referenced by compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledUnitary(), hadamard(), multiControlledUnitary(), sigmaX(), sigmaY(), and unitary().
 {
     long long int sizeHalfBlock = 1LL << (targetQubit);
     int chunksPerHalfBlock = sizeHalfBlock/chunkSize;
     if (chunkIsUpper){
         return chunkId + chunksPerHalfBlock;
     } else {
         return chunkId - chunksPerHalfBlock;
     }
 }
getImagAmpEl()
REAL getImagAmpEl (MultiQubit multiQubit, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
imaginary component at that index
Exceptions
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 102 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, getChunkIdFromIndex(), ComplexArray::imag, MPI_QuEST_REAL, MultiQubit::numAmpsPerChunk, REAL, and MultiQubit::stateVec.
{
     int chunkId = getChunkIdFromIndex(multiQubit, index);
     REAL el;
     if (multiQubit.chunkId==chunkId){
         el = multiQubit.stateVec.imag[index-chunkId*multiQubit.numAmpsPerChunk];
     }
     MPI_Bcast(&el, 1, MPI_QuEST_REAL, chunkId, MPI_COMM_WORLD);
     return el;
 }
getRealAmpEl()
REAL getRealAmpEl (MultiQubit multiQubit, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] multiQubit object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
real component at that index
Exceptions
exitWithError if index is outside [0,) where multiQubit.numQubits
Definition at line 92 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, getChunkIdFromIndex(), MPI_QuEST_REAL, MultiQubit::numAmpsPerChunk, ComplexArray::real, REAL, and MultiQubit::stateVec.
{
     int chunkId = getChunkIdFromIndex(multiQubit, index);
     REAL el;
     if (multiQubit.chunkId==chunkId){
         el = multiQubit.stateVec.real[index-chunkId*multiQubit.numAmpsPerChunk];
     }
     MPI_Bcast(&el, 1, MPI_QuEST_REAL, chunkId, MPI_COMM_WORLD);
     return el;
 }
getRotAngle()
static void getRotAngle (int chunkIsUpper, Complex * rot1, Complex * rot2, Complex alpha, Complex beta) static
Get rotation values for a given chunk.
Parameters
[in] chunkIsUpper 1: chunk is in upper half of block, 0: chunk is in lower half
[out] rot1,rot2 rotation values to use, allocated for upper/lower such that
stateUpper = rot1 * stateUpper + conj(rot2)  * stateLower
or
stateLower = rot1 * stateUpper + conj(rot2)  * stateLower
[in] alpha,beta initial rotation values
Definition at line 172 of file QuEST_env_mpi.c.
References chunkIsUpper(), Complex::imag, and Complex::real.
Referenced by compactUnitary(), and controlledCompactUnitary().
 {
     if (chunkIsUpper){
         *rot1=alpha;
         rot2->real=-beta.real;
         rot2->imag=-beta.imag;
     } else {
         *rot1=beta;
         *rot2=alpha;
     }
 }
getRotAngleFromUnitaryMatrix()
static void getRotAngleFromUnitaryMatrix (int chunkIsUpper, Complex * rot1, Complex * rot2, ComplexMatrix2 u) static
Get rotation values for a given chunk given a unitary matrix.
Parameters
[in] chunkIsUpper 1: chunk is in upper half of block, 0: chunk is in lower half
[out] rot1,rot2 rotation values to use, allocated for upper/lower such that
stateUpper = rot1 * stateUpper + conj(rot2)  * stateLower
or
stateLower = rot1 * stateUpper + conj(rot2)  * stateLower
[in] u unitary matrix operation
Definition at line 197 of file QuEST_env_mpi.c.
References chunkIsUpper(), ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, and ComplexMatrix2::r1c1.
Referenced by controlledUnitary(), multiControlledUnitary(), and unitary().
 {
     if (chunkIsUpper){
         *rot1=u.r0c0;
         *rot2=u.r0c1;
     } else {
         *rot1=u.r1c0;
         *rot2=u.r1c1;
     }
 }
hadamard()
void hadamard (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit Hadamard gate.
This takes to and to , and is equivalent to a rotation of around the x-axis then about the y-axis on the Bloch-sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 602 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), hadamardDistributed(), hadamardLocal(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), and MultiQubit::stateVec.
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         hadamardLocal(multiQubit, targetQubit);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. send values to hadamardDistributed
         // in the correct order
         if (rankIsUpper){
             hadamardDistributed(multiQubit,targetQubit,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec, rankIsUpper); //output
         } else {
             hadamardDistributed(multiQubit,targetQubit,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec, rankIsUpper); //output
         }
     }
 }
halfMatrixBlockFitsInChunk()
static int halfMatrixBlockFitsInChunk (long long int chunkSize, int targetQubit) static
return whether the current qubit rotation will use blocks that fit within a single chunk.
Parameters
[in] chunkSize number of amps in chunk
[in] targetQubit qubit being rotated
Returns
1: one chunk fits in one block 0: chunk is larger than block
Definition at line 235 of file QuEST_env_mpi.c.
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledUnitary(), findProbabilityOfOutcome(), hadamard(), measureWithStats(), multiControlledUnitary(), phaseGate(), sigmaX(), sigmaY(), and unitary().
 {
     long long int sizeHalfBlock = 1LL << (targetQubit);
     if (chunkSize > sizeHalfBlock) return 1;
     else return 0;
 }
initQuESTEnv()
void initQuESTEnv (QuESTEnv * env)
Initialize the QuEST environment.
If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here
Parameters
[in,out] env object representing the execution environment. A single instance is used for each program
Definition at line 33 of file QuEST_env_mpi.c.
References env, QuESTEnv::numRanks, QuESTEnv::rank, and seedQuESTDefault().
{
     // init MPI environment
     int rank, numRanks, initialized;
     MPI_Initialized(&initialized);
     if (!initialized){
         MPI_Init(NULL, NULL);
         MPI_Comm_size(MPI_COMM_WORLD, &numRanks);
         MPI_Comm_rank(MPI_COMM_WORLD, &rank);
         env->rank=rank;
         env->numRanks=numRanks;
     } else printf("ERROR: Trying to initialize QuESTEnv multiple times. Ignoring\n");
         seedQuESTDefault();
 }
isChunkToSkipInFindPZero()
static int isChunkToSkipInFindPZero (int chunkId, long long int chunkSize, int measureQubit) static
Find chunks to skip when calculating probability of qubit being zero.
When calculating probability of a bit q being zero, sum up 2^q values, then skip 2^q values, etc. This function finds if an entire chunk is in the range of values to be skipped
Parameters
[in] chunkId id of chunk in state vector
[in] chunkSize number of amps in chunk
[in] measureQubi qubit being measured
Returns
int – 1: skip, 0: don't skip
Definition at line 650 of file QuEST_env_mpi.c.
Referenced by collapseToOutcome(), findProbabilityOfOutcome(), and measureWithStats().
 {
     long long int sizeHalfBlock = 1LL << (measureQubit);
     int numChunksToSkip = sizeHalfBlock/chunkSize;
     // calculate probability by summing over numChunksToSkip, then skipping numChunksToSkip, etc
     int bitToCheck = chunkId & numChunksToSkip;
     return bitToCheck;
 }
measure()
int measure (MultiQubit multiQubit, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 706 of file QuEST_env_mpi.c.
References measureWithStats(), MultiQubit::numQubits, QuESTAssert(), and REAL.
{
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     REAL stateProb;
     return measureWithStats(multiQubit, measureQubit, &stateProb);
 }
measureWithStats()
int measureWithStats (MultiQubit multiQubit, int measureQubit, REAL * stateProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] measureQubit qubit to measure
[out] stateProb a pointer to a REAL which is set to the probability of the occurred outcome
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, multiQubit.numQubits)
Definition at line 712 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, collapseToOutcomeDistributedRenorm(), collapseToOutcomeDistributedSetZero(), collapseToOutcomeLocal(), findProbabilityOfOutcome(), genrand_real1(), halfMatrixBlockFitsInChunk(), isChunkToSkipInFindPZero(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, QuESTAssert(), REAL, and REAL_EPS.
Referenced by measure().
{
     QuESTAssert(measureQubit >= 0 && measureQubit < multiQubit.numQubits, 2, __func__);
     int outcome;
     // find probability of qubit being in state 1
     REAL stateProbInternal = findProbabilityOfOutcome(multiQubit, measureQubit, 1);
     // we can't collapse to a state that has a probability too close to zero
     if (stateProbInternal<REAL_EPS) outcome=0;
     else if (1-stateProbInternal<REAL_EPS) outcome=1;
     else {
         // ok. both P(0) and P(1) are large enough to resolve
         // generate random float on [0,1]
         float randNum = genrand_real1();
         if (randNum<=stateProbInternal) outcome = 1;
         else outcome = 0;
     }
     if (outcome==0) stateProbInternal = 1-stateProbInternal;
     int skipValuesWithinRank = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, measureQubit);
     if (skipValuesWithinRank) {
         collapseToOutcomeLocal(multiQubit, measureQubit, stateProbInternal, outcome);
     } else {
         if (!isChunkToSkipInFindPZero(multiQubit.chunkId, multiQubit.numAmpsPerChunk, measureQubit)){
             // chunk has amps for q=0
             if (outcome==0) collapseToOutcomeDistributedRenorm(multiQubit, measureQubit,
                     stateProbInternal);
             else collapseToOutcomeDistributedSetZero(multiQubit, measureQubit);
         } else {
             // chunk has amps for q=1
             if (outcome==1) collapseToOutcomeDistributedRenorm(multiQubit, measureQubit,
                     stateProbInternal);
             else collapseToOutcomeDistributedSetZero(multiQubit, measureQubit);
         }
     }
     *stateProb = stateProbInternal;
     return outcome;
 }
multiControlledUnitary()
void multiControlledUnitary (MultiQubit multiQubit, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits. The given 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] controlQubits applies unitary if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if numControlQubits is outside [1, multiQubit.numQubits]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, multiQubit.numQubits]), or if controlQubits contains targetQubit, or if u is not unitary.
Definition at line 441 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), multiControlledUnitaryDistributed(), multiControlledUnitaryLocal(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, and validateMatrixIsUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(numControlQubits > 0 && numControlQubits <= multiQubit.numQubits, 4, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     long long int mask=0;
     for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
     QuESTAssert(mask >=0 && mask <= (1LL<<multiQubit.numQubits)-1, 2, __func__);
     QuESTAssert((mask & (1LL<<targetQubit)) != (1LL<<targetQubit), 3, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     Complex rot1, rot2;
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         multiControlledUnitaryLocal(multiQubit, targetQubit, mask, u);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. send values to multiControlledUnitaryDistributed
         // in the correct order
         if (rankIsUpper){
             multiControlledUnitaryDistributed(multiQubit,targetQubit,mask,rot1,rot2,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec); //output
         } else {
             multiControlledUnitaryDistributed(multiQubit,targetQubit,mask,rot1,rot2,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec); //output
         }
     }
 }
phaseGate()
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 584 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, phaseGateDistributed(), phaseGateLocal(), and QuESTAssert().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     // rank's chunk is in upper half of block
     int rankIsUpper;
     if (useLocalDataOnly){
         phaseGateLocal(multiQubit, targetQubit, type);
     } else {
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         if (!rankIsUpper) phaseGateDistributed(multiQubit, targetQubit, type);
     }
 }
QuESTAssert()
void QuESTAssert (int isValid, int errorCode, const char * func)
Definition at line 760 of file QuEST_env_mpi.c.
References exitWithError().
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledUnitary(), findProbabilityOfOutcome(), hadamard(), measure(), measureWithStats(), multiControlledUnitary(), phaseGate(), sigmaX(), sigmaY(), and unitary().
{
     if (!isValid) exitWithError(errorCode, func);
 }
reportNodeList()
void reportNodeList (QuESTEnv env)
Report a list of CPU hostnames and the rank that is running on each if running with MPI enabled and an error message otherwise.
For debugging purposes.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 82 of file QuEST_env_mpi.c.
References env, and QuESTEnv::rank.
{
     char hostName[256];
     gethostname(hostName, 255);
     printf("hostname on rank %d: %s\n", env.rank, hostName);
 }
reportQuESTEnv()
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 67 of file QuEST_env_mpi.c.
References env, QuESTEnv::numRanks, QuESTEnv::rank, and REAL.
{
     if (env.rank==0){
         printf("EXECUTION ENVIRONMENT:\n");
         printf("Running distributed (MPI) version\n");
         printf("Number of ranks is %d\n", env.numRanks);
 # ifdef _OPENMP
         printf("OpenMP enabled\n");
         printf("Number of threads available is %d\n", omp_get_max_threads());
 # else
         printf("OpenMP disabled\n");
 # endif
         printf("Precision: size of REAL is %ld bytes\n", sizeof(REAL));
     }
 }
sigmaX()
void sigmaX (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-X (also known as the X, Pauli-X, NOT or bit-flip) gate.
This is a rotation of around the x-axis on the Bloch sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
Definition at line 487 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), sigmaXDistributed(), sigmaXLocal(), and MultiQubit::stateVec.
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         sigmaXLocal(multiQubit, targetQubit);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. sigmaX just replaces
         // this rank's values with pair values
         sigmaXDistributed(multiQubit, targetQubit,
                 multiQubit.pairStateVec, // in
                 multiQubit.stateVec); // out
     }
 }
sigmaY()
void sigmaY (MultiQubit multiQubit, const int targetQubit)
Apply the single-qubit sigma-Y (also known as the Y or Pauli-Y) gate.
This is a rotation of around the Y-axis on the Bloch sphere. I.e.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits).
fix – put duplicate code (sigmaX, sigmaY) in seperate function
Definition at line 553 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), sigmaYDistributed(), sigmaYLocal(), and MultiQubit::stateVec.
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         sigmaYLocal(multiQubit, targetQubit);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         //printf("%d rank has pair rank: %d\n", multiQubit.rank, pairRank);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block. sigmaX just replaces
         // this rank's values with pair values
         sigmaYDistributed(multiQubit,targetQubit,
                 multiQubit.pairStateVec, // in
                 multiQubit.stateVec, // out
                 rankIsUpper);
     }
 }
syncQuESTEnv()
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
Parameters
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 50 of file QuEST_env_mpi.c.
{
     MPI_Barrier(MPI_COMM_WORLD);
 }
syncQuESTSuccess()
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns
1 if all processes succeeded, 0 if any one process failed
Definition at line 54 of file QuEST_env_mpi.c.
{
     int totalSuccess;
     MPI_Allreduce(&successCode, &totalSuccess, 1, MPI_INT, MPI_LAND, MPI_COMM_WORLD);
     return totalSuccess;
 }
unitary()
void unitary (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] multiQubit object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit is outside [0, multiQubit.numQubits), or matrix u is not unitary.
Definition at line 312 of file QuEST_env_mpi.c.
References MultiQubit::chunkId, chunkIsUpper(), exchangeStateVectors(), getChunkPairId(), getRotAngleFromUnitaryMatrix(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmpsPerChunk, MultiQubit::numQubits, MultiQubit::pairStateVec, QuESTAssert(), MultiQubit::stateVec, unitaryDistributed(), unitaryLocal(), and validateMatrixIsUnitary().
 {
     QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
     QuESTAssert(validateMatrixIsUnitary(u), 5, __func__);
     // flag to require memory exchange. 1: an entire block fits on one rank, 0: at most half a block fits on one rank
     int useLocalDataOnly = halfMatrixBlockFitsInChunk(multiQubit.numAmpsPerChunk, targetQubit);
     Complex rot1, rot2;
     // rank's chunk is in upper half of block
     int rankIsUpper;
     int pairRank; // rank of corresponding chunk
     if (useLocalDataOnly){
         // all values required to update state vector lie in this rank
         unitaryLocal(multiQubit, targetQubit, u);
     } else {
         // need to get corresponding chunk of state vector from other rank
         rankIsUpper = chunkIsUpper(multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         getRotAngleFromUnitaryMatrix(rankIsUpper, &rot1, &rot2, u);
         pairRank = getChunkPairId(rankIsUpper, multiQubit.chunkId, multiQubit.numAmpsPerChunk, targetQubit);
         // get corresponding values from my pair
         exchangeStateVectors(multiQubit, pairRank);
         // this rank's values are either in the upper of lower half of the block.
         // send values to compactUnitaryDistributed in the correct order
         if (rankIsUpper){
             unitaryDistributed(multiQubit,targetQubit,rot1,rot2,
                     multiQubit.stateVec, //upper
                     multiQubit.pairStateVec, //lower
                     multiQubit.stateVec); //output
         } else {
             unitaryDistributed(multiQubit,targetQubit,rot1,rot2,
                     multiQubit.pairStateVec, //upper
                     multiQubit.stateVec, //lower
                     multiQubit.stateVec); //output
         }
     }
 }