
import os

# generated by ctags -x --c-kinds=fp ../sourcename > outname
# where ctags is brew installed (not default OSX)

fns = ['quest-h',
       'quest-common-c',
       'quest-newinternal-h',
       'quest-debug-h',
       'GPU-quest-cpp',
       'GPU-quest-internal-h',
       'GPU-quest-env-localgpu-cu',
       'CPU-quest-c',
       'CPU-quest-internal-h',
       'CPU-quest-env-mpi-c',
       'CPU-quest-env-local-c']

for fn in fns:

    with open(fn, 'r') as f:
        lines = f.read().strip().split('\n')

    funcs = []
    protos = []

    # compile list of functions and prototypes in file
    for line in lines:
        terms = line.split()
        if not terms:
            continue
        
        if terms[1] == 'function':
            funcs.append(terms[0])
        elif terms[1] == 'prototype':
            protos.append(terms[0])
        else:
            print('ERROR: unknown type %s', terms[1])
            exit()

    # sort them
    funcs = sorted(funcs)
    protos = sorted(protos)

    # display them
    print(fn)
    print('-------------------')
    print('\nPROTOTYPES\n')
    print('\n'.join(protos))
    print('\nFUNCTIONS\n')
    print('\n'.join(funcs))
    print('')

    


    
    
