cmake_minimum_required(VERSION 3.28)
project(CuQuantumRealSdkLink LANGUAGES CXX)
get_filename_component(QUEST_MODULE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../../../../cmake" ABSOLUTE)
list(PREPEND CMAKE_MODULE_PATH "${QUEST_MODULE_DIR}")
find_package(CUQUANTUM REQUIRED MODULE COMPONENTS cuStateVec)
add_executable(custatevec-link main.cpp)
target_link_libraries(custatevec-link PRIVATE CUQUANTUM::cuStateVec)
target_compile_features(custatevec-link PRIVATE cxx_std_14)
enable_testing()
add_test(NAME custatevec.version COMMAND custatevec-link)
