cmake_minimum_required(VERSION 3.28)

# Clear all loader controls for every child process, including less common ones
# such as LD_AUDIT and DYLD_VERSIONED_LIBRARY_PATH which can mask missing RPATHs.
execute_process(COMMAND "${CMAKE_COMMAND}" -E environment
  OUTPUT_VARIABLE environment COMMAND_ERROR_IS_FATAL ANY)
string(REGEX MATCHALL "(^|\n)(LD_[A-Za-z0-9_]*|DYLD_[A-Za-z0-9_]*|LIBPATH|SHLIB_PATH)="
  loader_variables "${environment}")
foreach(entry IN LISTS loader_variables)
  string(REGEX REPLACE "^[\r\n]*([^=]+)=$" "\\1" variable "${entry}")
  unset(ENV{${variable}})
endforeach()

function(run)
  execute_process(COMMAND ${ARGV} RESULT_VARIABLE result
    OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    string(JOIN " " command ${ARGV})
    message(FATAL_ERROR "Command failed (${result}): ${command}\n${output}\n${error}")
  endif()
endfunction()

function(read_rpath binary result_var)
  if(CMAKE_HOST_APPLE)
    set(arguments -l)
  else()
    set(arguments -d)
  endif()
  execute_process(COMMAND "${RPATH_INSPECTOR}" ${arguments} "${binary}"
    RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
  if(NOT result EQUAL 0)
    message(FATAL_ERROR "Cannot inspect ${binary}: ${error}")
  endif()
  set(paths)
  if(CMAKE_HOST_APPLE)
    string(REGEX MATCHALL "cmd LC_RPATH[^\n]*\n[^\n]*\n[^\n]*" records "${output}")
    foreach(record IN LISTS records)
      string(REGEX REPLACE ".*\n[ \t]*path (.*) \\(offset [0-9]+\\).*" "\\1" path "${record}")
      list(APPEND paths "${path}")
    endforeach()
  else()
    string(REGEX MATCHALL "\\((RPATH|RUNPATH)\\)[^\n]*" records "${output}")
    foreach(record IN LISTS records)
      string(REGEX REPLACE ".*\\[(.*)\\].*" "\\1" path "${record}")
      string(REPLACE ":" ";" path "${path}")
      list(APPEND paths ${path})
    endforeach()
  endif()
  set(${result_var} "${paths}" PARENT_SCOPE)
endfunction()

function(require_path paths expected binary)
  if(NOT "${expected}" IN_LIST paths)
    message(FATAL_ERROR "${binary}: missing runtime path '${expected}'; found '${paths}'")
  endif()
endfunction()

# Every path has spaces, including the independent external SDK and relocation.
file(REMOVE_RECURSE "${WORK_DIR}")
set(external "${WORK_DIR}/external sdk")
set(build "${WORK_DIR}/consumer build")
set(stage "${WORK_DIR}/install staging")
set(relocated "${WORK_DIR}/relocated install")
if(NOT CONFIG)
  set(CONFIG Release)
endif()
set(configure_args -G "${GENERATOR}" "-DCMAKE_BUILD_TYPE=${CONFIG}")
run("${CMAKE_COMMAND}" -S "${FIXTURE_DIR}/external" -B "${WORK_DIR}/external build"
  ${configure_args} "-DCMAKE_INSTALL_PREFIX=${external}")
run("${CMAKE_COMMAND}" --build "${WORK_DIR}/external build" --config "${CONFIG}")
run("${CMAKE_COMMAND}" --install "${WORK_DIR}/external build" --config "${CONFIG}")
run("${CMAKE_COMMAND}" -S "${FIXTURE_DIR}/runtime" -B "${build}"
  ${configure_args} "-DCMAKE_INSTALL_PREFIX=${stage}"
  "-DEXTERNAL_PREFIX=${external}" "-DQUEST_MODULE_DIR=${QUEST_MODULE_DIR}" "-DCASE=${CASE}")
run("${CMAKE_COMMAND}" --build "${build}" --config "${CONFIG}")
include("${build}/artifacts-${CONFIG}.cmake")

if(CMAKE_HOST_APPLE)
  set(origin "@loader_path")
else()
  set(origin "$ORIGIN")
endif()
set(artifacts "libraries/quest/${SHARED_NAME}"
  "tools/run/${ORDINARY_NAME}" "tools/run/examples/extended/${NESTED_NAME}")
set(expected_origins "${origin}/" "${origin}/../../libraries/quest"
  "${origin}/../../../../libraries/quest")
set(build_artifacts "${BUILD_SHARED}" "${BUILD_ORDINARY}" "${BUILD_NESTED}")

# Skip-RPATH suppresses build paths too. Build-with-install uses exactly the
# installed paths, which need not locate project libraries in the build tree.
foreach(binary IN LISTS build_artifacts)
  read_rpath("${binary}" paths)
  if(CASE STREQUAL "skip_rpath" AND paths)
    message(FATAL_ERROR "${binary}: CMAKE_SKIP_RPATH left build paths '${paths}'")
  endif()
  string(FIND "${paths}" "${build}" build_index)
  if(NOT CMAKE_HOST_APPLE AND NOT build_index EQUAL -1)
    message(FATAL_ERROR "${binary}: build runtime path is not relative: '${paths}'")
  endif()
endforeach()
if(NOT CASE STREQUAL "skip_rpath" AND NOT CASE STREQUAL "build_with_install_rpath")
  run("${BUILD_ORDINARY}")
  run("${BUILD_NESTED}")
endif()

run("${CMAKE_COMMAND}" --install "${build}" --config "${CONFIG}")
file(RENAME "${stage}" "${relocated}")
foreach(index RANGE 0 2)
  list(GET artifacts ${index} artifact)
  list(GET expected_origins ${index} expected_origin)
  list(GET build_artifacts ${index} build_binary)
  set(binary "${relocated}/${artifact}")
  read_rpath("${binary}" paths)
  message(STATUS "${CASE}: ${artifact}: ${paths}")
  if(CASE STREQUAL "skip_rpath" OR CASE STREQUAL "skip_install_rpath")
    if(paths)
      message(FATAL_ERROR "${binary}: skip-RPATH was ignored: '${paths}'")
    endif()
  else()
    require_path("${paths}" "${expected_origin}" "${binary}")
    if(CASE STREQUAL "explicit_rpath" OR CASE STREQUAL "build_with_install_rpath")
      require_path("${paths}" "${external}/lib" "${binary}")
      require_path("${paths}" "${origin}/user supplied" "${binary}")
    elseif(CASE STREQUAL "use_link_path")
      # The ordinary executable depends only on the shared intermediary. Its
      # intermediary and the executable with a static intermediary use the SDK.
      if(NOT index EQUAL 1)
        require_path("${paths}" "${external}/lib" "${binary}")
      endif()
    else()
      string(FIND "${paths}" "${external}" external_index)
      if(NOT external_index EQUAL -1)
        message(FATAL_ERROR "${binary}: default/OFF captured the external SDK: '${paths}'")
      endif()
    endif()
  endif()
  foreach(forbidden IN ITEMS "${build}" "${stage}")
    string(FIND "${paths}" "${forbidden}" found)
    if(NOT found EQUAL -1)
      message(FATAL_ERROR "${binary}: leaked build/install path '${forbidden}' in '${paths}'")
    endif()
  endforeach()
  if(CASE STREQUAL "build_with_install_rpath")
    read_rpath("${build_binary}" build_paths)
    if(NOT paths STREQUAL build_paths)
      message(FATAL_ERROR "${binary}: BUILD_WITH_INSTALL_RPATH changed at install: '${build_paths}' -> '${paths}'")
    endif()
  endif()
endforeach()

# Remove project build products so they cannot conceal broken relocation.
file(REMOVE_RECURSE "${build}" "${WORK_DIR}/external build")
if(CASE STREQUAL "explicit_rpath" OR CASE STREQUAL "use_link_path"
    OR CASE STREQUAL "build_with_install_rpath")
  run("${relocated}/tools/run/${ORDINARY_NAME}")
  run("${relocated}/tools/run/examples/extended/${NESTED_NAME}")
endif()
