QuEST: QASM Logging
QASM Logging
Functions for recording performed gates to QASM
Functions
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
void writeRecordedQASMToFile (Qureg qureg, char *filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Detailed Description
Functions for recording performed gates to QASM
Function Documentation
clearRecordedQASM()
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
This does not start or stop recording.
Parameters
[in,out] qureg The qureg of which to clear the QASM log
Author
Tyson Jones
Definition at line 95 of file QuEST.c.
{
     qasm_clearRecorded(qureg);
 }
References qasm_clearRecorded().
printRecordedQASM()
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
This does not clear the QASM log, nor does it start or stop QASM recording.
Parameters
[in] qureg Prints the QASM recorded for this qureg.
Author
Tyson Jones
Definition at line 99 of file QuEST.c.
{
     qasm_printRecorded(qureg);
 }
References qasm_printRecorded().
startRecordingQASM()
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
Gates applied to qureg will here-after be added to a growing log of QASM instructions, progressively consuming more memory until disabled with stopRecordingQASM(). The QASM log is bound to this qureg instance.
Parameters
[in,out] qureg The qureg to begin recording subsequent operations upon
Author
Tyson Jones
Definition at line 87 of file QuEST.c.
{
     qasm_startRecording(qureg);
 }
References qasm_startRecording().
stopRecordingQASM()
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
The recorded QASM will be maintained in qureg and continue to be appended to if startRecordingQASM is recalled.
Has no effect if qureg was not already recording operations.
Parameters
[in,out] qureg The qureg to halt recording subsequent operations upon
Author
Tyson Jones
Definition at line 91 of file QuEST.c.
{
     qasm_stopRecording(qureg);
 }
References qasm_stopRecording().
writeRecordedQASMToFile()
void writeRecordedQASMToFile (Qureg qureg, char * filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Parameters
[in] qureg Writes the QASM recorded for this qureg to file
[in] filename The filename of the file to contain the recorded QASM
Exceptions
invalidQuESTInputError()
if filename cannot be written to
Author
Tyson Jones
Definition at line 103 of file QuEST.c.
{
     int success = qasm_writeRecordedToFile(qureg, filename);
     validateFileOpened(success, filename, __func__);
 }
References qasm_writeRecordedToFile(), and validateFileOpened().