QuEST: Decoherence
Decoherence
Decoherence channels which act on density matrices to induce mixing.
Functions
void mixDamping (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit amplitude damping (decay to 0 state).
void mixDensityMatrix (Qureg combineQureg, qreal prob, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
void mixDephasing (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
void mixDepolarising (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
void mixKrausMap (Qureg qureg, int target, ComplexMatrix2 *ops, int numOps)
Apply a general single-qubit Kraus map to a density matrix, as specified by at most four Kraus operators, (ops).
void mixMultiQubitKrausMap (Qureg qureg, int *targets, int numTargets, ComplexMatrixN *ops, int numOps)
Apply a general N-qubit Kraus map to a density matrix, as specified by at most (2N)^2 Kraus operators.
void mixPauli (Qureg qureg, int targetQubit, qreal probX, qreal probY, qreal probZ)
Mixes a density matrix qureg to induce general single-qubit Pauli noise.
void mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
void mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
void mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 *ops, int numOps)
Apply a general two-qubit Kraus map to a density matrix, as specified by at most sixteen Kraus operators.
Detailed Description
Decoherence channels which act on density matrices to induce mixing.
Function Documentation
mixDamping()
void mixDamping (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit amplitude damping (decay to 0 state).
With probability prob, applies damping (transition from 1 to 0 state).
This transforms qureg = into the mixed state
where q = targetQubit and and are Kraus operators
prob cannot exceed 1, at which total damping/decay occurs. Note that unlike mixDephasing() and mixDepolarising(), this function can increase the purity of a mixed state (by, as prob becomes 1, gaining certainty that the qubit is in the 0 state).
See also
mixDephasing()
mixDepolarising()
mixKrausMap()
mixPauli()
mixDensityMatrix()
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce amplitude damping
[in] prob the probability of the damping
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if targetQubit is outside [0, qureg.numQubitsRepresented)
if prob is not in [0, 1]
Author
Nicolas Vogt of HQS (local CPU)
Ania Brown (GPU, patched local CPU)
Tyson Jones (distributed, doc)
Definition at line 1283 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDampingProb(prob, __func__);
     densmatr_mixDamping(qureg, targetQubit, prob);
 }
References densmatr_mixDamping(), validateDensityMatrQureg(), validateOneQubitDampingProb(), and validateTarget().
Referenced by TEST_CASE().
mixDensityMatrix()
void mixDensityMatrix (Qureg combineQureg, qreal prob, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
Both registers must be equal-dimension density matrices, and prob must be in [0, 1].
See also
mixDephasing()
mixDepolarising()
mixDamping()
mixKrausMap()
mixPauli()
Parameters
[in,out] combineQureg a density matrix to be modified
[in] prob the probability of otherQureg in the modified combineQureg
[in] otherQureg a density matrix to be mixed into combineQureg
Exceptions
invalidQuESTInputError()
if either combineQureg or otherQureg are not density matrices
if the dimensions of combineQureg and otherQureg do not match
if prob is not in [0, 1]
Author
Tyson Jones
Definition at line 1012 of file QuEST.c.
{
     validateDensityMatrQureg(combineQureg, __func__);
     validateDensityMatrQureg(otherQureg, __func__);
     validateMatchingQuregDims(combineQureg, otherQureg, __func__);
     validateProb(otherProb, __func__);
     densmatr_mixDensityMatrix(combineQureg, otherProb, otherQureg);
 }
References densmatr_mixDensityMatrix(), validateDensityMatrQureg(), validateMatchingQuregDims(), and validateProb().
Referenced by TEST_CASE().
mixDephasing()
void mixDephasing (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
With probability prob, applies Pauli Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 1/2, which maximally mixes targetQubit.
See also
mixTwoQubitDephasing()
mixDamping()
mixDepolarising()
mixKrausMap()
mixPauli()
mixDensityMatrix()
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if targetQubit is outside [0, qureg.numQubitsRepresented)
if prob is not in [0, 1/2]
Author
Tyson Jones (GPU, doc)
Ania Brown (CPU, distributed)
Definition at line 1250 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDephaseProb(prob, __func__);
     densmatr_mixDephasing(qureg, targetQubit, 2*prob);
     qasm_recordComment(qureg,
         "Here, a phase (Z) error occured on qubit %d with probability %g", targetQubit, prob);
 }
References densmatr_mixDephasing(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitDephaseProb(), and validateTarget().
Referenced by TEST_CASE().
mixDepolarising()
void mixDepolarising (Qureg qureg, int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
This is equivalent to, with probability prob, uniformly randomly applying either Pauli X, Y, or Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 3/4, at which maximal mixing occurs. The produced state is equivalently expressed as
where is the maximally mixed state of the target qubit.
See also
mixTwoQubitDepolarising()
mixDephasing()
mixDamping()
mixKrausMap()
mixPauli()
mixDensityMatrix()
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if targetQubit is outside [0, qureg.numQubitsRepresented)
if prob is not in [0, 3/4]
Author
Tyson Jones (GPU, doc)
Ania Brown (CPU, distributed)
Definition at line 1272 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDepolProb(prob, __func__);
     densmatr_mixDepolarising(qureg, targetQubit, (4*prob)/3.0);
     qasm_recordComment(qureg,
         "Here, a homogeneous depolarising error (X, Y, or Z) occured on "
         "qubit %d with total probability %g", targetQubit, prob);
 }
References densmatr_mixDepolarising(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitDepolProb(), and validateTarget().
Referenced by TEST_CASE().
mixKrausMap()
void mixKrausMap (Qureg qureg, int target, ComplexMatrix2 * ops, int numOps)
Apply a general single-qubit Kraus map to a density matrix, as specified by at most four Kraus operators, (ops).
A Kraus map is also referred to as a "operator-sum representation" of a quantum channel, and enables the simulation of general single-qubit noise process, by effecting
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
Note that in distributed mode, this routine requires that each node contains at least 4 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-2) numTargs nodes.
See also
ComplexMatrix2
mixTwoQubitKrausMap()
mixMultiQubitKrausMap()
mixDephasing()
mixDepolarising()
mixDamping()
mixPauli()
mixDensityMatrix()
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] target the target qubit of the map
[in] ops an array of at most 4 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= 4.
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if target is outside of [0, qureg.numQubitsRepresented)
if numOps is outside [1, 4]
if ops do not create a completely positive, trace preserving map
if a node cannot fit 4 amplitudes in distributed mode
Author
Balint Koczor
Tyson Jones (refactored, doc)
Definition at line 1314 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, target, __func__);
     validateOneQubitKrausMap(qureg, ops, numOps, __func__);
     densmatr_mixKrausMap(qureg, target, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed Kraus map was effected on qubit %d", target);
 }
References densmatr_mixKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitKrausMap(), and validateTarget().
Referenced by TEST_CASE().
mixMultiQubitKrausMap()
void mixMultiQubitKrausMap (Qureg qureg, int * targets, int numTargets, ComplexMatrixN * ops, int numOps)
Apply a general N-qubit Kraus map to a density matrix, as specified by at most (2N)^2 Kraus operators.
This allows one to simulate a general noise process.
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
The first qubit in targets is treated as the least significant qubit in each op in ops.
Note that in distributed mode, this routine requires that each node contains at least (2N)^2 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-2)/N^2 nodes.
Note too that this routine internally creates a 'superoperator'; a complex matrix of dimensions 2^(2*numTargets) by 2^(2*numTargets). Therefore, invoking this function incurs, for numTargs={1,2,3,4,5, ...}, an additional memory overhead of (at double-precision) {0.25 KiB, 4 KiB, 64 KiB, 1 MiB, 16 MiB, ...} (respectively). At quad precision (usually 10 B per number, but possibly 16 B due to alignment), this costs at most double the amount of memory. For numTargets < 4, this superoperator will be created in the runtime stack. For numTargs >= 4, the superoperator will be allocated in the heap and therefore this routine may suffer an anomalous slowdown.
See also
createComplexMatrixN()
initComplexMatrixN()
mixKrausMap()
mixTwoQubitKrausMap()
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] targets a list of target qubit indices, the first of which is treated as least significant in each op in ops
[in] numTargets the length of targets
[in] ops an array of at most (2N)^2 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= (2N)^2.
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if any target in targets is outside of [0, qureg.numQubitsRepresented)
if any qubit in targets is repeated
if numOps is outside [1, (2 numTargets)^2]
if any ComplexMatrixN in ops does not have op.numQubits == numTargets
if ops do not create a completely positive, trace preserving map
if a node cannot fit (2N)^2 amplitudes in distributed mode
Author
Tyson Jones
Balint Koczor
Definition at line 1334 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateMultiTargets(qureg, targets, numTargets, __func__);
     validateMultiQubitKrausMap(qureg, numTargets, ops, numOps, __func__);
     densmatr_mixMultiQubitKrausMap(qureg, targets, numTargets, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed %d-qubit Kraus map was applied to undisclosed qubits", numTargets);
 }
References densmatr_mixMultiQubitKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateMultiQubitKrausMap(), and validateMultiTargets().
Referenced by TEST_CASE().
mixPauli()
void mixPauli (Qureg qureg, int targetQubit, qreal probX, qreal probY, qreal probZ)
Mixes a density matrix qureg to induce general single-qubit Pauli noise.
With probabilities probX, probY and probZ, applies Pauli X, Y, and Z respectively to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. Each of probX, probY and probZ cannot exceed the chance of no error: 1 - probX - probY - probZ
This function operates by first converting the given Pauli probabilities into a single-qubit Kraus map (four 2x2 operators).
See also
mixDephasing()
mixDepolarising()
mixDamping()
mixKrausMap()
mixDensityMatrix()
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit to decohere
[in] probX the probability of inducing an X error
[in] probY the probability of inducing an Y error
[in] probZ the probability of inducing an Z error
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if targetQubit is outside [0, qureg.numQubitsRepresented)
if any of probX, probY or probZ are not in [0, 1]
if any of p in {probX, probY or probZ} don't satisfy p <= (1 - probX - probY - probZ)
Author
Balint Koczor
Tyson Jones (refactored, doc)
Definition at line 1303 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, qubit, __func__);
     validateOneQubitPauliProbs(probX, probY, probZ, __func__);
     densmatr_mixPauli(qureg, qubit, probX, probY, probZ);
     qasm_recordComment(qureg,
         "Here, X, Y and Z errors occured on qubit %d with probabilities "
         "%g, %g and %g respectively", qubit, probX, probY, probZ);
 }
References densmatr_mixPauli(), qasm_recordComment(), validateDensityMatrQureg(), validateOneQubitPauliProbs(), and validateTarget().
Referenced by TEST_CASE().
mixTwoQubitDephasing()
void mixTwoQubitDephasing (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
With probability prob, applies Pauli Z to either or both qubits.
This transforms qureg = into the mixed state
where a = qubit1, b = qubit2. prob cannot exceed 3/4, at which maximal mixing occurs.
See also
mixDephasing()
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce dephasing noise
[in] qubit2 qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented)
if qubit1 = qubit2
if prob is not in [0, 3/4]
Author
Tyson Jones (GPU, doc)
Ania Brown (CPU, distributed)
Definition at line 1260 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDephaseProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_mixTwoQubitDephasing(qureg, qubit1, qubit2, (4*prob)/3.0);
     qasm_recordComment(qureg,
         "Here, a phase (Z) error occured on either or both of qubits "
         "%d and %d with total probability %g", qubit1, qubit2, prob);
 }
References densmatr_mixTwoQubitDephasing(), ensureIndsIncrease(), qasm_recordComment(), validateDensityMatrQureg(), validateTwoQubitDephaseProb(), and validateUniqueTargets().
Referenced by TEST_CASE().
mixTwoQubitDepolarising()
void mixTwoQubitDepolarising (Qureg qureg, int qubit1, int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
With probability prob, applies to qubit1 and qubit2 any operator of the set . Note this is the set of all two-qubit Pauli gates excluding .
This transforms qureg = into the mixed state
or verbosely
where a = qubit1, b = qubit2.
prob cannot exceed 15/16, at which maximal mixing occurs.
The produced state is equivalently expressed as
where is the maximally mixed state of the two target qubits.
See also
mixDepolarising()
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce depolarising noise
[in] qubit2 qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented)
if qubit1 = qubit2
if prob is not in [0, 15/16]
Author
Tyson Jones (GPU, doc)
Ania Brown (CPU, distributed)
Definition at line 1291 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDepolProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_mixTwoQubitDepolarising(qureg, qubit1, qubit2, (16*prob)/15.0);
     qasm_recordComment(qureg,
         "Here, a homogeneous depolarising error occured on qubits %d and %d "
         "with total probability %g", qubit1, qubit2, prob);
 }
References densmatr_mixTwoQubitDepolarising(), ensureIndsIncrease(), qasm_recordComment(), validateDensityMatrQureg(), validateTwoQubitDepolProb(), and validateUniqueTargets().
Referenced by TEST_CASE().
mixTwoQubitKrausMap()
void mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 * ops, int numOps)
Apply a general two-qubit Kraus map to a density matrix, as specified by at most sixteen Kraus operators.
A Kraus map is also referred to as a "operator-sum representation" of a quantum channel. This allows one to simulate a general two-qubit noise process.
The Kraus map must be completely positive and trace preserving, which constrains each in ops by
where is the identity matrix.
targetQubit1 is treated as the least significant qubit in each op in ops.
Note that in distributed mode, this routine requires that each node contains at least 16 amplitudes. This means an q-qubit register can be distributed by at most 2^(q-4) numTargs nodes.
See also
ComplexMatrix4
mixMultiQubitKrausMap()
mixKrausMap()
Parameters
[in,out] qureg the density matrix to which to apply the map
[in] target1 the least significant target qubit in ops
[in] target2 the most significant target qubit in ops
[in] ops an array of at most 16 Kraus operators
[in] numOps the number of operators in ops which must be >0 and <= 16.
Exceptions
invalidQuESTInputError()
if qureg is not a density matrix
if either target1 or target2 is outside of [0, qureg.numQubitsRepresented)
if target1 = target2
if numOps is outside [1, 16]
if ops do not create a completely positive, trace preserving map
if a node cannot fit 16 amplitudes in distributed mode
Author
Balint Koczor
Tyson Jones (refactored, doc)
Definition at line 1324 of file QuEST.c.
{
     validateDensityMatrQureg(qureg, __func__);
     validateMultiTargets(qureg, (int[]) {target1,target2}, 2, __func__);
     validateTwoQubitKrausMap(qureg, ops, numOps, __func__);
     densmatr_mixTwoQubitKrausMap(qureg, target1, target2, ops, numOps);
     qasm_recordComment(qureg,
         "Here, an undisclosed two-qubit Kraus map was effected on qubits %d and %d", target1, target2);
 }
References densmatr_mixTwoQubitKrausMap(), qasm_recordComment(), validateDensityMatrQureg(), validateMultiTargets(), and validateTwoQubitKrausMap().
Referenced by TEST_CASE().