QuEST: Gates
Gates
Non-unitary but norm-preserving gates, such as measurements.
Functions
qreal collapseToOutcome (Qureg qureg, int measureQubit, int outcome)
Updates qureg to be consistent with measuring measureQubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Detailed Description
Non-unitary but norm-preserving gates, such as measurements.
Function Documentation
collapseToOutcome()
qreal collapseToOutcome (Qureg qureg, int measureQubit, int outcome)
Updates qureg to be consistent with measuring measureQubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a renormalising projection, or a measurement with a forced outcome. This is an irreversible change to the state, whereby computational states inconsistant with the outcome are given zero amplitude and the qureg is renormalised. The given outcome must not have a near zero probability, else it cannot be collapsed into.
Note that the collapse probably used for renormalisation is calculated for outcome = 0, and assumed 1 minus this probability if outcome = 1. Hence this routine will not correctly project un-normalised quregs onto outcome = 1.
To avoid renormalisation after projection, or force projection into non-physical states with very small probability, use applyProjector().
See also
measure()
measureWithStats()
applyProjector()
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns
probability of the (forced) measurement outcome
Exceptions
invalidQuESTInputError()
if measureQubit is outside [0, qureg.numQubitsRepresented)
if outcome is not in {0, 1}
if the probability of outcome is zero (within machine epsilon)
Author
Ania Brown (state-vector)
Tyson Jones (density matrix)
Definition at line 966 of file QuEST.c.
{
     validateTarget(qureg, measureQubit, __func__);
     validateOutcome(outcome, __func__);
     qreal outcomeProb;
     if (qureg.isDensityMatrix) {
         outcomeProb = densmatr_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     } else {
         outcomeProb = statevec_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     }
     qasm_recordMeasurement(qureg, measureQubit);
     return outcomeProb;
 }
References densmatr_calcProbOfOutcome(), densmatr_collapseToKnownProbOutcome(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_calcProbOfOutcome(), statevec_collapseToKnownProbOutcome(), validateMeasurementProb(), validateOutcome(), and validateTarget().
Referenced by TEST_CASE().
measure()
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
The random outcome generator is seeded by seedQuESTDefault() within createQuESTEnv(), unless later overridden by seedQuEST().
See also
measureWithStats()
collapseToOutcome()
seedQuEST()
seedQuESTDefault()
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
Returns
the measurement outcome, 0 or 1
Exceptions
invalidQuESTInputError()
if measureQubit is outside [0, qureg.numQubitsRepresented)
Author
Ania Brown (state-vector)
Tyson Jones (density matrix)
Definition at line 998 of file QuEST.c.
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     qreal discardedProb;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, &discardedProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, &discardedProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_measureWithStats(), and validateTarget().
Referenced by TEST_CASE().
measureWithStats()
int measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
The random outcome generator is seeded by seedQuESTDefault() within createQuESTEnv(), unless later overridden by seedQuEST().
See also
measure()
collapseToOutcome()
seedQuESTDefault()
seedQuEST()
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[out] outcomeProb a pointer to a qreal which is set to the probability of the occurred outcome
Returns
the measurement outcome, 0 or 1
Exceptions
invalidQuESTInputError()
if measureQubit is outside [0, qureg.numQubitsRepresented)
Author
Ania Brown (state-vector)
Tyson Jones (density matrix)
Definition at line 985 of file QuEST.c.
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, outcomeProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, outcomeProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), statevec_measureWithStats(), and validateTarget().
Referenced by TEST_CASE().