QuEST: mt19937ar.h File Reference
mt19937ar.h File Reference
Functions
double genrand_real1 (void)
double genrand_real2 (void)
double genrand_real3 (void)
double genrand_res53 (void)
void init_by_array (unsigned long init_key[], int key_length)
void init_genrand (unsigned long s)
Function Documentation
genrand_real1()
double genrand_real1 (void)
Definition at line 150 of file mt19937ar.c.
 {
     return genrand_int32()*(1.0/4294967295.0);
     /* divided by 2^32-1 */
 }
References genrand_int32().
Referenced by generateMeasurementOutcome().
genrand_real2()
double genrand_real2 (void)
Definition at line 157 of file mt19937ar.c.
 {
     return genrand_int32()*(1.0/4294967296.0);
     /* divided by 2^32 */
 }
References genrand_int32().
genrand_real3()
double genrand_real3 (void)
Definition at line 164 of file mt19937ar.c.
 {
     return (((double)genrand_int32()) + 0.5)*(1.0/4294967296.0);
     /* divided by 2^32 */
 }
References genrand_int32().
genrand_res53()
double genrand_res53 (void)
Definition at line 171 of file mt19937ar.c.
 {
     unsigned long a=genrand_int32()>>5, b=genrand_int32()>>6;
     return(a*67108864.0+b)*(1.0/9007199254740992.0);
 }
References genrand_int32().
init_by_array()
void init_by_array (unsigned long init_key[], int key_length)
Definition at line 80 of file mt19937ar.c.
 {
     int i, j, k;
     init_genrand(19650218UL);
     i=1; j=0;
     k = (N>key_length ? N : key_length);
     for (; k; k--) {
         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1664525UL))
           + init_key[j] + j; /* non linear */
         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
         i++; j++;
         if (i>=N) { mt[0] = mt[N-1]; i=1; }
         if (j>=key_length) j=0;
     }
     for (k=N-1; k; k--) {
         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1566083941UL))
           - i; /* non linear */
         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
         i++;
         if (i>=N) { mt[0] = mt[N-1]; i=1; }
     }
     mt[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */
 }
References init_genrand(), mt, and N.
Referenced by seedQuEST().
init_genrand()
void init_genrand (unsigned long s)
Definition at line 61 of file mt19937ar.c.
 {
     mt[0]= s & 0xffffffffUL;
     for (mti=1; mti<N; mti++) {
         mt[mti] =
             (1812433253UL * (mt[mti-1] ^ (mt[mti-1] >> 30)) + mti);
         /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
         /* In the previous versions, MSBs of the seed affect   */
         /* only MSBs of the array mt[].                        */
         /* 2002/01/09 modified by Makoto Matsumoto             */
         mt[mti] &= 0xffffffffUL;
         /* for >32 bit machines */
     }
 }
References mt, mti, and N.
Referenced by genrand_int32(), and init_by_array().