QuEST: mt19937ar.c File Reference
mt19937ar.c File Reference
#include <stdio.h>
Macros
#define LOWER_MASK 0x7fffffffUL /* least significant r bits */
#define M 397
#define MATRIX_A 0x9908b0dfUL /* constant vector a */
#define N 624
#define UPPER_MASK 0x80000000UL /* most significant w-r bits */
Functions
long genrand_int31 (void)
unsigned long genrand_int32 (void)
double genrand_real1 (void)
double genrand_real2 (void)
double genrand_real3 (void)
double genrand_res53 (void)
void init_by_array (unsigned long init_key[], int key_length)
void init_genrand (unsigned long s)
Variables
static unsigned long mt [N]
static int mti =N+1
Macro Definition Documentation
LOWER_MASK
#define LOWER_MASK 0x7fffffffUL /* least significant r bits */
Definition at line 51 of file mt19937ar.c.
M
#define M 397
Definition at line 48 of file mt19937ar.c.
MATRIX_A
#define MATRIX_A 0x9908b0dfUL /* constant vector a */
Definition at line 49 of file mt19937ar.c.
N
#define N 624
Definition at line 47 of file mt19937ar.c.
UPPER_MASK
#define UPPER_MASK 0x80000000UL /* most significant w-r bits */
Definition at line 50 of file mt19937ar.c.
Function Documentation
genrand_int31()
long genrand_int31 (void)
Definition at line 144 of file mt19937ar.c.
 {
     return (long)(genrand_int32()>>1);
 }
References genrand_int32().
genrand_int32()
unsigned long genrand_int32 (void)
Definition at line 106 of file mt19937ar.c.
 {
     unsigned long y;
     static unsigned long mag01[2]={0x0UL, MATRIX_A};
     /* mag01[x] = x * MATRIX_A  for x=0,1 */
     if (mti >= N) { /* generate N words at one time */
         int kk;
         if (mti == N+1)   /* if init_genrand() has not been called, */
             init_genrand(5489UL); /* a default initial seed is used */
         for (kk=0;kk<N-M;kk++) {
             y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
             mt[kk] = mt[kk+M] ^ (y >> 1) ^ mag01[y & 0x1UL];
         }
         for (;kk<N-1;kk++) {
             y = (mt[kk]&UPPER_MASK)|(mt[kk+1]&LOWER_MASK);
             mt[kk] = mt[kk+(M-N)] ^ (y >> 1) ^ mag01[y & 0x1UL];
         }
         y = (mt[N-1]&UPPER_MASK)|(mt[0]&LOWER_MASK);
         mt[N-1] = mt[M-1] ^ (y >> 1) ^ mag01[y & 0x1UL];
         mti = 0;
     }
     y = mt[mti++];
     /* Tempering */
     y ^= (y >> 11);
     y ^= (y << 7) & 0x9d2c5680UL;
     y ^= (y << 15) & 0xefc60000UL;
     y ^= (y >> 18);
     return y;
 }
References init_genrand(), LOWER_MASK, M, MATRIX_A, mt, mti, N, and UPPER_MASK.
Referenced by genrand_int31(), genrand_real1(), genrand_real2(), genrand_real3(), and genrand_res53().
genrand_real1()
double genrand_real1 (void)
Definition at line 150 of file mt19937ar.c.
 {
     return genrand_int32()*(1.0/4294967295.0);
     /* divided by 2^32-1 */
 }
References genrand_int32().
Referenced by generateMeasurementOutcome().
genrand_real2()
double genrand_real2 (void)
Definition at line 157 of file mt19937ar.c.
 {
     return genrand_int32()*(1.0/4294967296.0);
     /* divided by 2^32 */
 }
References genrand_int32().
genrand_real3()
double genrand_real3 (void)
Definition at line 164 of file mt19937ar.c.
 {
     return (((double)genrand_int32()) + 0.5)*(1.0/4294967296.0);
     /* divided by 2^32 */
 }
References genrand_int32().
genrand_res53()
double genrand_res53 (void)
Definition at line 171 of file mt19937ar.c.
 {
     unsigned long a=genrand_int32()>>5, b=genrand_int32()>>6;
     return(a*67108864.0+b)*(1.0/9007199254740992.0);
 }
References genrand_int32().
init_by_array()
void init_by_array (unsigned long init_key[], int key_length)
Definition at line 80 of file mt19937ar.c.
 {
     int i, j, k;
     init_genrand(19650218UL);
     i=1; j=0;
     k = (N>key_length ? N : key_length);
     for (; k; k--) {
         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1664525UL))
           + init_key[j] + j; /* non linear */
         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
         i++; j++;
         if (i>=N) { mt[0] = mt[N-1]; i=1; }
         if (j>=key_length) j=0;
     }
     for (k=N-1; k; k--) {
         mt[i] = (mt[i] ^ ((mt[i-1] ^ (mt[i-1] >> 30)) * 1566083941UL))
           - i; /* non linear */
         mt[i] &= 0xffffffffUL; /* for WORDSIZE > 32 machines */
         i++;
         if (i>=N) { mt[0] = mt[N-1]; i=1; }
     }
     mt[0] = 0x80000000UL; /* MSB is 1; assuring non-zero initial array */
 }
References init_genrand(), mt, and N.
Referenced by seedQuEST().
init_genrand()
void init_genrand (unsigned long s)
Definition at line 61 of file mt19937ar.c.
 {
     mt[0]= s & 0xffffffffUL;
     for (mti=1; mti<N; mti++) {
         mt[mti] =
             (1812433253UL * (mt[mti-1] ^ (mt[mti-1] >> 30)) + mti);
         /* See Knuth TAOCP Vol2. 3rd Ed. P.106 for multiplier. */
         /* In the previous versions, MSBs of the seed affect   */
         /* only MSBs of the array mt[].                        */
         /* 2002/01/09 modified by Makoto Matsumoto             */
         mt[mti] &= 0xffffffffUL;
         /* for >32 bit machines */
     }
 }
References mt, mti, and N.
Referenced by genrand_int32(), and init_by_array().
Variable Documentation
mt
unsigned long mt[N] static
Definition at line 57 of file mt19937ar.c.
Referenced by genrand_int32(), init_by_array(), and init_genrand().
mti
int mti =N+1 static
Definition at line 58 of file mt19937ar.c.
Referenced by genrand_int32(), and init_genrand().