Distributed QuEST: qubits_internal.h File Reference
qubits_internal.h File Reference
Internal functions used to implement the public facing API in qubits.h.
#include "precision.h"
Functions
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
int validateMatrixIsUnitary (ComplexMatrix2 u)
int validateAlphaBeta (Complex alpha, Complex beta)
int validateUnitVector (REAL ux, REAL uy, REAL uz)
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
void exitWithError (int errorCode, const char *func)
void QuESTAssert (int isValid, int errorCode, const char *func)
Variables
const char * errorCodes []
Detailed Description
Internal functions used to implement the public facing API in qubits.h.
Do not call these functions directly. In general, qubits_env_local.c and qubits_env_mpi.c will implement the public API by choosing the correct function or combination of functions to use from those included here.
Definition in file qubits_internal.h.
Function Documentation
REAL collapseToOutcomeDistributedRenorm (MultiQubit multiQubit, const int measureQubit, const REAL totalProbability)
Renormalise parts of the state vector where measureQubit=0 or 1, based on the total probability of that qubit being in state 0 or 1.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that the value 'outcome' has been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles the renormalisation.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being zero
Definition at line 1898 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // (good for shared memory parallelism)
        REAL renorm=1/sqrt(totalProbability);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        stateVecReal[thisTask] = stateVecReal[thisTask]*renorm;
                        stateVecImag[thisTask] = stateVecImag[thisTask]*renorm;
                }
        }
        return totalProbability;
}
void collapseToOutcomeDistributedSetZero (MultiQubit multiQubit, const int measureQubit)
Set all amplitudes in one chunk to 0.
Measure in Zero performs an irreversible change to the state vector: it updates the vector according to the event that a zero have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1. In the distributed version, one block (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) is spread over multiple chunks, meaning that each chunks performs only renormalisation or only setting amplitudes to 0. This function handles setting amplitudes to 0.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Definition at line 1940 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // (good for shared memory parallelism)
        // ---------------------------------------------------------------- //
        //            find probability                                      //
        // ---------------------------------------------------------------- //
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        stateVecReal[thisTask] = 0;
                        stateVecImag[thisTask] = 0;
                }
        }
}
void collapseToOutcomeLocal (MultiQubit multiQubit, int measureQubit, REAL totalProbability, int outcome)
Update the state vector to be consistent with measuring measureQubit=0 if outcome=0 and measureQubit=1 if outcome=1.
Performs an irreversible change to the state vector: it updates the vector according to the event that an outcome have been measured on the qubit indicated by measureQubit (where this label starts from 0, of course). It achieves this by setting all inconsistent amplitudes to 0 and then renormalising based on the total probability of measuring measureQubit=0 or 1 according to the value of outcome. In the local version, one or more blocks (with measureQubit=0 in the first half of the block and measureQubit=1 in the second half of the block) fit entirely into one chunk.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
[in] totalProbability probability of qubit measureQubit being either zero or one
[in] outcome to measure the probability of and set the state to -- either zero or one
Definition at line 1816 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by collapseToOutcome(), and measureWithStats().
{
        // ----- sizes
        long long int sizeBlock,                                           // size of blocks
        sizeHalfBlock;                                       // size of blocks halved
        // ----- indices
        long long int thisBlock,                                           // current block
             index;                                               // current index for first half block
        // ----- measured probability
        REAL   renorm;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        // (good for shared memory parallelism)
        long long int numTasks=multiQubit.numAmps>>1;
        // ---------------------------------------------------------------- //
        //            dimensions                                            //
        // ---------------------------------------------------------------- //
        sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
        // and then the number to skip
        sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
        renorm=1/sqrt(totalProbability);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default (none) \
        shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag,renorm,outcome) \
        private   (thisTask,thisBlock,index)
# endif
        {
                if (outcome==0){
                        // measure qubit is 0
# ifdef _OPENMP
                        # pragma omp for schedule  (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock = thisTask / sizeHalfBlock;
                                index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                stateVecReal[index]=stateVecReal[index]*renorm;
                                stateVecImag[index]=stateVecImag[index]*renorm;
                                stateVecReal[index+sizeHalfBlock]=0;
                                stateVecImag[index+sizeHalfBlock]=0;
                        }
                } else {
                        // measure qubit is 1
# ifdef _OPENMP
                        # pragma omp for schedule  (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock = thisTask / sizeHalfBlock;
                                index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                stateVecReal[index]=0;
                                stateVecImag[index]=0;
                                stateVecReal[index+sizeHalfBlock]=stateVecReal[index+sizeHalfBlock]*renorm;
                                stateVecImag[index+sizeHalfBlock]=stateVecImag[index+sizeHalfBlock]*renorm;
                        }
                }
        }
}
void compactUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta, and a subset of the state vector with upper and lower block values stored seperately.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 573 of file qubits.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by compactUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                        stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
                        stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
                }
        }
}
void compactUnitaryLocal (MultiQubit multiQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 444 of file qubits.c.
References Complex::imag, ComplexArray::imag, MultiQubit::numAmps, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by compactUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL alphaImag=alpha.imag, alphaReal=alpha.real;
        REAL betaImag=beta.imag, betaReal=beta.real;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        // store current state vector values in temp variables
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                        stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                                - betaReal*stateRealLo - betaImag*stateImagLo;
                        stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                                - betaReal*stateImagLo + betaImag*stateRealLo;
                        // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
                        stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                                + alphaReal*stateRealLo + alphaImag*stateImagLo;
                        stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                                + alphaReal*stateImagLo - alphaImag*stateRealLo;
                }
        }
}
void controlledCompactUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 883 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by controlledCompactUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                                // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp + rot2Real*stateRealLo + rot2Imag*stateImagLo;
                                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp + rot2Real*stateImagLo - rot2Imag*stateRealLo;
                        }
                }
        }
}
void controlledCompactUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 674 of file qubits.c.
References MultiQubit::chunkId, extractBit(), Complex::imag, ComplexArray::imag, MultiQubit::numAmps, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledCompactUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL alphaImag=alpha.imag, alphaReal=alpha.real;
        REAL betaImag=beta.imag, betaReal=beta.real;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, alphaReal,alphaImag, betaReal,betaImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
                                stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
                                        - betaReal*stateRealLo - betaImag*stateImagLo;
                                stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
                                        - betaReal*stateImagLo + betaImag*stateRealLo;
                                // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
                                stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
                                        + alphaReal*stateRealLo + alphaImag*stateImagLo;
                                stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
                                        + alphaReal*stateImagLo - alphaImag*stateRealLo;
                        }
                }
        }
}
void controlledNotDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk. Only perform the rotation for elements where controlQubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1212 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by controlledNot().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
        private  (thisTask,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
                                stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
                        }
                }
        }
}
void controlledNotLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit)
Definition at line 1147 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledNot().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit(controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateVecReal[indexUp] = stateVecReal[indexLo];
                                stateVecImag[indexUp] = stateVecImag[indexLo];
                                stateVecReal[indexLo] = stateRealUp;
                                stateVecImag[indexLo] = stateImagUp;
                        }
                }
        }
}
void controlledUnitaryDistributed (MultiQubit multiQubit, const int controlQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Rotate a single qubit in the state vector of probability amplitudes, given two complex numbers alpha and beta and a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where the control qubit is one.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 946 of file qubits.c.
References MultiQubit::chunkId, extractBit(), ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by controlledUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        controlBit = extractBit (controlQubit, thisTask+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                    + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                    + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                        }
                }
        }
}
void controlledUnitaryLocal (MultiQubit multiQubit, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 804 of file qubits.c.
References MultiQubit::chunkId, extractBit(), Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by controlledUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        int controlBit;
    // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo,controlBit)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        controlBit = extractBit (controlQubit, indexUp+chunkId*chunkSize);
                        if (controlBit){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                                stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                        + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                                stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                        + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                                // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                                stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                        + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                                stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                        + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                        }
                }
        }
}
void exitWithError (int errorCode, const char * func)
Definition at line 238 of file qubits_env_local.c.
References errorCodes.
Referenced by QuESTAssert().
{
    printf("!!!\n");
    printf("QuEST Error in function %s: %s\n", func, errorCodes[errorCode]);
    printf("!!!\n");
    printf("exiting..\n");
    exit(errorCode);
}
REAL findProbabilityOfZeroDistributed (MultiQubit multiQubit, const int measureQubit)
Measure the probability of a specified qubit being in the zero state across all amplitudes held in this chunk.
Size of regions to skip is a multiple of chunkSize.
Parameters:
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns:
probability of qubit measureQubit being zero
Definition at line 1669 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
{
        // ----- measured probability
        REAL   totalProbability;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps;
        // ---------------------------------------------------------------- //
        //            find probability                                      //
        // ---------------------------------------------------------------- //
        // initialise returned value
        totalProbability = 0.0;
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,stateVecReal,stateVecImag) \
        private   (thisTask) \
        reduction ( +:totalProbability )
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // summation -- simple implementation
                        totalProbability += stateVecReal[thisTask]*stateVecReal[thisTask]
                                + stateVecImag[thisTask]*stateVecImag[thisTask];
                        /*
                        // summation -- kahan correction
                        y = stateVecReal[thisTask]*stateVecReal[thisTask]
                        + stateVecImag[thisTask]*stateVecImag[thisTask] - c;
                        t = totalProbability + y;
                        c = (t - totalProbability) - y;
                        totalProbability = t;
                        */
                }
        }
        return totalProbability;
}
REAL findProbabilityOfZeroLocal (MultiQubit multiQubit, const int measureQubit)
Measure the total probability of a specified qubit being in the zero state across all amplitudes in this chunk.
Size of regions to skip is less than the size of one chunk.
Parameters:
[in] multiQubit object representing the set of qubits
[in] measureQubit qubit to measure
Returns:
probability of qubit measureQubit being zero
Definition at line 1597 of file qubits.c.
References DEBUG, ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by findProbabilityOfOutcome().
{
        // ----- sizes
        long long int sizeBlock,                                           // size of blocks
        sizeHalfBlock;                                       // size of blocks halved
        // ----- indices
        long long int thisBlock,                                           // current block
             index;                                               // current index for first half block
        // ----- measured probability
        REAL   totalProbability;                                    // probability (returned) value
        // ----- temp variables
        long long int thisTask;                                   // task based approach for expose loop with small granularity
        long long int numTasks=multiQubit.numAmps>>1;
        // ---------------------------------------------------------------- //
        //            dimensions                                            //
        // ---------------------------------------------------------------- //
        sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
        // and then the number to skip
        sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
        // initialise returned value
        totalProbability = 0.0;
        // initialise correction for kahan summation
        if (DEBUG) printf("sizeHalfBlock=%Ld sizeBlock=%Ld numTasks=%Ld\n",sizeHalfBlock,sizeBlock,numTasks);
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        shared    (numTasks,sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private   (thisTask,thisBlock,index) \
        reduction ( +:totalProbability )
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule  (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock = thisTask / sizeHalfBlock;
                        index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        if (index<0){ printf("ABORTING as index=%Ld with thisBlock = %Ld  thisTask=%Ld \n", index,thisBlock,thisTask); exit(1);}
                        // summation -- simple implementation
                        totalProbability += stateVecReal[index]*stateVecReal[index]
                                + stateVecImag[index]*stateVecImag[index];
                        /*
                        // summation -- kahan correction
                        y = stateVecReal[index]*stateVecReal[index]
                        + stateVecImag[index]*stateVecImag[index] - c;
                        t = totalProbability + y;
                        c = (t - totalProbability) - y;
                        totalProbability = t;
                        */
                }
        }
        return totalProbability;
}
void hadamardDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{1,1},{1,-1}}/sqrt2.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1400 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by hadamard().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        int sign;
        if (updateUpper) sign=1;
        else sign=-1;
        REAL recRoot2 = 1.0/sqrt(2);
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        recRoot2, sign) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        stateVecRealOut[thisTask] = recRoot2*(stateRealUp + sign*stateRealLo);
                        stateVecImagOut[thisTask] = recRoot2*(stateImagUp + sign*stateImagLo);
                }
        }
}
void hadamardLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1339 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by hadamard().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, recRoot2) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        stateVecReal[indexUp] = recRoot2*(stateRealUp + stateRealLo);
                        stateVecImag[indexUp] = recRoot2*(stateImagUp + stateImagLo);
                        stateVecReal[indexLo] = recRoot2*(stateRealUp - stateRealLo);
                        stateVecImag[indexLo] = recRoot2*(stateImagUp - stateImagLo);
                }
        }
}
void multiControlledUnitaryDistributed (MultiQubit multiQubit, const int targetQubit, long long int mask, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit in the state vector of probability amplitudes, given a subset of the state vector with upper and lower block values stored seperately.
Only perform the rotation where all the control qubits are 1.
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] controlQubit qubit to determine whether or not to perform a rotation
[in] rot1 rotation angle
[in] rot2 rotation angle
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1010 of file qubits.c.
References MultiQubit::chunkId, ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by multiControlledUnitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real,rot1Imag, rot2Real,rot2Imag, mask) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        if (mask == (mask & (thisTask+chunkId*chunkSize)) ){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecRealUp[thisTask];
                                stateImagUp = stateVecImagUp[thisTask];
                                stateRealLo = stateVecRealLo[thisTask];
                                stateImagLo = stateVecImagLo[thisTask];
                stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                    + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                    + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                        }
                }
        }
}
void multiControlledUnitaryLocal (MultiQubit multiQubit, const int targetQubit, long long int mask, ComplexMatrix2 u)
Definition at line 741 of file qubits.c.
References MultiQubit::chunkId, Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by multiControlledUnitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        const long long int chunkSize=multiQubit.numAmps;
        const long long int chunkId=multiQubit.chunkId;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u, mask) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        if (mask == (mask & (indexUp+chunkId*chunkSize)) ){
                                // store current state vector values in temp variables
                                stateRealUp = stateVecReal[indexUp];
                                stateImagUp = stateVecImag[indexUp];
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                                stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                        + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                                stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                        + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                                // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                                stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                        + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                                stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                        + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                        }
                }
        }
}
void phaseGate (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 169 of file qubits_env_local.c.
References MultiQubit::chunkId, chunkIsUpper(), halfMatrixBlockFitsInChunk(), MultiQubit::numAmps, MultiQubit::numQubits, phaseGateDistributed(), phaseGateLocal(), and QuESTAssert().
Referenced by sGate(), sigmaZ(), and tGate().
{
    QuESTAssert(targetQubit >= 0 && targetQubit < multiQubit.numQubits, 1, __func__);
        phaseGateLocal(multiQubit, targetQubit, type);
}
void phaseGateDistributed (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
Definition at line 1522 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
{
        REAL stateRealLo,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecReal,stateVecImag, recRoot2, type) \
        private  (thisTask,stateRealLo,stateImagLo)
# endif
        {
                if (type==SIGMA_Z){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateVecReal[thisTask] = -stateVecReal[thisTask];
                                stateVecImag[thisTask] = -stateVecImag[thisTask];
                        }
                } else if (type==S_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateRealLo = stateVecReal[thisTask];
                                stateImagLo = stateVecImag[thisTask];
                                stateVecReal[thisTask] = -stateImagLo;
                                stateVecImag[thisTask] = stateRealLo;
                        }
                } else if (type==T_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                stateRealLo = stateVecReal[thisTask];
                                stateImagLo = stateVecImag[thisTask];
                                stateVecReal[thisTask] = recRoot2 * (stateRealLo - stateImagLo);
                                stateVecImag[thisTask] = recRoot2 * (stateRealLo + stateImagLo);
                        }
                } else printf("Type %d is an invalid phase gate\n", type);
        }
}
void phaseGateLocal (MultiQubit multiQubit, const int targetQubit, enum phaseGateType type)
fix -- can i rewrite this to not use mod?
fix -- can i rewrite this to not use mod?
fix -- can i rewrite this to not use mod?
Definition at line 1446 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, S_GATE, SIGMA_Z, MultiQubit::stateVec, and T_GATE.
Referenced by phaseGate().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealLo,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
        REAL recRoot2 = 1.0/sqrt(2);
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock,stateVecReal,stateVecImag,recRoot2,type) \
        private  (thisTask,thisBlock,indexUp,indexLo,stateRealLo,stateImagLo)
# endif
        {
                if (type==SIGMA_Z){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateVecReal[indexLo] = -stateVecReal[indexLo];
                                stateVecImag[indexLo] = -stateVecImag[indexLo];
                        }
                }
                else if (type==S_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                stateVecReal[indexLo] = -stateImagLo;
                                stateVecImag[indexLo] = stateRealLo;
                        }
                } else if (type==T_GATE){
# ifdef _OPENMP
                        # pragma omp for schedule (static)
# endif
                        for (thisTask=0; thisTask<numTasks; thisTask++) {
                                thisBlock   = thisTask / sizeHalfBlock;
                                indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                                indexLo     = indexUp + sizeHalfBlock;
                                stateRealLo = stateVecReal[indexLo];
                                stateImagLo = stateVecImag[indexLo];
                                stateVecReal[indexLo] = recRoot2 * (stateRealLo - stateImagLo);
                                stateVecImag[indexLo] = recRoot2 * (stateRealLo + stateImagLo);
                        }
                } else printf("Type %d is an invalid phase gate\n", type);
        }
}
void QuESTAssert (int isValid, int errorCode, const char * func)
Definition at line 246 of file qubits_env_local.c.
References exitWithError().
Referenced by collapseToOutcome(), compactUnitary(), controlledCompactUnitary(), controlledNot(), controlledPhaseGate(), controlledUnitary(), createMultiQubit(), findProbabilityOfOutcome(), hadamard(), measure(), measureWithStats(), multiControlledPhaseGate(), multiControlledUnitary(), phaseGate(), sigmaX(), sigmaY(), and unitary().
{
    if (!isValid) exitWithError(errorCode, func);
}
void sigmaXDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut)
Rotate a single qubit by {{0,1},{1,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1119 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by sigmaX().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut) \
        private  (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        stateVecRealOut[thisTask] = stateVecRealIn[thisTask];
                        stateVecImagOut[thisTask] = stateVecImagIn[thisTask];
                }
        }
}
void sigmaXLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1060 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaX().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateVecReal[indexUp] = stateVecReal[indexLo];
                        stateVecImag[indexUp] = stateVecImag[indexLo];
                        stateVecReal[indexLo] = stateRealUp;
                        stateVecImag[indexLo] = stateImagUp;
                }
        }
}
void sigmaYDistributed (MultiQubit multiQubit, const int targetQubit, ComplexArray stateVecIn, ComplexArray stateVecOut, int updateUpper)
Rotate a single qubit by {{0,-i},{i,0}.
Operate on a subset of the state vector with upper and lower block values stored seperately. This rotation is just swapping upper and lower values, and stateVecIn must already be the correct section for this chunk
Remarks:
Qubits are zero-based and the the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] stateVecIn probability amplitudes in lower or upper half of a block depending on chunkId
[in] updateUpper flag, 1: updating upper values, 0: updating lower values in block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 1306 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, and REAL.
Referenced by sigmaY().
{
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL *stateVecRealIn=stateVecIn.real, *stateVecImagIn=stateVecIn.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
        int realSign=1, imagSign=1;
        if (updateUpper) imagSign=-1;
        else realSign = -1;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealIn,stateVecImagIn,stateVecRealOut,stateVecImagOut,realSign,imagSign) \
        private  (thisTask)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        stateVecRealOut[thisTask] = realSign*stateVecImagIn[thisTask];
                        stateVecImagOut[thisTask] = imagSign*stateVecRealIn[thisTask];
                }
        }
}
void sigmaYLocal (MultiQubit multiQubit, const int targetQubit)
Definition at line 1247 of file qubits.c.
References ComplexArray::imag, MultiQubit::numAmps, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by sigmaY().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateImagUp;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateVecReal[indexUp] = stateVecImag[indexLo];
                        stateVecImag[indexUp] = -stateVecReal[indexLo];
                        stateVecReal[indexLo] = -stateImagUp;
                        stateVecImag[indexLo] = stateRealUp;
                }
        }
}
void unitaryDistributed (MultiQubit multiQubit, const int targetQubit, Complex rot1, Complex rot2, ComplexArray stateVecUp, ComplexArray stateVecLo, ComplexArray stateVecOut)
Apply a unitary operation to a single qubit given a subset of the state vector with upper and lower block values stored seperately.
Remarks:
Qubits are zero-based and the first qubit is the rightmost
Parameters:
[in,out] multiQubit object representing the set of qubits
[in] targetQubit qubit to rotate
[in] u unitary matrix to apply
[in] stateVecUp probability amplitudes in upper half of a block
[in] stateVecLo probability amplitudes in lower half of a block
[out] stateVecOut array section to update (will correspond to either the lower or upper half of a block)
Definition at line 629 of file qubits.c.
References ComplexArray::imag, Complex::imag, MultiQubit::numAmps, ComplexArray::real, Complex::real, and REAL.
Referenced by unitary().
{
        REAL   stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps;
        REAL rot1Real=rot1.real, rot1Imag=rot1.imag;
        REAL rot2Real=rot2.real, rot2Imag=rot2.imag;
        REAL *stateVecRealUp=stateVecUp.real, *stateVecImagUp=stateVecUp.imag;
        REAL *stateVecRealLo=stateVecLo.real, *stateVecImagLo=stateVecLo.imag;
        REAL *stateVecRealOut=stateVecOut.real, *stateVecImagOut=stateVecOut.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (stateVecRealUp,stateVecImagUp,stateVecRealLo,stateVecImagLo,stateVecRealOut,stateVecImagOut, \
                        rot1Real, rot1Imag, rot2Real, rot2Imag) \
        private  (thisTask,stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        // store current state vector values in temp variables
                        stateRealUp = stateVecRealUp[thisTask];
                        stateImagUp = stateVecImagUp[thisTask];
                        stateRealLo = stateVecRealLo[thisTask];
                        stateImagLo = stateVecImagLo[thisTask];
                        stateVecRealOut[thisTask] = rot1Real*stateRealUp - rot1Imag*stateImagUp
                                + rot2Real*stateRealLo - rot2Imag*stateImagLo;
                        stateVecImagOut[thisTask] = rot1Real*stateImagUp + rot1Imag*stateRealUp
                                + rot2Real*stateImagLo + rot2Imag*stateRealLo;
                }
        }
}
void unitaryLocal (MultiQubit multiQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 503 of file qubits.c.
References Complex::imag, ComplexArray::imag, MultiQubit::numAmps, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, ComplexArray::real, REAL, and MultiQubit::stateVec.
Referenced by unitary().
{
        long long int sizeBlock, sizeHalfBlock;
        long long int thisBlock, // current block
             indexUp,indexLo;    // current index and corresponding index in lower half block
        REAL stateRealUp,stateRealLo,stateImagUp,stateImagLo;
        long long int thisTask;
        const long long int numTasks=multiQubit.numAmps>>1;
        // set dimensions
        sizeHalfBlock = 1LL << targetQubit;
        sizeBlock     = 2LL * sizeHalfBlock;
        // Can't use multiQubit.stateVec as a private OMP var
        REAL *stateVecReal = multiQubit.stateVec.real;
        REAL *stateVecImag = multiQubit.stateVec.imag;
# ifdef _OPENMP
# pragma omp parallel \
        default  (none) \
        shared   (sizeBlock,sizeHalfBlock, stateVecReal,stateVecImag, u) \
        private  (thisTask,thisBlock ,indexUp,indexLo, stateRealUp,stateImagUp,stateRealLo,stateImagLo)
# endif
        {
# ifdef _OPENMP
                # pragma omp for schedule (static)
# endif
                for (thisTask=0; thisTask<numTasks; thisTask++) {
                        thisBlock   = thisTask / sizeHalfBlock;
                        indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
                        indexLo     = indexUp + sizeHalfBlock;
                        // store current state vector values in temp variables
                        stateRealUp = stateVecReal[indexUp];
                        stateImagUp = stateVecImag[indexUp];
                        stateRealLo = stateVecReal[indexLo];
                        stateImagLo = stateVecImag[indexLo];
                        // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
                        stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
                                + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
                        stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
                                + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
                        // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
                        stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
                                + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
                        stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
                                + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
                }
        }
}
int validateAlphaBeta (Complex alpha, Complex beta)
Definition at line 369 of file qubits.c.
References Complex::imag, Complex::real, and REAL_EPS.
Referenced by compactUnitary(), and controlledCompactUnitary().
{
        if ( fabs(alpha.real*alpha.real
                + alpha.imag*alpha.imag
                + beta.real*beta.real
                + beta.imag*beta.imag - 1) > REAL_EPS ) return 0;
        else return 1;
}
int validateMatrixIsUnitary (ComplexMatrix2 u)
Definition at line 344 of file qubits.c.
References Complex::imag, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, Complex::real, and REAL_EPS.
Referenced by controlledUnitary(), multiControlledUnitary(), and unitary().
{
        if ( fabs(u.r0c0.real*u.r0c0.real
                + u.r0c0.imag*u.r0c0.imag
                + u.r1c0.real*u.r1c0.real
                + u.r1c0.imag*u.r1c0.imag - 1) > REAL_EPS ) return 0;
    // check
        if ( fabs(u.r0c1.real*u.r0c1.real
                + u.r0c1.imag*u.r0c1.imag
                + u.r1c1.real*u.r1c1.real
                + u.r1c1.imag*u.r1c1.imag - 1) > REAL_EPS ) return 0;
        if ( fabs(u.r0c0.real*u.r0c1.real
                + u.r0c0.imag*u.r0c1.imag
                + u.r1c0.real*u.r1c1.real
                + u.r1c0.imag*u.r1c1.imag) > REAL_EPS ) return 0;
        if ( fabs(u.r0c1.real*u.r0c0.imag
                - u.r0c0.real*u.r0c1.imag
                + u.r1c1.real*u.r1c0.imag
                - u.r1c0.real*u.r1c1.imag) > REAL_EPS ) return 0;
        return 1;
}
int validateUnitVector (REAL ux, REAL uy, REAL uz)
Definition at line 377 of file qubits.c.
References REAL_EPS.
{
        if ( fabs(sqrt(ux*ux + uy*uy + uz*uz) - 1) > REAL_EPS ) return 0;
        else return 1;
}
Variable Documentation
const char* errorCodes[]
Definition at line 20 of file qubits.c.
Referenced by exitWithError().