Quantum Exact Simulation Toolkit: QuEST_gpu.cu File Reference
QuEST_gpu.cu File Reference
An implementation of the pure backend in .
#include "../QuEST.h"
#include "../QuEST_precision.h"
#include "../mt19937ar.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
Defines
#define DEBUG 0
#define REDUCE_SHARED_SIZE 512
Functions
__global__ void copySharedReduceBlock (qreal *arrayIn, qreal *reducedArray, int length)
void copyStateFromGPU (Qureg qureg)
void copyStateToGPU (Qureg qureg)
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
void densmatr_addDensityMatrix (Qureg combineQureg, qreal otherProb, Qureg otherQureg)
__global__ void densmatr_addDensityMatrixKernel (Qureg combineQureg, qreal otherProb, Qureg otherQureg, long long int numAmpsToVisit)
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
__global__ void densmatr_calcFidelityKernel (Qureg dens, Qureg vec, long long int dim, qreal *reducedArray)
computes one term of (vec^*T) dens * vec
qreal densmatr_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
qreal densmatr_calcPurity (Qureg qureg)
Computes the trace of the density matrix squared.
__global__ void densmatr_calcPurityKernel (qreal *vecReal, qreal *vecImag, long long int numAmpsToSum, qreal *reducedArray)
qreal densmatr_calcTotalProb (Qureg qureg)
void densmatr_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal outcomeProb)
This involves finding |...i.
__global__ void densmatr_collapseToKnownProbOutcomeKernel (qreal outcomeProb, qreal *vecReal, qreal *vecImag, long long int numBasesToVisit, long long int part1, long long int part2, long long int part3, long long int rowBit, long long int colBit, long long int desired, long long int undesired)
Maps thread ID to a |..0.
qreal densmatr_findProbabilityOfZero (Qureg qureg, const int measureQubit)
__global__ void densmatr_findProbabilityOfZeroKernel (Qureg qureg, const int measureQubit, qreal *reducedArray)
void densmatr_initClassicalState (Qureg qureg, long long int stateInd)
__global__ void densmatr_initClassicalStateKernel (long long int densityNumElems, qreal *densityReal, qreal *densityImag, long long int densityInd)
void densmatr_initPlusState (Qureg qureg)
__global__ void densmatr_initPlusStateKernel (long long int stateVecSize, qreal probFactor, qreal *stateVecReal, qreal *stateVecImag)
void densmatr_initPureState (Qureg targetQureg, Qureg copyQureg)
__global__ void densmatr_initPureStateKernel (long long int numPureAmps, qreal *targetVecReal, qreal *targetVecImag, qreal *copyVecReal, qreal *copyVecImag)
void densmatr_oneQubitDephase (Qureg qureg, const int targetQubit, qreal dephase)
__global__ void densmatr_oneQubitDephaseKernel (qreal fac, qreal *vecReal, qreal *vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int colBit, long long int rowBit)
Called once for every 4 amplitudes in density matrix Works by establishing the |..0.
void densmatr_oneQubitDepolarise (Qureg qureg, const int targetQubit, qreal depolLevel)
__global__ void densmatr_oneQubitDepolariseKernel (qreal depolLevel, qreal *vecReal, qreal *vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int bothBits)
Works like oneQubitDephase but modifies every other element, and elements are averaged in pairs.
void densmatr_twoQubitDephase (Qureg qureg, int qubit1, int qubit2, qreal dephase)
__global__ void densmatr_twoQubitDephaseKernel (qreal fac, qreal *vecReal, qreal *vecImag, long long int numBackgroundStates, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int part4, long long int part5, long long int colBit1, long long int rowBit1, long long int colBit2, long long int rowBit2)
Called 12 times for every 16 amplitudes in density matrix Each sums from the |..0..0.
void densmatr_twoQubitDepolarise (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
__global__ void densmatr_twoQubitDepolariseKernel (qreal depolLevel, qreal *vecReal, qreal *vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int part4, long long int part5, long long int rowCol1, long long int rowCol2)
Called once for every 16 amplitudes.
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
static __device__ int extractBit (int locationOfBitFromRight, long long int theEncodedNumber)
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
int getNumReductionLevels (long long int numValuesToReduce, int numReducedPerLevel)
int GPUExists (void)
__device__ __host__ unsigned int log2Int (unsigned int x)
__device__ void reduceBlock (qreal *arrayIn, qreal *reducedArray, int length)
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
Terrible code which unnecessarily individually computes and sums the real and imaginary components of the inner product, so as to not have to worry about keeping the sums separated during reduction.
__global__ void statevec_calcInnerProductKernel (int getRealComp, qreal *vecReal1, qreal *vecImag1, qreal *vecReal2, qreal *vecImag2, long long int numTermsToSum, qreal *reducedArray)
computes either a real or imag term in the inner product
qreal statevec_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
qreal statevec_calcTotalProb (Qureg qureg)
void statevec_cloneQureg (Qureg targetQureg, Qureg copyQureg)
works for both statevectors and density matrices
void statevec_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal outcomeProb)
__global__ void statevec_collapseToKnownProbOutcomeKernel (Qureg qureg, int measureQubit, int outcome, qreal totalProbability)
void statevec_compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
__global__ void statevec_compactUnitaryKernel (Qureg qureg, const int rotQubit, Complex alpha, Complex beta)
int statevec_compareStates (Qureg mq1, Qureg mq2, qreal precision)
void statevec_controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
__global__ void statevec_controlledCompactUnitaryKernel (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void statevec_controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
__global__ void statevec_controlledNotKernel (Qureg qureg, const int controlQubit, const int targetQubit)
void statevec_controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
void statevec_controlledPauliYConj (Qureg qureg, const int controlQubit, const int targetQubit)
__global__ void statevec_controlledPauliYKernel (Qureg qureg, const int controlQubit, const int targetQubit, const int conjFac)
void statevec_controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
__global__ void statevec_controlledPhaseFlipKernel (Qureg qureg, const int idQubit1, const int idQubit2)
void statevec_controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
__global__ void statevec_controlledPhaseShiftKernel (Qureg qureg, const int idQubit1, const int idQubit2, qreal cosAngle, qreal sinAngle)
void statevec_controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
__global__ void statevec_controlledUnitaryKernel (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
void statevec_createQureg (Qureg *qureg, int numQubits, QuESTEnv env)
void statevec_destroyQureg (Qureg qureg, QuESTEnv env)
qreal statevec_findProbabilityOfZero (Qureg qureg, const int measureQubit)
__global__ void statevec_findProbabilityOfZeroKernel (Qureg qureg, const int measureQubit, qreal *reducedArray)
qreal statevec_getImagAmp (Qureg qureg, long long int index)
qreal statevec_getRealAmp (Qureg qureg, long long int index)
void statevec_hadamard (Qureg qureg, const int targetQubit)
__global__ void statevec_hadamardKernel (Qureg qureg, const int targetQubit)
void statevec_initClassicalState (Qureg qureg, long long int stateInd)
__global__ void statevec_initClassicalStateKernel (long long int stateVecSize, qreal *stateVecReal, qreal *stateVecImag, long long int stateInd)
void statevec_initPlusState (Qureg qureg)
__global__ void statevec_initPlusStateKernel (long long int stateVecSize, qreal *stateVecReal, qreal *stateVecImag)
void statevec_initStateDebug (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
__global__ void statevec_initStateDebugKernel (long long int stateVecSize, qreal *stateVecReal, qreal *stateVecImag)
int statevec_initStateFromSingleFile (Qureg *qureg, char filename[200], QuESTEnv env)
void statevec_initStateOfSingleQubit (Qureg *qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
__global__ void statevec_initStateOfSingleQubitKernel (long long int stateVecSize, qreal *stateVecReal, qreal *stateVecImag, int qubitId, int outcome)
void statevec_initZeroState (Qureg qureg)
__global__ void statevec_initZeroStateKernel (long long int stateVecSize, qreal *stateVecReal, qreal *stateVecImag)
void statevec_multiControlledPhaseFlip (Qureg qureg, int *controlQubits, int numControlQubits)
__global__ void statevec_multiControlledPhaseFlipKernel (Qureg qureg, long long int mask)
void statevec_multiControlledPhaseShift (Qureg qureg, int *controlQubits, int numControlQubits, qreal angle)
__global__ void statevec_multiControlledPhaseShiftKernel (Qureg qureg, long long int mask, qreal cosAngle, qreal sinAngle)
void statevec_multiControlledUnitary (Qureg qureg, int *controlQubits, int numControlQubits, const int targetQubit, ComplexMatrix2 u)
__global__ void statevec_multiControlledUnitaryKernel (Qureg qureg, long long int mask, const int targetQubit, ComplexMatrix2 u)
void statevec_pauliX (Qureg qureg, const int targetQubit)
__global__ void statevec_pauliXKernel (Qureg qureg, const int targetQubit)
void statevec_pauliY (Qureg qureg, const int targetQubit)
void statevec_pauliYConj (Qureg qureg, const int targetQubit)
__global__ void statevec_pauliYKernel (Qureg qureg, const int targetQubit, const int conjFac)
void statevec_phaseShiftByTerm (Qureg qureg, const int targetQubit, Complex term)
__global__ void statevec_phaseShiftByTermKernel (Qureg qureg, const int targetQubit, qreal cosAngle, qreal sinAngle)
void statevec_reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void statevec_setAmps (Qureg qureg, long long int startInd, qreal *reals, qreal *imags, long long int numAmps)
void statevec_unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
__global__ void statevec_unitaryKernel (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
void swapDouble (qreal **a, qreal **b)
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode).
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
Detailed Description
An implementation of the pure backend in .
./QuEST_ops_pure.h for a GPU environment.
Definition in file QuEST_gpu.cu.
Define Documentation
#define DEBUG 0
Definition at line 16 of file QuEST_gpu.cu.
Referenced by copyStateFromGPU(), and copyStateToGPU().
#define REDUCE_SHARED_SIZE 512
Definition at line 15 of file QuEST_gpu.cu.
Referenced by densmatr_calcFidelity(), densmatr_calcPurity(), densmatr_findProbabilityOfZero(), statevec_calcInnerProduct(), statevec_createQureg(), and statevec_findProbabilityOfZero().
Function Documentation
__global__ void copySharedReduceBlock (qreal * arrayIn, qreal * reducedArray, int length)
Definition at line 1353 of file QuEST_gpu.cu.
References qreal, and reduceBlock().
Referenced by densmatr_calcFidelity(), densmatr_calcPurity(), densmatr_findProbabilityOfZero(), statevec_calcInnerProduct(), and statevec_findProbabilityOfZero().
{
    extern __shared__ qreal tempReductionArray[];
    int blockOffset = blockIdx.x*length;
    tempReductionArray[threadIdx.x*2] = arrayIn[blockOffset + threadIdx.x*2];
    tempReductionArray[threadIdx.x*2+1] = arrayIn[blockOffset + threadIdx.x*2+1];
    __syncthreads();
    reduceBlock(tempReductionArray, reducedArray, length);
}
void copyStateFromGPU (Qureg qureg)
Definition at line 291 of file QuEST_gpu.cu.
References DEBUG, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and Qureg::stateVec.
Referenced by densmatr_calcTotalProb(), statevec_calcTotalProb(), statevec_compareStates(), and statevec_reportStateToScreen().
{
    cudaDeviceSynchronize();
    if (DEBUG) printf("Copying data from GPU\n");
    cudaMemcpy(qureg.stateVec.real, qureg.deviceStateVec.real,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.real)), cudaMemcpyDeviceToHost);
    cudaMemcpy(qureg.stateVec.imag, qureg.deviceStateVec.imag,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.imag)), cudaMemcpyDeviceToHost);
    if (DEBUG) printf("Finished copying data from GPU\n");
}
void copyStateToGPU (Qureg qureg)
Definition at line 277 of file QuEST_gpu.cu.
References DEBUG, Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and Qureg::stateVec.
Referenced by statevec_initStateFromSingleFile().
{
    if (DEBUG) printf("Copying data to GPU\n");
    cudaMemcpy(qureg.deviceStateVec.real, qureg.stateVec.real,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.real)), cudaMemcpyHostToDevice);
    cudaMemcpy(qureg.deviceStateVec.real, qureg.stateVec.real,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.real)), cudaMemcpyHostToDevice);
    cudaMemcpy(qureg.deviceStateVec.imag, qureg.stateVec.imag,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.imag)), cudaMemcpyHostToDevice);
    cudaMemcpy(qureg.deviceStateVec.imag, qureg.stateVec.imag,
            qureg.numAmpsPerChunk*sizeof(*(qureg.deviceStateVec.imag)), cudaMemcpyHostToDevice);
    if (DEBUG) printf("Finished copying data to GPU\n");
}
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
This should be called only once, and the environment should be freed with destroyQuESTEnv at the end of the user's code. If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here.
Returns:
object representing the execution environment. A single instance is used for each program
Definition at line 233 of file QuEST_gpu.cu.
References GPUExists(), QuESTEnv::numRanks, QuESTEnv::rank, and seedQuESTDefault().
{
    // init MPI environment
    if (!GPUExists()){
        printf("Trying to run GPU code with no GPU available\n");
        exit(EXIT_FAILURE);
    }
    QuESTEnv env;
    env.rank=0;
    env.numRanks=1;
    seedQuESTDefault();
    return env;
}
void densmatr_addDensityMatrix (Qureg combineQureg, qreal otherProb, Qureg otherQureg)
Definition at line 1979 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by addDensityMatrix().
{
    long long int numAmpsToVisit = combineQureg.numAmpsPerChunk;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numAmpsToVisit / (qreal) threadsPerCUDABlock);
    densmatr_addDensityMatrixKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        combineQureg, otherProb, otherQureg, numAmpsToVisit
    );
}
__global__ void densmatr_addDensityMatrixKernel (Qureg combineQureg, qreal otherProb, Qureg otherQureg, long long int numAmpsToVisit)
Definition at line 1967 of file QuEST_gpu.cu.
References Qureg::deviceStateVec.
{
    long long int ampInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (ampInd >= numAmpsToVisit) return;
    combineQureg.deviceStateVec.real[ampInd] *= 1-otherProb;
    combineQureg.deviceStateVec.imag[ampInd] *= 1-otherProb;
    combineQureg.deviceStateVec.real[ampInd] += otherProb*otherQureg.deviceStateVec.real[ampInd];
    combineQureg.deviceStateVec.imag[ampInd] += otherProb*otherQureg.deviceStateVec.imag[ampInd];
}
qreal densmatr_calcFidelity (Qureg qureg, Qureg pureState)
Definition at line 1727 of file QuEST_gpu.cu.
References copySharedReduceBlock(), Qureg::firstLevelReduction, Qureg::numQubitsRepresented, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcFidelity().
{
    // we're summing the square of every term in the density matrix
    long long int densityDim = 1LL << qureg.numQubitsRepresented;
    long long int numValuesToReduce = densityDim;
    int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
    int maxReducedPerLevel = REDUCE_SHARED_SIZE;
    int firstTime = 1;
    while (numValuesToReduce > 1) {
        // need less than one CUDA-BLOCK to reduce
        if (numValuesToReduce < maxReducedPerLevel) {
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        }
        // otherwise use only full CUDA-BLOCKS
        else {
            valuesPerCUDABlock = maxReducedPerLevel; // constrained by shared memory
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        // dictates size of reduction array
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        // spawn threads to sum the probs in each block
        // store the reduction in the pureState array
        if (firstTime) {
             densmatr_calcFidelityKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                 qureg, pureState, densityDim, pureState.firstLevelReduction);
            firstTime = 0;
        // sum the block probs
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    pureState.firstLevelReduction,
                    pureState.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(pureState.firstLevelReduction), &(pureState.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    qreal fidelity;
    cudaMemcpy(&fidelity, pureState.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    return fidelity;
}
__global__ void densmatr_calcFidelityKernel (Qureg dens, Qureg vec, long long int dim, qreal * reducedArray)
computes one term of (vec^*T) dens * vec
Definition at line 1688 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, qreal, and reduceBlock().
{
    // figure out which density matrix row to consider
    long long int col;
    long long int row = blockIdx.x*blockDim.x + threadIdx.x;
    if (row >= dim) return;
    qreal* densReal = dens.deviceStateVec.real;
    qreal* densImag = dens.deviceStateVec.imag;
    qreal* vecReal  = vec.deviceStateVec.real;
    qreal* vecImag  = vec.deviceStateVec.imag;
    // compute the row-th element of the product dens*vec
    qreal prodReal = 0;
    qreal prodImag = 0;
    for (col=0LL; col < dim; col++) {
        qreal densElemReal = densReal[dim*col + row];
        qreal densElemImag = densImag[dim*col + row];
        prodReal += densElemReal*vecReal[col] - densElemImag*vecImag[col];
        prodImag += densElemReal*vecImag[col] + densElemImag*vecReal[col];
    }
    // multiply with row-th elem of (vec^*)
    qreal termReal = prodImag*vecImag[row] + prodReal*vecReal[row];
    // imag of every term should be zero, because each is a valid fidelity calc of an eigenstate
    //qreal termImag = prodImag*vecReal[row] - prodReal*vecImag[row];
    extern __shared__ qreal tempReductionArray[];
    tempReductionArray[threadIdx.x] = termReal;
    __syncthreads();
    // every second thread reduces
    if (threadIdx.x<blockDim.x/2)
        reduceBlock(tempReductionArray, reducedArray, blockDim.x);
}
qreal densmatr_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Definition at line 1560 of file QuEST_gpu.cu.
References densmatr_findProbabilityOfZero(), and qreal.
Referenced by calcProbOfOutcome(), collapseToOutcome(), and densmatr_measureWithStats().
{
    qreal outcomeProb = densmatr_findProbabilityOfZero(qureg, measureQubit);
    if (outcome==1)
        outcomeProb = 1.0 - outcomeProb;
    return outcomeProb;
}
qreal densmatr_calcPurity (Qureg qureg)
Computes the trace of the density matrix squared.
Definition at line 1797 of file QuEST_gpu.cu.
References copySharedReduceBlock(), Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::numAmpsPerChunk, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcPurity().
{
    // we're summing the square of every term in the density matrix
    long long int numValuesToReduce = qureg.numAmpsPerChunk;
    int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
    int maxReducedPerLevel = REDUCE_SHARED_SIZE;
    int firstTime = 1;
    while (numValuesToReduce > 1) {
        // need less than one CUDA-BLOCK to reduce
        if (numValuesToReduce < maxReducedPerLevel) {
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        }
        // otherwise use only full CUDA-BLOCKS
        else {
            valuesPerCUDABlock = maxReducedPerLevel; // constrained by shared memory
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        // dictates size of reduction array
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        // spawn threads to sum the probs in each block
        if (firstTime) {
             densmatr_calcPurityKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                 qureg.deviceStateVec.real, qureg.deviceStateVec.imag,
                 numValuesToReduce, qureg.firstLevelReduction);
            firstTime = 0;
        // sum the block probs
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    qureg.firstLevelReduction,
                    qureg.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(qureg.firstLevelReduction), &(qureg.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    qreal traceDensSquared;
    cudaMemcpy(&traceDensSquared, qureg.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    return traceDensSquared;
}
__global__ void densmatr_calcPurityKernel (qreal * vecReal, qreal * vecImag, long long int numAmpsToSum, qreal * reducedArray)
Definition at line 1778 of file QuEST_gpu.cu.
References qreal, and reduceBlock().
{
    // figure out which density matrix term this thread is assigned
    long long int index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index >= numAmpsToSum) return;
    qreal term = vecReal[index]*vecReal[index] + vecImag[index]*vecImag[index];
    // array of each thread's collected probability, to be summed
    extern __shared__ qreal tempReductionArray[];
    tempReductionArray[threadIdx.x] = term;
    __syncthreads();
    // every second thread reduces
    if (threadIdx.x<blockDim.x/2)
        reduceBlock(tempReductionArray, reducedArray, blockDim.x);
}
qreal densmatr_calcTotalProb (Qureg qureg)
Definition at line 1110 of file QuEST_gpu.cu.
References copyStateFromGPU(), Qureg::numQubitsRepresented, qreal, Qureg::stateVec, and y.
Referenced by calcTotalProb().
{
    // computes the trace using Kahan summation
    qreal pTotal=0;
    qreal y, t, c;
    c = 0;
    long long int numCols = 1LL << qureg.numQubitsRepresented;
    long long diagIndex;
    copyStateFromGPU(qureg);
    for (int col=0; col< numCols; col++) {
        diagIndex = col*(numCols + 1);
        y = qureg.stateVec.real[diagIndex] - c;
        t = pTotal + y;
        c = ( t - pTotal ) - y; // brackets are important
        pTotal = t;
    }
    return pTotal;
}
void densmatr_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal outcomeProb)
This involves finding |...i.
Renorms (/prob) every | * outcome * >< * outcome * | state, setting all others to zero.
..><...j...| states and killing those where i!=j
Definition at line 1938 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by collapseToOutcome(), and densmatr_measureWithStats().
{
        int rowQubit = measureQubit + qureg.numQubitsRepresented;
    int colBit = 1LL << measureQubit;
    int rowBit = 1LL << rowQubit;
    long long int numBasesToVisit = qureg.numAmpsPerChunk/4;
        long long int part1 = colBit -1;
        long long int part2 = (rowBit >> 1) - colBit;
        long long int part3 = numBasesToVisit - (rowBit >> 1);
    long long int desired, undesired;
    if (outcome == 0) {
        desired = 0;
        undesired = colBit | rowBit;
    } else {
        desired = colBit | rowBit;
        undesired = 0;
    }
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numBasesToVisit / (qreal) threadsPerCUDABlock);
    densmatr_collapseToKnownProbOutcomeKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        outcomeProb, qureg.deviceStateVec.real, qureg.deviceStateVec.imag, numBasesToVisit,
        part1, part2, part3, rowBit, colBit, desired, undesired);
}
__global__ void densmatr_collapseToKnownProbOutcomeKernel (qreal outcomeProb, qreal * vecReal, qreal * vecImag, long long int numBasesToVisit, long long int part1, long long int part2, long long int part3, long long int rowBit, long long int colBit, long long int desired, long long int undesired)
Maps thread ID to a |..0.
.><..0..| state and then locates |0><1|, |1><0| and |1><1|
Definition at line 1912 of file QuEST_gpu.cu.
{
    long long int scanInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (scanInd >= numBasesToVisit) return;
    long long int base = (scanInd&part1) + ((scanInd&part2)<<1) + ((scanInd&part3)<<2);
    // renormalise desired outcome
    vecReal[base + desired] /= outcomeProb;
    vecImag[base + desired] /= outcomeProb;
    // kill undesired outcome
    vecReal[base + undesired] = 0;
    vecImag[base + undesired] = 0;
    // kill |..0..><..1..| states
    vecReal[base + colBit] = 0;
    vecImag[base + colBit] = 0;
    vecReal[base + rowBit] = 0;
    vecImag[base + rowBit] = 0;
}
qreal densmatr_findProbabilityOfZero (Qureg qureg, const int measureQubit)
Definition at line 1466 of file QuEST_gpu.cu.
References copySharedReduceBlock(), Qureg::firstLevelReduction, Qureg::numQubitsRepresented, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by densmatr_calcProbOfOutcome().
{
    long long int densityDim = 1LL << qureg.numQubitsRepresented;
    long long int numValuesToReduce = densityDim >> 1;  // half of the diagonal has measureQubit=0
    int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
    int maxReducedPerLevel = REDUCE_SHARED_SIZE;
    int firstTime = 1;
    while (numValuesToReduce > 1) {
        // need less than one CUDA-BLOCK to reduce
        if (numValuesToReduce < maxReducedPerLevel) {
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        }
        // otherwise use only full CUDA-BLOCKS
        else {
            valuesPerCUDABlock = maxReducedPerLevel; // constrained by shared memory
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        // spawn threads to sum the probs in each block
        if (firstTime) {
            densmatr_findProbabilityOfZeroKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                qureg, measureQubit, qureg.firstLevelReduction);
            firstTime = 0;
        // sum the block probs
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    qureg.firstLevelReduction,
                    qureg.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(qureg.firstLevelReduction), &(qureg.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    qreal zeroProb;
    cudaMemcpy(&zeroProb, qureg.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    return zeroProb;
}
__global__ void densmatr_findProbabilityOfZeroKernel (Qureg qureg, const int measureQubit, qreal * reducedArray)
Definition at line 1362 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numQubitsRepresented, qreal, and reduceBlock().
  {
    // run by each thread
    // use of block here refers to contiguous amplitudes where measureQubit = 0,
    // (then =1) and NOT the CUDA block, which is the partitioning of CUDA threads
    long long int densityDim    = 1LL << qureg.numQubitsRepresented;
    long long int numTasks      = densityDim >> 1;
    long long int sizeHalfBlock = 1LL << (measureQubit);
    long long int sizeBlock     = 2LL * sizeHalfBlock;
    long long int thisBlock;    // which block this thread is processing
    long long int thisTask;     // which part of the block this thread is processing
    long long int basisIndex;   // index of this thread's computational basis state
    long long int densityIndex; // " " index of |basis><basis| in the flat density matrix
    // array of each thread's collected probability, to be summed
    extern __shared__ qreal tempReductionArray[];
    // figure out which density matrix prob that this thread is assigned
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock = thisTask / sizeHalfBlock;
    basisIndex = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    densityIndex = (densityDim + 1) * basisIndex;
    // record the probability in the CUDA-BLOCK-wide array
    qreal prob = qureg.deviceStateVec.real[densityIndex];   // im[densityIndex] assumed ~ 0
    tempReductionArray[threadIdx.x] = prob;
    // sum the probs collected by this CUDA-BLOCK's threads into a per-CUDA-BLOCK array
    __syncthreads();
    if (threadIdx.x<blockDim.x/2){
        reduceBlock(tempReductionArray, reducedArray, blockDim.x);
    }
}
void densmatr_initClassicalState (Qureg qureg, long long int stateInd)
Definition at line 138 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by initClassicalState().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    // index of the desired state in the flat density matrix
    long long int densityDim = 1LL << qureg.numQubitsRepresented;
    long long int densityInd = (densityDim + 1)*stateInd;
    // identical to pure version
    densmatr_initClassicalStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag, densityInd);
}
__global__ void densmatr_initClassicalStateKernel (long long int densityNumElems, qreal * densityReal, qreal * densityImag, long long int densityInd)
Definition at line 119 of file QuEST_gpu.cu.
{
    // initialise the state to all zeros
    long long int index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index >= densityNumElems) return;
    densityReal[index] = 0.0;
    densityImag[index] = 0.0;
    if (index==densityInd){
        // classical state has probability 1
        densityReal[densityInd] = 1.0;
        densityImag[densityInd] = 0.0;
    }
}
void densmatr_initPlusState (Qureg qureg)
Definition at line 106 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by initPlusState().
{
    qreal probFactor = 1.0/((qreal) (1LL << qureg.numQubitsRepresented));
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    densmatr_initPlusStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        probFactor,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag);
}
__global__ void densmatr_initPlusStateKernel (long long int stateVecSize, qreal probFactor, qreal * stateVecReal, qreal * stateVecImag)
Definition at line 96 of file QuEST_gpu.cu.
{
    long long int index;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    stateVecReal[index] = probFactor;
    stateVecImag[index] = 0.0;
}
void densmatr_initPureState (Qureg targetQureg, Qureg copyQureg)
Definition at line 85 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initPureState().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(copyQureg.numAmpsPerChunk)/threadsPerCUDABlock);
    densmatr_initPureStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        copyQureg.numAmpsPerChunk,
        targetQureg.deviceStateVec.real, targetQureg.deviceStateVec.imag,
        copyQureg.deviceStateVec.real,   copyQureg.deviceStateVec.imag);
}
__global__ void densmatr_initPureStateKernel (long long int numPureAmps, qreal * targetVecReal, qreal * targetVecImag, qreal * copyVecReal, qreal * copyVecImag)
Definition at line 66 of file QuEST_gpu.cu.
References qreal.
{
    // this is a particular index of the pure copyQureg
    long long int index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=numPureAmps) return;
    qreal realRow = copyVecReal[index];
    qreal imagRow = copyVecImag[index];
    for (long long int col=0; col < numPureAmps; col++) {
        qreal realCol =   copyVecReal[col];
        qreal imagCol = - copyVecImag[col]; // minus for conjugation
        targetVecReal[col*numPureAmps + index] = realRow*realCol - imagRow*imagCol;
        targetVecImag[col*numPureAmps + index] = realRow*imagCol + imagRow*realCol;
    }
}
void densmatr_oneQubitDephase (Qureg qureg, const int targetQubit, qreal dephase)
Definition at line 2011 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by applyOneQubitDephaseError(), densmatr_oneQubitDepolarise(), and densmatr_oneQubitDepolariseDistributed().
{
    if (dephase == 0)
        return;
    long long int numAmpsToVisit = qureg.numAmpsPerChunk/4;
    int rowQubit = targetQubit + qureg.numQubitsRepresented;
    long long int colBit = 1LL << targetQubit;
    long long int rowBit = 1LL << rowQubit;
    long long int part1 = colBit - 1;
    long long int part2 = (rowBit >> 1) - colBit;
    long long int part3 = numAmpsToVisit - (rowBit >> 1);
    qreal dephFac = 1 - dephase;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numAmpsToVisit / (qreal) threadsPerCUDABlock);
    densmatr_oneQubitDephaseKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        dephFac, qureg.deviceStateVec.real, qureg.deviceStateVec.imag, numAmpsToVisit,
        part1, part2, part3, colBit, rowBit);
}
__global__ void densmatr_oneQubitDephaseKernel (qreal fac, qreal * vecReal, qreal * vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int colBit, long long int rowBit)
Called once for every 4 amplitudes in density matrix Works by establishing the |..0.
.><..0..| state (for its given index) then visiting |..1..><..0..| and |..0..><..1..|. Labels |part1 X pa><rt2 NOT(X) part3| From the brain of Simon Benjamin
Definition at line 1996 of file QuEST_gpu.cu.
{
    long long int scanInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (scanInd >= numAmpsToVisit) return;
    long long int ampInd = (scanInd&part1) + ((scanInd&part2)<<1) + ((scanInd&part3)<<2);
    vecReal[ampInd + colBit] *= fac;
    vecImag[ampInd + colBit] *= fac;
    vecReal[ampInd + rowBit] *= fac;
    vecImag[ampInd + rowBit] *= fac;
}
void densmatr_oneQubitDepolarise (Qureg qureg, const int targetQubit, qreal depolLevel)
Definition at line 2127 of file QuEST_gpu.cu.
References densmatr_oneQubitDephase(), Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by applyOneQubitDepolariseError().
{
    if (depolLevel == 0)
        return;
    densmatr_oneQubitDephase(qureg, targetQubit, depolLevel);
    long long int numAmpsToVisit = qureg.numAmpsPerChunk/4;
    int rowQubit = targetQubit + qureg.numQubitsRepresented;
    long long int colBit = 1LL << targetQubit;
    long long int rowBit = 1LL << rowQubit;
    long long int bothBits = colBit | rowBit;
    long long int part1 = colBit - 1;
    long long int part2 = (rowBit >> 1) - colBit;
    long long int part3 = numAmpsToVisit - (rowBit >> 1);
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numAmpsToVisit / (qreal) threadsPerCUDABlock);
    densmatr_oneQubitDepolariseKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        depolLevel, qureg.deviceStateVec.real, qureg.deviceStateVec.imag, numAmpsToVisit,
        part1, part2, part3, bothBits);
}
__global__ void densmatr_oneQubitDepolariseKernel (qreal depolLevel, qreal * vecReal, qreal * vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int bothBits)
Works like oneQubitDephase but modifies every other element, and elements are averaged in pairs.
Definition at line 2102 of file QuEST_gpu.cu.
References qreal.
{
    long long int scanInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (scanInd >= numAmpsToVisit) return;
    long long int baseInd = (scanInd&part1) + ((scanInd&part2)<<1) + ((scanInd&part3)<<2);
    long long int targetInd = baseInd + bothBits;
    qreal realAvDepol = depolLevel * 0.5 * (vecReal[baseInd] + vecReal[targetInd]);
    qreal imagAvDepol = depolLevel * 0.5 * (vecImag[baseInd] + vecImag[targetInd]);
    vecReal[baseInd]   *= 1 - depolLevel;
    vecImag[baseInd]   *= 1 - depolLevel;
    vecReal[targetInd] *= 1 - depolLevel;
    vecImag[targetInd] *= 1 - depolLevel;
    vecReal[baseInd]   += realAvDepol;
    vecImag[baseInd]   += imagAvDepol;
    vecReal[targetInd] += realAvDepol;
    vecImag[targetInd] += imagAvDepol;
}
void densmatr_twoQubitDephase (Qureg qureg, int qubit1, int qubit2, qreal dephase)
Definition at line 2065 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by applyTwoQubitDephaseError(), and densmatr_twoQubitDepolarise().
{
    if (dephase == 0)
        return;
    // assumes qubit2 > qubit1
    int rowQubit1 = qubit1 + qureg.numQubitsRepresented;
    int rowQubit2 = qubit2 + qureg.numQubitsRepresented;
    long long int colBit1 = 1LL << qubit1;
    long long int rowBit1 = 1LL << rowQubit1;
    long long int colBit2 = 1LL << qubit2;
    long long int rowBit2 = 1LL << rowQubit2;
    long long int part1 = colBit1 - 1;
    long long int part2 = (colBit2 >> 1) - colBit1;
    long long int part3 = (rowBit1 >> 2) - (colBit2 >> 1);
    long long int part4 = (rowBit2 >> 3) - (rowBit1 >> 2);
    long long int part5 = (qureg.numAmpsPerChunk/16) - (rowBit2 >> 3);
    qreal dephFac = 1 - dephase;
    // refers to states |a 0 b 0 c><d 0 e 0 f| (target qubits are fixed)
    long long int numBackgroundStates = qureg.numAmpsPerChunk/16;
    // 12 of these states experience dephasing
    long long int numAmpsToVisit = 12 * numBackgroundStates;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numAmpsToVisit / (qreal) threadsPerCUDABlock);
    densmatr_twoQubitDephaseKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        dephFac, qureg.deviceStateVec.real, qureg.deviceStateVec.imag, numBackgroundStates, numAmpsToVisit,
        part1, part2, part3, part4, part5, colBit1, rowBit1, colBit2, rowBit2);
}
__global__ void densmatr_twoQubitDephaseKernel (qreal fac, qreal * vecReal, qreal * vecImag, long long int numBackgroundStates, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int part4, long long int part5, long long int colBit1, long long int rowBit1, long long int colBit2, long long int rowBit2)
Called 12 times for every 16 amplitudes in density matrix Each sums from the |..0..0.
.><..0..0..| index to visit either |..0..0..><..0..1..|, |..0..0..><..1..0..|, |..0..0..><..1..1..|, |..0..1..><..0..0..| etc and so on to |..1..1..><..1..0|. Labels |part1 0 part2 0 par><t3 0 part4 0 part5|. From the brain of Simon Benjamin
Definition at line 2041 of file QuEST_gpu.cu.
{
    long long int outerInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (outerInd >= numAmpsToVisit) return;
    // sets meta in 1...14 excluding 5, 10, creating bit string DCBA for |..D..C..><..B..A|
    int meta = 1 + (outerInd/numBackgroundStates);
    if (meta > 4) meta++;
    if (meta > 9) meta++;
    long long int shift = rowBit2*((meta>>3)%2) + rowBit1*((meta>>2)%2) + colBit2*((meta>>1)%2) + colBit1*(meta%2);
    long long int scanInd = outerInd % numBackgroundStates;
    long long int stateInd = (
        shift +
        (scanInd&part1) + ((scanInd&part2)<<1) + ((scanInd&part3)<<2) + ((scanInd&part4)<<3) + ((scanInd&part5)<<4));
    vecReal[stateInd] *= fac;
    vecImag[stateInd] *= fac;
}
void densmatr_twoQubitDepolarise (Qureg qureg, int qubit1, int qubit2, qreal depolLevel)
Definition at line 2186 of file QuEST_gpu.cu.
References densmatr_twoQubitDephase(), Qureg::deviceStateVec, Qureg::numAmpsPerChunk, Qureg::numQubitsRepresented, and qreal.
Referenced by applyTwoQubitDepolariseError().
{
    if (depolLevel == 0)
        return;
    // assumes qubit2 > qubit1
    densmatr_twoQubitDephase(qureg, qubit1, qubit2, depolLevel);
    int rowQubit1 = qubit1 + qureg.numQubitsRepresented;
    int rowQubit2 = qubit2 + qureg.numQubitsRepresented;
    long long int colBit1 = 1LL << qubit1;
    long long int rowBit1 = 1LL << rowQubit1;
    long long int colBit2 = 1LL << qubit2;
    long long int rowBit2 = 1LL << rowQubit2;
    long long int rowCol1 = colBit1 | rowBit1;
    long long int rowCol2 = colBit2 | rowBit2;
    long long int numAmpsToVisit = qureg.numAmpsPerChunk/16;
    long long int part1 = colBit1 - 1;
    long long int part2 = (colBit2 >> 1) - colBit1;
    long long int part3 = (rowBit1 >> 2) - (colBit2 >> 1);
    long long int part4 = (rowBit2 >> 3) - (rowBit1 >> 2);
    long long int part5 = numAmpsToVisit - (rowBit2 >> 3);
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil(numAmpsToVisit / (qreal) threadsPerCUDABlock);
    densmatr_twoQubitDepolariseKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        depolLevel, qureg.deviceStateVec.real, qureg.deviceStateVec.imag, numAmpsToVisit,
        part1, part2, part3, part4, part5, rowCol1, rowCol2);
}
__global__ void densmatr_twoQubitDepolariseKernel (qreal depolLevel, qreal * vecReal, qreal * vecImag, long long int numAmpsToVisit, long long int part1, long long int part2, long long int part3, long long int part4, long long int part5, long long int rowCol1, long long int rowCol2)
Called once for every 16 amplitudes.
Definition at line 2154 of file QuEST_gpu.cu.
References qreal.
{
    long long int scanInd = blockIdx.x*blockDim.x + threadIdx.x;
    if (scanInd >= numAmpsToVisit) return;
    // index of |..0..0..><..0..0|
    long long int ind00 = (scanInd&part1) + ((scanInd&part2)<<1) + ((scanInd&part3)<<2) + ((scanInd&part4)<<3) + ((scanInd&part5)<<4);
    long long int ind01 = ind00 + rowCol1;
    long long int ind10 = ind00 + rowCol2;
    long long int ind11 = ind00 + rowCol1 + rowCol2;
    qreal realAvDepol = depolLevel * 0.25 * (
        vecReal[ind00] + vecReal[ind01] + vecReal[ind10] + vecReal[ind11]);
    qreal imagAvDepol = depolLevel * 0.25 * (
        vecImag[ind00] + vecImag[ind01] + vecImag[ind10] + vecImag[ind11]);
    qreal retain = 1 - depolLevel;
    vecReal[ind00] *= retain; vecImag[ind00] *= retain;
    vecReal[ind01] *= retain; vecImag[ind01] *= retain;
    vecReal[ind10] *= retain; vecImag[ind10] *= retain;
    vecReal[ind11] *= retain; vecImag[ind11] *= retain;
    vecReal[ind00] += realAvDepol; vecImag[ind00] += imagAvDepol;
    vecReal[ind01] += realAvDepol; vecImag[ind01] += imagAvDepol;
    vecReal[ind10] += realAvDepol; vecImag[ind10] += imagAvDepol;
    vecReal[ind11] += realAvDepol; vecImag[ind11] += imagAvDepol;
}
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 257 of file QuEST_gpu.cu.
{
    // MPI finalize goes here in MPI version. Call this function anyway for consistency
}
static __device__ int extractBit (int locationOfBitFromRight, long long int theEncodedNumber) [static]
Definition at line 19 of file QuEST_gpu.cu.
Referenced by statevec_controlledCompactUnitaryKernel(), statevec_controlledNotKernel(), statevec_controlledPauliYKernel(), statevec_controlledPhaseFlipKernel(), statevec_controlledPhaseShiftKernel(), statevec_controlledUnitaryKernel(), and statevec_initStateOfSingleQubitKernel().
{
    return (theEncodedNumber & ( 1LL << locationOfBitFromRight )) >> locationOfBitFromRight;
}
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
Definition at line 273 of file QuEST_gpu.cu.
References Qureg::numQubitsInStateVec.
{
    sprintf(str, "%dqubits_GPU_noMpi_noOMP", qureg.numQubitsInStateVec);
}
int getNumReductionLevels (long long int numValuesToReduce, int numReducedPerLevel)
Definition at line 1450 of file QuEST_gpu.cu.
{
    int levels=0;
    while (numValuesToReduce){
        numValuesToReduce = numValuesToReduce/numReducedPerLevel;
        levels++;
    }
    return levels;
}
int GPUExists (void)
Definition at line 216 of file QuEST_gpu.cu.
Referenced by createQuESTEnv().
                   {
    int deviceCount, device;
    int gpuDeviceCount = 0;
    struct cudaDeviceProp properties;
    cudaError_t cudaResultCode = cudaGetDeviceCount(&deviceCount);
    if (cudaResultCode != cudaSuccess) deviceCount = 0;
    /* machines with no GPUs can still report one emulation device */
    for (device = 0; device < deviceCount; ++device) {
        cudaGetDeviceProperties(&properties, device);
        if (properties.major != 9999) { /* 9999 means emulation only */
            ++gpuDeviceCount;
        }
    }
    if (gpuDeviceCount) return 1;
    else return 0;
}
__device__ __host__ unsigned int log2Int (unsigned int x)
Definition at line 1327 of file QuEST_gpu.cu.
Referenced by reduceBlock().
{
    unsigned int ans = 0 ;
    while( x>>=1 ) ans++;
    return ans ;
}
__device__ void reduceBlock (qreal * arrayIn, qreal * reducedArray, int length)
Definition at line 1334 of file QuEST_gpu.cu.
References log2Int().
Referenced by copySharedReduceBlock(), densmatr_calcFidelityKernel(), densmatr_calcPurityKernel(), densmatr_findProbabilityOfZeroKernel(), statevec_calcInnerProductKernel(), and statevec_findProbabilityOfZeroKernel().
{
    int i, l, r;
    int threadMax, maxDepth;
    threadMax = length/2;
    maxDepth = log2Int(length/2);
    for (i=0; i<maxDepth+1; i++){
        if (threadIdx.x<threadMax){
            l = threadIdx.x;
            r = l + threadMax;
            arrayIn[l] = arrayIn[r] + arrayIn[l];
        }
        threadMax = threadMax >> 1;
        __syncthreads(); // optimise -- use warp shuffle instead
    }
    if (threadIdx.x==0) reducedArray[blockIdx.x] = arrayIn[0];
}
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 261 of file QuEST_gpu.cu.
References QuESTEnv::numRanks.
{
    printf("EXECUTION ENVIRONMENT:\n");
    printf("Running locally on one node with GPU\n");
    printf("Number of ranks is %d\n", env.numRanks);
# ifdef _OPENMP
    printf("OpenMP enabled\n");
    printf("Number of threads available is %d\n", omp_get_max_threads());
# else
    printf("OpenMP disabled\n");
# endif
}
Complex statevec_calcInnerProduct (Qureg bra, Qureg ket)
Terrible code which unnecessarily individually computes and sums the real and imaginary components of the inner product, so as to not have to worry about keeping the sums separated during reduction.
Truly disgusting, probably doubles runtime, please fix. could even do the kernel twice, storing real in bra.reduc and imag in ket.reduc?
Definition at line 1600 of file QuEST_gpu.cu.
References copySharedReduceBlock(), Qureg::deviceStateVec, Qureg::firstLevelReduction, Complex::imag, Qureg::numAmpsPerChunk, qreal, Complex::real, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by calcInnerProduct(), and statevec_calcFidelity().
{
    qreal innerProdReal, innerProdImag;
    int getRealComp;
    long long int numValuesToReduce;
    int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
    int maxReducedPerLevel;
    int firstTime;
    // compute real component of inner product
    getRealComp = 1;
    numValuesToReduce = bra.numAmpsPerChunk;
    maxReducedPerLevel = REDUCE_SHARED_SIZE;
    firstTime = 1;
    while (numValuesToReduce > 1) {
        if (numValuesToReduce < maxReducedPerLevel) {
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        }
        else {
            valuesPerCUDABlock = maxReducedPerLevel;
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        if (firstTime) {
             statevec_calcInnerProductKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                 getRealComp,
                 bra.deviceStateVec.real, bra.deviceStateVec.imag,
                 ket.deviceStateVec.real, ket.deviceStateVec.imag,
                 numValuesToReduce,
                 bra.firstLevelReduction);
            firstTime = 0;
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    bra.firstLevelReduction,
                    bra.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(bra.firstLevelReduction), &(bra.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    cudaMemcpy(&innerProdReal, bra.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    // compute imag component of inner product
    getRealComp = 0;
    numValuesToReduce = bra.numAmpsPerChunk;
    maxReducedPerLevel = REDUCE_SHARED_SIZE;
    firstTime = 1;
    while (numValuesToReduce > 1) {
        if (numValuesToReduce < maxReducedPerLevel) {
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        }
        else {
            valuesPerCUDABlock = maxReducedPerLevel;
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        if (firstTime) {
             statevec_calcInnerProductKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                 getRealComp,
                 bra.deviceStateVec.real, bra.deviceStateVec.imag,
                 ket.deviceStateVec.real, ket.deviceStateVec.imag,
                 numValuesToReduce,
                 bra.firstLevelReduction);
            firstTime = 0;
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    bra.firstLevelReduction,
                    bra.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(bra.firstLevelReduction), &(bra.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    cudaMemcpy(&innerProdImag, bra.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    // return complex
    Complex innerProd;
    innerProd.real = innerProdReal;
    innerProd.imag = innerProdImag;
    return innerProd;
}
__global__ void statevec_calcInnerProductKernel (int getRealComp, qreal * vecReal1, qreal * vecImag1, qreal * vecReal2, qreal * vecImag2, long long int numTermsToSum, qreal * reducedArray)
computes either a real or imag term in the inner product
Definition at line 1570 of file QuEST_gpu.cu.
References qreal, and reduceBlock().
{
    long long int index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index >= numTermsToSum) return;
    // choose whether to calculate the real or imaginary term of the inner product
    qreal innerProdTerm;
    if (getRealComp)
        innerProdTerm = vecReal1[index]*vecReal2[index] + vecImag1[index]*vecImag2[index];
    else
        innerProdTerm = vecReal1[index]*vecImag2[index] - vecImag1[index]*vecReal2[index];
    // array of each thread's collected probability, to be summed
    extern __shared__ qreal tempReductionArray[];
    tempReductionArray[threadIdx.x] = innerProdTerm;
    __syncthreads();
    // every second thread reduces
    if (threadIdx.x<blockDim.x/2)
        reduceBlock(tempReductionArray, reducedArray, blockDim.x);
}
qreal statevec_calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Definition at line 1552 of file QuEST_gpu.cu.
References qreal, and statevec_findProbabilityOfZero().
Referenced by calcProbOfOutcome(), collapseToOutcome(), and statevec_measureWithStats().
{
    qreal outcomeProb = statevec_findProbabilityOfZero(qureg, measureQubit);
    if (outcome==1)
        outcomeProb = 1.0 - outcomeProb;
    return outcomeProb;
}
qreal statevec_calcTotalProb (Qureg qureg)
Definition at line 1133 of file QuEST_gpu.cu.
References copyStateFromGPU(), Qureg::numAmpsPerChunk, qreal, Qureg::stateVec, and y.
Referenced by calcTotalProb().
{
    /* IJB - implemented using Kahan summation for greater accuracy at a slight floating
       point operation overhead. For more details see https://en.wikipedia.org/wiki/Kahan_summation_algorithm */
    /* Don't change the bracketing in this routine! */
    qreal pTotal=0;
    qreal y, t, c;
    long long int index;
    long long int numAmpsPerRank = qureg.numAmpsPerChunk;
    copyStateFromGPU(qureg);
    c = 0.0;
    for (index=0; index<numAmpsPerRank; index++){
        /* Perform pTotal+=qureg.stateVec.real[index]*qureg.stateVec.real[index]; by Kahan */
        // pTotal+=qureg.stateVec.real[index]*qureg.stateVec.real[index];
        y = qureg.stateVec.real[index]*qureg.stateVec.real[index] - c;
        t = pTotal + y;
        c = ( t - pTotal ) - y;
        pTotal = t;
        /* Perform pTotal+=qureg.stateVec.imag[index]*qureg.stateVec.imag[index]; by Kahan */
        //pTotal+=qureg.stateVec.imag[index]*qureg.stateVec.imag[index];
        y = qureg.stateVec.imag[index]*qureg.stateVec.imag[index] - c;
        t = pTotal + y;
        c = ( t - pTotal ) - y;
        pTotal = t;
    }
    return pTotal;
}
void statevec_cloneQureg (Qureg targetQureg, Qureg copyQureg)
works for both statevectors and density matrices
Definition at line 50 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, and Qureg::numAmpsPerChunk.
Referenced by cloneQureg(), and initPureState().
{
    // copy copyQureg's GPU statevec to targetQureg's GPU statevec
    cudaDeviceSynchronize();
    cudaMemcpy(
        targetQureg.deviceStateVec.real,
        copyQureg.deviceStateVec.real,
        targetQureg.numAmpsPerChunk*sizeof(*(targetQureg.deviceStateVec.real)),
        cudaMemcpyDeviceToDevice);
    cudaMemcpy(
        targetQureg.deviceStateVec.imag,
        copyQureg.deviceStateVec.imag,
        targetQureg.numAmpsPerChunk*sizeof(*(targetQureg.deviceStateVec.imag)),
        cudaMemcpyDeviceToDevice);
}
void statevec_collapseToKnownProbOutcome (Qureg qureg, const int measureQubit, int outcome, qreal outcomeProb)
Definition at line 1903 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by collapseToOutcome(), and statevec_measureWithStats().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_collapseToKnownProbOutcomeKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, measureQubit, outcome, outcomeProb);
}
__global__ void statevec_collapseToKnownProbOutcomeKernel (Qureg qureg, int measureQubit, int outcome, qreal totalProbability)
Definition at line 1846 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         index;                                               // current index for first half block
    // ----- measured probability
    qreal   renorm;                                    // probability (returned) value
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    // (good for shared memory parallelism)
    long long int numTasks=qureg.numAmpsPerChunk>>1;
    // ---------------------------------------------------------------- //
    //            dimensions                                            //
    // ---------------------------------------------------------------- //
    sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
    // and then the number to skip
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
    // ---------------------------------------------------------------- //
    //            find probability                                      //
    // ---------------------------------------------------------------- //
    //
    // --- task-based shared-memory parallel implementation
    //
    renorm=1/sqrt(totalProbability);
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock = thisTask / sizeHalfBlock;
    index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    if (outcome==0){
        stateVecReal[index]=stateVecReal[index]*renorm;
        stateVecImag[index]=stateVecImag[index]*renorm;
        stateVecReal[index+sizeHalfBlock]=0;
        stateVecImag[index+sizeHalfBlock]=0;
    } else if (outcome==1){
        stateVecReal[index]=0;
        stateVecImag[index]=0;
        stateVecReal[index+sizeHalfBlock]=stateVecReal[index+sizeHalfBlock]*renorm;
        stateVecImag[index+sizeHalfBlock]=stateVecImag[index+sizeHalfBlock]*renorm;
    }
}
void statevec_compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Definition at line 585 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by compactUnitary(), statevec_rotateAroundAxis(), and statevec_rotateAroundAxisConj().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_compactUnitaryKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit, alpha, beta);
}
__global__ void statevec_compactUnitaryKernel (Qureg qureg, const int rotQubit, Complex alpha, Complex beta)
fix -- no necessary for GPU version
Definition at line 530 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Complex::imag, Qureg::numAmpsPerChunk, qreal, and Complex::real.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    sizeHalfBlock = 1LL << rotQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    qreal alphaImag=alpha.imag, alphaReal=alpha.real;
    qreal betaImag=beta.imag, betaReal=beta.real;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    // store current state vector values in temp variables
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    stateRealLo = stateVecReal[indexLo];
    stateImagLo = stateVecImag[indexLo];
    // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
    stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
        - betaReal*stateRealLo - betaImag*stateImagLo;
    stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
        - betaReal*stateImagLo + betaImag*stateRealLo;
    // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
    stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
        + alphaReal*stateRealLo + alphaImag*stateImagLo;
    stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
        + alphaReal*stateImagLo - alphaImag*stateRealLo;
}
int statevec_compareStates (Qureg mq1, Qureg mq2, qreal precision)
Definition at line 512 of file QuEST_gpu.cu.
References copyStateFromGPU(), Qureg::numAmpsPerChunk, qreal, and Qureg::stateVec.
Referenced by compareStates().
{
    qreal diff;
    int chunkSize = mq1.numAmpsPerChunk;
    copyStateFromGPU(mq1);
    copyStateFromGPU(mq2);
    for (int i=0; i<chunkSize; i++){
        diff = mq1.stateVec.real[i] - mq2.stateVec.real[i];
        if (diff<0) diff *= -1;
        if (diff>precision) return 0;
        diff = mq1.stateVec.imag[i] - mq2.stateVec.imag[i];
        if (diff<0) diff *= -1;
        if (diff>precision) return 0;
    }
    return 1;
}
void statevec_controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Definition at line 652 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledCompactUnitary(), statevec_controlledRotateAroundAxis(), and statevec_controlledRotateAroundAxisConj().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_controlledCompactUnitaryKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, controlQubit, targetQubit, alpha, beta);
}
__global__ void statevec_controlledCompactUnitaryKernel (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
fix -- no necessary for GPU version
Definition at line 593 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Complex::imag, Qureg::numAmpsPerChunk, qreal, and Complex::real.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    int controlBit;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    qreal alphaImag=alpha.imag, alphaReal=alpha.real;
    qreal betaImag=beta.imag, betaReal=beta.real;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    controlBit = extractBit(controlQubit, indexUp);
    if (controlBit){
        // store current state vector values in temp variables
        stateRealUp = stateVecReal[indexUp];
        stateImagUp = stateVecImag[indexUp];
        stateRealLo = stateVecReal[indexLo];
        stateImagLo = stateVecImag[indexLo];
        // state[indexUp] = alpha * state[indexUp] - conj(beta)  * state[indexLo]
        stateVecReal[indexUp] = alphaReal*stateRealUp - alphaImag*stateImagUp
            - betaReal*stateRealLo - betaImag*stateImagLo;
        stateVecImag[indexUp] = alphaReal*stateImagUp + alphaImag*stateRealUp
            - betaReal*stateImagLo + betaImag*stateRealLo;
        // state[indexLo] = beta  * state[indexUp] + conj(alpha) * state[indexLo]
        stateVecReal[indexLo] = betaReal*stateRealUp - betaImag*stateImagUp
            + alphaReal*stateRealLo + alphaImag*stateImagLo;
        stateVecImag[indexLo] = betaReal*stateImagUp + betaImag*stateRealUp
            + alphaReal*stateImagLo - alphaImag*stateRealLo;
    }
}
void statevec_controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 1319 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledNot().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_controlledNotKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, controlQubit, targetQubit);
}
__global__ void statevec_controlledNotKernel (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 1280 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Qureg::numAmpsPerChunk, and qreal.
{
    long long int index;
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    long long int stateVecSize;
    int controlBit;
    // ----- temp variables
    qreal   stateRealUp,                             // storage for previous state values
           stateImagUp;                             // (used in updates)
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=(stateVecSize>>1)) return;
    thisBlock   = index / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + index%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    controlBit = extractBit(controlQubit, indexUp);
    if (controlBit){
        stateRealUp = stateVecReal[indexUp];
        stateImagUp = stateVecImag[indexUp];
        stateVecReal[indexUp] = stateVecReal[indexLo];
        stateVecImag[indexUp] = stateVecImag[indexLo];
        stateVecReal[indexLo] = stateRealUp;
        stateVecImag[indexLo] = stateImagUp;
    }
}
void statevec_controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 982 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledPauliY().
{
    int conjFactor = 1;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_controlledPauliYKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, controlQubit, targetQubit, conjFactor);
}
void statevec_controlledPauliYConj (Qureg qureg, const int controlQubit, const int targetQubit)
Definition at line 991 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledPauliY().
{
    int conjFactor = -1;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_controlledPauliYKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, controlQubit, targetQubit, conjFactor);
}
__global__ void statevec_controlledPauliYKernel (Qureg qureg, const int controlQubit, const int targetQubit, const int conjFac)
Definition at line 946 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Qureg::numAmpsPerChunk, and qreal.
{
    long long int index;
    long long int sizeBlock, sizeHalfBlock;
    long long int stateVecSize;
    int controlBit;
    qreal   stateRealUp, stateImagUp;
    long long int thisBlock, indexUp, indexLo;
    sizeHalfBlock = 1LL << targetQubit;
    sizeBlock     = 2LL * sizeHalfBlock;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=(stateVecSize>>1)) return;
    thisBlock   = index / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + index%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    controlBit = extractBit(controlQubit, indexUp);
    if (controlBit){
        stateRealUp = stateVecReal[indexUp];
        stateImagUp = stateVecImag[indexUp];
        // update under +-{{0, -i}, {i, 0}}
        stateVecReal[indexUp] = conjFac * stateVecImag[indexLo];
        stateVecImag[indexUp] = conjFac * -stateVecReal[indexLo];
        stateVecReal[indexLo] = conjFac * -stateImagUp;
        stateVecImag[indexLo] = conjFac * stateRealUp;
    }
}
void statevec_controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
Definition at line 1186 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledPhaseFlip().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_controlledPhaseFlipKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, idQubit1, idQubit2);
}
__global__ void statevec_controlledPhaseFlipKernel (Qureg qureg, const int idQubit1, const int idQubit2)
Definition at line 1165 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Qureg::numAmpsPerChunk, and qreal.
{
    long long int index;
    long long int stateVecSize;
    int bit1, bit2;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    bit1 = extractBit (idQubit1, index);
    bit2 = extractBit (idQubit2, index);
    if (bit1 && bit2) {
        stateVecReal [index] = - stateVecReal [index];
        stateVecImag [index] = - stateVecImag [index];
    }
}
void statevec_controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
Definition at line 1064 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledPhaseShift().
{
    qreal cosAngle = cos(angle);
    qreal sinAngle = sin(angle);
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_controlledPhaseShiftKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, idQubit1, idQubit2, cosAngle, sinAngle);
}
__global__ void statevec_controlledPhaseShiftKernel (Qureg qureg, const int idQubit1, const int idQubit2, qreal cosAngle, qreal sinAngle)
Definition at line 1039 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Qureg::numAmpsPerChunk, and qreal.
{
    long long int index;
    long long int stateVecSize;
    int bit1, bit2;
    qreal stateRealLo, stateImagLo;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    bit1 = extractBit (idQubit1, index);
    bit2 = extractBit (idQubit2, index);
    if (bit1 && bit2) {
        stateRealLo = stateVecReal[index];
        stateImagLo = stateVecImag[index];
        stateVecReal[index] = cosAngle*stateRealLo - sinAngle*stateImagLo;
        stateVecImag[index] = sinAngle*stateRealLo + cosAngle*stateImagLo;
    }
}
void statevec_controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Definition at line 779 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by controlledUnitary().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_controlledUnitaryKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, controlQubit, targetQubit, u);
}
__global__ void statevec_controlledUnitaryKernel (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
fix -- no necessary for GPU version
Definition at line 721 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, extractBit(), Complex::imag, Qureg::numAmpsPerChunk, qreal, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, and Complex::real.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    int controlBit;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    // store current state vector values in temp variables
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    stateRealLo = stateVecReal[indexLo];
    stateImagLo = stateVecImag[indexLo];
    controlBit = extractBit(controlQubit, indexUp);
    if (controlBit){
        // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
        stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
            + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
        stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
            + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
        // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
        stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
            + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
        stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
            + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
    }
}
void statevec_createQureg (Qureg * qureg, int numQubits, QuESTEnv env)
Definition at line 155 of file QuEST_gpu.cu.
References Qureg::chunkId, Qureg::deviceStateVec, Qureg::firstLevelReduction, Qureg::isDensityMatrix, Qureg::numAmpsPerChunk, Qureg::numAmpsTotal, Qureg::numChunks, Qureg::numQubitsInStateVec, QuESTEnv::numRanks, Qureg::pairStateVec, qreal, QuESTEnv::rank, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and Qureg::stateVec.
Referenced by createDensityQureg(), and createQureg().
{
    // allocate CPU memory
    long long int numAmps = 1L << numQubits;
    long long int numAmpsPerRank = numAmps/env.numRanks;
    qureg->stateVec.real = (qreal*) malloc(numAmpsPerRank * sizeof(qureg->stateVec.real));
    qureg->stateVec.imag = (qreal*) malloc(numAmpsPerRank * sizeof(qureg->stateVec.imag));
    if (env.numRanks>1){
        qureg->pairStateVec.real = (qreal*) malloc(numAmpsPerRank * sizeof(qureg->pairStateVec.real));
        qureg->pairStateVec.imag = (qreal*) malloc(numAmpsPerRank * sizeof(qureg->pairStateVec.imag));
    }
    // check cpu memory allocation was successful
    if ( (!(qureg->stateVec.real) || !(qureg->stateVec.imag))
            && numAmpsPerRank ) {
        printf("Could not allocate memory!\n");
        exit (EXIT_FAILURE);
    }
    if ( env.numRanks>1 && (!(qureg->pairStateVec.real) || !(qureg->pairStateVec.imag))
            && numAmpsPerRank ) {
        printf("Could not allocate memory!\n");
        exit (EXIT_FAILURE);
    }
    qureg->numQubitsInStateVec = numQubits;
    qureg->numAmpsPerChunk = numAmpsPerRank;
    qureg->numAmpsTotal = numAmps;
    qureg->chunkId = env.rank;
    qureg->numChunks = env.numRanks;
    qureg->isDensityMatrix = 0;
    // allocate GPU memory
    cudaMalloc(&(qureg->deviceStateVec.real), qureg->numAmpsPerChunk*sizeof(*(qureg->deviceStateVec.real)));
    cudaMalloc(&(qureg->deviceStateVec.imag), qureg->numAmpsPerChunk*sizeof(*(qureg->deviceStateVec.imag)));
    cudaMalloc(&(qureg->firstLevelReduction), ceil(qureg->numAmpsPerChunk/(qreal)REDUCE_SHARED_SIZE)*sizeof(qreal));
    cudaMalloc(&(qureg->secondLevelReduction), ceil(qureg->numAmpsPerChunk/(qreal)(REDUCE_SHARED_SIZE*REDUCE_SHARED_SIZE))*
            sizeof(qreal));
    // check gpu memory allocation was successful
    if (!(qureg->deviceStateVec.real) || !(qureg->deviceStateVec.imag)){
        printf("Could not allocate memory on GPU!\n");
        exit (EXIT_FAILURE);
    }
}
void statevec_destroyQureg (Qureg qureg, QuESTEnv env)
Definition at line 201 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, QuESTEnv::numRanks, Qureg::pairStateVec, and Qureg::stateVec.
Referenced by destroyQureg().
{
    // Free CPU memory
    free(qureg.stateVec.real);
    free(qureg.stateVec.imag);
    if (env.numRanks>1){
        free(qureg.pairStateVec.real);
        free(qureg.pairStateVec.imag);
    }
    // Free GPU memory
    cudaFree(qureg.deviceStateVec.real);
    cudaFree(qureg.deviceStateVec.imag);
}
qreal statevec_findProbabilityOfZero (Qureg qureg, const int measureQubit)
Definition at line 1514 of file QuEST_gpu.cu.
References copySharedReduceBlock(), Qureg::firstLevelReduction, Qureg::numAmpsPerChunk, qreal, REDUCE_SHARED_SIZE, Qureg::secondLevelReduction, and swapDouble().
Referenced by statevec_calcProbOfOutcome().
{
    long long int numValuesToReduce = qureg.numAmpsPerChunk>>1;
    int valuesPerCUDABlock, numCUDABlocks, sharedMemSize;
    qreal stateProb=0;
    int firstTime=1;
    int maxReducedPerLevel = REDUCE_SHARED_SIZE;
    while(numValuesToReduce>1){
        if (numValuesToReduce<maxReducedPerLevel){
            // Need less than one CUDA block to reduce values
            valuesPerCUDABlock = numValuesToReduce;
            numCUDABlocks = 1;
        } else {
            // Use full CUDA blocks, with block size constrained by shared mem usage
            valuesPerCUDABlock = maxReducedPerLevel;
            numCUDABlocks = ceil((qreal)numValuesToReduce/valuesPerCUDABlock);
        }
        sharedMemSize = valuesPerCUDABlock*sizeof(qreal);
        if (firstTime){
            statevec_findProbabilityOfZeroKernel<<<numCUDABlocks, valuesPerCUDABlock, sharedMemSize>>>(
                    qureg, measureQubit, qureg.firstLevelReduction);
            firstTime=0;
        } else {
            cudaDeviceSynchronize();
            copySharedReduceBlock<<<numCUDABlocks, valuesPerCUDABlock/2, sharedMemSize>>>(
                    qureg.firstLevelReduction,
                    qureg.secondLevelReduction, valuesPerCUDABlock);
            cudaDeviceSynchronize();
            swapDouble(&(qureg.firstLevelReduction), &(qureg.secondLevelReduction));
        }
        numValuesToReduce = numValuesToReduce/maxReducedPerLevel;
    }
    cudaMemcpy(&stateProb, qureg.firstLevelReduction, sizeof(qreal), cudaMemcpyDeviceToHost);
    return stateProb;
}
__global__ void statevec_findProbabilityOfZeroKernel (Qureg qureg, const int measureQubit, qreal * reducedArray)
Definition at line 1400 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, qreal, and reduceBlock().
  {
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         index;                                               // current index for first half block
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    long long int numTasks=qureg.numAmpsPerChunk>>1;
    // (good for shared memory parallelism)
    extern __shared__ qreal tempReductionArray[];
    // ---------------------------------------------------------------- //
    //            dimensions                                            //
    // ---------------------------------------------------------------- //
    sizeHalfBlock = 1LL << (measureQubit);                       // number of state vector elements to sum,
    // and then the number to skip
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks (pairs of measure and skip entries)
    // ---------------------------------------------------------------- //
    //            find probability                                      //
    // ---------------------------------------------------------------- //
    //
    // --- task-based shared-memory parallel implementation
    //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock = thisTask / sizeHalfBlock;
    index     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    qreal realVal, imagVal;
    realVal = stateVecReal[index];
    imagVal = stateVecImag[index];
    tempReductionArray[threadIdx.x] = realVal*realVal + imagVal*imagVal;
    __syncthreads();
    if (threadIdx.x<blockDim.x/2){
        reduceBlock(tempReductionArray, reducedArray, blockDim.x);
    }
}
qreal statevec_getImagAmp (Qureg qureg, long long int index)
Definition at line 338 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, and qreal.
Referenced by getAmp(), getDensityAmp(), getImagAmp(), and statevec_getProbAmp().
{
    qreal el=0;
    cudaMemcpy(&el, &(qureg.deviceStateVec.imag[index]),
            sizeof(*(qureg.deviceStateVec.imag)), cudaMemcpyDeviceToHost);
    return el;
}
qreal statevec_getRealAmp (Qureg qureg, long long int index)
Definition at line 331 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, and qreal.
Referenced by getAmp(), getDensityAmp(), getRealAmp(), and statevec_getProbAmp().
{
    qreal el=0;
    cudaMemcpy(&el, &(qureg.deviceStateVec.real[index]),
            sizeof(*(qureg.deviceStateVec.real)), cudaMemcpyDeviceToHost);
    return el;
}
void statevec_hadamard (Qureg qureg, const int targetQubit)
Definition at line 1272 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by hadamard().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_hadamardKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit);
}
__global__ void statevec_hadamardKernel (Qureg qureg, const int targetQubit)
fix -- no necessary for GPU version
Definition at line 1223 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    qreal recRoot2 = 1.0/sqrt(2.0);
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    // store current state vector values in temp variables
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    stateRealLo = stateVecReal[indexLo];
    stateImagLo = stateVecImag[indexLo];
    stateVecReal[indexUp] = recRoot2*(stateRealUp + stateRealLo);
    stateVecImag[indexUp] = recRoot2*(stateImagUp + stateImagLo);
    stateVecReal[indexLo] = recRoot2*(stateRealUp - stateRealLo);
    stateVecImag[indexLo] = recRoot2*(stateImagUp - stateImagLo);
}
void statevec_initClassicalState (Qureg qureg, long long int stateInd)
Definition at line 409 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initClassicalState().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_initClassicalStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag, stateInd);
}
__global__ void statevec_initClassicalStateKernel (long long int stateVecSize, qreal * stateVecReal, qreal * stateVecImag, long long int stateInd)
Definition at line 394 of file QuEST_gpu.cu.
{
    long long int index;
    // initialise the state to |stateInd>
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    stateVecReal[index] = 0.0;
    stateVecImag[index] = 0.0;
    if (index==stateInd){
        // classical state has probability 1
        stateVecReal[stateInd] = 1.0;
        stateVecImag[stateInd] = 0.0;
    }
}
void statevec_initPlusState (Qureg qureg)
Definition at line 383 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initPlusState().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_initPlusStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag);
}
__global__ void statevec_initPlusStateKernel (long long int stateVecSize, qreal * stateVecReal, qreal * stateVecImag)
Definition at line 372 of file QuEST_gpu.cu.
References qreal.
{
    long long int index;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    qreal normFactor = 1.0/sqrt((qreal)stateVecSize);
    stateVecReal[index] = normFactor;
    stateVecImag[index] = 0.0;
}
void statevec_initStateDebug (Qureg qureg)
Initialise the state vector of probability amplitudes to an (unphysical) state with each component of each probability amplitude a unique floating point value.
For debugging processes
Parameters:
[in,out] qureg object representing the set of qubits to be initialised
Definition at line 430 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initStateDebug().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_initStateDebugKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag);
}
__global__ void statevec_initStateDebugKernel (long long int stateVecSize, qreal * stateVecReal, qreal * stateVecImag)
Definition at line 420 of file QuEST_gpu.cu.
{
    long long int index;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    stateVecReal[index] = (index*2.0)/10.0;
    stateVecImag[index] = (index*2.0+1.0)/10.0;
}
int statevec_initStateFromSingleFile (Qureg * qureg, char filename[200], QuESTEnv env)
Definition at line 468 of file QuEST_gpu.cu.
References Qureg::chunkId, copyStateToGPU(), Qureg::numAmpsPerChunk, Qureg::numChunks, qreal, and Qureg::stateVec.
Referenced by initStateFromSingleFile().
{
    long long int chunkSize, stateVecSize;
    long long int indexInChunk, totalIndex;
    chunkSize = qureg->numAmpsPerChunk;
    stateVecSize = chunkSize*qureg->numChunks;
    qreal *stateVecReal = qureg->stateVec.real;
    qreal *stateVecImag = qureg->stateVec.imag;
    FILE *fp;
    char line[200];
    fp = fopen(filename, "r");
    if (fp == NULL)
        return 0;
    indexInChunk = 0; totalIndex = 0;
    while (fgets(line, sizeof(char)*200, fp) != NULL && totalIndex<stateVecSize){
        if (line[0]!='#'){
            int chunkId = totalIndex/chunkSize;
            if (chunkId==qureg->chunkId){
                # if QuEST_PREC==1
                    sscanf(line, "%f, %f", &(stateVecReal[indexInChunk]),
                            &(stateVecImag[indexInChunk]));
                # elif QuEST_PREC==2
                    sscanf(line, "%lf, %lf", &(stateVecReal[indexInChunk]),
                            &(stateVecImag[indexInChunk]));
                # elif QuEST_PREC==4
                    sscanf(line, "%lf, %lf", &(stateVecReal[indexInChunk]),
                            &(stateVecImag[indexInChunk]));
                # endif
                indexInChunk += 1;
            }
            totalIndex += 1;
        }
    }
    fclose(fp);
    copyStateToGPU(*qureg);
    // indicate success
    return 1;
}
void statevec_initStateOfSingleQubit (Qureg * qureg, int qubitId, int outcome)
Initialise the state vector of probability amplitudes such that one qubit is set to 'outcome' and all other qubits are in an equal superposition of zero and one.
Parameters:
[in,out] qureg object representing the set of qubits to be initialised
[in] qubitId id of qubit to set to state 'outcome'
[in] value of qubit 'qubitId'
Definition at line 459 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initStateOfSingleQubit().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg->numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_initStateOfSingleQubitKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg->numAmpsPerChunk, qureg->deviceStateVec.real, qureg->deviceStateVec.imag, qubitId, outcome);
}
__global__ void statevec_initStateOfSingleQubitKernel (long long int stateVecSize, qreal * stateVecReal, qreal * stateVecImag, int qubitId, int outcome)
Definition at line 441 of file QuEST_gpu.cu.
References extractBit(), and qreal.
{
    long long int index;
    int bit;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    qreal normFactor = 1.0/sqrt((qreal)stateVecSize/2);
    bit = extractBit(qubitId, index);
    if (bit==outcome) {
        stateVecReal[index] = normFactor;
        stateVecImag[index] = 0.0;
    } else {
        stateVecReal[index] = 0.0;
        stateVecImag[index] = 0.0;
    }
}
void statevec_initZeroState (Qureg qureg)
Definition at line 361 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
Referenced by initZeroState().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_initZeroStateKernel<<<CUDABlocks, threadsPerCUDABlock>>>(
        qureg.numAmpsPerChunk,
        qureg.deviceStateVec.real,
        qureg.deviceStateVec.imag);
}
__global__ void statevec_initZeroStateKernel (long long int stateVecSize, qreal * stateVecReal, qreal * stateVecImag)
Definition at line 345 of file QuEST_gpu.cu.
{
    long long int index;
    // initialise the state to |0000..0000>
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    stateVecReal[index] = 0.0;
    stateVecImag[index] = 0.0;
    if (index==0){
        // zero state |0000..0000> has probability 1
        stateVecReal[0] = 1.0;
        stateVecImag[0] = 0.0;
    }
}
void statevec_multiControlledPhaseFlip (Qureg qureg, int * controlQubits, int numControlQubits)
Definition at line 1212 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by multiControlledPhaseFlip().
{
    int threadsPerCUDABlock, CUDABlocks;
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_multiControlledPhaseFlipKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, mask);
}
__global__ void statevec_multiControlledPhaseFlipKernel (Qureg qureg, long long int mask)
Definition at line 1194 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    long long int index;
    long long int stateVecSize;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    if (mask == (mask & index) ){
        stateVecReal [index] = - stateVecReal [index];
        stateVecImag [index] = - stateVecImag [index];
    }
}
void statevec_multiControlledPhaseShift (Qureg qureg, int * controlQubits, int numControlQubits, qreal angle)
Definition at line 1095 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by multiControlledPhaseShift().
{
    qreal cosAngle = cos(angle);
    qreal sinAngle = sin(angle);
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++)
        mask = mask | (1LL<<controlQubits[i]);
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk)/threadsPerCUDABlock);
    statevec_multiControlledPhaseShiftKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, mask, cosAngle, sinAngle);
}
__global__ void statevec_multiControlledPhaseShiftKernel (Qureg qureg, long long int mask, qreal cosAngle, qreal sinAngle)
Definition at line 1075 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    qreal stateRealLo, stateImagLo;
    long long int index;
    long long int stateVecSize;
    stateVecSize = qureg.numAmpsPerChunk;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    index = blockIdx.x*blockDim.x + threadIdx.x;
    if (index>=stateVecSize) return;
    if (mask == (mask & index) ){
        stateRealLo = stateVecReal[index];
        stateImagLo = stateVecImag[index];
        stateVecReal[index] = cosAngle*stateRealLo - sinAngle*stateImagLo;
        stateVecImag[index] = sinAngle*stateRealLo + cosAngle*stateImagLo;
    }
}
void statevec_multiControlledUnitary (Qureg qureg, int * controlQubits, int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Definition at line 843 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by multiControlledUnitary().
{
    int threadsPerCUDABlock, CUDABlocks;
    long long int mask=0;
    for (int i=0; i<numControlQubits; i++) mask = mask | (1LL<<controlQubits[i]);
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_multiControlledUnitaryKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, mask, targetQubit, u);
}
__global__ void statevec_multiControlledUnitaryKernel (Qureg qureg, long long int mask, const int targetQubit, ComplexMatrix2 u)
fix -- no necessary for GPU version
Definition at line 787 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Complex::imag, Qureg::numAmpsPerChunk, qreal, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, and Complex::real.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    if (mask == (mask & indexUp) ){
        // store current state vector values in temp variables
        stateRealUp = stateVecReal[indexUp];
        stateImagUp = stateVecImag[indexUp];
        stateRealLo = stateVecReal[indexLo];
        stateImagLo = stateVecImag[indexLo];
        // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
        stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
            + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
        stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
            + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
        // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
        stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
            + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
        stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
            + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
    }
}
void statevec_pauliX (Qureg qureg, const int targetQubit)
Definition at line 897 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by pauliX().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_pauliXKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit);
}
__global__ void statevec_pauliXKernel (Qureg qureg, const int targetQubit)
fix -- no necessary for GPU version
Definition at line 853 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,                             // storage for previous state values
           stateImagUp;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    // store current state vector values in temp variables
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    stateVecReal[indexUp] = stateVecReal[indexLo];
    stateVecImag[indexUp] = stateVecImag[indexLo];
    stateVecReal[indexLo] = stateRealUp;
    stateVecImag[indexLo] = stateImagUp;
}
void statevec_pauliY (Qureg qureg, const int targetQubit)
Definition at line 930 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by pauliY().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_pauliYKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit, 1);
}
void statevec_pauliYConj (Qureg qureg, const int targetQubit)
Definition at line 938 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by pauliY().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_pauliYKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit, -1);
}
__global__ void statevec_pauliYKernel (Qureg qureg, const int targetQubit, const int conjFac)
Definition at line 905 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    long long int sizeHalfBlock = 1LL << targetQubit;
    long long int sizeBlock     = 2LL * sizeHalfBlock;
    long long int numTasks      = qureg.numAmpsPerChunk >> 1;
    long long int thisTask      = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    long long int thisBlock     = thisTask / sizeHalfBlock;
    long long int indexUp       = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    long long int indexLo       = indexUp + sizeHalfBlock;
    qreal  stateRealUp, stateImagUp;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    // update under +-{{0, -i}, {i, 0}}
    stateVecReal[indexUp] = conjFac * stateVecImag[indexLo];
    stateVecImag[indexUp] = conjFac * -stateVecReal[indexLo];
    stateVecReal[indexLo] = conjFac * -stateImagUp;
    stateVecImag[indexLo] = conjFac * stateRealUp;
}
void statevec_phaseShiftByTerm (Qureg qureg, const int targetQubit, Complex term)
Definition at line 1028 of file QuEST_gpu.cu.
References Complex::imag, Qureg::numAmpsPerChunk, qreal, and Complex::real.
Referenced by statevec_pauliZ(), statevec_phaseShift(), statevec_sGate(), statevec_sGateConj(), statevec_tGate(), and statevec_tGateConj().
{
    qreal cosAngle = term.real;
    qreal sinAngle = term.imag;
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_phaseShiftByTermKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit, cosAngle, sinAngle);
}
__global__ void statevec_phaseShiftByTermKernel (Qureg qureg, const int targetQubit, qreal cosAngle, qreal sinAngle)
Definition at line 1000 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Qureg::numAmpsPerChunk, and qreal.
{
    long long int sizeBlock, sizeHalfBlock;
    long long int thisBlock, indexUp,indexLo;
    qreal stateRealLo, stateImagLo;
    long long int thisTask;
    const long long int numTasks = qureg.numAmpsPerChunk >> 1;
    sizeHalfBlock = 1LL << targetQubit;
    sizeBlock     = 2LL * sizeHalfBlock;
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    stateRealLo = stateVecReal[indexLo];
    stateImagLo = stateVecImag[indexLo];
    stateVecReal[indexLo] = cosAngle*stateRealLo - sinAngle*stateImagLo;
    stateVecImag[indexLo] = sinAngle*stateRealLo + cosAngle*stateImagLo;
}
void statevec_reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 305 of file QuEST_gpu.cu.
References Qureg::chunkId, copyStateFromGPU(), Qureg::numAmpsPerChunk, Qureg::numChunks, Qureg::numQubitsInStateVec, Qureg::stateVec, and syncQuESTEnv().
Referenced by reportStateToScreen().
{
    long long int index;
    int rank;
    copyStateFromGPU(qureg);
    if (qureg.numQubitsInStateVec<=5){
        for (rank=0; rank<qureg.numChunks; rank++){
            if (qureg.chunkId==rank){
                if (reportRank) {
                    printf("Reporting state from rank %d [\n", qureg.chunkId);
                    //printf("\trank, index, real, imag\n");
                    printf("real, imag\n");
                } else if (rank==0) {
                    printf("Reporting state [\n");
                    printf("real, imag\n");
                }
                for(index=0; index<qureg.numAmpsPerChunk; index++){
                    printf(REAL_STRING_FORMAT ", " REAL_STRING_FORMAT "\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
                }
                if (reportRank || rank==qureg.numChunks-1) printf("]\n");
            }
            syncQuESTEnv(env);
        }
    }
}
void statevec_setAmps (Qureg qureg, long long int startInd, qreal * reals, qreal * imags, long long int numAmps)
Definition at line 33 of file QuEST_gpu.cu.
References Qureg::deviceStateVec.
Referenced by initStateFromAmps(), and setAmps().
{
    cudaDeviceSynchronize();
    cudaMemcpy(
        qureg.deviceStateVec.real + startInd,
        reals,
        numAmps * sizeof(*(qureg.deviceStateVec.real)),
        cudaMemcpyHostToDevice);
    cudaMemcpy(
        qureg.deviceStateVec.imag + startInd,
        imags,
        numAmps * sizeof(*(qureg.deviceStateVec.real)),
        cudaMemcpyHostToDevice);
}
void statevec_unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Definition at line 713 of file QuEST_gpu.cu.
References Qureg::numAmpsPerChunk, and qreal.
Referenced by unitary().
{
    int threadsPerCUDABlock, CUDABlocks;
    threadsPerCUDABlock = 128;
    CUDABlocks = ceil((qreal)(qureg.numAmpsPerChunk>>1)/threadsPerCUDABlock);
    statevec_unitaryKernel<<<CUDABlocks, threadsPerCUDABlock>>>(qureg, targetQubit, u);
}
__global__ void statevec_unitaryKernel (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
fix -- no necessary for GPU version
Definition at line 660 of file QuEST_gpu.cu.
References Qureg::deviceStateVec, Complex::imag, Qureg::numAmpsPerChunk, qreal, ComplexMatrix2::r0c0, ComplexMatrix2::r0c1, ComplexMatrix2::r1c0, ComplexMatrix2::r1c1, and Complex::real.
{
    // ----- sizes
    long long int sizeBlock,                                           // size of blocks
         sizeHalfBlock;                                       // size of blocks halved
    // ----- indices
    long long int thisBlock,                                           // current block
         indexUp,indexLo;                                     // current index and corresponding index in lower half block
    // ----- temp variables
    qreal   stateRealUp,stateRealLo,                             // storage for previous state values
           stateImagUp,stateImagLo;                             // (used in updates)
    // ----- temp variables
    long long int thisTask;                                   // task based approach for expose loop with small granularity
    const long long int numTasks=qureg.numAmpsPerChunk>>1;
    sizeHalfBlock = 1LL << targetQubit;                               // size of blocks halved
    sizeBlock     = 2LL * sizeHalfBlock;                           // size of blocks
    // ---------------------------------------------------------------- //
    //            rotate                                                //
    // ---------------------------------------------------------------- //
    qreal *stateVecReal = qureg.deviceStateVec.real;
    qreal *stateVecImag = qureg.deviceStateVec.imag;
    thisTask = blockIdx.x*blockDim.x + threadIdx.x;
    if (thisTask>=numTasks) return;
    thisBlock   = thisTask / sizeHalfBlock;
    indexUp     = thisBlock*sizeBlock + thisTask%sizeHalfBlock;
    indexLo     = indexUp + sizeHalfBlock;
    // store current state vector values in temp variables
    stateRealUp = stateVecReal[indexUp];
    stateImagUp = stateVecImag[indexUp];
    stateRealLo = stateVecReal[indexLo];
    stateImagLo = stateVecImag[indexLo];
    // state[indexUp] = u00 * state[indexUp] + u01 * state[indexLo]
    stateVecReal[indexUp] = u.r0c0.real*stateRealUp - u.r0c0.imag*stateImagUp
        + u.r0c1.real*stateRealLo - u.r0c1.imag*stateImagLo;
    stateVecImag[indexUp] = u.r0c0.real*stateImagUp + u.r0c0.imag*stateRealUp
        + u.r0c1.real*stateImagLo + u.r0c1.imag*stateRealLo;
    // state[indexLo] = u10  * state[indexUp] + u11 * state[indexLo]
    stateVecReal[indexLo] = u.r1c0.real*stateRealUp  - u.r1c0.imag*stateImagUp
        + u.r1c1.real*stateRealLo  -  u.r1c1.imag*stateImagLo;
    stateVecImag[indexLo] = u.r1c0.real*stateImagUp + u.r1c0.imag*stateRealUp
        + u.r1c1.real*stateImagLo + u.r1c1.imag*stateRealLo;
}
void swapDouble (qreal ** a, qreal ** b)
Definition at line 1459 of file QuEST_gpu.cu.
References qreal.
Referenced by densmatr_calcFidelity(), densmatr_calcPurity(), densmatr_findProbabilityOfZero(), statevec_calcInnerProduct(), and statevec_findProbabilityOfZero().
{
    qreal *temp;
    temp = *a;
    *a = *b;
    *b = temp;
}
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode).
Parameters:
[in] env object representing the execution environment. A single instance is used for each program
Definition at line 249 of file QuEST_gpu.cu.
Referenced by statevec_initStateFromSingleFile(), and statevec_reportStateToScreen().
{
    cudaDeviceSynchronize();
}
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters:
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns:
1 if all processes succeeded, 0 if any one process failed
Definition at line 253 of file QuEST_gpu.cu.
{
    return successCode;
}