Quantum Exact Simulation Toolkit: QuEST_ops_mixed.h File Reference
QuEST_ops_mixed.h File Reference
Functions operating upon mixed states which are provided by a hardware-specific backend.
#include "QuEST.h"
#include "QuEST_precision.h"
Functions
REAL mixed_calcTotalProbability (QubitRegister qureg)
void mixed_initClassicalState (QubitRegister qureg, long long int stateInd)
void mixed_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
void mixed_initStatePlus (QubitRegister targetQureg)
Detailed Description
Functions operating upon mixed states which are provided by a hardware-specific backend.
Definition in file QuEST_ops_mixed.h.
Function Documentation
mixed_calcTotalProbability()
REAL mixed_calcTotalProbability (QubitRegister qureg)
Referenced by calcTotalProbability().
mixed_initClassicalState()
void mixed_initClassicalState (QubitRegister qureg, long long int stateInd)
Referenced by initClassicalState().
mixed_initPureState()
void mixed_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
Referenced by initPureState().
mixed_initStatePlus()
void mixed_initStatePlus (QubitRegister targetQureg)
Referenced by initStatePlus().