QuEST: QuEST_common.c File Reference
QuEST_common.c File Reference
#include "QuEST.h"
#include "QuEST_internal.h"
#include "QuEST_precision.h"
#include "QuEST_validation.h"
#include "QuEST_qasm.h"
#include "mt19937ar.h"
#include <unistd.h>
#include <sys/time.h>
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
Macros
#define M_PI 3.1415926535897932384626433832795028841971
#define macro_allocStackComplexMatrixN(matrix, numQubits)
#define macro_initialiseStackComplexMatrixN(matrix, numQubits, real, imag)
#define macro_populateKrausOperator(superOp, ops, numOps, opDim)
#define macro_setConjugateMatrix(dest, src, dim)
Functions
void agnostic_applyQFT (Qureg qureg, int *qubits, int numQubits)
void agnostic_applyTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order, int reps)
void applyExponentiatedPauliHamil (Qureg qureg, PauliHamil hamil, qreal fac, int reverse)
void applySymmetrizedTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order)
ComplexMatrixN bindArraysToStackComplexMatrixN (int numQubits, qreal re[][1<< numQubits], qreal im[][1<< numQubits], qreal **reStorage, qreal **imStorage)
void densmatr_applyKrausSuperoperator (Qureg qureg, int target, ComplexMatrix4 superOp)
void densmatr_applyMultiQubitKrausSuperoperator (Qureg qureg, int *targets, int numTargets, ComplexMatrixN superOp)
void densmatr_applyTwoQubitKrausSuperoperator (Qureg qureg, int target1, int target2, ComplexMatrixN superOp)
int densmatr_measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
void densmatr_mixKrausMap (Qureg qureg, int target, ComplexMatrix2 *ops, int numOps)
void densmatr_mixMultiQubitKrausMap (Qureg qureg, int *targets, int numTargets, ComplexMatrixN *ops, int numOps)
void densmatr_mixPauli (Qureg qureg, int qubit, qreal probX, qreal probY, qreal probZ)
void densmatr_mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 *ops, int numOps)
void ensureIndsIncrease (int *ind1, int *ind2)
int generateMeasurementOutcome (qreal zeroProb, qreal *outcomeProb)
void getComplexPairAndPhaseFromUnitary (ComplexMatrix2 u, Complex *alpha, Complex *beta, qreal *globalPhase)
maps U(r0c0, r0c1, r1c0, r1c1) to exp(i globalPhase) U(alpha, beta)
void getComplexPairFromRotation (qreal angle, Vector axis, Complex *alpha, Complex *beta)
ComplexMatrix2 getConjugateMatrix2 (ComplexMatrix2 src)
ComplexMatrix4 getConjugateMatrix4 (ComplexMatrix4 src)
Complex getConjugateScalar (Complex scalar)
long long int getControlFlipMask (int *controlQubits, int *controlState, int numControlQubits)
long long int getQubitBitMask (int *qubits, int numQubits)
void getQuESTDefaultSeedKey (unsigned long int *key)
Vector getUnitVector (Vector vec)
qreal getVectorMagnitude (Vector vec)
void getZYZRotAnglesFromComplexPair (Complex alpha, Complex beta, qreal *rz2, qreal *ry, qreal *rz1)
maps U(alpha, beta) to Rz(rz2) Ry(ry) Rz(rz1)
unsigned long int hashString (char *str)
void populateKrausSuperOperator2 (ComplexMatrix4 *superOp, ComplexMatrix2 *ops, int numOps)
void populateKrausSuperOperator4 (ComplexMatrixN *superOp, ComplexMatrix4 *ops, int numOps)
void populateKrausSuperOperatorN (ComplexMatrixN *superOp, ComplexMatrixN *ops, int numOps)
void reportQuregParams (Qureg qureg)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void reportState (Qureg qureg)
Print the current state vector of probability amplitudes for a set of qubits to file.
void setConjugateMatrixN (ComplexMatrixN m)
void shiftIndices (int *indices, int numIndices, int shift)
void shiftSubregIndices (int *allInds, int *numIndsPerReg, int numRegs, int shift)
void statevec_applyPauliProd (Qureg workspace, int *targetQubits, enum pauliOpType *pauliCodes, int numTargets)
void statevec_applyPauliSum (Qureg inQureg, enum pauliOpType *allCodes, qreal *termCoeffs, int numSumTerms, Qureg outQureg)
qreal statevec_calcExpecPauliProd (Qureg qureg, int *targetQubits, enum pauliOpType *pauliCodes, int numTargets, Qureg workspace)
qreal statevec_calcExpecPauliSum (Qureg qureg, enum pauliOpType *allCodes, qreal *termCoeffs, int numSumTerms, Qureg workspace)
qreal statevec_calcFidelity (Qureg qureg, Qureg pureState)
void statevec_controlledMultiQubitUnitary (Qureg qureg, int ctrl, int *targets, int numTargets, ComplexMatrixN u)
void statevec_controlledRotateAroundAxis (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
void statevec_controlledRotateAroundAxisConj (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
void statevec_controlledRotateX (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledRotateY (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledRotateZ (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
void statevec_controlledTwoQubitUnitary (Qureg qureg, int controlQubit, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
qreal statevec_getProbAmp (Qureg qureg, long long int index)
int statevec_measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
void statevec_multiControlledMultiRotatePauli (Qureg qureg, long long int ctrlMask, int *targetQubits, enum pauliOpType *targetPaulis, int numTargets, qreal angle, int applyConj)
void statevec_multiQubitUnitary (Qureg qureg, int *targets, int numTargets, ComplexMatrixN u)
void statevec_multiRotatePauli (Qureg qureg, int *targetQubits, enum pauliOpType *targetPaulis, int numTargets, qreal angle, int applyConj)
applyConj=1 will apply conjugate operation, else applyConj=0
void statevec_pauliZ (Qureg qureg, int targetQubit)
void statevec_phaseShift (Qureg qureg, int targetQubit, qreal angle)
void statevec_rotateAroundAxis (Qureg qureg, int rotQubit, qreal angle, Vector axis)
void statevec_rotateAroundAxisConj (Qureg qureg, int rotQubit, qreal angle, Vector axis)
void statevec_rotateX (Qureg qureg, int rotQubit, qreal angle)
void statevec_rotateY (Qureg qureg, int rotQubit, qreal angle)
void statevec_rotateZ (Qureg qureg, int rotQubit, qreal angle)
void statevec_sGate (Qureg qureg, int targetQubit)
void statevec_sGateConj (Qureg qureg, int targetQubit)
void statevec_sqrtSwapGate (Qureg qureg, int qb1, int qb2)
void statevec_sqrtSwapGateConj (Qureg qureg, int qb1, int qb2)
void statevec_tGate (Qureg qureg, int targetQubit)
void statevec_tGateConj (Qureg qureg, int targetQubit)
void statevec_twoQubitUnitary (Qureg qureg, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
Detailed Description
Internal and API functions which are hardware-agnostic. These must never call a front-end function in QuEST.c, which would lead to duplication of e.g. QASM logging and validation. Note that though many of these functions are prefixed with statevec_, they will be called multiple times to effect their equivalent operation on density matrices, so the passed Qureg can be assumed a statevector. Functions prefixed with densmatr_ may still explicitly call statevec_ functions, but will need to manually apply the conjugate qubit-shifted operations to satisfy the Choi–Jamiolkowski isomorphism
Author
Tyson Jones
Ania Brown (seeding, reporting)
Balint Koczor (Kraus maps, mixPauli, Windows compatibility)
Definition in file QuEST_common.c.
Macro Definition Documentation
M_PI
#define M_PI 3.1415926535897932384626433832795028841971
Definition at line 41 of file QuEST_common.c.
macro_allocStackComplexMatrixN
#define macro_allocStackComplexMatrixN (matrix, numQubits)
Value:
    /* reArr_, imArr_, reStorage_, and imStorage_ must not exist in calling scope */ \
    qreal reArr_[1<<(numQubits)][1<<(numQubits)]; \
    qreal imArr_[1<<(numQubits)][1<<(numQubits)]; \
    macro_initialiseStackComplexMatrixN(matrix, (numQubits), reArr_, imArr_);
Definition at line 675 of file QuEST_common.c.
macro_initialiseStackComplexMatrixN
#define macro_initialiseStackComplexMatrixN (matrix, numQubits, real, imag)
Value:
    /* reStorage_ and imStorage_ must not exist in calling scope */ \
    qreal* reStorage_[1<<(numQubits)]; \
    qreal* imStorage_[1<<(numQubits)]; \
    matrix = bindArraysToStackComplexMatrixN((numQubits), real, imag, reStorage_, imStorage_);
Definition at line 669 of file QuEST_common.c.
macro_populateKrausOperator
#define macro_populateKrausOperator (superOp, ops, numOps, opDim)
Value:
    /* clear the superop */ \
    for (int r=0; r < (opDim)*(opDim); r++) \
        for (int c=0; c < (opDim)*(opDim); c++) { \
            superOp->real[r][c] = 0; \
            superOp->imag[r][c] = 0; \
        } \
    /* add each op's contribution to the superop */ \
    for (int n=0; n<(numOps); n++) \
        /* superop += conjugate(op) (x) op, where (x) is a tensor product */ \
        for (int i = 0; i < (opDim); i++) \
            for (int j = 0; j < (opDim); j++) \
                        for (int k = 0; k < (opDim); k++) \
                    for (int l = 0; l < (opDim); l++) { \
                        superOp->real[i*(opDim) + k][j*(opDim) + l] += \
                            ops[n].real[i][j]*ops[n].real[k][l] + \
                            ops[n].imag[i][j]*ops[n].imag[k][l];  \
                                        superOp->imag[i*(opDim) + k][j*(opDim) + l] += \
                            ops[n].real[i][j]*ops[n].imag[k][l] - \
                            ops[n].imag[i][j]*ops[n].real[k][l];  \
                    }
Definition at line 585 of file QuEST_common.c.
macro_setConjugateMatrix
#define macro_setConjugateMatrix (dest, src, dim)
Value:
    for (int i=0; i<dim; i++) \
        for (int j=0; j<dim; j++) { \
            dest.real[i][j] =   src.real[i][j]; \
            dest.imag[i][j] = - src.imag[i][j]; /* negative for conjugate */ \
        }
Definition at line 99 of file QuEST_common.c.
Function Documentation
agnostic_applyQFT()
void agnostic_applyQFT (Qureg qureg, int * qubits, int numQubits)
Definition at line 849 of file QuEST_common.c.
{
     int densShift = qureg.numQubitsRepresented;
     // start with top/left-most qubit, work down
     for (int q=numQubits-1; q >= 0; q--) {
         // H
         statevec_hadamard(qureg, qubits[q]);
         if (qureg.isDensityMatrix)
             statevec_hadamard(qureg, qubits[q] + densShift);
         qasm_recordGate(qureg, GATE_HADAMARD, qubits[q]);
         if (q == 0)
             break;
         // succession of C-phases, control on qubits[q], targeting each of
         // qubits[q-1], qubits[q-1], ... qubits[0]. This can be expressed by
         // a single invocation of applyNamedPhaseFunc product
         int numRegs = 2;
         int numQubitsPerReg[2] = {q, 1};
         int regs[100]; // [q+1];
         for (int i=0; i<q+1; i++)
             regs[i] = qubits[i]; // qubits[q] is in own register
         int numParams = 1;
         qreal params[1] = { M_PI / (1 << q) };
         int conj = 0;
         statevec_applyParamNamedPhaseFuncOverrides(
             qureg, regs, numQubitsPerReg, numRegs,
             UNSIGNED, SCALED_PRODUCT, params, numParams,
             NULL, NULL, 0,
             conj);
         if (qureg.isDensityMatrix) {
             conj = 1;
             shiftSubregIndices(regs, numQubitsPerReg, numRegs, densShift);
             statevec_applyParamNamedPhaseFuncOverrides(
                 qureg, regs, numQubitsPerReg, numRegs,
                 UNSIGNED, SCALED_PRODUCT, params, numParams,
                 NULL, NULL, 0,
                 conj);
             shiftSubregIndices(regs, numQubitsPerReg, numRegs, - densShift);
         }
         qasm_recordNamedPhaseFunc(
             qureg, regs, numQubitsPerReg, numRegs,
             UNSIGNED, SCALED_PRODUCT, params, numParams,
             NULL, NULL, 0);
     }
     // final swaps
     for (int i=0; i<(numQubits/2); i++) {
         int qb1 = qubits[i];
         int qb2 = qubits[numQubits-i-1];
         statevec_swapQubitAmps(qureg, qb1, qb2);
         if (qureg.isDensityMatrix)
             statevec_swapQubitAmps(qureg, qb1 + densShift, qb2 + densShift);
         qasm_recordControlledGate(qureg, GATE_SWAP, qb1, qb2);
     }
 }
References GATE_HADAMARD, GATE_SWAP, Qureg::isDensityMatrix, M_PI, Qureg::numQubitsRepresented, qasm_recordControlledGate(), qasm_recordGate(), qasm_recordNamedPhaseFunc(), qreal, SCALED_PRODUCT, shiftSubregIndices(), statevec_applyParamNamedPhaseFuncOverrides(), statevec_hadamard(), statevec_swapQubitAmps(), and UNSIGNED.
Referenced by applyFullQFT(), and applyQFT().
agnostic_applyTrotterCircuit()
void agnostic_applyTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order, int reps)
Definition at line 840 of file QuEST_common.c.
{
     if (time == 0)
         return;
     for (int r=0; r<reps; r++)
         applySymmetrizedTrotterCircuit(qureg, hamil, time/reps, order);
 }
References applySymmetrizedTrotterCircuit().
Referenced by applyTrotterCircuit().
applyExponentiatedPauliHamil()
void applyExponentiatedPauliHamil (Qureg qureg, PauliHamil hamil, qreal fac, int reverse)
Definition at line 765 of file QuEST_common.c.
{
     /* applies a first-order one-repetition approximation of exp(-i fac H)
      * to qureg. Letting H = sum_j c_j h_j, it does this via
      * exp(-i fac H) ~ prod_j exp(-i fac c_j h_j), where each inner exp
      * is performed with multiRotatePauli (with pre-factor 2).
      */
     // prepare targets for multiRotatePauli
     // (all qubits; actual targets are determined by Pauli codes)
     int vecTargs[100]; // [hamil.numQubits];
     int densTargs[100]; // [hamil.numQubits];
     for (int q=0; q<hamil.numQubits; q++) {
         vecTargs[q] = q;
         densTargs[q] = q + hamil.numQubits;
     }
     for (int i=0; i<hamil.numSumTerms; i++) {
         int t=i;
         if (reverse)
             t=hamil.numSumTerms-1-i;
         qreal angle = 2*fac*hamil.termCoeffs[t];
         statevec_multiRotatePauli(
             qureg, vecTargs, &(hamil.pauliCodes[t*hamil.numQubits]),
             hamil.numQubits, angle, 0);
         if (qureg.isDensityMatrix)
             statevec_multiRotatePauli(
                 qureg, densTargs, &(hamil.pauliCodes[t*hamil.numQubits]),
                 hamil.numQubits, angle, 1);
         // record qasm
         char buff[1024];
         int b=0;
         for (int q=0; q<hamil.numQubits; q++) {
             enum pauliOpType op = hamil.pauliCodes[q + t*hamil.numQubits];
             char p = 'I';
             if (op == PAULI_X) p = 'X';
             if (op == PAULI_Y) p = 'Y';
             if (op == PAULI_Z) p = 'Z';
             buff[b++] = p;
             buff[b++] = ' ';
         }
         buff[b] = '\0';
         qasm_recordComment(qureg,
             "Here, a multiRotatePauli with angle %g and paulis %s was applied.",
             angle, buff);
     }
 }
References Qureg::isDensityMatrix, PauliHamil::numQubits, PauliHamil::numSumTerms, PAULI_X, PAULI_Y, PAULI_Z, PauliHamil::pauliCodes, qasm_recordComment(), qreal, statevec_multiRotatePauli(), and PauliHamil::termCoeffs.
Referenced by applySymmetrizedTrotterCircuit().
applySymmetrizedTrotterCircuit()
void applySymmetrizedTrotterCircuit (Qureg qureg, PauliHamil hamil, qreal time, int order)
Definition at line 820 of file QuEST_common.c.
{
     if (order == 1) {
         applyExponentiatedPauliHamil(qureg, hamil, time, 0);
     }
     else if (order == 2) {
         applyExponentiatedPauliHamil(qureg, hamil, time/2., 0);
         applyExponentiatedPauliHamil(qureg, hamil, time/2., 1);
     }
     else {
         qreal p = 1. / (4 - pow(4, 1./(order-1)));
         int lower = order-2;
         applySymmetrizedTrotterCircuit(qureg, hamil, p*time, lower);
         applySymmetrizedTrotterCircuit(qureg, hamil, p*time, lower);
         applySymmetrizedTrotterCircuit(qureg, hamil, (1-4*p)*time, lower);
         applySymmetrizedTrotterCircuit(qureg, hamil, p*time, lower);
         applySymmetrizedTrotterCircuit(qureg, hamil, p*time, lower);
     }
 }
References applyExponentiatedPauliHamil(), and qreal.
Referenced by agnostic_applyTrotterCircuit().
bindArraysToStackComplexMatrixN()
ComplexMatrixN bindArraysToStackComplexMatrixN (int numQubits, qreal re[][1<< numQubits], qreal im[][1<< numQubits], qreal ** reStorage, qreal ** imStorage)
Definition at line 652 of file QuEST_common.c.
   {
     ComplexMatrixN m;
     m.numQubits = numQubits;
     m.real = reStorage;
     m.imag = imStorage;
     int len = 1<<numQubits;
     for (int i=0; i<len; i++) {
         m.real[i] = re[i];
         m.imag[i] = im[i];
     }
     return m;
 }
References ComplexMatrixN::imag, ComplexMatrixN::numQubits, and ComplexMatrixN::real.
densmatr_applyKrausSuperoperator()
void densmatr_applyKrausSuperoperator (Qureg qureg, int target, ComplexMatrix4 superOp)
Definition at line 620 of file QuEST_common.c.
{
     long long int ctrlMask = 0;
     statevec_multiControlledTwoQubitUnitary(qureg, ctrlMask, target, target + qureg.numQubitsRepresented, superOp);
 }
References Qureg::numQubitsRepresented, and statevec_multiControlledTwoQubitUnitary().
Referenced by densmatr_mixKrausMap().
densmatr_applyMultiQubitKrausSuperoperator()
void densmatr_applyMultiQubitKrausSuperoperator (Qureg qureg, int * targets, int numTargets, ComplexMatrixN superOp)
Definition at line 634 of file QuEST_common.c.
{
     long long int ctrlMask = 0;
     int allTargets[200]; // [2*numTargets];
     for (int t=0; t < numTargets; t++) {
         allTargets[t] = targets[t];
         allTargets[t+numTargets] = targets[t] + qureg.numQubitsRepresented;
     }
     statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, allTargets, 2*numTargets, superOp);
 }
References Qureg::numQubitsRepresented, and statevec_multiControlledMultiQubitUnitary().
Referenced by densmatr_mixMultiQubitKrausMap().
densmatr_applyTwoQubitKrausSuperoperator()
void densmatr_applyTwoQubitKrausSuperoperator (Qureg qureg, int target1, int target2, ComplexMatrixN superOp)
Definition at line 626 of file QuEST_common.c.
{
     long long int ctrlMask = 0;
     int numQb = qureg.numQubitsRepresented;
     int allTargets[4] = {target1, target2, target1+numQb, target2+numQb};
     statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, allTargets, 4, superOp);
 }
References Qureg::numQubitsRepresented, and statevec_multiControlledMultiQubitUnitary().
Referenced by densmatr_mixTwoQubitKrausMap().
densmatr_measureWithStats()
int densmatr_measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Definition at line 372 of file QuEST_common.c.
{
     qreal zeroProb = densmatr_calcProbOfOutcome(qureg, measureQubit, 0);
     int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
     densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
     return outcome;
 }
References densmatr_calcProbOfOutcome(), densmatr_collapseToKnownProbOutcome(), generateMeasurementOutcome(), and qreal.
Referenced by measure(), and measureWithStats().
densmatr_mixKrausMap()
void densmatr_mixKrausMap (Qureg qureg, int target, ComplexMatrix2 * ops, int numOps)
Definition at line 644 of file QuEST_common.c.
{
     ComplexMatrix4 superOp;
     populateKrausSuperOperator2(&superOp, ops, numOps);
     densmatr_applyKrausSuperoperator(qureg, target, superOp);
 }
References densmatr_applyKrausSuperoperator(), and populateKrausSuperOperator2().
Referenced by densmatr_mixPauli(), and mixKrausMap().
densmatr_mixMultiQubitKrausMap()
void densmatr_mixMultiQubitKrausMap (Qureg qureg, int * targets, int numTargets, ComplexMatrixN * ops, int numOps)
Definition at line 701 of file QuEST_common.c.
{
     ComplexMatrixN superOp;
     /* superOp will contain 2^(4 numTargets) complex numbers.
      * At double precision, superOp will cost additional memory:
      * numTargs=1   ->   0.25 KiB
      * numTargs=2   ->   4 KiB
      * numTargs=3   ->   64 KiB
      * numTargs=4   ->   1 MiB
      * numTargs=5   ->   16 MiB.
      * At quad precision (usually 10 B per number, but possibly 16 B due to alignment),
      * this costs at most double.
      *
      * Hence, if superOp is kept in the stack, numTargs >= 4 would exceed Windows' 1 MB
      * maximum stack-space allocation (numTargs >= 5 exceeding Linux' 8 MB). Therefore,
      * for numTargets < 4, superOp will be kept in the stack, else in the heap
      */
      // if NOT on Windows, allocate ComplexN on stack depending on size
      #ifndef _WIN32
          if (numTargets < 4) {
              // everything must live in 'if' since this macro declares local vars
              macro_allocStackComplexMatrixN(superOp, 2*numTargets);
              populateKrausSuperOperatorN(&superOp, ops, numOps);
              densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
          }
          else {
              superOp = createComplexMatrixN(2*numTargets);
              populateKrausSuperOperatorN(&superOp, ops, numOps);
              densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
              destroyComplexMatrixN(superOp);
          }
      // on Windows, we must always create in heap
      #else
          superOp = createComplexMatrixN(2*numTargets);
          populateKrausSuperOperatorN(&superOp, ops, numOps);
          densmatr_applyMultiQubitKrausSuperoperator(qureg, targets, numTargets, superOp);
          destroyComplexMatrixN(superOp);
      #endif
 }
References createComplexMatrixN(), densmatr_applyMultiQubitKrausSuperoperator(), destroyComplexMatrixN(), macro_allocStackComplexMatrixN, and populateKrausSuperOperatorN().
Referenced by mixMultiQubitKrausMap().
densmatr_mixPauli()
void densmatr_mixPauli (Qureg qureg, int qubit, qreal probX, qreal probY, qreal probZ)
Definition at line 743 of file QuEST_common.c.
{
     // convert pauli probabilities into Kraus map
     const int numOps = 4;
     ComplexMatrix2 ops[4]; // [numOps];
     for (int n=0; n < numOps; n++)
         ops[n] = (ComplexMatrix2) {.real={{0}}, .imag={{0}}};
     qreal facs[4] = { // literal numOps=4 for valid initialisation
                 sqrt(1-(probX + probY + probZ)),
                 sqrt(probX),
                 sqrt(probY),
                 sqrt(probZ)
         };
     ops[0].real[0][0] =  facs[0]; ops[0].real[1][1] =  facs[0];
     ops[1].real[0][1] =  facs[1]; ops[1].real[1][0] =  facs[1];
     ops[2].imag[0][1] = -facs[2]; ops[2].imag[1][0] =  facs[2];
     ops[3].real[0][0] =  facs[3]; ops[3].real[1][1] = -facs[3];
     densmatr_mixKrausMap(qureg, qubit, ops, numOps);
 }
References densmatr_mixKrausMap(), ComplexMatrix2::imag, qreal, and ComplexMatrix2::real.
Referenced by mixPauli().
densmatr_mixTwoQubitKrausMap()
void densmatr_mixTwoQubitKrausMap (Qureg qureg, int target1, int target2, ComplexMatrix4 * ops, int numOps)
Definition at line 682 of file QuEST_common.c.
{
   // if NOT on Windows, allocate ComplexN on stack
   #ifndef _WIN32
       ComplexMatrixN superOp;
       macro_allocStackComplexMatrixN(superOp, 4);
       populateKrausSuperOperator4(&superOp, ops, numOps);
       densmatr_applyTwoQubitKrausSuperoperator(qureg, target1, target2, superOp);
   // but on Windows, we MUST allocated dynamically
   #else
       ComplexMatrixN superOp = createComplexMatrixN(4);
       populateKrausSuperOperator4(&superOp, ops, numOps);
       densmatr_applyTwoQubitKrausSuperoperator(qureg, target1, target2, superOp);
       destroyComplexMatrixN(superOp);
   #endif
 }
References createComplexMatrixN(), densmatr_applyTwoQubitKrausSuperoperator(), destroyComplexMatrixN(), macro_allocStackComplexMatrixN, and populateKrausSuperOperator4().
Referenced by mixTwoQubitKrausMap().
ensureIndsIncrease()
void ensureIndsIncrease (int * ind1, int * ind2)
Definition at line 70 of file QuEST_common.c.
{
     if (*ind1 > *ind2) {
         int copy = *ind1;
         *ind1 = *ind2;
         *ind2 = copy;
     }
 }
Referenced by mixTwoQubitDephasing(), and mixTwoQubitDepolarising().
generateMeasurementOutcome()
int generateMeasurementOutcome (qreal zeroProb, qreal * outcomeProb)
Definition at line 168 of file QuEST_common.c.
{
     // randomly choose outcome
     int outcome;
     if (zeroProb < REAL_EPS)
         outcome = 1;
     else if (1-zeroProb < REAL_EPS)
         outcome = 0;
     else
         outcome = (genrand_real1() > zeroProb);
     // set probability of outcome
     *outcomeProb = (outcome==0)? zeroProb : 1-zeroProb;
     return outcome;
 }
References genrand_real1().
Referenced by densmatr_measureWithStats(), and statevec_measureWithStats().
getComplexPairAndPhaseFromUnitary()
void getComplexPairAndPhaseFromUnitary (ComplexMatrix2 u, Complex * alpha, Complex * beta, qreal * globalPhase)
maps U(r0c0, r0c1, r1c0, r1c1) to exp(i globalPhase) U(alpha, beta)
Definition at line 142 of file QuEST_common.c.
{
     qreal r0c0Phase = atan2(u.imag[0][0], u.real[0][0]);
     qreal r1c1Phase = atan2(u.imag[1][1], u.real[1][1]);
     *globalPhase = (r0c0Phase + r1c1Phase)/2.0;
     qreal cosPhase = cos(*globalPhase);
     qreal sinPhase = sin(*globalPhase);
     alpha->real = u.real[0][0]*cosPhase + u.imag[0][0]*sinPhase;
     alpha->imag = u.imag[0][0]*cosPhase - u.real[0][0]*sinPhase;
     beta->real  = u.real[1][0]*cosPhase + u.imag[1][0]*sinPhase;
     beta->imag  = u.imag[1][0]*cosPhase - u.real[1][0]*sinPhase;
 }
References Complex::imag, ComplexMatrix2::imag, qreal, Complex::real, and ComplexMatrix2::real.
Referenced by qasm_recordControlledUnitary(), qasm_recordMultiControlledUnitary(), and qasm_recordUnitary().
getComplexPairFromRotation()
void getComplexPairFromRotation (qreal angle, Vector axis, Complex * alpha, Complex * beta)
Definition at line 120 of file QuEST_common.c.
{
     Vector unitAxis = getUnitVector(axis);
     alpha->real =   cos(angle/2.0);
     alpha->imag = - sin(angle/2.0)*unitAxis.z;
     beta->real  =   sin(angle/2.0)*unitAxis.y;
     beta->imag  = - sin(angle/2.0)*unitAxis.x;
 }
References getUnitVector(), Complex::imag, Complex::real, Vector::x, Vector::y, and Vector::z.
Referenced by qasm_recordAxisRotation(), qasm_recordControlledAxisRotation(), statevec_controlledRotateAroundAxis(), statevec_controlledRotateAroundAxisConj(), statevec_rotateAroundAxis(), and statevec_rotateAroundAxisConj().
getConjugateMatrix2()
ComplexMatrix2 getConjugateMatrix2 (ComplexMatrix2 src)
Definition at line 105 of file QuEST_common.c.
{
     ComplexMatrix2 conj;
     macro_setConjugateMatrix(conj, src, 2);
     return conj;
 }
References macro_setConjugateMatrix.
Referenced by controlledUnitary(), multiControlledUnitary(), multiStateControlledUnitary(), and unitary().
getConjugateMatrix4()
ComplexMatrix4 getConjugateMatrix4 (ComplexMatrix4 src)
Definition at line 110 of file QuEST_common.c.
{
     ComplexMatrix4 conj;
     macro_setConjugateMatrix(conj, src, 4);
     return conj;
 }
References macro_setConjugateMatrix.
Referenced by controlledTwoQubitUnitary(), multiControlledTwoQubitUnitary(), and twoQubitUnitary().
getConjugateScalar()
Complex getConjugateScalar (Complex scalar)
Definition at line 91 of file QuEST_common.c.
{
     Complex conjScalar;
     conjScalar.real =   scalar.real;
     conjScalar.imag = - scalar.imag;
     return conjScalar;
 }
References Complex::imag, and Complex::real.
Referenced by compactUnitary(), and controlledCompactUnitary().
getControlFlipMask()
long long int getControlFlipMask (int * controlQubits, int * controlState, int numControlQubits)
Definition at line 60 of file QuEST_common.c.
{
     long long int mask=0;
     for (int i=0; i<numControlQubits; i++)
         if (controlState[i] == 0)
             mask = mask | (1LL << controlQubits[i]);
     return mask;
 }
Referenced by multiStateControlledUnitary().
getQubitBitMask()
long long int getQubitBitMask (int * qubits, int numQubits)
Definition at line 50 of file QuEST_common.c.
{
     long long int mask=0;
     for (int i=0; i<numQubits; i++)
         mask = mask | (1LL << qubits[i]);
     return mask;
 }
Referenced by applyMultiControlledMatrixN(), multiControlledMultiQubitNot(), multiControlledMultiQubitUnitary(), multiControlledMultiRotatePauli(), multiControlledMultiRotateZ(), multiControlledTwoQubitUnitary(), multiControlledUnitary(), multiQubitNot(), multiRotateZ(), multiStateControlledUnitary(), statevec_multiControlledMultiQubitUnitary(), statevec_multiControlledMultiRotatePauli(), statevec_multiControlledPhaseFlip(), statevec_multiControlledPhaseShift(), statevec_multiRotatePauli(), and validateMultiControlsMultiTargets().
getQuESTDefaultSeedKey()
void getQuESTDefaultSeedKey (unsigned long int * key)
Definition at line 195 of file QuEST_common.c.
{
     // init MT random number generator with two keys -- time and pid
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
 #if defined(_WIN32) && ! defined(__MINGW32__)
     unsigned long int pid = (unsigned long int) _getpid();
     unsigned long int msecs = (unsigned long int) GetTickCount64();
     key[0] = msecs; key[1] = pid;
 #else
     struct timeval  tv;
     gettimeofday(&tv, NULL);
     double time_in_mill =
         (tv.tv_sec) * 1000 + (tv.tv_usec) / 1000 ; // convert tv_sec & tv_usec to millisecond
     unsigned long int pid = getpid();
     unsigned long int msecs = (unsigned long int) time_in_mill;
     key[0] = msecs; key[1] = pid;
 #endif
 }
Referenced by seedQuESTDefault().
getUnitVector()
Vector getUnitVector (Vector vec)
Definition at line 84 of file QuEST_common.c.
{
     qreal mag = getVectorMagnitude(vec);
     Vector unitVec = (Vector) {.x=vec.x/mag, .y=vec.y/mag, .z=vec.z/mag};
     return unitVec;
 }
References getVectorMagnitude(), qreal, Vector::x, Vector::y, and Vector::z.
Referenced by getComplexPairFromRotation().
getVectorMagnitude()
qreal getVectorMagnitude (Vector vec)
Definition at line 79 of file QuEST_common.c.
{
     return sqrt(vec.x*vec.x + vec.y*vec.y + vec.z*vec.z);
 }
References Vector::x, Vector::y, and Vector::z.
Referenced by getUnitVector(), and validateVector().
getZYZRotAnglesFromComplexPair()
void getZYZRotAnglesFromComplexPair (Complex alpha, Complex beta, qreal * rz2, qreal * ry, qreal * rz1)
maps U(alpha, beta) to Rz(rz2) Ry(ry) Rz(rz1)
Definition at line 130 of file QuEST_common.c.
{
     qreal alphaMag = sqrt(alpha.real*alpha.real + alpha.imag*alpha.imag);
     *ry = 2.0 * acos(alphaMag);
     qreal alphaPhase = atan2(alpha.imag, alpha.real);
     qreal betaPhase  = atan2(beta.imag,  beta.real);
     *rz2 = - alphaPhase + betaPhase;
     *rz1 = - alphaPhase - betaPhase;
 }
References Complex::imag, qreal, and Complex::real.
Referenced by qasm_recordAxisRotation(), qasm_recordCompactUnitary(), qasm_recordControlledAxisRotation(), qasm_recordControlledCompactUnitary(), qasm_recordControlledUnitary(), qasm_recordMultiControlledUnitary(), and qasm_recordUnitary().
hashString()
unsigned long int hashString (char * str)
Definition at line 185 of file QuEST_common.c.
{
     unsigned long int hash = 5381;
     int c;
     while ((c = *str++))
         hash = ((hash << 5) + hash) + c; /* hash * 33 + c */
     return hash;
 }
populateKrausSuperOperator2()
void populateKrausSuperOperator2 (ComplexMatrix4 * superOp, ComplexMatrix2 * ops, int numOps)
Definition at line 607 of file QuEST_common.c.
{
     int opDim = 2;
     macro_populateKrausOperator(superOp, ops, numOps, opDim);
 }
References macro_populateKrausOperator.
Referenced by densmatr_mixKrausMap().
populateKrausSuperOperator4()
void populateKrausSuperOperator4 (ComplexMatrixN * superOp, ComplexMatrix4 * ops, int numOps)
Definition at line 611 of file QuEST_common.c.
{
     int opDim = 4;
     macro_populateKrausOperator(superOp, ops, numOps, opDim);
 }
References macro_populateKrausOperator.
Referenced by densmatr_mixTwoQubitKrausMap().
populateKrausSuperOperatorN()
void populateKrausSuperOperatorN (ComplexMatrixN * superOp, ComplexMatrixN * ops, int numOps)
Definition at line 615 of file QuEST_common.c.
{
     int opDim = 1 << ops[0].numQubits;
     macro_populateKrausOperator(superOp, ops, numOps, opDim);
 }
References macro_populateKrausOperator, and ComplexMatrixN::numQubits.
Referenced by densmatr_mixMultiQubitKrausMap().
setConjugateMatrixN()
void setConjugateMatrixN (ComplexMatrixN m)
Definition at line 115 of file QuEST_common.c.
{
     int len = 1 << m.numQubits;
     macro_setConjugateMatrix(m, m, len);
 }
References macro_setConjugateMatrix, and ComplexMatrixN::numQubits.
Referenced by controlledMultiQubitUnitary(), multiControlledMultiQubitUnitary(), and multiQubitUnitary().
shiftIndices()
void shiftIndices (int * indices, int numIndices, int shift)
Definition at line 156 of file QuEST_common.c.
{
     for (int j=0; j < numIndices; j++)
         indices[j] += shift;
 }
Referenced by applyPhaseFunc(), applyPhaseFuncOverrides(), controlledMultiQubitUnitary(), multiControlledMultiQubitUnitary(), multiControlledMultiRotatePauli(), multiControlledPhaseFlip(), multiControlledPhaseShift(), multiQubitUnitary(), and multiRotatePauli().
shiftSubregIndices()
void shiftSubregIndices (int * allInds, int * numIndsPerReg, int numRegs, int shift)
Definition at line 161 of file QuEST_common.c.
{
     int i=0;
     for (int r=0; r<numRegs; r++)
         for (int j=0; j<numIndsPerReg[r]; j++)
             allInds[i++] += shift;
 }
Referenced by agnostic_applyQFT(), applyMultiVarPhaseFunc(), applyMultiVarPhaseFuncOverrides(), applyNamedPhaseFunc(), applyNamedPhaseFuncOverrides(), applyParamNamedPhaseFunc(), and applyParamNamedPhaseFuncOverrides().
statevec_applyPauliProd()
void statevec_applyPauliProd (Qureg workspace, int * targetQubits, enum pauliOpType * pauliCodes, int numTargets)
Definition at line 495 of file QuEST_common.c.
{
     for (int i=0; i < numTargets; i++) {
         // (pauliCodes[i] == PAULI_I) applies no operation
         if (pauliCodes[i] == PAULI_X)
             statevec_pauliX(workspace, targetQubits[i]);
         if (pauliCodes[i] == PAULI_Y)
             statevec_pauliY(workspace, targetQubits[i]);
         if (pauliCodes[i] == PAULI_Z)
             statevec_pauliZ(workspace, targetQubits[i]);
     }
 }
References PAULI_X, PAULI_Y, PAULI_Z, statevec_pauliX(), statevec_pauliY(), and statevec_pauliZ().
Referenced by statevec_applyPauliSum(), and statevec_calcExpecPauliProd().
statevec_applyPauliSum()
void statevec_applyPauliSum (Qureg inQureg, enum pauliOpType * allCodes, qreal * termCoeffs, int numSumTerms, Qureg outQureg)
Definition at line 538 of file QuEST_common.c.
{
     int numQb = inQureg.numQubitsRepresented;
     int targs[100]; // [numQb];
     for (int q=0; q < numQb; q++)
         targs[q] = q;
     statevec_initBlankState(outQureg);
     for (int t=0; t < numSumTerms; t++) {
         Complex coef = (Complex) {.real=termCoeffs[t], .imag=0};
         Complex iden = (Complex) {.real=1, .imag=0};
         Complex zero = (Complex) {.real=0, .imag=0};
         // outQureg += coef paulis(inQureg)
         statevec_applyPauliProd(inQureg, targs, &allCodes[t*numQb], numQb);
         statevec_setWeightedQureg(coef, inQureg, iden, outQureg, zero, outQureg);
         // undero paulis(inQureg), exploiting XX=YY=ZZ=I
         statevec_applyPauliProd(inQureg, targs, &allCodes[t*numQb], numQb);
     }
 }
References Qureg::numQubitsRepresented, Complex::real, statevec_applyPauliProd(), statevec_initBlankState(), and statevec_setWeightedQureg().
Referenced by applyPauliHamil(), and applyPauliSum().
statevec_calcExpecPauliProd()
qreal statevec_calcExpecPauliProd (Qureg qureg, int * targetQubits, enum pauliOpType * pauliCodes, int numTargets, Qureg workspace)
Definition at line 509 of file QuEST_common.c.
{
     statevec_cloneQureg(workspace, qureg);
     statevec_applyPauliProd(workspace, targetQubits, pauliCodes, numTargets);
     // compute the expected value
     qreal value;
     if (qureg.isDensityMatrix)
         value = densmatr_calcTotalProb(workspace); // Trace(ops qureg)
     else
         value = statevec_calcInnerProduct(workspace, qureg).real; // <qureg|ops|qureg>
     return value;
 }
References densmatr_calcTotalProb(), Qureg::isDensityMatrix, qreal, Complex::real, statevec_applyPauliProd(), statevec_calcInnerProduct(), and statevec_cloneQureg().
Referenced by calcExpecPauliProd(), and statevec_calcExpecPauliSum().
statevec_calcExpecPauliSum()
qreal statevec_calcExpecPauliSum (Qureg qureg, enum pauliOpType * allCodes, qreal * termCoeffs, int numSumTerms, Qureg workspace)
Definition at line 524 of file QuEST_common.c.
{
     int numQb = qureg.numQubitsRepresented;
     int targs[100]; // [numQb];
     for (int q=0; q < numQb; q++)
         targs[q] = q;
     qreal value = 0;
     for (int t=0; t < numSumTerms; t++)
         value += termCoeffs[t] * statevec_calcExpecPauliProd(qureg, targs, &allCodes[t*numQb], numQb, workspace);
     return value;
 }
References Qureg::numQubitsRepresented, qreal, and statevec_calcExpecPauliProd().
Referenced by calcExpecPauliHamil(), and calcExpecPauliSum().
statevec_calcFidelity()
qreal statevec_calcFidelity (Qureg qureg, Qureg pureState)
Definition at line 380 of file QuEST_common.c.
{
     Complex innerProd = statevec_calcInnerProduct(qureg, pureState);
     qreal innerProdMag = innerProd.real*innerProd.real + innerProd.imag*innerProd.imag;
     return innerProdMag;
 }
References Complex::imag, qreal, Complex::real, and statevec_calcInnerProduct().
Referenced by calcFidelity().
statevec_controlledMultiQubitUnitary()
void statevec_controlledMultiQubitUnitary (Qureg qureg, int ctrl, int * targets, int numTargets, ComplexMatrixN u)
Definition at line 579 of file QuEST_common.c.
{
     long long int ctrlMask = 1LL << ctrl;
     statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, targets, numTargets, u);
 }
References statevec_multiControlledMultiQubitUnitary().
Referenced by controlledMultiQubitUnitary().
statevec_controlledRotateAroundAxis()
void statevec_controlledRotateAroundAxis (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
Definition at line 330 of file QuEST_common.c.
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
References getComplexPairFromRotation(), and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis(), statevec_controlledRotateX(), statevec_controlledRotateY(), and statevec_controlledRotateZ().
statevec_controlledRotateAroundAxisConj()
void statevec_controlledRotateAroundAxisConj (Qureg qureg, int controlQubit, int targetQubit, qreal angle, Vector axis)
Definition at line 337 of file QuEST_common.c.
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     alpha.imag *= -1;
     beta.imag *= -1;
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
References getComplexPairFromRotation(), Complex::imag, and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis().
statevec_controlledRotateX()
void statevec_controlledRotateX (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 346 of file QuEST_common.c.
{
     Vector unitAxis = {1, 0, 0};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateX().
statevec_controlledRotateY()
void statevec_controlledRotateY (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 352 of file QuEST_common.c.
{
     Vector unitAxis = {0, 1, 0};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateY().
statevec_controlledRotateZ()
void statevec_controlledRotateZ (Qureg qureg, int controlQubit, int targetQubit, qreal angle)
Definition at line 358 of file QuEST_common.c.
{
     Vector unitAxis = {0, 0, 1};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateZ().
statevec_controlledTwoQubitUnitary()
void statevec_controlledTwoQubitUnitary (Qureg qureg, int controlQubit, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
Definition at line 567 of file QuEST_common.c.
{
     long long int ctrlMask = 1LL << controlQubit;
     statevec_multiControlledTwoQubitUnitary(qureg, ctrlMask, targetQubit1, targetQubit2, u);
 }
References statevec_multiControlledTwoQubitUnitary().
Referenced by controlledTwoQubitUnitary().
statevec_getProbAmp()
qreal statevec_getProbAmp (Qureg qureg, long long int index)
Definition at line 248 of file QuEST_common.c.
{
     qreal real = statevec_getRealAmp(qureg, index);
     qreal imag = statevec_getImagAmp(qureg, index);
     return real*real + imag*imag;
 }
References qreal, statevec_getImagAmp(), and statevec_getRealAmp().
Referenced by getProbAmp().
statevec_measureWithStats()
int statevec_measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Definition at line 364 of file QuEST_common.c.
{
     qreal zeroProb = statevec_calcProbOfOutcome(qureg, measureQubit, 0);
     int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
     statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
     return outcome;
 }
References generateMeasurementOutcome(), qreal, statevec_calcProbOfOutcome(), and statevec_collapseToKnownProbOutcome().
Referenced by measure(), and measureWithStats().
statevec_multiControlledMultiRotatePauli()
void statevec_multiControlledMultiRotatePauli (Qureg qureg, long long int ctrlMask, int * targetQubits, enum pauliOpType * targetPaulis, int numTargets, qreal angle, int applyConj)
Definition at line 453 of file QuEST_common.c.
   {
     qreal fac = 1/sqrt(2);
     qreal sgn = (applyConj)? 1 : -1;
     ComplexMatrix2 uRx = {.real={{fac,0},{0,fac}}, .imag={{0,sgn*fac},{sgn*fac,0}}}; // Rx(pi/2)* rotates Z -> Y
     ComplexMatrix2 uRy = {.real={{fac,fac},{-fac,fac}}, .imag={{0,0},{0,0}}};        // Ry(-pi/2) rotates Z -> X
     // this function is controlled on the all-one state, so no ctrl flips
     long long int ctrlFlipMask = 0;
     // mask may be modified to remove superfluous Identity ops
     long long int targMask = getQubitBitMask(targetQubits, numTargets);
     // rotate basis so that exp(Z) will effect exp(Y) and exp(X)
     for (int t=0; t < numTargets; t++) {
         if (targetPaulis[t] == PAULI_I)
             targMask -= 1LL << targetQubits[t]; // remove target from mask
         if (targetPaulis[t] == PAULI_X)
             statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRy);
         if (targetPaulis[t] == PAULI_Y)
             statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRx);
         // (targetPaulis[t] == 3) is Z basis
     }
     // does nothing if there are no qubits to 'rotate'
     if (targMask != 0)
         statevec_multiControlledMultiRotateZ(qureg, ctrlMask, targMask, (applyConj)? -angle : angle);
     // undo X and Y basis rotations
     uRx.imag[0][1] *= -1; uRx.imag[1][0] *= -1;
     uRy.real[0][1] *= -1; uRy.real[1][0] *= -1;
     for (int t=0; t < numTargets; t++) {
         if (targetPaulis[t] == PAULI_X)
             statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRy);
         if (targetPaulis[t] == PAULI_Y)
             statevec_multiControlledUnitary(qureg, ctrlMask, ctrlFlipMask, targetQubits[t], uRx);
     }
 }
References getQubitBitMask(), ComplexMatrix2::imag, PAULI_I, PAULI_X, PAULI_Y, qreal, ComplexMatrix2::real, statevec_multiControlledMultiRotateZ(), and statevec_multiControlledUnitary().
Referenced by multiControlledMultiRotatePauli().
statevec_multiQubitUnitary()
void statevec_multiQubitUnitary (Qureg qureg, int * targets, int numTargets, ComplexMatrixN u)
Definition at line 573 of file QuEST_common.c.
{
     long long int ctrlMask = 0;
     statevec_multiControlledMultiQubitUnitary(qureg, ctrlMask, targets, numTargets, u);
 }
References statevec_multiControlledMultiQubitUnitary().
Referenced by applyMatrixN(), and multiQubitUnitary().
statevec_multiRotatePauli()
void statevec_multiRotatePauli (Qureg qureg, int * targetQubits, enum pauliOpType * targetPaulis, int numTargets, qreal angle, int applyConj)
applyConj=1 will apply conjugate operation, else applyConj=0
Definition at line 414 of file QuEST_common.c.
   {
     qreal fac = 1/sqrt(2);
     Complex uRxAlpha = {.real = fac, .imag = 0}; // Rx(pi/2)* rotates Z -> Y
     Complex uRxBeta = {.real = 0, .imag = (applyConj)? fac : -fac};
     Complex uRyAlpha = {.real = fac, .imag = 0}; // Ry(-pi/2) rotates Z -> X
     Complex uRyBeta = {.real = -fac, .imag = 0};
     // mask may be modified to remove superfluous Identity ops
     long long int mask = getQubitBitMask(targetQubits, numTargets);
     // rotate basis so that exp(Z) will effect exp(Y) and exp(X)
     for (int t=0; t < numTargets; t++) {
         if (targetPaulis[t] == PAULI_I)
             mask -= 1LL << targetQubits[t]; // remove target from mask
         if (targetPaulis[t] == PAULI_X)
             statevec_compactUnitary(qureg, targetQubits[t], uRyAlpha, uRyBeta);
         if (targetPaulis[t] == PAULI_Y)
             statevec_compactUnitary(qureg, targetQubits[t], uRxAlpha, uRxBeta);
         // (targetPaulis[t] == 3) is Z basis
     }
     // does nothing if there are no qubits to 'rotate'
     if (mask != 0)
         statevec_multiRotateZ(qureg, mask, (applyConj)? -angle : angle);
     // undo X and Y basis rotations
     uRxBeta.imag *= -1;
     uRyBeta.real *= -1;
     for (int t=0; t < numTargets; t++) {
         if (targetPaulis[t] == PAULI_X)
             statevec_compactUnitary(qureg, targetQubits[t], uRyAlpha, uRyBeta);
         if (targetPaulis[t] == PAULI_Y)
             statevec_compactUnitary(qureg, targetQubits[t], uRxAlpha, uRxBeta);
     }
 }
References getQubitBitMask(), Complex::imag, PAULI_I, PAULI_X, PAULI_Y, qreal, Complex::real, statevec_compactUnitary(), and statevec_multiRotateZ().
Referenced by applyExponentiatedPauliHamil(), and multiRotatePauli().
statevec_pauliZ()
void statevec_pauliZ (Qureg qureg, int targetQubit)
Definition at line 261 of file QuEST_common.c.
{
     Complex term;
     term.real = -1;
     term.imag =  0;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by pauliZ(), and statevec_applyPauliProd().
statevec_phaseShift()
void statevec_phaseShift (Qureg qureg, int targetQubit, qreal angle)
Definition at line 254 of file QuEST_common.c.
{
     Complex term;
     term.real = cos(angle);
     term.imag = sin(angle);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by phaseShift().
statevec_rotateAroundAxis()
void statevec_rotateAroundAxis (Qureg qureg, int rotQubit, qreal angle, Vector axis)
Definition at line 314 of file QuEST_common.c.
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     statevec_compactUnitary(qureg, rotQubit, alpha, beta);
 }
References getComplexPairFromRotation(), and statevec_compactUnitary().
Referenced by rotateAroundAxis(), statevec_rotateX(), statevec_rotateY(), and statevec_rotateZ().
statevec_rotateAroundAxisConj()
void statevec_rotateAroundAxisConj (Qureg qureg, int rotQubit, qreal angle, Vector axis)
Definition at line 321 of file QuEST_common.c.
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     alpha.imag *= -1;
     beta.imag *= -1;
     statevec_compactUnitary(qureg, rotQubit, alpha, beta);
 }
References getComplexPairFromRotation(), Complex::imag, and statevec_compactUnitary().
Referenced by rotateAroundAxis().
statevec_rotateX()
void statevec_rotateX (Qureg qureg, int rotQubit, qreal angle)
Definition at line 296 of file QuEST_common.c.
{
     Vector unitAxis = {1, 0, 0};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
References statevec_rotateAroundAxis().
Referenced by rotateX().
statevec_rotateY()
void statevec_rotateY (Qureg qureg, int rotQubit, qreal angle)
Definition at line 302 of file QuEST_common.c.
{
     Vector unitAxis = {0, 1, 0};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
References statevec_rotateAroundAxis().
Referenced by rotateY().
statevec_rotateZ()
void statevec_rotateZ (Qureg qureg, int rotQubit, qreal angle)
Definition at line 308 of file QuEST_common.c.
{
     Vector unitAxis = {0, 0, 1};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
References statevec_rotateAroundAxis().
Referenced by rotateZ().
statevec_sGate()
void statevec_sGate (Qureg qureg, int targetQubit)
Definition at line 268 of file QuEST_common.c.
{
     Complex term;
     term.real = 0;
     term.imag = 1;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
statevec_sGateConj()
void statevec_sGateConj (Qureg qureg, int targetQubit)
Definition at line 282 of file QuEST_common.c.
{
     Complex term;
     term.real =  0;
     term.imag = -1;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
statevec_sqrtSwapGate()
void statevec_sqrtSwapGate (Qureg qureg, int qb1, int qb2)
Definition at line 387 of file QuEST_common.c.
{
     ComplexMatrix4 u = (ComplexMatrix4) {.real={{0}}, .imag={{0}}};
     u.real[0][0]=1;
     u.real[3][3]=1;
     u.real[1][1] = .5; u.imag[1][1] = .5;
     u.real[1][2] = .5; u.imag[1][2] =-.5;
     u.real[2][1] = .5; u.imag[2][1] =-.5;
     u.real[2][2] = .5; u.imag[2][2] = .5;
     statevec_twoQubitUnitary(qureg, qb1, qb2, u);
 }
References ComplexMatrix4::imag, ComplexMatrix4::real, and statevec_twoQubitUnitary().
Referenced by sqrtSwapGate().
statevec_sqrtSwapGateConj()
void statevec_sqrtSwapGateConj (Qureg qureg, int qb1, int qb2)
Definition at line 400 of file QuEST_common.c.
{
     ComplexMatrix4 u = (ComplexMatrix4) {.real={{0}}, .imag={{0}}};
     u.real[0][0]=1;
     u.real[3][3]=1;
     u.real[1][1] = .5; u.imag[1][1] =-.5;
     u.real[1][2] = .5; u.imag[1][2] = .5;
     u.real[2][1] = .5; u.imag[2][1] = .5;
     u.real[2][2] = .5; u.imag[2][2] =-.5;
     statevec_twoQubitUnitary(qureg, qb1, qb2, u);
 }
References ComplexMatrix4::imag, ComplexMatrix4::real, and statevec_twoQubitUnitary().
Referenced by sqrtSwapGate().
statevec_tGate()
void statevec_tGate (Qureg qureg, int targetQubit)
Definition at line 275 of file QuEST_common.c.
{
     Complex term;
     term.real = 1/sqrt(2);
     term.imag = 1/sqrt(2);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
statevec_tGateConj()
void statevec_tGateConj (Qureg qureg, int targetQubit)
Definition at line 289 of file QuEST_common.c.
{
     Complex term;
     term.real =  1/sqrt(2);
     term.imag = -1/sqrt(2);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
statevec_twoQubitUnitary()
void statevec_twoQubitUnitary (Qureg qureg, int targetQubit1, int targetQubit2, ComplexMatrix4 u)
Definition at line 561 of file QuEST_common.c.
{
     long long int ctrlMask = 0;
     statevec_multiControlledTwoQubitUnitary(qureg, ctrlMask, targetQubit1, targetQubit2, u);
 }
References statevec_multiControlledTwoQubitUnitary().
Referenced by applyMatrix4(), statevec_sqrtSwapGate(), statevec_sqrtSwapGateConj(), and twoQubitUnitary().