Quantum Exact Simulation Toolkit: QuEST_ops_pure.h File Reference
QuEST_ops_pure.h File Reference
Functions operating upon pure states which are provided by a hardware-specific backend.
#include "QuEST.h"
#include "QuEST_precision.h"
Functions
REAL pure_calcTotalProbability (QubitRegister qureg)
REAL pure_collapseToOutcome (QubitRegister qureg, const int measureQubit, int outcome)
void pure_compactUnitary (QubitRegister qureg, const int targetQubit, Complex alpha, Complex beta)
int pure_compareStates (QubitRegister mq1, QubitRegister mq2, REAL precision)
void pure_controlledCompactUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void pure_controlledNot (QubitRegister qureg, const int controlQubit, const int targetQubit)
void pure_controlledPhaseFlip (QubitRegister qureg, const int idQubit1, const int idQubit2)
void pure_controlledPhaseShift (QubitRegister qureg, const int idQubit1, const int idQubit2, REAL angle)
void pure_controlledRotateAroundAxis (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
void pure_controlledRotateAroundAxisConj (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
void pure_controlledRotateX (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void pure_controlledRotateY (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void pure_controlledRotateZ (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void pure_controlledUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
void pure_createQubitRegister (QubitRegister *qureg, int numQubits, QuESTEnv env)
void pure_destroyQubitRegister (QubitRegister qureg, QuESTEnv env)
REAL pure_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
REAL pure_getImagAmpEl (QubitRegister qureg, long long int index)
int pure_getNumAmps (QubitRegister qureg)
int pure_getNumQubits (QubitRegister qureg)
REAL pure_getProbEl (QubitRegister qureg, long long int index)
REAL pure_getRealAmpEl (QubitRegister qureg, long long int index)
void pure_hadamard (QubitRegister qureg, const int targetQubit)
void pure_initClassicalState (QubitRegister qureg, long long int stateInd)
void pure_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
void pure_initStateDebug (QubitRegister qureg)
void pure_initStateFromSingleFile (QubitRegister *qureg, char filename[200], QuESTEnv env)
void pure_initStateOfSingleQubit (QubitRegister *qureg, int qubitId, int outcome)
void pure_initStatePlus (QubitRegister qureg)
void pure_initStateZero (QubitRegister qureg)
int pure_measure (QubitRegister qureg, int measureQubit)
int pure_measureWithStats (QubitRegister qureg, int measureQubit, REAL *stateProb)
void pure_multiControlledPhaseFlip (QubitRegister qureg, int *controlQubits, int numControlQubits)
void pure_multiControlledPhaseShift (QubitRegister qureg, int *controlQubits, int numControlQubits, REAL angle)
void pure_multiControlledUnitary (QubitRegister qureg, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
void pure_phaseShift (QubitRegister qureg, const int targetQubit, REAL angle)
void pure_phaseShiftByTerm (QubitRegister qureg, const int targetQubit, Complex term)
void pure_reportStateToScreen (QubitRegister qureg, QuESTEnv env, int reportRank)
void pure_rotateAroundAxis (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
void pure_rotateAroundAxisConj (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
void pure_rotateX (QubitRegister qureg, const int rotQubit, REAL angle)
void pure_rotateY (QubitRegister qureg, const int rotQubit, REAL angle)
void pure_rotateZ (QubitRegister qureg, const int rotQubit, REAL angle)
void pure_sGate (QubitRegister qureg, const int targetQubit)
void pure_sGateConj (QubitRegister qureg, const int targetQubit)
void pure_sigmaX (QubitRegister qureg, const int targetQubit)
void pure_sigmaY (QubitRegister qureg, const int targetQubit)
void pure_sigmaZ (QubitRegister qureg, const int targetQubit)
void pure_tGate (QubitRegister qureg, const int targetQubit)
void pure_tGateConj (QubitRegister qureg, const int targetQubit)
void pure_unitary (QubitRegister qureg, const int targetQubit, ComplexMatrix2 u)
Detailed Description
Functions operating upon pure states which are provided by a hardware-specific backend.
Definition in file QuEST_ops_pure.h.
Function Documentation
pure_calcTotalProbability()
REAL pure_calcTotalProbability (QubitRegister qureg)
Referenced by calcTotalProbability().
pure_collapseToOutcome()
REAL pure_collapseToOutcome (QubitRegister qureg, const int measureQubit, int outcome)
Referenced by collapseToOutcome().
pure_compactUnitary()
void pure_compactUnitary (QubitRegister qureg, const int targetQubit, Complex alpha, Complex beta)
Referenced by compactUnitary(), pure_rotateAroundAxis(), and pure_rotateAroundAxisConj().
pure_compareStates()
int pure_compareStates (QubitRegister mq1, QubitRegister mq2, REAL precision)
Referenced by compareStates().
pure_controlledCompactUnitary()
void pure_controlledCompactUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Referenced by controlledCompactUnitary(), pure_controlledRotateAroundAxis(), and pure_controlledRotateAroundAxisConj().
pure_controlledNot()
void pure_controlledNot (QubitRegister qureg, const int controlQubit, const int targetQubit)
Referenced by controlledNot().
pure_controlledPhaseFlip()
void pure_controlledPhaseFlip (QubitRegister qureg, const int idQubit1, const int idQubit2)
Referenced by controlledPhaseFlip().
pure_controlledPhaseShift()
void pure_controlledPhaseShift (QubitRegister qureg, const int idQubit1, const int idQubit2, REAL angle)
Referenced by controlledPhaseShift().
pure_controlledRotateAroundAxis()
void pure_controlledRotateAroundAxis (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Definition at line 268 of file QuEST_common.c.
References getAlphaBetaFromRotation(), and pure_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis(), pure_controlledRotateX(), pure_controlledRotateY(), and pure_controlledRotateZ().
{
     Complex alpha, beta;
     getAlphaBetaFromRotation(angle, axis, &alpha, &beta);
     pure_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
pure_controlledRotateAroundAxisConj()
void pure_controlledRotateAroundAxisConj (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Definition at line 275 of file QuEST_common.c.
References getAlphaBetaFromRotation(), Complex::imag, and pure_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis().
{
     Complex alpha, beta;
     getAlphaBetaFromRotation(angle, axis, &alpha, &beta);
         alpha.imag *= -1;
         beta.imag *= -1;
     pure_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
pure_controlledRotateX()
void pure_controlledRotateX (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 284 of file QuEST_common.c.
References pure_controlledRotateAroundAxis().
Referenced by controlledRotateX().
{
     Vector unitAxis = {1, 0, 0};
     pure_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
pure_controlledRotateY()
void pure_controlledRotateY (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 290 of file QuEST_common.c.
References pure_controlledRotateAroundAxis().
Referenced by controlledRotateY().
{
     Vector unitAxis = {0, 1, 0};
     pure_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
pure_controlledRotateZ()
void pure_controlledRotateZ (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 296 of file QuEST_common.c.
References pure_controlledRotateAroundAxis().
Referenced by controlledRotateZ().
{
     Vector unitAxis = {0, 0, 1};
     pure_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
pure_controlledUnitary()
void pure_controlledUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Referenced by controlledUnitary().
pure_createQubitRegister()
void pure_createQubitRegister (QubitRegister * qureg, int numQubits, QuESTEnv env)
Referenced by createDensityQubitRegister(), and createQubitRegister().
pure_destroyQubitRegister()
void pure_destroyQubitRegister (QubitRegister qureg, QuESTEnv env)
Referenced by destroyQubitRegister().
pure_findProbabilityOfOutcome()
REAL pure_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
Referenced by findProbabilityOfOutcome().
pure_getImagAmpEl()
REAL pure_getImagAmpEl (QubitRegister qureg, long long int index)
Referenced by getImagAmpEl(), and pure_getProbEl().
pure_getNumAmps()
int pure_getNumAmps (QubitRegister qureg)
Definition at line 148 of file QuEST_common.c.
References QubitRegister::numAmpsPerChunk, and QubitRegister::numChunks.
Referenced by getNumAmps().
{
     return qureg.numAmpsPerChunk*qureg.numChunks;
 }
pure_getNumQubits()
int pure_getNumQubits (QubitRegister qureg)
Definition at line 144 of file QuEST_common.c.
References QubitRegister::numQubits.
Referenced by getNumQubits().
{
     return qureg.numQubits;
 }
pure_getProbEl()
REAL pure_getProbEl (QubitRegister qureg, long long int index)
Definition at line 138 of file QuEST_common.c.
References pure_getImagAmpEl(), pure_getRealAmpEl(), and REAL.
Referenced by getProbEl().
{
     REAL real = pure_getRealAmpEl(qureg, index);
     REAL imag = pure_getImagAmpEl(qureg, index);
     return real*real + imag*imag;
 }
pure_getRealAmpEl()
REAL pure_getRealAmpEl (QubitRegister qureg, long long int index)
Referenced by getRealAmpEl(), and pure_getProbEl().
pure_hadamard()
void pure_hadamard (QubitRegister qureg, const int targetQubit)
Referenced by hadamard().
pure_initClassicalState()
void pure_initClassicalState (QubitRegister qureg, long long int stateInd)
Referenced by initClassicalState().
pure_initPureState()
void pure_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
Referenced by initPureState().
pure_initStateDebug()
void pure_initStateDebug (QubitRegister qureg)
Referenced by initStateDebug().
pure_initStateFromSingleFile()
void pure_initStateFromSingleFile (QubitRegister * qureg, char filename[200], QuESTEnv env)
Referenced by initStateFromSingleFile().
pure_initStateOfSingleQubit()
void pure_initStateOfSingleQubit (QubitRegister * qureg, int qubitId, int outcome)
Referenced by initStateOfSingleQubit().
pure_initStatePlus()
void pure_initStatePlus (QubitRegister qureg)
Referenced by initStatePlus().
pure_initStateZero()
void pure_initStateZero (QubitRegister qureg)
Referenced by initStateZero().
pure_measure()
int pure_measure (QubitRegister qureg, int measureQubit)
Referenced by measure().
pure_measureWithStats()
int pure_measureWithStats (QubitRegister qureg, int measureQubit, REAL * stateProb)
Referenced by measureWithStats().
pure_multiControlledPhaseFlip()
void pure_multiControlledPhaseFlip (QubitRegister qureg, int * controlQubits, int numControlQubits)
Referenced by multiControlledPhaseFlip().
pure_multiControlledPhaseShift()
void pure_multiControlledPhaseShift (QubitRegister qureg, int * controlQubits, int numControlQubits, REAL angle)
Referenced by multiControlledPhaseShift().
pure_multiControlledUnitary()
void pure_multiControlledUnitary (QubitRegister qureg, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Referenced by multiControlledUnitary().
pure_phaseShift()
void pure_phaseShift (QubitRegister qureg, const int targetQubit, REAL angle)
Definition at line 181 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by phaseShift().
{
         Complex term;
         term.real = cos(angle);
         term.imag = sin(angle);
         pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_phaseShiftByTerm()
void pure_phaseShiftByTerm (QubitRegister qureg, const int targetQubit, Complex term)
Referenced by pure_phaseShift(), pure_sGate(), pure_sGateConj(), pure_sigmaZ(), pure_tGate(), and pure_tGateConj().
pure_reportStateToScreen()
void pure_reportStateToScreen (QubitRegister qureg, QuESTEnv env, int reportRank)
Referenced by reportStateToScreen().
pure_rotateAroundAxis()
void pure_rotateAroundAxis (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
Definition at line 252 of file QuEST_common.c.
References getAlphaBetaFromRotation(), and pure_compactUnitary().
Referenced by pure_rotateX(), pure_rotateY(), pure_rotateZ(), and rotateAroundAxis().
{
     Complex alpha, beta;
     getAlphaBetaFromRotation(angle, axis, &alpha, &beta);
     pure_compactUnitary(qureg, rotQubit, alpha, beta);
 }
pure_rotateAroundAxisConj()
void pure_rotateAroundAxisConj (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
Definition at line 259 of file QuEST_common.c.
References getAlphaBetaFromRotation(), Complex::imag, and pure_compactUnitary().
Referenced by rotateAroundAxis().
{
     Complex alpha, beta;
     getAlphaBetaFromRotation(angle, axis, &alpha, &beta);
         alpha.imag *= -1;
         beta.imag *= -1;
     pure_compactUnitary(qureg, rotQubit, alpha, beta);
 }
pure_rotateX()
void pure_rotateX (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 223 of file QuEST_common.c.
References pure_rotateAroundAxis().
Referenced by rotateX().
{
     Vector unitAxis = {1, 0, 0};
     pure_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
pure_rotateY()
void pure_rotateY (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 229 of file QuEST_common.c.
References pure_rotateAroundAxis().
Referenced by rotateY().
{
     Vector unitAxis = {0, 1, 0};
     pure_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
pure_rotateZ()
void pure_rotateZ (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 235 of file QuEST_common.c.
References pure_rotateAroundAxis().
Referenced by rotateZ().
{
     Vector unitAxis = {0, 0, 1};
     pure_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
pure_sGate()
void pure_sGate (QubitRegister qureg, const int targetQubit)
Definition at line 195 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by sGate().
{
         Complex term;
         term.real = 0;
         term.imag = 1;
     pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_sGateConj()
void pure_sGateConj (QubitRegister qureg, const int targetQubit)
Definition at line 209 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by sGate().
{
         Complex term;
         term.real =  0;
         term.imag = -1;
     pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_sigmaX()
void pure_sigmaX (QubitRegister qureg, const int targetQubit)
Referenced by sigmaX().
pure_sigmaY()
void pure_sigmaY (QubitRegister qureg, const int targetQubit)
Referenced by sigmaY().
pure_sigmaZ()
void pure_sigmaZ (QubitRegister qureg, const int targetQubit)
Definition at line 188 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by sigmaZ().
{
         Complex term;
         term.real = -1;
         term.imag =  0;
     pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_tGate()
void pure_tGate (QubitRegister qureg, const int targetQubit)
Definition at line 202 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by tGate().
{
         Complex term;
         term.real = 1/sqrt(2);
         term.imag = 1/sqrt(2);
     pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_tGateConj()
void pure_tGateConj (QubitRegister qureg, const int targetQubit)
Definition at line 216 of file QuEST_common.c.
References Complex::imag, pure_phaseShiftByTerm(), and Complex::real.
Referenced by tGate().
{
         Complex term;
         term.real =  1/sqrt(2);
         term.imag = -1/sqrt(2);
     pure_phaseShiftByTerm(qureg, targetQubit, term);
 }
pure_unitary()
void pure_unitary (QubitRegister qureg, const int targetQubit, ComplexMatrix2 u)
Referenced by unitary().