Quantum Exact Simulation Toolkit: QuEST_ops.h File Reference
QuEST_ops.h File Reference
Functions operating upon pure states which are provided by a hardware-specific backend.
#include "QuEST.h"
#include "QuEST_precision.h"
Functions
REAL densmatr_calcFidelity (QubitRegister qureg, QubitRegister pureState)
REAL densmatr_calcPurity (QubitRegister qureg)
REAL densmatr_calcTotalProbability (QubitRegister qureg)
void densmatr_collapseToKnownProbOutcome (QubitRegister qureg, const int measureQubit, int outcome, REAL outcomeProb)
void densmatr_combineDensityMatrices (REAL combineProb, QubitRegister combineQureg, REAL otherProb, QubitRegister otherQureg)
REAL densmatr_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
void densmatr_initClassicalState (QubitRegister qureg, long long int stateInd)
void densmatr_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
void densmatr_initStatePlus (QubitRegister targetQureg)
int densmatr_measureWithStats (QubitRegister qureg, int measureQubit, REAL *outcomeProb)
void densmatr_oneQubitDephase (QubitRegister qureg, const int targetQubit, REAL dephase)
void densmatr_oneQubitDepolarise (QubitRegister qureg, const int targetQubit, REAL depolLevel)
void densmatr_twoQubitDephase (QubitRegister qureg, const int qubit1, const int qubit2, REAL dephase)
void densmatr_twoQubitDepolarise (QubitRegister qureg, int qubit1, int qubit2, REAL depolLevel)
REAL statevec_calcFidelity (QubitRegister qureg, QubitRegister pureState)
Complex statevec_calcInnerProduct (QubitRegister bra, QubitRegister ket)
REAL statevec_calcTotalProbability (QubitRegister qureg)
void statevec_cloneQubitRegister (QubitRegister targetQureg, QubitRegister copyQureg)
void statevec_collapseToKnownProbOutcome (QubitRegister qureg, const int measureQubit, int outcome, REAL outcomeProb)
void statevec_compactUnitary (QubitRegister qureg, const int targetQubit, Complex alpha, Complex beta)
int statevec_compareStates (QubitRegister mq1, QubitRegister mq2, REAL precision)
void statevec_controlledCompactUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
void statevec_controlledNot (QubitRegister qureg, const int controlQubit, const int targetQubit)
void statevec_controlledPhaseFlip (QubitRegister qureg, const int idQubit1, const int idQubit2)
void statevec_controlledPhaseShift (QubitRegister qureg, const int idQubit1, const int idQubit2, REAL angle)
void statevec_controlledRotateAroundAxis (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
void statevec_controlledRotateAroundAxisConj (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
void statevec_controlledRotateX (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void statevec_controlledRotateY (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void statevec_controlledRotateZ (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
void statevec_controlledSigmaY (QubitRegister qureg, const int controlQubit, const int targetQubit)
void statevec_controlledSigmaYConj (QubitRegister qureg, const int controlQubit, const int targetQubit)
void statevec_controlledUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
void statevec_createQubitRegister (QubitRegister *qureg, int numQubits, QuESTEnv env)
void statevec_destroyQubitRegister (QubitRegister qureg, QuESTEnv env)
REAL statevec_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
REAL statevec_getImagAmpEl (QubitRegister qureg, long long int index)
REAL statevec_getProbEl (QubitRegister qureg, long long int index)
REAL statevec_getRealAmpEl (QubitRegister qureg, long long int index)
void statevec_hadamard (QubitRegister qureg, const int targetQubit)
void statevec_initClassicalState (QubitRegister qureg, long long int stateInd)
void statevec_initStateDebug (QubitRegister qureg)
int statevec_initStateFromSingleFile (QubitRegister *qureg, char filename[200], QuESTEnv env)
void statevec_initStateOfSingleQubit (QubitRegister *qureg, int qubitId, int outcome)
void statevec_initStatePlus (QubitRegister qureg)
void statevec_initStateZero (QubitRegister qureg)
int statevec_measureWithStats (QubitRegister qureg, int measureQubit, REAL *outcomeProb)
void statevec_multiControlledPhaseFlip (QubitRegister qureg, int *controlQubits, int numControlQubits)
void statevec_multiControlledPhaseShift (QubitRegister qureg, int *controlQubits, int numControlQubits, REAL angle)
void statevec_multiControlledUnitary (QubitRegister qureg, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
void statevec_phaseShift (QubitRegister qureg, const int targetQubit, REAL angle)
void statevec_phaseShiftByTerm (QubitRegister qureg, const int targetQubit, Complex term)
void statevec_reportStateToScreen (QubitRegister qureg, QuESTEnv env, int reportRank)
void statevec_rotateAroundAxis (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
void statevec_rotateAroundAxisConj (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
void statevec_rotateX (QubitRegister qureg, const int rotQubit, REAL angle)
void statevec_rotateY (QubitRegister qureg, const int rotQubit, REAL angle)
void statevec_rotateZ (QubitRegister qureg, const int rotQubit, REAL angle)
void statevec_sGate (QubitRegister qureg, const int targetQubit)
void statevec_sGateConj (QubitRegister qureg, const int targetQubit)
void statevec_sigmaX (QubitRegister qureg, const int targetQubit)
void statevec_sigmaY (QubitRegister qureg, const int targetQubit)
void statevec_sigmaYConj (QubitRegister qureg, const int targetQubit)
void statevec_sigmaZ (QubitRegister qureg, const int targetQubit)
void statevec_tGate (QubitRegister qureg, const int targetQubit)
void statevec_tGateConj (QubitRegister qureg, const int targetQubit)
void statevec_unitary (QubitRegister qureg, const int targetQubit, ComplexMatrix2 u)
Detailed Description
Functions operating upon pure states which are provided by a hardware-specific backend.
Definition in file QuEST_ops.h.
Function Documentation
densmatr_calcFidelity()
REAL densmatr_calcFidelity (QubitRegister qureg, QubitRegister pureState)
Referenced by calcFidelity().
densmatr_calcPurity()
REAL densmatr_calcPurity (QubitRegister qureg)
Referenced by calcPurity().
densmatr_calcTotalProbability()
REAL densmatr_calcTotalProbability (QubitRegister qureg)
Referenced by calcTotalProbability().
densmatr_collapseToKnownProbOutcome()
void densmatr_collapseToKnownProbOutcome (QubitRegister qureg, const int measureQubit, int outcome, REAL outcomeProb)
Referenced by collapseToOutcome(), and densmatr_measureWithStats().
densmatr_combineDensityMatrices()
void densmatr_combineDensityMatrices (REAL combineProb, QubitRegister combineQureg, REAL otherProb, QubitRegister otherQureg)
Referenced by combineDensityMatrices().
densmatr_findProbabilityOfOutcome()
REAL densmatr_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
Referenced by collapseToOutcome(), densmatr_measureWithStats(), and findProbabilityOfOutcome().
densmatr_initClassicalState()
void densmatr_initClassicalState (QubitRegister qureg, long long int stateInd)
Referenced by initClassicalState().
densmatr_initPureState()
void densmatr_initPureState (QubitRegister targetQureg, QubitRegister copyQureg)
Referenced by initPureState().
densmatr_initStatePlus()
void densmatr_initStatePlus (QubitRegister targetQureg)
Referenced by initStatePlus().
densmatr_measureWithStats()
int densmatr_measureWithStats (QubitRegister qureg, int measureQubit, REAL * outcomeProb)
Definition at line 313 of file QuEST_common.c.
References densmatr_collapseToKnownProbOutcome(), densmatr_findProbabilityOfOutcome(), generateMeasurementOutcome(), and REAL.
Referenced by measure(), and measureWithStats().
{
     REAL zeroProb = densmatr_findProbabilityOfOutcome(qureg, measureQubit, 0);
     int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
     densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
     return outcome;
 }
densmatr_oneQubitDephase()
void densmatr_oneQubitDephase (QubitRegister qureg, const int targetQubit, REAL dephase)
Referenced by oneQubitDephase().
densmatr_oneQubitDepolarise()
void densmatr_oneQubitDepolarise (QubitRegister qureg, const int targetQubit, REAL depolLevel)
Referenced by oneQubitDepolarise().
densmatr_twoQubitDephase()
void densmatr_twoQubitDephase (QubitRegister qureg, const int qubit1, const int qubit2, REAL dephase)
Referenced by twoQubitDephase().
densmatr_twoQubitDepolarise()
void densmatr_twoQubitDepolarise (QubitRegister qureg, int qubit1, int qubit2, REAL depolLevel)
Referenced by twoQubitDepolarise().
statevec_calcFidelity()
REAL statevec_calcFidelity (QubitRegister qureg, QubitRegister pureState)
Definition at line 321 of file QuEST_common.c.
References Complex::imag, Complex::real, REAL, and statevec_calcInnerProduct().
Referenced by calcFidelity().
{
     Complex innerProd = statevec_calcInnerProduct(qureg, pureState);
     REAL innerProdMag = innerProd.real*innerProd.real + innerProd.imag*innerProd.imag;
     return innerProdMag;
 }
statevec_calcInnerProduct()
Complex statevec_calcInnerProduct (QubitRegister bra, QubitRegister ket)
Referenced by calcInnerProduct(), and statevec_calcFidelity().
statevec_calcTotalProbability()
REAL statevec_calcTotalProbability (QubitRegister qureg)
Referenced by calcTotalProbability().
statevec_cloneQubitRegister()
void statevec_cloneQubitRegister (QubitRegister targetQureg, QubitRegister copyQureg)
Referenced by cloneQubitRegister(), and initPureState().
statevec_collapseToKnownProbOutcome()
void statevec_collapseToKnownProbOutcome (QubitRegister qureg, const int measureQubit, int outcome, REAL outcomeProb)
Referenced by collapseToOutcome(), and statevec_measureWithStats().
statevec_compactUnitary()
void statevec_compactUnitary (QubitRegister qureg, const int targetQubit, Complex alpha, Complex beta)
Referenced by compactUnitary(), statevec_rotateAroundAxis(), and statevec_rotateAroundAxisConj().
statevec_compareStates()
int statevec_compareStates (QubitRegister mq1, QubitRegister mq2, REAL precision)
Referenced by compareStates().
statevec_controlledCompactUnitary()
void statevec_controlledCompactUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Referenced by controlledCompactUnitary(), statevec_controlledRotateAroundAxis(), and statevec_controlledRotateAroundAxisConj().
statevec_controlledNot()
void statevec_controlledNot (QubitRegister qureg, const int controlQubit, const int targetQubit)
Referenced by controlledNot().
statevec_controlledPhaseFlip()
void statevec_controlledPhaseFlip (QubitRegister qureg, const int idQubit1, const int idQubit2)
Referenced by controlledPhaseFlip().
statevec_controlledPhaseShift()
void statevec_controlledPhaseShift (QubitRegister qureg, const int idQubit1, const int idQubit2, REAL angle)
Referenced by controlledPhaseShift().
statevec_controlledRotateAroundAxis()
void statevec_controlledRotateAroundAxis (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Definition at line 271 of file QuEST_common.c.
References getComplexPairFromRotation(), and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis(), statevec_controlledRotateX(), statevec_controlledRotateY(), and statevec_controlledRotateZ().
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
statevec_controlledRotateAroundAxisConj()
void statevec_controlledRotateAroundAxisConj (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle, Vector axis)
Definition at line 278 of file QuEST_common.c.
References getComplexPairFromRotation(), Complex::imag, and statevec_controlledCompactUnitary().
Referenced by controlledRotateAroundAxis().
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     alpha.imag *= -1;
     beta.imag *= -1;
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
 }
statevec_controlledRotateX()
void statevec_controlledRotateX (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 287 of file QuEST_common.c.
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateX().
{
     Vector unitAxis = {1, 0, 0};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
statevec_controlledRotateY()
void statevec_controlledRotateY (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 293 of file QuEST_common.c.
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateY().
{
     Vector unitAxis = {0, 1, 0};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
statevec_controlledRotateZ()
void statevec_controlledRotateZ (QubitRegister qureg, const int controlQubit, const int targetQubit, REAL angle)
Definition at line 299 of file QuEST_common.c.
References statevec_controlledRotateAroundAxis().
Referenced by controlledRotateZ().
{
     Vector unitAxis = {0, 0, 1};
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, unitAxis);
 }
statevec_controlledSigmaY()
void statevec_controlledSigmaY (QubitRegister qureg, const int controlQubit, const int targetQubit)
Referenced by controlledSigmaY().
statevec_controlledSigmaYConj()
void statevec_controlledSigmaYConj (QubitRegister qureg, const int controlQubit, const int targetQubit)
Referenced by controlledSigmaY().
statevec_controlledUnitary()
void statevec_controlledUnitary (QubitRegister qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Referenced by controlledUnitary().
statevec_createQubitRegister()
void statevec_createQubitRegister (QubitRegister * qureg, int numQubits, QuESTEnv env)
Referenced by createDensityQubitRegister(), and createQubitRegister().
statevec_destroyQubitRegister()
void statevec_destroyQubitRegister (QubitRegister qureg, QuESTEnv env)
Referenced by destroyQubitRegister().
statevec_findProbabilityOfOutcome()
REAL statevec_findProbabilityOfOutcome (QubitRegister qureg, const int measureQubit, int outcome)
Referenced by collapseToOutcome(), findProbabilityOfOutcome(), and statevec_measureWithStats().
statevec_getImagAmpEl()
REAL statevec_getImagAmpEl (QubitRegister qureg, long long int index)
Referenced by getDensityAmplitude(), getImagAmpEl(), and statevec_getProbEl().
statevec_getProbEl()
REAL statevec_getProbEl (QubitRegister qureg, long long int index)
Definition at line 160 of file QuEST_common.c.
References REAL, statevec_getImagAmpEl(), and statevec_getRealAmpEl().
Referenced by getProbEl().
{
     REAL real = statevec_getRealAmpEl(qureg, index);
     REAL imag = statevec_getImagAmpEl(qureg, index);
     return real*real + imag*imag;
 }
statevec_getRealAmpEl()
REAL statevec_getRealAmpEl (QubitRegister qureg, long long int index)
Referenced by getDensityAmplitude(), getRealAmpEl(), and statevec_getProbEl().
statevec_hadamard()
void statevec_hadamard (QubitRegister qureg, const int targetQubit)
Referenced by hadamard().
statevec_initClassicalState()
void statevec_initClassicalState (QubitRegister qureg, long long int stateInd)
Referenced by initClassicalState().
statevec_initStateDebug()
void statevec_initStateDebug (QubitRegister qureg)
Referenced by initStateDebug().
statevec_initStateFromSingleFile()
int statevec_initStateFromSingleFile (QubitRegister * qureg, char filename[200], QuESTEnv env)
Referenced by initStateFromSingleFile().
statevec_initStateOfSingleQubit()
void statevec_initStateOfSingleQubit (QubitRegister * qureg, int qubitId, int outcome)
Referenced by initStateOfSingleQubit().
statevec_initStatePlus()
void statevec_initStatePlus (QubitRegister qureg)
Referenced by initStatePlus().
statevec_initStateZero()
void statevec_initStateZero (QubitRegister qureg)
Referenced by initStateZero().
statevec_measureWithStats()
int statevec_measureWithStats (QubitRegister qureg, int measureQubit, REAL * outcomeProb)
Definition at line 305 of file QuEST_common.c.
References generateMeasurementOutcome(), REAL, statevec_collapseToKnownProbOutcome(), and statevec_findProbabilityOfOutcome().
Referenced by measure(), and measureWithStats().
{
     REAL zeroProb = statevec_findProbabilityOfOutcome(qureg, measureQubit, 0);
     int outcome = generateMeasurementOutcome(zeroProb, outcomeProb);
     statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, *outcomeProb);
     return outcome;
 }
statevec_multiControlledPhaseFlip()
void statevec_multiControlledPhaseFlip (QubitRegister qureg, int * controlQubits, int numControlQubits)
Referenced by multiControlledPhaseFlip().
statevec_multiControlledPhaseShift()
void statevec_multiControlledPhaseShift (QubitRegister qureg, int * controlQubits, int numControlQubits, REAL angle)
Referenced by multiControlledPhaseShift().
statevec_multiControlledUnitary()
void statevec_multiControlledUnitary (QubitRegister qureg, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Referenced by multiControlledUnitary().
statevec_phaseShift()
void statevec_phaseShift (QubitRegister qureg, const int targetQubit, REAL angle)
Definition at line 195 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by phaseShift().
{
     Complex term;
     term.real = cos(angle);
     term.imag = sin(angle);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_phaseShiftByTerm()
void statevec_phaseShiftByTerm (QubitRegister qureg, const int targetQubit, Complex term)
Referenced by statevec_phaseShift(), statevec_sGate(), statevec_sGateConj(), statevec_sigmaZ(), statevec_tGate(), and statevec_tGateConj().
statevec_reportStateToScreen()
void statevec_reportStateToScreen (QubitRegister qureg, QuESTEnv env, int reportRank)
Referenced by reportStateToScreen().
statevec_rotateAroundAxis()
void statevec_rotateAroundAxis (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
Definition at line 255 of file QuEST_common.c.
References getComplexPairFromRotation(), and statevec_compactUnitary().
Referenced by rotateAroundAxis(), statevec_rotateX(), statevec_rotateY(), and statevec_rotateZ().
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     statevec_compactUnitary(qureg, rotQubit, alpha, beta);
 }
statevec_rotateAroundAxisConj()
void statevec_rotateAroundAxisConj (QubitRegister qureg, const int rotQubit, REAL angle, Vector axis)
Definition at line 262 of file QuEST_common.c.
References getComplexPairFromRotation(), Complex::imag, and statevec_compactUnitary().
Referenced by rotateAroundAxis().
{
     Complex alpha, beta;
     getComplexPairFromRotation(angle, axis, &alpha, &beta);
     alpha.imag *= -1;
     beta.imag *= -1;
     statevec_compactUnitary(qureg, rotQubit, alpha, beta);
 }
statevec_rotateX()
void statevec_rotateX (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 237 of file QuEST_common.c.
References statevec_rotateAroundAxis().
Referenced by rotateX().
{
     Vector unitAxis = {1, 0, 0};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
statevec_rotateY()
void statevec_rotateY (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 243 of file QuEST_common.c.
References statevec_rotateAroundAxis().
Referenced by rotateY().
{
     Vector unitAxis = {0, 1, 0};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
statevec_rotateZ()
void statevec_rotateZ (QubitRegister qureg, const int rotQubit, REAL angle)
Definition at line 249 of file QuEST_common.c.
References statevec_rotateAroundAxis().
Referenced by rotateZ().
{
     Vector unitAxis = {0, 0, 1};
     statevec_rotateAroundAxis(qureg, rotQubit, angle, unitAxis);
 }
statevec_sGate()
void statevec_sGate (QubitRegister qureg, const int targetQubit)
Definition at line 209 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
{
     Complex term;
     term.real = 0;
     term.imag = 1;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_sGateConj()
void statevec_sGateConj (QubitRegister qureg, const int targetQubit)
Definition at line 223 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sGate().
{
     Complex term;
     term.real =  0;
     term.imag = -1;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_sigmaX()
void statevec_sigmaX (QubitRegister qureg, const int targetQubit)
Referenced by sigmaX().
statevec_sigmaY()
void statevec_sigmaY (QubitRegister qureg, const int targetQubit)
Referenced by sigmaY().
statevec_sigmaYConj()
void statevec_sigmaYConj (QubitRegister qureg, const int targetQubit)
Referenced by sigmaY().
statevec_sigmaZ()
void statevec_sigmaZ (QubitRegister qureg, const int targetQubit)
Definition at line 202 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by sigmaZ().
{
     Complex term;
     term.real = -1;
     term.imag =  0;
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_tGate()
void statevec_tGate (QubitRegister qureg, const int targetQubit)
Definition at line 216 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
{
     Complex term;
     term.real = 1/sqrt(2);
     term.imag = 1/sqrt(2);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_tGateConj()
void statevec_tGateConj (QubitRegister qureg, const int targetQubit)
Definition at line 230 of file QuEST_common.c.
References Complex::imag, Complex::real, and statevec_phaseShiftByTerm().
Referenced by tGate().
{
     Complex term;
     term.real =  1/sqrt(2);
     term.imag = -1/sqrt(2);
     statevec_phaseShiftByTerm(qureg, targetQubit, term);
 }
statevec_unitary()
void statevec_unitary (QubitRegister qureg, const int targetQubit, ComplexMatrix2 u)
Referenced by unitary().