Quantum Exact Simulation Toolkit: QuEST.h File Reference
QuEST.h File Reference
The QuEST API.
#include "QuEST_precision.h"
Data Structures
struct Complex
Represents one complex number.
struct ComplexMatrix2
Represents a 2x2 matrix of complex numbers.
struct QuESTEnv
Information about the environment the program is running in.
struct Qureg
Represents a system of qubits.
struct Vector
Represents a 3-vector of real numbers.
Typedefs
typedef struct Complex Complex
Represents one complex number.
typedef struct ComplexMatrix2 ComplexMatrix2
Represents a 2x2 matrix of complex numbers.
typedef struct QuESTEnv QuESTEnv
Information about the environment the program is running in.
typedef struct Qureg Qureg
Represents a system of qubits.
typedef struct Vector Vector
Represents a 3-vector of real numbers.
Functions
void addDensityMatrix (Qureg combineQureg, qreal prob, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
void applyOneQubitDephaseError (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
void applyOneQubitDepolariseError (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
void applyTwoQubitDephaseError (Qureg qureg, const int qubit1, const int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
void applyTwoQubitDepolariseError (Qureg qureg, const int qubit1, const int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
qreal calcFidelity (Qureg qureg, Qureg pureState)
Calculates the fidelity of qureg (a statevector or density matrix) against a reference pure state (necessarily a statevector).
Complex calcInnerProduct (Qureg bra, Qureg ket)
Computes <bra|ket>
qreal calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
qreal calcPurity (Qureg qureg)
Calculates the purity of a density matrix, by the trace of the density matrix squared.
qreal calcTotalProb (Qureg qureg)
A debugging function which calculates the probability of being in any state, which should always be 1.
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
void cloneQureg (Qureg targetQureg, Qureg copyQureg)
Set targetQureg to be a clone of copyQureg.
qreal collapseToOutcome (Qureg qureg, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
void compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
void controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
void controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
void controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled pauliY (single control, single target) gate, also known as the c-Y and c-sigma-Y gate.
void controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase flip gate, also known as the controlled pauliZ gate.
void controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
Introduce a phase factor on state of qubits idQubit1 and idQubit2.
void controlledRotateAroundAxis (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
void controlledRotateX (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
void controlledRotateY (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
void controlledRotateZ (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
void controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
Qureg createDensityQureg (int numQubits, QuESTEnv env)
Create a Qureg for qubits which are represented by a density matrix, and can be in mixed states.
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
Qureg createQureg (int numQubits, QuESTEnv env)
Create a Qureg object representing a set of qubits which will remain in a pure state.
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
void destroyQureg (Qureg qureg, QuESTEnv env)
Deallocate a Qureg object representing a set of qubits.
Complex getAmp (Qureg qureg, long long int index)
Getthe complex amplitude at a given index in the state vector.
Complex getDensityAmp (Qureg qureg, long long int row, long long int col)
Get an amplitude from a density matrix at a given row and column.
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
qreal getImagAmp (Qureg qureg, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
int getNumAmps (Qureg qureg)
Get the number of probability amplitudes in a qureg object, given by 2^numQubits.
int getNumQubits (Qureg qureg)
Get the number of qubits in a qureg object.
qreal getProbAmp (Qureg qureg, long long int index)
Get the probability of the state at an index in the full state vector.
qreal getRealAmp (Qureg qureg, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
void hadamard (Qureg qureg, const int targetQubit)
Apply the single-qubit Hadamard gate.
void initClassicalState (Qureg qureg, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
void initPlusState (Qureg qureg)
Initialise a set of qubits to the plus state .
void initPureState (Qureg qureg, Qureg pure)
Initialise a set of qubits, which can be a state vector or density matrix, to a given pure state.
void initStateFromAmps (Qureg qureg, qreal *reals, qreal *imags)
Initialise qureg by specifying the complete statevector.
void initZeroState (Qureg qureg)
Initialise a set of qubits to the classical zero state .
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
int measureWithStats (Qureg qureg, int measureQubit, qreal *outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
void multiControlledPhaseFlip (Qureg qureg, int *controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase flip gate, also known as the multiple-qubit controlled pauliZ gate.
void multiControlledPhaseShift (Qureg qureg, int *controlQubits, int numControlQubits, qreal angle)
Introduce a phase factor on state of the passed qubits.
void multiControlledUnitary (Qureg qureg, int *controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
void pauliX (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-X (also known as the X, sigma-X, NOT or bit-flip) gate.
void pauliY (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Y (also known as the Y or sigma-Y) gate.
void pauliZ (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Z (also known as the Z, sigma-Z or phase-flip) gate.
void phaseShift (Qureg qureg, const int targetQubit, qreal angle)
Shift the phase between and of a single qubit by a given angle.
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
void reportQuregParams (Qureg qureg)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
void reportState (Qureg qureg)
Print the current state vector of probability amplitudes for a set of qubits to file.
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
void rotateAroundAxis (Qureg qureg, const int rotQubit, qreal angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
void rotateX (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
void rotateY (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
void rotateZ (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
void seedQuEST (unsigned long int *seedArray, int numSeeds)
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
void setAmps (Qureg qureg, long long int startInd, qreal *reals, qreal *imags, long long int numAmps)
Edit qureg to adopt the subset of amplitudes passed in reals and imags.
void sGate (Qureg qureg, const int targetQubit)
Apply the single-qubit S gate.
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
void tGate (Qureg qureg, const int targetQubit)
Apply the single-qubit T gate.
void unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
void writeRecordedQASMToFile (Qureg qureg, char *filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Detailed Description
The QuEST API.
This file contains the comments used by doxygen for generating API doc
Definition in file QuEST.h.
Typedef Documentation
Complex
typedef struct Complex Complex
Represents one complex number.
ComplexMatrix2
typedef struct ComplexMatrix2 ComplexMatrix2
Represents a 2x2 matrix of complex numbers.
QuESTEnv
typedef struct QuESTEnv QuESTEnv
Information about the environment the program is running in.
In practice, this holds info about MPI ranks and helps to hide MPI initialization code
Qureg
typedef struct Qureg Qureg
Represents a system of qubits.
Qubits are zero-based
Vector
typedef struct Vector Vector
Represents a 3-vector of real numbers.
Function Documentation
addDensityMatrix()
void addDensityMatrix (Qureg combineQureg, qreal prob, Qureg otherQureg)
Modifies combineQureg to become (1-prob)combineProb + prob otherQureg.
Both registers must be equal-dimension density matrices, and prob must be in [0, 1].
Parameters
[in,out] combineQureg a density matrix to be modified
[in] prob the probability of otherQureg in the modified combineQureg
[in] otherQureg a density matrix to be mixed into combineQureg
Exceptions
exitWithError if either combineQureg or otherQureg are not density matrices, or if the dimensions of combineQureg and otherQureg do not match, or if prob is not in [0, 1]
Definition at line 585 of file QuEST.c.
References densmatr_addDensityMatrix(), validateDensityMatrQureg(), validateMatchingQuregDims(), and validateProb().
{
     validateDensityMatrQureg(combineQureg, __func__);
     validateDensityMatrQureg(otherQureg, __func__);
     validateMatchingQuregDims(combineQureg, otherQureg, __func__);
     validateProb(otherProb, __func__);
     densmatr_addDensityMatrix(combineQureg, otherProb, otherQureg);
 }
applyOneQubitDephaseError()
void applyOneQubitDephaseError (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit dephasing noise.
With probability prob, applies Pauli Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 1/2, which maximally mixes targetQubit.
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if prob is not in [0, 1/2]
Definition at line 645 of file QuEST.c.
References densmatr_oneQubitDephase(), validateDensityMatrQureg(), validateOneQubitDephaseProb(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDephaseProb(prob, __func__);
     densmatr_oneQubitDephase(qureg, targetQubit, 2*prob);
 }
applyOneQubitDepolariseError()
void applyOneQubitDepolariseError (Qureg qureg, const int targetQubit, qreal prob)
Mixes a density matrix qureg to induce single-qubit homogeneous depolarising noise.
With probability prob, applies (uniformly) either Pauli X, Y, or Z to targetQubit.
This transforms qureg = into the mixed state
where q = targetQubit. prob cannot exceed 3/4, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] targetQubit qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if targetQubit is outside [0, qureg.numQubitsRepresented), or if prob is not in [0, 3/4]
Definition at line 662 of file QuEST.c.
References densmatr_oneQubitDepolarise(), validateDensityMatrQureg(), validateOneQubitDepolProb(), and validateTarget().
{
     validateDensityMatrQureg(qureg, __func__);
     validateTarget(qureg, targetQubit, __func__);
     validateOneQubitDepolProb(prob, __func__);
     densmatr_oneQubitDepolarise(qureg, targetQubit, (4*prob)/3.0);
 }
applyTwoQubitDephaseError()
void applyTwoQubitDephaseError (Qureg qureg, const int qubit1, const int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit dephasing noise.
With probability prob, applies Pauli Z to either or both qubits.
This transforms qureg = into the mixed state
where a = qubit1, b = qubit2. prob cannot exceed 3/4, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce dephasing noise
[in] qubit2 qubit upon which to induce dephasing noise
[in] prob the probability of the phase error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented), or if qubit1 = qubit2, or if prob is not in [0, 3/4]
Definition at line 653 of file QuEST.c.
References densmatr_twoQubitDephase(), ensureIndsIncrease(), validateDensityMatrQureg(), validateTwoQubitDephaseProb(), and validateUniqueTargets().
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDephaseProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_twoQubitDephase(qureg, qubit1, qubit2, (4*prob)/3.0);
 }
applyTwoQubitDepolariseError()
void applyTwoQubitDepolariseError (Qureg qureg, const int qubit1, const int qubit2, qreal prob)
Mixes a density matrix qureg to induce two-qubit homogeneous depolarising noise.
With probability prob, applies to qubit1 and qubit2 any operator of the set . Note this is the set of all two-qubit Pauli gates excluding .
This transforms qureg = into the mixed state
or verbosely
where a = qubit1, b = qubit2. prob cannot exceed 15/16, at which maximal mixing occurs.
Parameters
[in,out] qureg a density matrix
[in] qubit1 qubit upon which to induce depolarising noise
[in] qubit2 qubit upon which to induce depolarising noise
[in] prob the probability of the depolarising error occuring
Exceptions
exitWithError if qureg is not a density matrix, or if either qubit1 or qubit2 is outside [0, qureg.numQubitsRepresented), or if qubit1 = qubit2, or if prob is not in [0, 15/16]
Definition at line 670 of file QuEST.c.
References densmatr_twoQubitDepolarise(), ensureIndsIncrease(), validateDensityMatrQureg(), validateTwoQubitDepolProb(), and validateUniqueTargets().
{
     validateDensityMatrQureg(qureg, __func__);
     validateUniqueTargets(qureg, qubit1, qubit2, __func__);
     validateTwoQubitDepolProb(prob, __func__);
     ensureIndsIncrease(&qubit1, &qubit2);
     densmatr_twoQubitDepolarise(qureg, qubit1, qubit2, (16*prob)/15.0);
 }
calcFidelity()
qreal calcFidelity (Qureg qureg, Qureg pureState)
Calculates the fidelity of qureg (a statevector or density matrix) against a reference pure state (necessarily a statevector).
For two pure states, this is |<qureg|pureState>|^2. For a mixed and pure state, this is <pureState|qureg|pureState>. In either case, the fidelity lies in [0, 1]. The number of qubits represented in qureg and pureState must match.
Parameters
[in] qureg a density matrix or state vector
[in] pureState a state vector
Returns
the fidelity between the input registers
Exceptions
exitWithError if the dimensions qureg and pureState do not match
Definition at line 630 of file QuEST.c.
References densmatr_calcFidelity(), Qureg::isDensityMatrix, statevec_calcFidelity(), validateMatchingQuregDims(), and validateSecondQuregStateVec().
{
     validateSecondQuregStateVec(pureState, __func__);
     validateMatchingQuregDims(qureg, pureState, __func__);
     if (qureg.isDensityMatrix)
         return densmatr_calcFidelity(qureg, pureState);
     else
         return statevec_calcFidelity(qureg, pureState);
 }
calcInnerProduct()
Complex calcInnerProduct (Qureg bra, Qureg ket)
Computes <bra|ket>
Definition at line 606 of file QuEST.c.
References statevec_calcInnerProduct(), validateMatchingQuregDims(), and validateStateVecQureg().
{
     validateStateVecQureg(bra, __func__);
     validateStateVecQureg(ket, __func__);
     validateMatchingQuregDims(bra, ket,  __func__);
     return statevec_calcInnerProduct(bra, ket);
 }
calcProbOfOutcome()
qreal calcProbOfOutcome (Qureg qureg, const int measureQubit, int outcome)
Gives the probability of a specified qubit being measured in the given outcome (0 or 1).
This performs no actual measurement and does not change the state of the qubits.
Parameters
[in] qureg object representing the set of all qubits
[in] measureQubit qubit to study
[in] outcome for which to find the probability of the qubit being measured in
Returns
probability of qubit measureQubit being measured in the given outcome
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented), or if outcome is not in {0, 1}.
Definition at line 614 of file QuEST.c.
References densmatr_calcProbOfOutcome(), Qureg::isDensityMatrix, statevec_calcProbOfOutcome(), validateOutcome(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     validateOutcome(outcome, __func__);
     if (qureg.isDensityMatrix)
         return densmatr_calcProbOfOutcome(qureg, measureQubit, outcome);
     else
         return statevec_calcProbOfOutcome(qureg, measureQubit, outcome);
 }
calcPurity()
qreal calcPurity (Qureg qureg)
Calculates the purity of a density matrix, by the trace of the density matrix squared.
Returns . For a pure state, this =1. For a mixed state, the purity is less than 1 and is lower bounded by 1/2^n, where n is the number of qubits. The minimum purity is achieved for the maximally mixed state identity/2^n.
This function does not accept state-vectors, which clearly have purity 1.
Parameters
[in] qureg a density matrix of which to measure the purity
Returns
the purity
Exceptions
exitWithError if either combineQureg or otherQureg are not density matrices, or if the dimensions of combineQureg and otherQureg do not match, or if prob is not in [0, 1]
Definition at line 624 of file QuEST.c.
References densmatr_calcPurity(), and validateDensityMatrQureg().
{
     validateDensityMatrQureg(qureg, __func__);
     return densmatr_calcPurity(qureg);
 }
calcTotalProb()
qreal calcTotalProb (Qureg qureg)
A debugging function which calculates the probability of being in any state, which should always be 1.
For pure states, this is the norm of the entire state vector and for mixed states, is the trace of the density matrix. Note this calculation utilises Kahan summation for greaster accuracy, but is not parallelised and so will be slower than other functions.
Parameters
[in] qureg object representing a set of qubits
Returns
total probability
Definition at line 599 of file QuEST.c.
References densmatr_calcTotalProb(), Qureg::isDensityMatrix, and statevec_calcTotalProb().
{
     if (qureg.isDensityMatrix)
             return densmatr_calcTotalProb(qureg);
         else
             return statevec_calcTotalProb(qureg);
 }
clearRecordedQASM()
void clearRecordedQASM (Qureg qureg)
Clear all QASM so far recorded.
This does not start or stop recording
Definition at line 74 of file QuEST.c.
References qasm_clearRecorded().
{
     qasm_clearRecorded(qureg);
 }
cloneQureg()
void cloneQureg (Qureg targetQureg, Qureg copyQureg)
Set targetQureg to be a clone of copyQureg.
Registers must either both be state-vectors, or both be density matrices. Only the quantum state is cloned, auxilary info (like recorded QASM) is unchanged. copyQureg is unaffected.
Parameters
[in,out] targetQureg the qureg to have its quantum state overwritten
[in] copyQureg the qureg to have its quantum state cloned in targetQureg.
Definition at line 148 of file QuEST.c.
References statevec_cloneQureg(), validateMatchingQuregDims(), and validateMatchingQuregTypes().
{
     validateMatchingQuregTypes(targetQureg, copyQureg, __func__);
     validateMatchingQuregDims(targetQureg, copyQureg, __func__);
     statevec_cloneQureg(targetQureg, copyQureg);
 }
collapseToOutcome()
qreal collapseToOutcome (Qureg qureg, const int measureQubit, int outcome)
Updates the state vector to be consistent with measuring the measure qubit in the given outcome (0 or 1), and returns the probability of such a measurement outcome.
This is effectively performing a measurement and forcing the outcome. This is an irreversible change to the state vector, whereby incompatible states in the state vector are given zero amplitude and the remaining states are renormalised. Exits with error if the given outcome has ~zero probability, and so cannot be collapsed into.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[in] outcome to force the measure qubit to enter
Returns
probability of the (forced) measurement outcome
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented), or if outcome is not in {0, 1}, or if the probability of outcome is zero (within machine epsilon)
Definition at line 539 of file QuEST.c.
References densmatr_calcProbOfOutcome(), densmatr_collapseToKnownProbOutcome(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_calcProbOfOutcome(), statevec_collapseToKnownProbOutcome(), validateMeasurementProb(), validateOutcome(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     validateOutcome(outcome, __func__);
     qreal outcomeProb;
     if (qureg.isDensityMatrix) {
         outcomeProb = densmatr_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         densmatr_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     } else {
         outcomeProb = statevec_calcProbOfOutcome(qureg, measureQubit, outcome);
         validateMeasurementProb(outcomeProb, __func__);
         statevec_collapseToKnownProbOutcome(qureg, measureQubit, outcome, outcomeProb);
     }
     qasm_recordMeasurement(qureg, measureQubit);
     return outcomeProb;
 }
compactUnitary()
void compactUnitary (Qureg qureg, const int targetQubit, Complex alpha, Complex beta)
Apply a single-qubit unitary parameterised by two given complex scalars.
Given valid complex numbers and , applies the unitary
which is general up to a global phase factor.
Valid , satisfy .
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented), or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 280 of file QuEST.c.
References getConjugateScalar(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordCompactUnitary(), statevec_compactUnitary(), validateTarget(), and validateUnitaryComplexPair().
{
     validateTarget(qureg, targetQubit, __func__);
     validateUnitaryComplexPair(alpha, beta, __func__);
     statevec_compactUnitary(qureg, targetQubit, alpha, beta);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_compactUnitary(qureg, targetQubit+shift, getConjugateScalar(alpha), getConjugateScalar(beta));
     }
     qasm_recordCompactUnitary(qureg, alpha, beta, targetQubit);
 }
controlledCompactUnitary()
void controlledCompactUnitary (Qureg qureg, const int controlQubit, const int targetQubit, Complex alpha, Complex beta)
Apply a controlled unitary (single control, single target) parameterised by two given complex scalars.
Given valid complex numbers and , applies the two-qubit unitary
to the control and target qubits. Valid , satisfy . The target unitary is general up to a global phase factor.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit apply the target unitary if this qubit has value 1
[in] targetQubit qubit on which to apply the target unitary
[in] alpha complex unitary parameter (row 1, column 1)
[in] beta complex unitary parameter (row 2, column 1)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal, or if alpha, beta don't satisfy |alpha|^2 + |beta|^2 = 1.
Definition at line 293 of file QuEST.c.
References getConjugateScalar(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledCompactUnitary(), statevec_controlledCompactUnitary(), validateControlTarget(), and validateUnitaryComplexPair().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateUnitaryComplexPair(alpha, beta, __func__);
     statevec_controlledCompactUnitary(qureg, controlQubit, targetQubit, alpha, beta);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledCompactUnitary(qureg,
             controlQubit+shift, targetQubit+shift,
             getConjugateScalar(alpha), getConjugateScalar(beta));
     }
     qasm_recordControlledCompactUnitary(qureg, alpha, beta, controlQubit, targetQubit);
 }
controlledNot()
void controlledNot (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled not (single control, single target) gate, also known as the c-X, c-sigma-X, c-Pauli-X and c-bit-flip gate.
This applies pauliX to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit nots the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 400 of file QuEST.c.
References GATE_SIGMA_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledNot(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledNot(qureg, controlQubit, targetQubit);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledNot(qureg, controlQubit+shift, targetQubit+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_X, controlQubit, targetQubit);
 }
controlledPauliY()
void controlledPauliY (Qureg qureg, const int controlQubit, const int targetQubit)
Apply the controlled pauliY (single control, single target) gate, also known as the c-Y and c-sigma-Y gate.
This applies pauliY to the target qubit if the control qubit has value 1. This effects the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit applies pauliY to the target if this qubit is 1
[in] targetQubit qubit to not
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented), or are equal.
Definition at line 412 of file QuEST.c.
References GATE_SIGMA_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledPauliY(), statevec_controlledPauliYConj(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledPauliY(qureg, controlQubit, targetQubit);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPauliYConj(qureg, controlQubit+shift, targetQubit+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_Y, controlQubit, targetQubit);
 }
controlledPhaseFlip()
void controlledPhaseFlip (Qureg qureg, const int idQubit1, const int idQubit2)
Apply the (two-qubit) controlled phase flip gate, also known as the controlled pauliZ gate.
For each state, if both input qubits have value one, multiply the amplitude of that state by -1. This applies the two-qubit unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] idQubit1,idQubit2 qubits to operate upon
Exceptions
exitWithError if idQubit1 or idQubit2 are outside [0, qureg.numQubitsRepresented), or are equal
Definition at line 424 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledGate(), statevec_controlledPhaseFlip(), and validateControlTarget().
{
     validateControlTarget(qureg, idQubit1, idQubit2, __func__);
     statevec_controlledPhaseFlip(qureg, idQubit1, idQubit2);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPhaseFlip(qureg, idQubit1+shift, idQubit2+shift);
     }
     qasm_recordControlledGate(qureg, GATE_SIGMA_Z, idQubit1, idQubit2);
 }
controlledPhaseShift()
void controlledPhaseShift (Qureg qureg, const int idQubit1, const int idQubit2, qreal angle)
Introduce a phase factor on state of qubits idQubit1 and idQubit2.
For angle , this effects the unitary
on idQubit1 and idQubit2.
Parameters
[in,out] qureg object representing the set of all qubits
[in] idQubit1 first qubit in the state to phase shift
[in] idQubit2 second qubit in the state to phase shift
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if idQubit1 or idQubit2 are outside [0, qureg.numQubitsRepresented), or are equal
Definition at line 374 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledPhaseShift(), and validateControlTarget().
{
     validateControlTarget(qureg, idQubit1, idQubit2, __func__);
     statevec_controlledPhaseShift(qureg, idQubit1, idQubit2, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledPhaseShift(qureg, idQubit1+shift, idQubit2+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_PHASE_SHIFT, idQubit1, idQubit2, angle);
 }
controlledRotateAroundAxis()
void controlledRotateAroundAxis (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle, Vector axis)
Applies a controlled rotation by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies to states where the target qubit is 1 (is the vector of Pauli matrices).
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit with value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal or if axis is the zero vector
Definition at line 463 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledAxisRotation(), statevec_controlledRotateAroundAxis(), statevec_controlledRotateAroundAxisConj(), validateControlTarget(), and validateVector().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateVector(axis, __func__);
     statevec_controlledRotateAroundAxis(qureg, controlQubit, targetQubit, angle, axis);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateAroundAxisConj(qureg, controlQubit+shift, targetQubit+shift, angle, axis);
     }
     qasm_recordControlledAxisRotation(qureg, angle, axis, controlQubit, targetQubit);
 }
controlledRotateX()
void controlledRotateX (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the X-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 204 of file QuEST.c.
References GATE_ROTATE_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateX(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateX(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateX(qureg, controlQubit+shift, targetQubit+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_X, controlQubit, targetQubit, angle);
 }
controlledRotateY()
void controlledRotateY (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Y-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 216 of file QuEST.c.
References GATE_ROTATE_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateY(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateY(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateY(qureg, controlQubit+shift, targetQubit+shift, angle); // rotateY is real
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_Y, controlQubit, targetQubit, angle);
 }
controlledRotateZ()
void controlledRotateZ (Qureg qureg, const int controlQubit, const int targetQubit, qreal angle)
Applies a controlled rotation by a given angle around the Z-axis of the Bloch-sphere.
The target qubit is rotated in states where the control qubit has value 1.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit qubit which has value 1 in the rotated states
[in] targetQubit qubit to rotate
[in] angle angle by which to rotate the target qubit in radians
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal.
Definition at line 228 of file QuEST.c.
References GATE_ROTATE_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledParamGate(), statevec_controlledRotateZ(), and validateControlTarget().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     statevec_controlledRotateZ(qureg, controlQubit, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledRotateZ(qureg, controlQubit+shift, targetQubit+shift, -angle);
     }
     qasm_recordControlledParamGate(qureg, GATE_ROTATE_Z, controlQubit, targetQubit, angle);
 }
controlledUnitary()
void controlledUnitary (Qureg qureg, const int controlQubit, const int targetQubit, ComplexMatrix2 u)
Apply a general controlled unitary (single control, single target), which can include a global phase factor.
The given unitary is applied to the target qubit if the control qubit has value 1, effecting the two-qubit unitary
on the control and target qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubit apply unitary if this qubit is 1
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if either controlQubit or targetQubit are outside [0, qureg.numQubitsRepresented) or are equal, or if u is not unitary.
Definition at line 252 of file QuEST.c.
References getConjugateMatrix(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordControlledUnitary(), statevec_controlledUnitary(), validateControlTarget(), and validateUnitaryMatrix().
{
     validateControlTarget(qureg, controlQubit, targetQubit, __func__);
     validateUnitaryMatrix(u, __func__);
     statevec_controlledUnitary(qureg, controlQubit, targetQubit, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_controlledUnitary(qureg, controlQubit+shift, targetQubit+shift, getConjugateMatrix(u));
     }
     qasm_recordControlledUnitary(qureg, u, controlQubit, targetQubit);
 }
createDensityQureg()
Qureg createDensityQureg (int numQubits, QuESTEnv env)
Create a Qureg for qubits which are represented by a density matrix, and can be in mixed states.
Allocate space for a density matrix of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. initZeroState should be called after this to initialise the qubits to the zero pure state.
Returns
an object representing the set of qubits
Parameters
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions
exitWithError if numQubits <= 0
Definition at line 42 of file QuEST.c.
References initZeroState(), Qureg::isDensityMatrix, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, qasm_setup(), statevec_createQureg(), and validateCreateNumQubits().
{
     validateCreateNumQubits(numQubits, __func__);
     Qureg qureg;
     statevec_createQureg(&qureg, 2*numQubits, env);
     qureg.isDensityMatrix = 1;
     qureg.numQubitsRepresented = numQubits;
     qureg.numQubitsInStateVec = 2*numQubits;
     qasm_setup(&qureg);
     initZeroState(qureg);
     return qureg;
 }
createQuESTEnv()
QuESTEnv createQuESTEnv (void)
Create the QuEST execution environment.
This should be called only once, and the environment should be freed with destroyQuESTEnv at the end of the user's code. If something needs to be done to set up the execution environment, such as initializing MPI when running in distributed mode, it is handled here.
Returns
object representing the execution environment. A single instance is used for each program
createQureg()
Qureg createQureg (int numQubits, QuESTEnv env)
Create a Qureg object representing a set of qubits which will remain in a pure state.
Allocate space for state vector of probability amplitudes, including space for temporary values to be copied from one other chunk if running the distributed version. Define properties related to the size of the set of qubits. The qubits are initialised in the zero state (i.e. initZeroState is automatically called)
Returns
an object representing the set of qubits
Parameters
[in] numQubits number of qubits in the system
[in] env object representing the execution environment (local, multinode etc)
Exceptions
exitWithError if numQubits <= 0
Definition at line 28 of file QuEST.c.
References initZeroState(), Qureg::isDensityMatrix, Qureg::numQubitsInStateVec, Qureg::numQubitsRepresented, qasm_setup(), statevec_createQureg(), and validateCreateNumQubits().
{
     validateCreateNumQubits(numQubits, __func__);
     Qureg qureg;
     statevec_createQureg(&qureg, numQubits, env);
     qureg.isDensityMatrix = 0;
     qureg.numQubitsRepresented = numQubits;
     qureg.numQubitsInStateVec = numQubits;
     qasm_setup(&qureg);
     initZeroState(qureg);
     return qureg;
 }
destroyQuESTEnv()
void destroyQuESTEnv (QuESTEnv env)
Destroy the QuEST environment.
If something needs to be done to clean up the execution environment, such as finalizing MPI when running in distributed mode, it is handled here
Parameters
[in] env object representing the execution environment. A single instance is used for each program
destroyQureg()
void destroyQureg (Qureg qureg, QuESTEnv env)
Deallocate a Qureg object representing a set of qubits.
Free memory allocated to state vector of probability amplitudes, including temporary vector for values copied from another chunk if running the distributed version.
Parameters
[in,out] qureg object to be deallocated
[in] env object representing the execution environment (local, multinode etc)
Definition at line 56 of file QuEST.c.
References qasm_free(), and statevec_destroyQureg().
{
     statevec_destroyQureg(qureg, env);
     qasm_free(qureg);
 }
getAmp()
Complex getAmp (Qureg qureg, long long int index)
Getthe complex amplitude at a given index in the state vector.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
amplitude at index, returned as a Complex struct (with .real and .imag attributes)
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 512 of file QuEST.c.
References Complex::imag, Complex::real, statevec_getImagAmp(), statevec_getRealAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     Complex amp;
     amp.real = statevec_getRealAmp(qureg, index);
     amp.imag = statevec_getImagAmp(qureg, index);
     return amp;
 }
getDensityAmp()
Complex getDensityAmp (Qureg qureg, long long int row, long long int col)
Get an amplitude from a density matrix at a given row and column.
Parameters
[in] qureg object representing a density matrix
[in] row row of the desired amplitude in the density matrix
[in] col column of the desired amplitude in the density matrix
Returns
a Complex scalar representing the desired amplitude
Exceptions
exitWithError if qureg is a statevector, or if row or col are outside [0,) where qureg.numQubitsRepresented
Definition at line 522 of file QuEST.c.
References Qureg::numQubitsRepresented, Complex::real, statevec_getImagAmp(), statevec_getRealAmp(), validateDensityMatrQureg(), and validateStateIndex().
{
     validateDensityMatrQureg(qureg, __func__);
     validateStateIndex(qureg, row, __func__);
     validateStateIndex(qureg, col, __func__);
     long long ind = row + col*(1LL << qureg.numQubitsRepresented);
     Complex amp;
     amp.real = statevec_getRealAmp(qureg, ind);
     amp.imag = statevec_getImagAmp(qureg, ind);
     return amp;
 }
getEnvironmentString()
void getEnvironmentString (QuESTEnv env, Qureg qureg, char str[200])
getImagAmp()
qreal getImagAmp (Qureg qureg, long long int index)
Get the imaginary component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
imaginary component at that index
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 498 of file QuEST.c.
References statevec_getImagAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getImagAmp(qureg, index);
 }
getNumAmps()
int getNumAmps (Qureg qureg)
Get the number of probability amplitudes in a qureg object, given by 2^numQubits.
Definition at line 485 of file QuEST.c.
References Qureg::numAmpsTotal, and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     return qureg.numAmpsTotal;
 }
getNumQubits()
int getNumQubits (Qureg qureg)
Get the number of qubits in a qureg object.
Definition at line 481 of file QuEST.c.
References Qureg::numQubitsRepresented.
{
     return qureg.numQubitsRepresented;
 }
getProbAmp()
qreal getProbAmp (Qureg qureg, long long int index)
Get the probability of the state at an index in the full state vector.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
realEl*realEl + imagEl*imagEl
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 505 of file QuEST.c.
References statevec_getProbAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getProbAmp(qureg, index);
 }
getRealAmp()
qreal getRealAmp (Qureg qureg, long long int index)
Get the real component of the complex probability amplitude at an index in the state vector.
For debugging purposes.
Parameters
[in] qureg object representing a set of qubits
[in] index index in state vector of probability amplitudes
Returns
real component at that index
Exceptions
exitWithError if index is outside [0,) where qureg.numQubitsRepresented
Definition at line 491 of file QuEST.c.
References statevec_getRealAmp(), validateStateIndex(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateStateIndex(qureg, index, __func__);
     return statevec_getRealAmp(qureg, index);
 }
hadamard()
void hadamard (Qureg qureg, const int targetQubit)
Apply the single-qubit Hadamard gate.
This takes to and to , and is equivalent to a rotation of around the x-axis then about the y-axis on the Bloch-sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 160 of file QuEST.c.
References GATE_HADAMARD, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_hadamard(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_hadamard(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_hadamard(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_HADAMARD, targetQubit);
 }
initClassicalState()
void initClassicalState (Qureg qureg, long long int stateInd)
Initialise a set of qubits to the classical state with index stateInd.
Note has stateInd 0, has stateInd 1, has stateInd , etc. Subsequent calls to getProbAmp will yield 0 for all indices except stateInd.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] stateInd the index (0 to the number of amplitudes, exclusive) of the state to give probability 1
Definition at line 107 of file QuEST.c.
References densmatr_initClassicalState(), Qureg::isDensityMatrix, qasm_recordInitClassical(), statevec_initClassicalState(), and validateStateIndex().
{
     validateStateIndex(qureg, stateInd, __func__);
     if (qureg.isDensityMatrix)
         densmatr_initClassicalState(qureg, stateInd);
     else
         statevec_initClassicalState(qureg, stateInd);
     qasm_recordInitClassical(qureg, stateInd);
 }
initPlusState()
void initPlusState (Qureg qureg)
Initialise a set of qubits to the plus state .
This is the product state of qubits where every classical state is uniformly populated with real coefficient . This is equivalent to applying a Hadamard to every qubit in the zero state:
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
Definition at line 98 of file QuEST.c.
References densmatr_initPlusState(), Qureg::isDensityMatrix, qasm_recordInitPlus(), and statevec_initPlusState().
{
     if (qureg.isDensityMatrix)
         densmatr_initPlusState(qureg);
     else
         statevec_initPlusState(qureg);
     qasm_recordInitPlus(qureg);
 }
initPureState()
void initPureState (Qureg qureg, Qureg pure)
Initialise a set of qubits, which can be a state vector or density matrix, to a given pure state.
If qureg is a state-vector, this merely makes qureg an identical copy of pure. If qureg is a density matrix, this makes qureg 100% likely to be in the pure state.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] pure the pure state to be copied or to give probability 1 in qureg
Definition at line 119 of file QuEST.c.
References densmatr_initPureState(), Qureg::isDensityMatrix, qasm_recordComment(), statevec_cloneQureg(), validateMatchingQuregDims(), and validateSecondQuregStateVec().
{
     validateSecondQuregStateVec(pure, __func__);
     validateMatchingQuregDims(qureg, pure, __func__);
     if (qureg.isDensityMatrix)
         densmatr_initPureState(qureg, pure);
     else
         statevec_cloneQureg(qureg, pure);
     qasm_recordComment(qureg, "Here, the register was initialised to an undisclosed given pure state.");
 }
initStateFromAmps()
void initStateFromAmps (Qureg qureg, qreal * reals, qreal * imags)
Initialise qureg by specifying the complete statevector.
The real and imaginary components of the amplitudes are passed in separate arrays, each of which must have length qureg.numAmpsTotal. There is no automatic checking that the passed arrays are L2 normalised.
Parameters
[in,out] qureg the object representing the set of qubits to be initialised
[in] reals array of the real components of the new amplitudes
[in] imags array of the imaginary components of the new amplitudes
Exceptions
exitWithError if qureg is not a statevector (i.e. is a density matrix)
Definition at line 131 of file QuEST.c.
References Qureg::numAmpsTotal, qasm_recordComment(), statevec_setAmps(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     statevec_setAmps(qureg, 0, reals, imags, qureg.numAmpsTotal);
     qasm_recordComment(qureg, "Here, the register was initialised to an undisclosed given pure state.");
 }
initZeroState()
void initZeroState (Qureg qureg)
Initialise a set of qubits to the classical zero state .
Parameters
[in,out] qureg the object representing the set of all qubits to initialise
Definition at line 92 of file QuEST.c.
References qasm_recordInitZero(), and statevec_initZeroState().
Referenced by createDensityQureg(), and createQureg().
{
     statevec_initZeroState(qureg); // valid for both statevec and density matrices
     qasm_recordInitZero(qureg);
 }
measure()
int measure (Qureg qureg, int measureQubit)
Measures a single qubit, collapsing it randomly to 0 or 1.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 571 of file QuEST.c.
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), qreal, statevec_measureWithStats(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     qreal discardedProb;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, &discardedProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, &discardedProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
measureWithStats()
int measureWithStats (Qureg qureg, int measureQubit, qreal * outcomeProb)
Measures a single qubit, collapsing it randomly to 0 or 1, and additionally gives the probability of that outcome.
Outcome probabilities are weighted by the state vector, which is irreversibly changed after collapse to be consistent with the outcome.
Parameters
[in,out] qureg object representing the set of all qubits
[in] measureQubit qubit to measure
[out] outcomeProb a pointer to a qreal which is set to the probability of the occurred outcome
Returns
the measurement outcome, 0 or 1
Exceptions
exitWithError if measureQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 558 of file QuEST.c.
References densmatr_measureWithStats(), Qureg::isDensityMatrix, qasm_recordMeasurement(), statevec_measureWithStats(), and validateTarget().
{
     validateTarget(qureg, measureQubit, __func__);
     int outcome;
     if (qureg.isDensityMatrix)
         outcome = densmatr_measureWithStats(qureg, measureQubit, outcomeProb);
     else
         outcome = statevec_measureWithStats(qureg, measureQubit, outcomeProb);
     qasm_recordMeasurement(qureg, measureQubit);
     return outcome;
 }
multiControlledPhaseFlip()
void multiControlledPhaseFlip (Qureg qureg, int * controlQubits, int numControlQubits)
Apply the multiple-qubit controlled phase flip gate, also known as the multiple-qubit controlled pauliZ gate.
For each state, if all control qubits have value one, multiply the amplitude of that state by -1. This applies the many-qubit unitary:
on the control qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits array of input qubits
[in] numControlQubits number of input qubits
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented)
Definition at line 436 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledGate(), shiftIndices(), statevec_multiControlledPhaseFlip(), and validateMultiControls().
{
     validateMultiControls(qureg, controlQubits, numControlQubits, __func__);
     statevec_multiControlledPhaseFlip(qureg, controlQubits, numControlQubits);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(controlQubits, numControlQubits, shift);
         statevec_multiControlledPhaseFlip(qureg, controlQubits, numControlQubits);
         shiftIndices(controlQubits, numControlQubits, -shift);
     }
     qasm_recordMultiControlledGate(qureg, GATE_SIGMA_Z, controlQubits, numControlQubits-1, controlQubits[numControlQubits-1]);
 }
multiControlledPhaseShift()
void multiControlledPhaseShift (Qureg qureg, int * controlQubits, int numControlQubits, qreal angle)
Introduce a phase factor on state of the passed qubits.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits array of qubits to phase shift
[in] numControlQubits the length of array controlQubits
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit index in controlQubits is outside [0, qureg.numQubitsRepresented])
Definition at line 386 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledParamGate(), shiftIndices(), statevec_multiControlledPhaseShift(), and validateMultiControls().
{
     validateMultiControls(qureg, controlQubits, numControlQubits, __func__);
     statevec_multiControlledPhaseShift(qureg, controlQubits, numControlQubits, angle);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(controlQubits, numControlQubits, shift);
         statevec_multiControlledPhaseShift(qureg, controlQubits, numControlQubits, angle);
         shiftIndices(controlQubits, numControlQubits, -shift);
     }
     qasm_recordMultiControlledParamGate(qureg, GATE_PHASE_SHIFT, controlQubits, numControlQubits-1, controlQubits[numControlQubits-1], angle);
 }
multiControlledUnitary()
void multiControlledUnitary (Qureg qureg, int * controlQubits, const int numControlQubits, const int targetQubit, ComplexMatrix2 u)
Apply a general multiple-control single-target unitary, which can include a global phase factor.
Any number of control qubits can be specified, and if all have value 1, the given unitary is applied to the target qubit. This effects the many-qubit unitary
on the control and target qubits. The given 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] qureg object representing the set of all qubits
[in] controlQubits applies unitary if all qubits in this array equal 1
[in] numControlQubits number of control qubits
[in] targetQubit qubit to operate on
[in] u single-qubit unitary matrix to apply
Exceptions
exitWithError if numControlQubits is outside [1, qureg.numQubitsRepresented]), or if any qubit index (targetQubit or one in controlQubits) is outside [0, qureg.numQubitsRepresented]), or if controlQubits contains targetQubit, or if u is not unitary.
Definition at line 265 of file QuEST.c.
References getConjugateMatrix(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordMultiControlledUnitary(), shiftIndices(), statevec_multiControlledUnitary(), validateMultiControlsTarget(), and validateUnitaryMatrix().
{
     validateMultiControlsTarget(qureg, controlQubits, numControlQubits, targetQubit, __func__);
     validateUnitaryMatrix(u, __func__);
     statevec_multiControlledUnitary(qureg, controlQubits, numControlQubits, targetQubit, u);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         shiftIndices(controlQubits, numControlQubits, shift);
         statevec_multiControlledUnitary(qureg, controlQubits, numControlQubits, targetQubit+shift, getConjugateMatrix(u));
         shiftIndices(controlQubits, numControlQubits, -shift);
     }
     qasm_recordMultiControlledUnitary(qureg, u, controlQubits, numControlQubits, targetQubit);
 }
pauliX()
void pauliX (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-X (also known as the X, sigma-X, NOT or bit-flip) gate.
This is a rotation of around the x-axis on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 308 of file QuEST.c.
References GATE_SIGMA_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliX(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliX(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliX(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_X, targetQubit);
 }
pauliY()
void pauliY (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Y (also known as the Y or sigma-Y) gate.
This is a rotation of around the Y-axis on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 319 of file QuEST.c.
References GATE_SIGMA_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliY(), statevec_pauliYConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliY(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliYConj(qureg, targetQubit + qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_Y, targetQubit);
 }
pauliZ()
void pauliZ (Qureg qureg, const int targetQubit)
Apply the single-qubit Pauli-Z (also known as the Z, sigma-Z or phase-flip) gate.
This is a rotation of around the Z-axis (a phase shift) on the Bloch sphere. I.e.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 330 of file QuEST.c.
References GATE_SIGMA_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_pauliZ(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_pauliZ(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_pauliZ(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_SIGMA_Z, targetQubit);
 }
phaseShift()
void phaseShift (Qureg qureg, const int targetQubit, qreal angle)
Shift the phase between and of a single qubit by a given angle.
This is equivalent to a rotation Z-axis of the Bloch-sphere up to a global phase factor. For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to undergo a phase shift
[in] angle amount by which to shift the phase in radians
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 363 of file QuEST.c.
References GATE_PHASE_SHIFT, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_phaseShift(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_phaseShift(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_phaseShift(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_PHASE_SHIFT, targetQubit, angle);
 }
printRecordedQASM()
void printRecordedQASM (Qureg qureg)
Print recorded QASM to stdout.
Definition at line 78 of file QuEST.c.
References qasm_printRecorded().
{
     qasm_printRecorded(qureg);
 }
reportQuESTEnv()
void reportQuESTEnv (QuESTEnv env)
Report information about the QuEST environment.
Parameters
[in] env object representing the execution environment. A single instance is used for each program
reportQuregParams()
void reportQuregParams (Qureg qureg)
Report metainformation about a set of qubits: number of qubits, number of probability amplitudes.
Parameters
[in] qureg object representing the set of qubits
Definition at line 191 of file QuEST_common.c.
References Qureg::chunkId, Qureg::numChunks, and Qureg::numQubitsInStateVec.
{
     long long int numAmps = 1L << qureg.numQubitsInStateVec;
     long long int numAmpsPerRank = numAmps/qureg.numChunks;
     if (qureg.chunkId==0){
         printf("QUBITS:\n");
         printf("Number of qubits is %d.\n", qureg.numQubitsInStateVec);
         printf("Number of amps is %lld.\n", numAmps);
         printf("Number of amps per rank is %lld.\n", numAmpsPerRank);
     }
 }
reportState()
void reportState (Qureg qureg)
Print the current state vector of probability amplitudes for a set of qubits to file.
File format:
real, imag
realComponent1, imagComponent1
realComponent2, imagComponent2
...
realComponentN, imagComponentN
File naming convention:
For each node that the program runs on, a file 'state_rank_[node_rank].csv' is generated. If there is more than one node, ranks after the first do not include the header
real, imag
so that files are easier to combine.
Parameters
[in,out] qureg object representing the set of qubits
Definition at line 173 of file QuEST_common.c.
References Qureg::chunkId, Qureg::numAmpsPerChunk, and Qureg::stateVec.
{
     FILE *state;
     char filename[100];
     long long int index;
     sprintf(filename, "state_rank_%d.csv", qureg.chunkId);
     state = fopen(filename, "w");
     if (qureg.chunkId==0) fprintf(state, "real, imag\n");
     for(index=0; index<qureg.numAmpsPerChunk; index++){
         # if QuEST_PREC==1 || QuEST_PREC==2
         fprintf(state, "%.12f, %.12f\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
         # elif QuEST_PREC == 4
         fprintf(state, "%.12Lf, %.12Lf\n", qureg.stateVec.real[index], qureg.stateVec.imag[index]);
         #endif
     }
     fclose(state);
 }
reportStateToScreen()
void reportStateToScreen (Qureg qureg, QuESTEnv env, int reportRank)
Print the current state vector of probability amplitudes for a set of qubits to standard out.
For debugging purposes. Each rank should print output serially. Only print output for systems <= 5 qubits
Definition at line 705 of file QuEST.c.
References statevec_reportStateToScreen().
{
     statevec_reportStateToScreen(qureg, env, reportRank);
 }
rotateAroundAxis()
void rotateAroundAxis (Qureg qureg, const int rotQubit, qreal angle, Vector axis)
Rotate a single qubit by a given angle around a given vector on the Bloch-sphere.
The vector must not be zero (else an error is thrown), but needn't be unit magnitude.
For angle and axis vector , applies where is the vector of Pauli matrices.
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
[in] axis vector around which to rotate (can be non-unit; will be normalised)
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented), or if axis is the zero vector
Definition at line 450 of file QuEST.c.
References Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordAxisRotation(), statevec_rotateAroundAxis(), statevec_rotateAroundAxisConj(), validateTarget(), and validateVector().
{
     validateTarget(qureg, rotQubit, __func__);
     validateVector(axis, __func__);
     statevec_rotateAroundAxis(qureg, rotQubit, angle, axis);
     if (qureg.isDensityMatrix) {
         int shift = qureg.numQubitsRepresented;
         statevec_rotateAroundAxisConj(qureg, rotQubit+shift, angle, axis);
     }
     qasm_recordAxisRotation(qureg, angle, axis, rotQubit);
 }
rotateX()
void rotateX (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the X-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 171 of file QuEST.c.
References GATE_ROTATE_X, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateX(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateX(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateX(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_X, targetQubit, angle);
 }
rotateY()
void rotateY (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Y-axis of the Bloch-sphere.
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 182 of file QuEST.c.
References GATE_ROTATE_Y, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateY(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateY(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateY(qureg, targetQubit+qureg.numQubitsRepresented, angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_Y, targetQubit, angle);
 }
rotateZ()
void rotateZ (Qureg qureg, const int rotQubit, qreal angle)
Rotate a single qubit by a given angle around the Z-axis of the Bloch-sphere (also known as a phase shift gate).
For angle , applies
Parameters
[in,out] qureg object representing the set of all qubits
[in] rotQubit qubit to rotate
[in] angle angle by which to rotate in radians
Exceptions
exitWithError if rotQubit is outside [0, qureg.numQubitsRepresented).
Definition at line 193 of file QuEST.c.
References GATE_ROTATE_Z, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordParamGate(), statevec_rotateZ(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_rotateZ(qureg, targetQubit, angle);
     if (qureg.isDensityMatrix) {
         statevec_rotateZ(qureg, targetQubit+qureg.numQubitsRepresented, -angle);
     }
     qasm_recordParamGate(qureg, GATE_ROTATE_Z, targetQubit, angle);
 }
seedQuEST()
void seedQuEST (unsigned long int * seedArray, int numSeeds)
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
This function uses the mt19937 init_by_array function with numSeeds keys supplied by the user. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
Parameters
[in] seedArray Array of integers to use as seed. This allows the MT to be initialised with more than a 32-bit integer if required
[in] numSeeds Length of seedArray
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Seed the Mersenne Twister used for random number generation in the QuEST environment with a user defined seed.
Definition at line 160 of file QuEST_common.c.
References init_by_array().
{
     // init MT random number generator with user defined list of seeds
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     init_by_array(seedArray, numSeeds);
 }
seedQuESTDefault()
void seedQuESTDefault (void)
Seed the Mersenne Twister used for random number generation in the QuEST environment with an example defualt seed.
This default seeding function uses the mt19937 init_by_array function with three keys – time, pid and hostname. Subsequent calls to mt19937 genrand functions will use this seeding. For a multi process code, the same seed is given to all process, therefore this seeding is only appropriate to use for functions such as measure where all processes require the same random value.
For more information about the MT, see http://www.math.sci.hiroshima-u.ac.jp/~m-mat/MT/MT2002/emt19937ar.html
Definition at line 135 of file QuEST_common.c.
References hashString(), and init_by_array().
{
     // init MT random number generator with three keys -- time, pid and a hash of hostname
     // for the MPI version, it is ok that all procs will get the same seed as random numbers will only be
     // used by the master process
     struct timeval  tv;
     gettimeofday(&tv, NULL);
     double time_in_mill =
         (tv.tv_sec) * 1000 + (tv.tv_usec) / 1000 ; // convert tv_sec & tv_usec to millisecond
     unsigned long int pid = getpid();
     unsigned long int msecs = (unsigned long int) time_in_mill;
     char hostName[MAXHOSTNAMELEN+1];
     gethostname(hostName, sizeof(hostName));
     unsigned long int hostNameInt = hashString(hostName);
     unsigned long int key[3];
     key[0] = msecs; key[1] = pid; key[2] = hostNameInt;
     init_by_array(key, 3);
 }
setAmps()
void setAmps (Qureg qureg, long long int startInd, qreal * reals, qreal * imags, long long int numAmps)
Edit qureg to adopt the subset of amplitudes passed in reals and imags.
Only amplitudes with indices in [startInd, startInd + numAmps] will be changed, which means the new state may not be L2 normalised. This allows the user to initialise a custom state by setting batches of amplitudes.
Parameters
[in,out] qureg the statevector to modify
[in] startInd the index of the first amplitude in qureg's statevector to modify
[in] reals array of the real components of the new amplitudes
[in] imags array of the imaginary components of the new amplitudes
[in] numAmps the length of each of the reals and imags arrays.
Exceptions
exitWithError if qureg is not a statevector (i.e. is a density matrix)
Definition at line 139 of file QuEST.c.
References qasm_recordComment(), statevec_setAmps(), validateNumAmps(), and validateStateVecQureg().
{
     validateStateVecQureg(qureg, __func__);
     validateNumAmps(qureg, startInd, numAmps, __func__);
     statevec_setAmps(qureg, startInd, reals, imags, numAmps);
     qasm_recordComment(qureg, "Here, some amplitudes in the statevector were manually edited.");
 }
sGate()
void sGate (Qureg qureg, const int targetQubit)
Apply the single-qubit S gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 341 of file QuEST.c.
References GATE_S, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_sGate(), statevec_sGateConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_sGate(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_sGateConj(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_S, targetQubit);
 }
startRecordingQASM()
void startRecordingQASM (Qureg qureg)
Enable QASM recording.
Gates applied to qureg will here-after be added to growing QASM instructions, progressively consuming more memory until stopped
Definition at line 66 of file QuEST.c.
References qasm_startRecording().
{
     qasm_startRecording(qureg);
 }
stopRecordingQASM()
void stopRecordingQASM (Qureg qureg)
Disable QASM recording.
The recorded QASM will be maintained in qureg and continue to be added to if startRecordingQASM is recalled.
Definition at line 70 of file QuEST.c.
References qasm_stopRecording().
{
     qasm_stopRecording(qureg);
 }
syncQuESTEnv()
void syncQuESTEnv (QuESTEnv env)
Guarantees that all code up to the given point has been executed on all nodes (if running in distributed mode)
Parameters
[in] env object representing the execution environment. A single instance is used for each program
syncQuESTSuccess()
int syncQuESTSuccess (int successCode)
Performs a logical AND on all successCodes held by all processes.
If any one process has a zero successCode all processes will return a zero success code.
Parameters
[in] successCode 1 if process task succeeded, 0 if process task failed
Returns
1 if all processes succeeded, 0 if any one process failed
tGate()
void tGate (Qureg qureg, const int targetQubit)
Apply the single-qubit T gate.
This is a rotation of around the Z-axis on the Bloch sphere, or the unitary:
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate upon
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented)
Definition at line 352 of file QuEST.c.
References GATE_T, Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordGate(), statevec_tGate(), statevec_tGateConj(), and validateTarget().
{
     validateTarget(qureg, targetQubit, __func__);
     statevec_tGate(qureg, targetQubit);
     if (qureg.isDensityMatrix) {
         statevec_tGateConj(qureg, targetQubit+qureg.numQubitsRepresented);
     }
     qasm_recordGate(qureg, GATE_T, targetQubit);
 }
unitary()
void unitary (Qureg qureg, const int targetQubit, ComplexMatrix2 u)
Apply a general single-qubit unitary (including a global phase factor).
The passed 2x2 ComplexMatrix must be unitary, otherwise an error is thrown.
Parameters
[in,out] qureg object representing the set of all qubits
[in] targetQubit qubit to operate on
[in] u unitary matrix to apply
Exceptions
exitWithError if targetQubit is outside [0, qureg.numQubitsRepresented), or matrix u is not unitary.
Definition at line 240 of file QuEST.c.
References getConjugateMatrix(), Qureg::isDensityMatrix, Qureg::numQubitsRepresented, qasm_recordUnitary(), statevec_unitary(), validateTarget(), and validateUnitaryMatrix().
{
     validateTarget(qureg, targetQubit, __func__);
     validateUnitaryMatrix(u, __func__);
     statevec_unitary(qureg, targetQubit, u);
     if (qureg.isDensityMatrix) {
         statevec_unitary(qureg, targetQubit+qureg.numQubitsRepresented, getConjugateMatrix(u));
     }
     qasm_recordUnitary(qureg, u, targetQubit);
 }
writeRecordedQASMToFile()
void writeRecordedQASMToFile (Qureg qureg, char * filename)
Writes recorded QASM to a file, throwing an error if inaccessible.
Definition at line 82 of file QuEST.c.
References qasm_writeRecordedToFile(), and validateFileOpened().
{
     int success = qasm_writeRecordedToFile(qureg, filename);
     validateFileOpened(success, __func__);
 }