# CPack policy is separate from build and install policy. Include after install().
include_guard(DIRECTORY)
if(NOT QUEST_ENABLE_PACKAGING)
  return()
endif()
if(NOT QUEST_ENABLE_INSTALL)
  message(FATAL_ERROR "QUEST_ENABLE_PACKAGING requires QUEST_ENABLE_INSTALL.")
endif()

macro(_quest_cpack_default name value)
  if(NOT DEFINED ${name})
    set(${name} "${value}")
  endif()
endmacro()

file(STRINGS "${PROJECT_SOURCE_DIR}/AUTHORS.txt" _quest_contact REGEX "^Contact:")
string(REGEX REPLACE "^Contact:[ \t]*" "" _quest_contact "${_quest_contact}")
_quest_cpack_default(CPACK_PACKAGE_NAME "QuEST")
_quest_cpack_default(CPACK_PACKAGE_VENDOR "The QuEST Authors and Contributors")
_quest_cpack_default(CPACK_PACKAGE_CONTACT "${_quest_contact}")
_quest_cpack_default(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
_quest_cpack_default(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Quantum Exact Simulation Toolkit")
_quest_cpack_default(CPACK_PACKAGE_DESCRIPTION "QuEST is a high performance simulator of quantum circuits, state vectors and density matrices.")
_quest_cpack_default(CPACK_PACKAGE_HOMEPAGE_URL "https://quest.qtechtheory.org/")
_quest_cpack_default(CPACK_RESOURCE_FILE_LICENSE "${PROJECT_SOURCE_DIR}/LICENCE.txt")
_quest_cpack_default(CPACK_OUTPUT_CONFIG_FILE "${PROJECT_BINARY_DIR}/CPackConfig.cmake")
_quest_cpack_default(CPACK_SOURCE_OUTPUT_CONFIG_FILE "${PROJECT_BINARY_DIR}/CPackSourceConfig.cmake")
_quest_cpack_default(CPACK_GENERATOR "TGZ;ZIP")
_quest_cpack_default(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
_quest_cpack_default(CPACK_SOURCE_INSTALLED_DIRECTORIES "${PROJECT_SOURCE_DIR};/")
_quest_cpack_default(CPACK_SOURCE_PACKAGE_FILE_NAME "QuEST-${PROJECT_VERSION}-Source")
_quest_cpack_default(CPACK_PACKAGE_DIRECTORY "${PROJECT_BINARY_DIR}/packages")
if(NOT DEFINED CPACK_PACKAGING_INSTALL_PREFIX)
  set(CPACK_QUEST_DEFAULT_PREFIX "${CMAKE_INSTALL_PREFIX}")
  set(CPACK_PACKAGING_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
endif()
_quest_cpack_default(CPACK_INSTALL_CMAKE_PROJECTS "${PROJECT_BINARY_DIR};${PROJECT_NAME};ALL;/")
# Escape generated CMake strings, including user paths with spaces or backslashes.
set(CPACK_VERBATIM_VARIABLES YES)

set(QUEST_NATIVE_PACKAGE_PROFILE "" CACHE STRING "Native packaging profile: ubuntu24.04, fedora44, or custom")
set_property(CACHE QUEST_NATIVE_PACKAGE_PROFILE PROPERTY STRINGS "" ubuntu24.04 fedora44 custom)
set(CPACK_QUEST_NATIVE_PROFILE "${QUEST_NATIVE_PACKAGE_PROFILE}")
if(NOT CPACK_QUEST_NATIVE_PROFILE AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  cmake_host_system_information(RESULT _quest_os QUERY DISTRIB_INFO)
  if(_quest_os_ID STREQUAL "ubuntu" AND _quest_os_VERSION_ID STREQUAL "24.04")
    set(CPACK_QUEST_NATIVE_PROFILE ubuntu24.04)
  elseif(_quest_os_ID STREQUAL "fedora" AND _quest_os_VERSION_ID STREQUAL "44")
    set(CPACK_QUEST_NATIVE_PROFILE fedora44)
  endif()
endif()
set(CPACK_QUEST_BUILT_SHARED "${QUEST_BUILT_SHARED}")
set(CPACK_QUEST_HAVE_EXAMPLES "${QUEST_HAVE_INSTALLABLE_EXAMPLES}")
set(CPACK_QUEST_MPI_LIBRARIES "${MPI_CXX_LIBRARIES}")
set(CPACK_QUEST_COMPILER_ID "${CMAKE_CXX_COMPILER_ID}")
set(CPACK_QUEST_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}")
set(CPACK_QUEST_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")
set(CPACK_QUEST_INSTALL_LIBDIR "${CMAKE_INSTALL_LIBDIR}")
set(CPACK_QUEST_INSTALL_BINDIR "${CMAKE_INSTALL_BINDIR}")
set(CPACK_QUEST_INSTALL_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}")
set(CPACK_QUEST_BUILD_CONFIG "${CMAKE_BUILD_TYPE}")
set(CPACK_QUEST_MULTI_CONFIG "${CMAKE_CONFIGURATION_TYPES}")
set(CPACK_QUEST_COMPONENTS Development)
if(QUEST_BUILT_SHARED)
  list(PREPEND CPACK_QUEST_COMPONENTS Runtime)
  set(_quest_linkage shared)
else()
  set(_quest_linkage static)
endif()
if(QUEST_HAVE_INSTALLABLE_EXAMPLES)
  list(APPEND CPACK_QUEST_COMPONENTS Examples)
endif()
set(_quest_backends cpu)
foreach(_quest_feature OMP NUMA MPI SUBCOMM CUDA HIP CUQUANTUM ADIOS2 BMI2 DEPRECATED_API)
  set(CPACK_QUEST_ENABLE_${_quest_feature} "${QUEST_ENABLE_${_quest_feature}}")
  if(QUEST_ENABLE_${_quest_feature})
    string(TOLOWER "${_quest_feature}" _quest_feature_lower)
    string(APPEND _quest_backends "-${_quest_feature_lower}")
  endif()
endforeach()
set(CPACK_QUEST_NAME_PREFIX "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_QUEST_NAME_SUFFIX "${_quest_linkage}-fp${QUEST_FLOAT_PRECISION}-${_quest_backends}")
# Let -C select the configuration at packaging time without losing explicit names.
if(NOT DEFINED CPACK_PACKAGE_FILE_NAME)
  if(CMAKE_BUILD_TYPE)
    set(_quest_default_config "${CMAKE_BUILD_TYPE}")
  else()
    set(_quest_default_config NoConfig)
  endif()
  set(CPACK_QUEST_DEFAULT_NAME "${CPACK_QUEST_NAME_PREFIX}-${_quest_default_config}-${CPACK_QUEST_NAME_SUFFIX}")
  set(CPACK_PACKAGE_FILE_NAME "${CPACK_QUEST_DEFAULT_NAME}")
endif()

# Only QuEST components are packaged, even if an external subproject installs files.
set(CPACK_COMPONENTS_ALL "${CPACK_QUEST_COMPONENTS}")
_quest_cpack_default(CPACK_COMPONENT_RUNTIME_DESCRIPTION "QuEST shared runtime library")
_quest_cpack_default(CPACK_COMPONENT_DEVELOPMENT_DESCRIPTION "QuEST headers, libraries and CMake package")
_quest_cpack_default(CPACK_COMPONENT_EXAMPLES_DESCRIPTION "QuEST example programs")

# Default exclusions are appended to packager exclusions: never ship local build state.
set(_quest_source_ignore_patterns
  "/[.]git(/|$)" "/[.]hg(/|$)" "/[.]svn(/|$)"
  "/[.]worktrees(/|$)" "/[.]cache(/|$)"
  "/build[^/]*(/|$)" "/cmake-build[^/]*(/|$)" "/_deps(/|$)"
  "/_CPack_Packages(/|$)" "/packages(/|$)" "/CMakeFiles(/|$)"
  "/CMakeCache[.]txt$" "/CMakeUserPresets[.]json$" "/CPack[^/]*[.]cmake$"
  "/[^/]*[.](deb|rpm|zip|tar[.]gz)$" "/__pycache__(/|$)")
# Match entries inside this source tree, never similarly named checkout ancestors.
string(REGEX REPLACE "([][+.*()^$?\\\\|])" "[\\1]" _quest_source_regex "${PROJECT_SOURCE_DIR}")
foreach(_quest_pattern IN LISTS _quest_source_ignore_patterns)
  list(APPEND CPACK_SOURCE_IGNORE_FILES "^${_quest_source_regex}(/[^/]+)*${_quest_pattern}")
endforeach()
# Detect arbitrary existing in-tree build directory names rather than assuming build/.
file(GLOB_RECURSE _quest_source_caches LIST_DIRECTORIES FALSE "${PROJECT_SOURCE_DIR}/*CMakeCache.txt")
set(_quest_exclude_dirs "${PROJECT_BINARY_DIR}" "${CPACK_PACKAGE_DIRECTORY}")
foreach(_quest_cache IN LISTS _quest_source_caches)
  get_filename_component(_quest_cache_dir "${_quest_cache}" DIRECTORY)
  list(APPEND _quest_exclude_dirs "${_quest_cache_dir}")
endforeach()
foreach(_quest_dir IN LISTS _quest_exclude_dirs)
  if(NOT _quest_dir STREQUAL PROJECT_SOURCE_DIR)
    # Bracket classes avoid backslash escaping in the generated CPack config.
    string(REGEX REPLACE "([][+.*()^$?\\\\|])" "[\\1]" _quest_dir_regex "${_quest_dir}")
    list(APPEND CPACK_SOURCE_IGNORE_FILES "^${_quest_dir_regex}(/|$)")
  endif()
endforeach()
list(REMOVE_DUPLICATES CPACK_SOURCE_IGNORE_FILES)

# Wrap an existing hook: packager settings are loaded before QuEST defaults/checks.
set(CPACK_QUEST_USER_PROJECT_CONFIG "${CPACK_PROJECT_CONFIG_FILE}")
configure_file("${CMAKE_CURRENT_LIST_DIR}/QuESTCPackOptions.cmake.in"
  "${PROJECT_BINARY_DIR}/QuESTCPackOptions.cmake" COPYONLY)
set(CPACK_PROJECT_CONFIG_FILE "${PROJECT_BINARY_DIR}/QuESTCPackOptions.cmake")
configure_file("${CMAKE_CURRENT_LIST_DIR}/QuESTCPackMPI.cmake.in"
  "${PROJECT_BINARY_DIR}/QuESTCPackMPI.cmake" COPYONLY)
set(CPACK_QUEST_MPI_POLICY "${PROJECT_BINARY_DIR}/QuESTCPackMPI.cmake")
configure_file("${CMAKE_CURRENT_LIST_DIR}/QuESTCPackStage.cmake.in"
  "${PROJECT_BINARY_DIR}/QuESTCPackStage.cmake" COPYONLY)
list(APPEND CPACK_PRE_BUILD_SCRIPTS "${PROJECT_BINARY_DIR}/QuESTCPackStage.cmake")
configure_file("${CMAKE_CURRENT_LIST_DIR}/QuESTCPackVerify.cmake.in"
  "${PROJECT_BINARY_DIR}/QuESTCPackVerify.cmake" COPYONLY)
list(APPEND CPACK_POST_BUILD_SCRIPTS "${PROJECT_BINARY_DIR}/QuESTCPackVerify.cmake")
include(CPack)
