# inspiration here:
# https://github.com/MarkSchofield/WindowsToolchain/blob/main/.github/workflows/ci.yaml

name: Windows CUDA (via choco) test

# huh it doesn't appear under manual workflows yet!
on:
    push:
      branches:
        - ci-compiling
    pull_request:
      branches:
        - ci-compiling

jobs:

  # test only compilation succeeds (no execution)
  build-test:
    name: Testing compilation
    runs-on: windows-latest

    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      - name: Install CUDA
        shell: pwsh
        run: |
          choco install cuda
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyInstaller.psm1"
          Update-SessionEnvironment
          "CUDA_PATH=$env:CUDA_PATH" >> $env:GITHUB_ENV

      - name: Configure CMake
        shell: pwsh
        run: >
          cmake -B build
          -DENABLE_CUDA=ON
          -DCMAKE_CUDA_ARCHITECTURES=70

      - name: Compile
        shell: pwsh
        run: >
          cmake --build build
