name: Compilation

on:
  push:
    branches:
      - ci-compiling
  pull_request:
    branches:
      - ci-compiling

jobs:

  # test only compilation succeeds (no execution)
  build-test:
    name: Testing compilation
    runs-on: ${{ matrix.os }}

    strategy:

      # continue other jobs if any fail
      fail-fast: false

      # perform job for all combinations of...
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        precision: [1, 2, 4]
        omp: [ON, OFF]

        # assign each OS a bespoke compiler
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: clang++
          - os: windows-latest
            compiler: cl

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      - name: Make build directory
        run: mkdir build_dir

      - name: Configure CMake
        working-directory: build_dir
        run: >
          cmake .. 
          -DENABLE_MULTITHREADING=${{ matrix.omp }}
          -DFLOAT_PRECISION=${{ matrix.precision }}
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Compile
        run: >
          cmake --build build_dir

