name: Compilation

on:
  push:
    branches:
      - ci-compiling
  pull_request:
    branches:
      - ci-compiling

jobs:

  # test only compilation succeeds (no execution)
  build-test:
    name: Testing compilation
    runs-on: ${{ matrix.os }}

    strategy:
      # continue other jobs if any fail
      fail-fast: false

      # perform job for all combinations of...
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        precision: [1, 2, 4]
        multithreading: [ON, OFF]
        distribution: [ON, OFF]

        # assign each OS a bespoke compiler
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: clang++
          - os: windows-latest
            compiler: cl

    # constants
    env:
      build_dir: "build"

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      # obtain OMP for Clang multithreading
      - name: Install libomp 
        if: ${{ matrix.compiler == 'clang++' && matrix.multithreading == 'ON' }}
        run: >
          brew install libomp;
          echo "OpenMP_ROOT=$(brew --prefix)/opt/libomp" >> $GITHUB_ENV

      # obtain MPI for distribution
      - name: Setup MPI
        if: ${{ matrix.distribution == 'ON' }}
        uses: mpi4py/setup-mpi@v1

      - name: Configure CMake
        run: >
          cmake -B ${{ env.build_dir }}
          -DENABLE_MULTITHREADING=${{ matrix.multithreading }}
          -DENABLE_DISTRIBUTION=${{ matrix.distribution }}
          -DFLOAT_PRECISION=${{ matrix.precision }}
          -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}

      - name: Compile
        run: >
          cmake --build ${{ env.build_dir }}

