# ### THIS IS WORKING BEAUTIFULLY!


# name: CUBLAS test

# on:
#   push:
#     branches:
#       - ci-compiling

# jobs:

#   # test only compilation succeeds (no execution)
#   build-test:
#     name: Testing compilation
#     runs-on: ubuntu-latest

#     steps:
#       - name: Get QuEST
#         uses: actions/checkout@v4

#       - name: Install CUDA
#         uses: Jimver/cuda-toolkit@v0.2.21
#         with:
#           method: network
#           sub-packages: '["nvcc", "cudart", "thrust"]'
#           non-cuda-sub-packages: '["libcublas"]'

#       - name: Obtain cuQuantum
#         run: >
#           wget https://developer.download.nvidia.com/compute/cuquantum/redist/cuquantum/linux-x86_64/cuquantum-linux-x86_64-24.08.0.5_cuda12-archive.tar.xz;
#           tar -xvf cuquantum-linux-x86_64-24.08.0.5_cuda12-archive.tar.xz;
#           echo "CUQUANTUM_ROOT=cuquantum-linux-x86_64-24.08.0.5_cuda12-archive" >> $GITHUB_ENV

#       - name: Configure CMake
#         run: >
#           cmake -B build
#           -DENABLE_CUDA=ON
#           -DENABLE_CUQUANTUM=ON
#           -DCMAKE_CUDA_ARCHITECTURES=70

#       - name: Compile
#         run: >
#           cmake --build build
