name: NVCC Windows test

on:
  push:
    branches:
      - ci-compiling

jobs:

  # test only compilation succeeds (no execution)
  build-test:
    name: Testing compilation
    runs-on: windows-2019

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      # obtain CUDA for GPU acceleration (cublas only needed for cuQuantum)
      - name: Obtain CUDA
        uses: Jimver/cuda-toolkit@v0.2.21
        id: cuda-toolkit
        with:
          cuda: '12.5.0'
          method: network
          sub-packages: '["nvcc", "cudart", "thrust"]'

      # invoke cmake, disabling LTO (it duplicates symbols with CUDA+MPI)
      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_FLAGS="-fno-lto ${CMAKE_CXX_FLAGS}"
          -DENABLE_CUDA=ON
          -DCMAKE_CUDA_ARCHITECTURES=70
          -DCMAKE_GENERATOR_TOOLSET="cuda=${{steps.cuda-toolkit.outputs.CUDA_PATH}}"

      - name: Compile
        run: >
          cmake --build build