# THIS JUST SIMPLY WILL NOT WORK!
# cuda is installed fine, but CMake is passing ill-formed commands to NVCC when
# attempting to compile gpu_config and gpu_subroutines, and I cannot determine why!




name: NVCC Windows test

on:
  push:
    branches:
      - ci-compiling

jobs:

  # test only compilation succeeds (no execution)
  build-test:
    name: Testing compilation
    runs-on: windows-latest

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      # obtain CUDA for GPU acceleration
      # NOTE:
      # - cuQuantum (Linux only) requires: non-cuda-sub-packages: '["libcublas"]'
      # - Windows requires additional sub-package: "visual_studio_integration"

      - name: Obtain CUDA
        uses: Jimver/cuda-toolkit@v0.2.21
        id: cuda-toolkit
        with:
          method: network
          sub-packages: '["nvcc", "cudart", "thrust", "visual_studio_integration"]'

      # invoke cmake, disabling LTO (it duplicates symbols with CUDA+MPI)
      - name: Configure CMake
        run: >
          cmake -B build
          -DCMAKE_CXX_FLAGS="-fno-lto ${CMAKE_CXX_FLAGS}"
          -DENABLE_CUDA=ON
          -DCMAKE_CUDA_ARCHITECTURES=70
        
      - name: Compile
        run: >
          cmake --build build --verbose
