name: HIP compile



# disabled since confirmed workin
on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      build_dir: "build"
      hip_arch: gfx801
      rocm_dir: /opt/rocm
      path_dir: /opt/rocm/bin

    steps:

      # free space for big ROCm installer
      - name: Free disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

      # then obtain QuEST
      - name: Get QuEST
        uses: actions/checkout@v4

      # download and install ROCm (takes about 10 minutes)
      - name: Install ROCm
        run: |
          sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
          sudo apt install python3-setuptools python3-wheel
          sudo usermod -a -G render,video $USER
          wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
          sudo apt install ./amdgpu-install_6.3.60303-1_all.deb
          sudo apt update
          sudo apt install amdgpu-dkms rocm

      - name: Update path
        run: echo "${{ env.path_dir }}" >> $GITHUB_PATH

      - name: Show version
        run: hipcc --version
      
      - name: Configure CMake
        run: >
          cmake -B ${{ env.build_dir }}
          -DBUILD_EXAMPLES=ON
          -DENABLE_TESTING=ON
          -DENABLE_MULTITHREADING=OFF
          -DENABLE_HIP=ON
          -DCMAKE_HIP_ARCHITECTURES=${{ env.hip_arch }}

      - name: Compile
        run: cmake --build ${{ env.build_dir }}
