name: HIP test

on:
  push:
    branches:
      - amd-patch
  pull_request:
    branches:
      - amd-patch

jobs:
  build:
    runs-on: ubuntu-latest-m

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ROCm
        run: |
          sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
          sudo apt install python3-setuptools python3-wheel
        
      - run: |
          sudo usermod -a -G render,video $USER

      - run: |
          wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
      - run: |
          sudo apt install ./amdgpu-install_6.3.60303-1_all.deb
      - run: |
          sudo apt update
      - run: |
          sudo apt install amdgpu-dkms rocm

      - name: test
        run: hipcc --version