name: HIP test

on:
  push:
    branches:
      - amd-patch
  pull_request:
    branches:
      - amd-patch

jobs:
  build:
    # WARNING: paid runner (with large enough disk to install ROCm)
    runs-on: ubuntu-latest-m

    env:
      build_dir: "build"
      hip_arch: gfx801
      rocm_dir: /opt/rocm

    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      - name: Install ROCm
        run: |
          sudo apt install "linux-headers-$(uname -r)" "linux-modules-extra-$(uname -r)"
          sudo apt install python3-setuptools python3-wheel
          sudo usermod -a -G render,video $USER
          wget https://repo.radeon.com/amdgpu-install/6.3.3/ubuntu/noble/amdgpu-install_6.3.60303-1_all.deb
          sudo apt install ./amdgpu-install_6.3.60303-1_all.deb
          sudo apt update
          sudo apt install amdgpu-dkms rocm

      - name: Configure CMake
        run: >
          cmake -B ${{ env.build_dir }}
          -DBUILD_EXAMPLES=ON
          -DENABLE_TESTING=ON
          -DENABLE_MULTITHREADING=OFF
          -DENABLE_HIP=ON
          -DCMAKE_HIP_ARCHITECTURES=${{ env.hip_arch }}
          -DCMAKE_PREFIX_PATH=${{ env.rocm_dir }}
          -DHIP_ROOT_DIR=${{ env.rocm_dir }}

      - name: Compile
        run: cmake --build ${{ env.build_dir }}