name: HIP test

on:
  push:
    branches:
      - amd-patch
  pull_request:
    branches:
      - amd-patch

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: rocm-setup
        uses: neoblizz/rocm-setup@v0.1.0-beta
        with:
          rocm: '5.5.0'

      - name: test
        run: hipcc --version