name: HIP Windows compile



# disabled
on:
  push:
    branches:
      - v4
  pull_request:
    branches:
      - v4


jobs:
  build:
    runs-on: windows-latest
    env:
      direc: "C:/workdirec"

    steps:

      - name: view drives
        run: Get-PSDrive

      - run: mkdir ${{ env.direc }}
      - run: cd ${{ env.direc }}

      - name: Download AMD HIP Compiler
        run: Invoke-WebRequest -Uri "https://download.amd.com/developer/eula/rocm-hub/AMD-Software-PRO-Edition-24.Q4-WinSvr2022-For-HIP.exe" -OutFile "Setup.exe"
        shell: pwsh
        working-directory: ${{ env.direc }}

      - run: Get-ChildItem ${{ env.direc }}
        shell: pwsh

      - name: Install AMD HIP Compiler
        run: Start-Process Setup.exe -NoNewWindow -Wait
        shell: pwsh
        working-directory: ${{ env.direc }}
