# Some free, ad hoc tests which test only specific
# functions in specific regimes, covering edge cases.
# These are intended as a stop gap in the interim to
# an improved test harness.
#
# So far, we test only CPU functions which have
# template parameters (like NumCtrls or NumTargs)
# which inform an optimised definition for more than
# 6 involved qubits (e.g. 7-10). The tests run by
# both test_free.yml and test_paid.yml do not cover
# such settings, since they use 6-qubit Quregs. So,
# we trigger them here with larger Quregs (8 and 12
# qubits), which requires turning lots of other things
# off to save time and sanity!
# 
# @author Tyson Jones

name: test (egde cases)


on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel


jobs:

  # run only some non-parallelised v4 unit tests at default (double) precision
  serial-unit-test:
    name: >
      ${{ startsWith(matrix.os, 'ubuntu' ) && 'Linux'   || 
          startsWith(matrix.os, 'macos'  ) && 'MacOS'   ||
          startsWith(matrix.os, 'windows') && 'Windows' ||
                                              'Unknown' }}
      ${{ endsWith(matrix.os, '26-intel') && '(Intel 2026)' || '' }}
      serial
      ${{ matrix.bmi2      == 'ON' && '(BMI)'  || '' }}
      edgecases

    runs-on: ${{ matrix.os }}

    strategy:
      # continue other jobs if any fail
      fail-fast: false

      # we will compile QuEST with all precisions but no parallelisation (though with Intel BMI2)
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, macos-26-intel]
        bmi2:      [ON, OFF]

        exclude:
          # cannot use BMI2 on non-Intel MacOS
          - bmi2: ON
            os: macos-latest
  
    # constants; all tests are non-comprehensive for speed
    env:
      build_dir: "build"
      QUEST_TEST_MAX_NUM_QUBIT_PERMUTATIONS: 10
      QUEST_TEST_NUM_MIXED_DEPLOYMENT_REPETITIONS: 5

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@main

      # compile serial unit tests
      - name: Configure CMake
        run: >
          cmake -B ${{ env.build_dir }}
          -DQUEST_BUILD_TESTS=ON
          -DQUEST_ENABLE_OMP=OFF
          -DQUEST_ENABLE_BMI2=${{ matrix.bmi2 }}

      # force 'Release' build (needed by MSVC to enable optimisations)
      - name: Compile
        run: cmake --build ${{ env.build_dir }} --config Release

      # # test statevector and density-matrix functions which exhibit
      # # optimisations on up to 5 ctrl + 2 target qubits, with 8-qubit
      # # Quregs, in order to test the non-optimised implementation
      # - name: 8-qubit edge-cases
      #   run: ctest -C Release -R "Swap|CompMatr1|CompMatr2"
      #   working-directory: ${{ env.build_dir }}
      #   env:
      #     QUEST_TEST_NUM_QUBITS_IN_QUREG: 8

      # subsequent tests use only statevectors, which requires we
      # trigger only the "statevector" Catch2 test subsection, which
      # is not possible through ctest; so we must call the test binary
      # directly, of which the location differs between Unix and Windows
      - name: Set test binary path (Unix)
        if: ${{ ! startsWith(matrix.os, 'windows') }}
        run: echo "TEST_BIN=./tests/tests" >> $GITHUB_ENV
      - name: Set test binary path (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        run: echo "TEST_BIN=./tests/Release/tests.exe" >> $GITHUB_ENV

      # test statevector functions which exhibit optimisations on up to
      # 5 ctrl + 5 target qubits, with 12-qubit Quregs, in order to test
      # the non-optimised implementation (6 ctrls + 6 targets). 
      - name: 12-qubit statevector edge-cases
        run: |
          TESTS=(
            "applyMultiStateControlledCompMatr"
            "applyMultiStateControlledDiagMatr"
            "applyMultiStateControlledPauliStr"
            "applyMultiStateControlledPauliGadget"
          )
          for t in "${TESTS[@]}"; do
            echo "::group::Running $t"
            $TEST_BIN "$t" -c "correctness" -c "statevector"
            echo "::endgroup::"
          done
        shell: bash
        working-directory: ${{ env.build_dir }}
        env:
          QUEST_TEST_NUM_QUBITS_IN_QUREG: 12
