name: TESTING NEW AUDIT


on:
  push:
    branches:
      - code-cov
  pull_request:
    branches:
      - code-cov


jobs:

  # run and report lcov
  coverage-test:
    name: code coverage

    # test only serial double-precision QuEST on Ubuntu
    runs-on: ubuntu-latest

    # constants
    env:
      tracefile: "coverage.info"

    # perform the job
    steps:
      - name: Get QuEST
        uses: actions/checkout@v4

      # work in a build directory to reduce verbosity below
      - run: > 
          mkdir build;
          cd build

      # compile QuEST and unit tests in coverage mode
      - name: Configure CMake
        run: >
          cmake -B .
          -DENABLE_TESTING=ON
          -DENABLE_MULTITHREADING=OFF
          -DCMAKE_CXX_FLAGS=--coverage
          -DCMAKE_EXE_LINKER_FLAGS=--coverage

      - name: Compile unit tests
        run: make

      # run the unit tests, saving coverage data to file
      - name: Run unit tests
        run: ctest -j2 --output-on-failure -R applyHadamard  ########## not waiting for full tst right now

      # analyse the unit test coverage
      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Run LCOV
        run: lcov --directory . --capture --output-file ${{ env.tracefile }} --ignore-errors source

      # remove standard-library and testing and code from coverage data
      - name: Filter LCOV results
        run: lcov --remove ${{ env.tracefile }} '/usr/*' '*/tests/*' '*/_deps/*' --output-file ${{ env.tracefile }}

      - name: Preview LCOV results
        run: lcov --list ${{ env.tracefile }}
      
      # report coverage of remaining files in the triggering PR
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: ./${{ env.tracefile }} ######### github issue claims this is bugged and needs build dir prefix
          minimum-coverage: 50
          artifact-name: code-coverage-report
          update-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
